### ISSUE TITLE
Error while querying jsob column from postgres

### ISSUE THREAD

**Issue by kalkrishnan** [apache/incubator-superset#10008]
While querying jsonb columns from a postgres database, I get an exception.

### Expected results

The json value stored in the column

### Actual results

I get the below exception:
postgresql error: name 'isinstance' is not defined

#### Screenshots

![image](https://user-images.githubusercontent.com/6913583/83956104-58710880-a80f-11ea-949f-8f3f6060b72d.png)

#### How to reproduce the bug

1. Connect to a postgres database
2. select a jsonb column from a table
3. Scroll down to results
4. See error postgresql error: name 'isinstance' is not defined

### Environment

(please complete the following information):

Superset 0.35.2
Python 3.6.9
No node or npm

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Logs:

ERROR:root:Query 199: name 'isinstance' is not defined
Traceback (most recent call last):
File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 236, in execute_sql_statement
data = db_engine_spec.fetch_data(cursor, query.limit)
File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/superset/db_engine_specs/postgres.py", line 52, in fetch_data
return cursor.fetchall()
File "/home/superset/.virtualenvs/superset/lib/python3.6/site-packages/psycopg2/_json.py", line 167, in typecast_json
return loads(s)
File "/usr/lib/python3.6/json/__init__.py", line 341, in loads
if isinstance(s, str):
NameError: name 'isinstance' is not defined

**Comment by kalkrishnan** [comment]
Any updates on this?
