### ISSUE TITLE
TypeError: entry_points() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by chakpongchung** [apache/incubator-superset#10016]
### Expected results

able to run `superset db upgrade`

what you expected to happen.

### Actual results
```
cpchung:incubator-superset$ superset db upgrade
Traceback (most recent call last):
  File "/home/cpchung/anaconda3/bin/superset", line 18, in <module>
    from superset.cli import superset
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/superset/app.py", line 29, in <module>
    from superset.extensions import (
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/superset/extensions.py", line 118, in <module>
    celery_app = celery.Celery()
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/celery/utils/__init__.py", line 19, in <module>
    from .nodenames import nodename, nodesplit, worker_direct
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/kombu/entity.py", line 9, in <module>
    from .serialization import prepare_accept_content
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/kombu/serialization.py", line 456, in <module>
    for ep, args in entrypoints('kombu.serializers'):  # pragma: no cover
  File "/home/cpchung/anaconda3/lib/python3.6/site-packages/kombu/utils/compat.py", line 93, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
TypeError: entry_points() missing 1 required positional argument: 'name'
```
what actually happens.

### Environment
```
cpchung:incubator-superset$ uname -a
Linux cpchung 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
(please complete the following information):

```
cpchung:incubator-superset$ npm -v
6.14.5
cpchung:incubator-superset$ python --version
Python 3.6.8 :: Anaconda, Inc.
cpchung:incubator-superset$ node -v
v10.16.0


```
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

similar.

**Comment by mistercrunch** [comment]
Looks like dependencies might have gotten out of sync after you upgraded. 

Try `pip install -r requirements/base.txt`
