### ISSUE TITLE
KeyError when setting TimeRange

### ISSUE THREAD

**Issue by med4it** [apache/incubator-superset#10058]
I get the KeyError once I set the `Time Range` on any visualization.
Datasource used is Clickhouse.

Stacktrace : 
```
INFO:superset.connectors.sqla.models:SELECT subcategory AS subcategory, COUNT(*) AS count
FROM ecom.tillnow
WHERE event_time >= toDateTime('2020-06-14 17:00:00') AND event_time < toDateTime('2020-06-15 00:00:00') GROUP BY subcategory ORDER BY count DESC
 LIMIT 50000
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): clickhouse:8123
DEBUG:urllib3.connectionpool:http://clickhouse:8123 "POST / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): clickhouse:8123
DEBUG:urllib3.connectionpool:http://clickhouse:8123 "POST /?database=default HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): clickhouse:8123
DEBUG:urllib3.connectionpool:http://clickhouse:8123 "POST /?database=default HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): clickhouse:8123
DEBUG:urllib3.connectionpool:http://clickhouse:8123 "POST /?query_id=2d2b6f18-af52-11ea-9d6a-0242c0a87003&database=default HTTP/1.1" 200 None
Caching 741 chars at key b229be20a1606d62cddbe69a8d1c97cd
INFO:superset.viz:Caching 741 chars at key b229be20a1606d62cddbe69a8d1c97cd
'subcategory'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views/base.py", line 124, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 717, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 639, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 406, in get_payload
    payload["data"] = self.get_data(df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 2874, in get_data
    levels = self.levels_for("agg_sum", groups, df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 2756, in levels_for
    agg_df = df.groupby(groups[:i]) if i else df
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/grouper.py", line 621, in _get_grouper
    raise KeyError(gpr)
KeyError: 'subcategory'
ERROR:superset.views.base:'subcategory'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views/base.py", line 124, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 717, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 639, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 406, in get_payload
    payload["data"] = self.get_data(df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 2874, in get_data
    levels = self.levels_for("agg_sum", groups, df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 2756, in levels_for
    agg_df = df.groupby(groups[:i]) if i else df
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/grouper.py", line 621, in _get_grouper
    raise KeyError(gpr)
KeyError: 'subcategory'
```

**Comment by willbarrett** [comment]
@med4it what is your Superset version?
