### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 20-21:

### ISSUE THREAD

**Issue by wushu0725** [apache/incubator-superset#10126]
WARNING:superset.connectors.sqla.models:Query SELECT COUNT(*) AS `数量`
FROM ads_big_data.ads_company_updown_month
WHERE dt >= STR_TO_DATE('2020-06-15', '%Y-%m-%d')
  AND dt < STR_TO_DATE('2020-06-22', '%Y-%m-%d')
ORDER BY `数量` DESC
LIMIT 10000 on schema ads_big_data failed
Traceback (most recent call last):
  File "/home/ubuntu/incubator-superset/superset/connectors/sqla/models.py", line 1133, in query
    df = self.database.get_df(sql, self.schema, mutator)
  File "/home/ubuntu/incubator-superset/superset/models/core.py", line 375, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/home/ubuntu/incubator-superset/superset/db_engine_specs/base.py", line 822, in execute
    cursor.execute(query)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 191, in execute
    query = query.encode(db.encoding)
  File "/usr/lib/python3.6/encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 20-21: character maps to <undefined>

system ubantu
python 3.6

**Comment by willbarrett** [comment]
Hi @wushu0725 - this bug traces back to the MySQL database connector and Python 3.6's string encoding functionality. I believe this bug is with Python itself or the MySQL driver rather than Superset. Closing.
