### ISSUE TITLE
superset load_examples 

### ISSUE THREAD

**Issue by reesezxf** [apache/incubator-superset#10125]
when I run superset load_examples, then raise error:
```
(superset) D:\workspace\incubator-superset\superset\bin>python superset load_examples
INFO:superset.utils.logging_configurator:logging was configured successfully
D:\soft\anconda\envs\superset\lib\site-packages\flask_caching\__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: sqlite:///C:\Users\zhang\.superset\superset.db
Traceback (most recent call last):
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 974, in send
    self.connect()
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 1415, in connect
    super().connect()
  File "D:\soft\anconda\envs\superset\lib\http\client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\soft\anconda\envs\superset\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\soft\anconda\envs\superset\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "superset", line 21, in <module>
    superset()
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\soft\anconda\envs\superset\lib\site-packages\superset\cli.py", line 165, in load_examples
    load_examples_run(load_test_data, only_metadata, force)
  File "D:\soft\anconda\envs\superset\lib\site-packages\superset\cli.py", line 105, in load_examples_run
    examples.load_energy(only_metadata, force)
  File "D:\soft\anconda\envs\superset\lib\site-packages\superset\examples\energy.py", line 39, in load_energy
    data = get_example_data("energy.json.gz")
  File "D:\soft\anconda\envs\superset\lib\site-packages\superset\examples\helpers.py", line 71, in get_example_data
    content = request.urlopen(f"{BASE_URL}{filepath}?raw=true").read()
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\soft\anconda\envs\superset\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```
------------------------------------------------------------------
I try to change BASE_URL in helpers.py , also does not work.

**Comment by mistercrunch** [comment]
Windows isn't really supported, we recommend you use docker or a VM of some sort.

**Comment by reesezxf** [comment]
I build a http service in local, and download examples-data, then change helpers.py BASE_URL = "http://localhost:8888/D%3A/workspace/examples-data/", and problem sovled.
