### ISSUE TITLE
superset celery  ImportError: cannot import name 'TimeGrain'

### ISSUE THREAD

**Issue by reesezxf** [apache/incubator-superset#10144]
I have also set my database conection to allow async execution, so I want start celery, 
but in sql_lab run query then  in pending status.

I am running celery using the below command
celery worker --app=superset.tasks.celery_app:app -Ofair
then error like this:
  File "d:\soft\anconda\envs\superset\lib\site-packages\superset\sql_lab.py", line 43, in <module>
    from superset.db_engine_specs import BaseEngineSpec
  File "d:\soft\anconda\envs\superset\lib\site-packages\superset\db_engine_specs\__init__.py", line 36, in <module>
    from superset.db_engine_specs.base import BaseEngineSpec
  File "d:\soft\anconda\envs\superset\lib\site-packages\superset\db_engine_specs\base.py", line 54, in <module>
    from superset.models.sql_lab import Query
  File "d:\soft\anconda\envs\superset\lib\site-packages\superset\models\__init__.py", line 17, in <module>
    from . import core, datasource_access_request, schedules, sql_lab, user_attributes
  File "d:\soft\anconda\envs\superset\lib\site-packages\superset\models\core.py", line 55, in <module>
    from superset.db_engine_specs.base import TimeGrain
ImportError: cannot import name 'TimeGrain'

- superset version: `superset version` 0.36.0
- python version: `python --version`3.6.10

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version` 0.36.0
- python version: `python --version`3.6.10
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Hi @reesezxf - from the path output you posted, it looks like you are attempting to run Superset on Windows. Is that correct? We do not currently support the Windows OS - I would recommend that you run Superset under a Linux-based OS, or under Docker on Windows if a Linux-based host OS is not available.

**Comment by l4ngl3y** [comment]
Running under Linux-based OS (in docker):
`/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 531, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/superset/sql_lab.py", line 43, in <module>
    from superset.db_engine_specs import BaseEngineSpec
  File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/__init__.py", line 36, in <module>
    from superset.db_engine_specs.base import BaseEngineSpec
  File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/base.py", line 54, in <module>
    from superset.models.sql_lab import Query
  File "/usr/local/lib/python3.6/site-packages/superset/models/__init__.py", line 17, in <module>
    from . import core, datasource_access_request, schedules, sql_lab, user_attributes
  File "/usr/local/lib/python3.6/site-packages/superset/models/core.py", line 55, in <module>
    from superset.db_engine_specs.base import TimeGrain
ImportError: cannot import name 'TimeGrain'`
