### ISSUE TITLE
无法创建用户名

### ISSUE THREAD

**Issue by 17671123357** [apache/incubator-superset#10201]
`User first name [admin]: a
User last name [user]: n
Email [admin@fab.org]: admin
Password:
Repeat for confirmation:
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python38\Scripts\fabmanager.exe\__main__.py", line 7, in <module>
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\flask_appbuilder\console.py", line 425, in cli
    cli_app()
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\flask_appbuilder\console.py", line 138, in create_admin
    auth_type.get(_appbuilder.sm.auth_type, "No Auth method")
AttributeError: 'NoneType' object has no attribute 'auth_type'`
以上win10环境，python3.8下创建账户出错，请帮我看一下应该怎么处理

**Comment by etr2460** [comment]
Hi, unfortunately we don't officially support Windows for deployment of Superset. I'd recommend using a Unix based OS for development and deployment
