### ISSUE TITLE
The 'flask-appbuilder<4.0.0,>=3.0.1' distribution was not found and is required by apache-superset

### ISSUE THREAD

**Issue by codepic** [apache/incubator-superset#10319]
### Expected results

`docker-compose up` working properly 

### Actual results

```
superset_init            |
superset_init            | ######################################################################
superset_init            |
superset_init            |
superset_init            | Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )
superset_init            |
superset_init            |
superset_init            | ######################################################################
superset_init            |
superset_init            | Traceback (most recent call last):
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_master
superset_init            |     ws.require(__requires__)
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 899, in require
superset_init            |     needed = self.resolve(parse_requirements(requirements))
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 790, in resolve
superset_init            |     raise VersionConflict(dist, req).with_context(dependent_req)
superset_init            | pkg_resources.ContextualVersionConflict: (Flask-AppBuilder 3.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('flask-appbuilder<4.0.0,>=3.0.1'), {'apache-superset'})
superset_init            |
superset_init            | During handling of the above exception, another exception occurred:
superset_init            |
superset_init            | Traceback (most recent call last):
superset_init            |   File "/usr/local/bin/superset", line 4, in <module>
superset_init            |     __import__('pkg_resources').require('apache-superset==0.999.0.dev0')
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3256, in <module>
superset_init            |     @_call_aside
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
superset_init            |     f(*args, **kwargs)
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
superset_init            |     working_set = WorkingSet._build_master()
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
superset_init            |     return cls._build_from_requirements(__requires__)
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
superset_init            |     dists = ws.resolve(reqs, Environment())
superset_init            |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 785, in resolve
superset_init            |     raise DistributionNotFound(req, requirers)
superset_init            | pkg_resources.DistributionNotFound: The 'flask-appbuilder<4.0.0,>=3.0.1' distribution was not found and is required by apache-superset
superset_init exited with code 1
```

#### How to reproduce the bug

1. `git clone -b 0.37.0rc1 https://github.com/apache/incubator-superset.git`
2. `cd incubator-superset/docker`
3. `docker-compose up`

### Environment

(please complete the following information):

- superset version: `0.37.0rc1 `
- python version: `3.8.2`
- node.js version: `v12.18.2`
- npm version: `6.14.5`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Running on Ubuntu 20.04 with WSL2 on Windows 10 and Docker version 19.03.8, build afacb8b7f0

**Comment by villebro** [comment]
@codepic There is a problem with the current docker-compose, see #10055 for an interim solution until this is fixed. Can you try if this solves your problem?

**Comment by codepic** [comment]
@villebro if you mean 

```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker system prune -a
```
Then no, it doesn't help. I tried it before filing the bug.

**Comment by willbarrett** [comment]
This issue should now be resolved on master. Closing.
