### ISSUE TITLE
fabmanager run --app superset error 

### ISSUE THREAD

**Issue by EkaX** [apache/incubator-superset#10514]
Hi i have a error while run superset via fabmanager run --app superset 

This error massages

fabmanager is going to be deprecated in 2.2.X, you can use the same commands on the improved 'flask fab <command>'
Traceback (most recent call last):
  File "/root/venv/bin/fabmanager", line 8, in <module>
    sys.exit(cli())
  File "/root/venv/lib/python3.6/site-packages/flask_appbuilder/console.py", line 422, in cli
    cli_app()
  File "/root/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/venv/lib/python3.6/site-packages/flask_appbuilder/console.py", line 187, in run
    _appbuilder.get_app.run(host=host, port=port, debug=debug)
  File "/root/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/root/venv/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/root/venv/lib/python3.6/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

Thanks before

**Comment by EkaX** [comment]
I try run with this command and work
superset run -h 0.0.0.0 -p 8088 
{-h is your ip address server and -p 8088 is your port for superset}

**Comment by shoaibshaik26** [comment]
worked for me
