### ISSUE TITLE
"TypeError: 'str' object is not callable" on "Show record" in "Saved Queries" 

### ISSUE THREAD

**Issue by PhucNgo1711** [apache/incubator-superset#10663]
### Expected results

Displays the metadata of the target saved query

### Actual results

The error `TypeError: 'str' object is not callable` is thrown

#### How to reproduce the bug

1. Set up a query from `SQL Editor` in `SQL Lab`
2. Save the query (with or without description)
3. Go to `Saved Queries` in `SQL Lab`
4. Click on `Show record` on any saved query

### Environment

(please complete the following information):

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.8.5`
- node.js version: `v11.0.0`
- npm version: `6.14.7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi, I'm not being able to reproduce this, if I visit `http://localhost:8088/savedqueryview/show/1` for example the page is rendered has expected

**Comment by PhucNgo1711** [comment]
Hmm. I pulled the latest master yesterday and still got that error. I'll take a deeper look into this.

**Comment by dpgaspar** [comment]
A bigger chunk of server logs would help on reproducing the issue

**Comment by PhucNgo1711** [comment]
Here are the logs that show up on my end

```
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:18] "GET /savedqueryview/show/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/Users/ptn/Desktop/incubator-superset/superset/views/sql_lab.py", line 95, in show
    return self.render_template(
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 280, in render_template
    return render_template(
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/ptn/Desktop/incubator-superset/superset/templates/superset/models/savedquery/show.html", line 19, in top-level template code
    {% extends "appbuilder/general/model/show.html" %}
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/Users/ptn/Desktop/incubator-superset/superset/templates/superset/base.html", line 20, in top-level template code
    {% from 'superset/partials/asset_bundle.html' import css_bundle, js_bundle with context %}
  File "/Users/ptn/Desktop/incubator-superset/superset/templates/appbuilder/baselayout.html", line 20, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/Users/ptn/Desktop/incubator-superset/venv/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/Users/ptn/Desktop/incubator-superset/superset/templates/appbuilder/baselayout.html", line 45, in block "body"
    <div id="app" data-bootstrap="{{ bootstrap_data() }}"></div>
TypeError: 'str' object is not callable
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:18] "GET /savedqueryview/show/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:18] "GET /savedqueryview/show/1?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:18] "GET /savedqueryview/show/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:19] "GET /savedqueryview/show/1?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Aug/2020 20:08:19] "GET /savedqueryview/show/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by dpgaspar** [comment]
Strange, seems like `bootstrap_data` is a string. Does it only happen on saved queries?

**Comment by PhucNgo1711** [comment]
Yeah other “Show record” in other tabs are fine

**Comment by dpgaspar** [comment]
I was able to reproduce it

**Comment by PhucNgo1711** [comment]
Oh what was the underlying cause?

**Comment by dpgaspar** [comment]
ok, found the cause, I'll make a fix ASAP
