### ISSUE TITLE
SQL Lab. Celery task.forget() is not supported by all backends. "NotImplementedError: backend does not implement forget."

### ISSUE THREAD

**Issue by jinhyukchang** [apache/incubator-superset#10757]
Hi,
We are using SQS on Celery and with this [PR](https://github.com/apache/incubator-superset/pull/10279), it invokes `forget()` call, but it seems SQS backend has not implemented it. From Google search, AMQP also hasn't implemented it yet.

Since, not all backend implementation has this method implemented, how about isolate this failure by wrapping with `try...except`?

```
Traceback (most recent call last):
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/superset/views/core.py", line 2117, in _sql_json_async
    task.forget()
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/celery/result.py", line 146, in forget
    self.backend.forget(self.id)
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/celery/backends/base.py", line 463, in forget
    self._forget(task_id)
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/celery/backends/base.py", line 466, in _forget
    raise NotImplementedError('backend does not implement forget.')
NotImplementedError: backend does not implement forget.
```

### Expected results

No exception when user submit query from SQL Lab.

### Actual results

Failing with message at https://github.com/apache/incubator-superset/blob/master/superset/views/core.py#L2142

#### How to reproduce the bug

1. Use SQS as Celery backend
2. Submit query in SQLLab

### Environment

(please complete the following information):

- superset version: `0.37`
- python version: `3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment]
Closing as fixed.
