### ISSUE TITLE
Connect with Google Sheet error

### ISSUE THREAD

**Issue by EkaX** [apache/incubator-superset#11057]
Hi when i try connect superset with Google Sheet i got this error 
ERROR: Could not load database driver: gsheets

And the google sheet table in my superset shows an error like this

        Traceback (most recent call last):
  File "/root/reqmon/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/reqmon/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/reqmon/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/reqmon/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/reqmon/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/reqmon/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/reqmon/lib/python3.8/site-packages/superset/utils/log.py", line 70, in wrapper
    value = f(*args, **kwargs)
  File "/root/reqmon/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/root/reqmon/lib/python3.8/site-packages/superset/views/core.py", line 706, in explore
    "datasource": datasource.data,
  File "/root/reqmon/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 602, in data
    data_ = super().data
  File "/root/reqmon/lib/python3.8/site-packages/superset/connectors/base/models.py", line 266, in data
    "select_star": self.select_star,
  File "/root/reqmon/lib/python3.8/site-packages/superset/connectors/sqla/models.py", line 596, in select_star
    return self.database.select_star(
  File "/root/reqmon/lib/python3.8/site-packages/superset/models/core.py", line 435, in select_star
    eng = self.get_sqla_engine(schema=schema, source=utils.QuerySource.SQL_LAB)
  File "/root/reqmon/lib/python3.8/site-packages/superset/utils/core.py", line 165, in __call__
    value = self.func(*args, **kwargs)
  File "/root/reqmon/lib/python3.8/site-packages/superset/models/core.py", line 359, in get_sqla_engine
    return create_engine(sqlalchemy_url, **params)
  File "/root/reqmon/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/reqmon/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/root/reqmon/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/root/reqmon/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 267, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:gsheets

I use ubuntu 20 and python 3.8

Thanks Before

**Comment by dpgaspar** [comment]
Hi, 

Please make sure you have installed `gsheetsdb>=0.1.9`
