### ISSUE TITLE
Issue while using Forecasting 

### ISSUE THREAD

**Issue by kkalyan** [apache/incubator-superset#11106]
I'm trying to use Prophet forecasting on Druid datasource and it throws the following exception 
Unexpected Error
Error: Column ds has timezone specified, which is not supported. Remove timezone.

### Expected results
Forecast as illustrated in https://github.com/apache/incubator-superset/pull/10752

### Actual results
ValueError: Column ds has timezone specified, which is not supported. Remove timezone.
ERROR:superset.common.query_context:Column ds has timezone specified, which is not supported. Remove timezone.
Traceback (most recent call last):
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/superset/common/query_context.py", line 251, in get_df_payload
    query_result = self.get_query_result(query_obj)
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/superset/common/query_context.py", line 117, in get_query_result
    df = query_object.exec_post_processing(df)
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/superset/common/query_object.py", line 262, in exec_post_processing
    df = getattr(pandas_postprocessing, operation)(df, **options)
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/superset/utils/pandas_postprocessing.py", line 672, in prophet
    freq=freq,
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/superset/utils/pandas_postprocessing.py", line 602, in _prophet_fit_and_predict
    model.fit(df)
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1111, in fit
    history = self.setup_dataframe(history, initialize_scales=True)
  File "/local/home/kkanuri/env/lib/python3.6/site-packages/fbprophet/forecaster.py", line 265, in setup_dataframe
    'Column ds has timezone specified, which is not supported. '
ValueError: Column ds has timezone specified, which is not supported. Remove timezone.

### Environment

(please complete the following information):

- superset version: `superset version` - 0.37.2 
- python version: `python --version` 3.6.9
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@villebro

**Comment by junlincc** [comment]
@kkalyan Thanks for reporting and contributing!!!
