### ISSUE TITLE
AUTH_REMOTE_USER and Scheduled email reports

### ISSUE THREAD

**Issue by yackushevas** [apache/incubator-superset#11119]
### Expected results

Ability to work with service users when using AUTH_TYPE = AUTH_REMOTE_USER.

### Actual results

The user specified in EMAIL_REPORTS_USER does not have a simplified authorization option (or I could not find it in the documentation).

#### How to reproduce the bug

1. Set AUTH_TYPE = AUTH_REMOTE_USER and use CUSTOM_SECURITY_MANAGER
2. Set ENABLE_SCHEDULED_EMAIL_REPORTS = True
3. See error:
```
Exception on /login/ [GET]
Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/superset/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/superset/venv/bin/superset_config.py", line 142, in login
    login_user(user)
  File "/opt/superset/venv/lib/python3.6/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
```

**Comment by jawabuu** [comment]
Hey @yackushevas Are you using any middleware?
Could you share your CustomSecurityManager?

**Comment by jawabuu** [comment]
@mistercrunch Using tour example here
https://gist.github.com/mistercrunch/6d31af4a11c47edcedc1ba6ceb5f5fab works fine for remote user login but returns 

`raised unexpected: WebDriverException('Failed to decode response from marionette', None, None)` 
or
` NoSuchElementException('Unable to locate element: .grid-container', None, None)`

for email Reports.
Switching to AUTH_OAUTH or AUTH_DB resolves it.

**Comment by yackushevas** [comment]
> for email Reports.
> Switching to AUTH_OAUTH or AUTH_DB resolves it.

Then AUTH_REMOTE_USER will not work.

**Comment by Kingflyinger** [comment]
when i use fabmanager create-admin --app superset,it occurs the same problem
hou could i solve it, or just use the earlier version?
`Traceback (most recent call last):
  File "c:\users\admin\.conda\envs\superset\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\.conda\envs\superset\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\.conda\envs\superset\Scripts\fabmanager.exe\__main__.py", line 7, in <module>
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\flask_appbuilder\console.py", line 422, in cli
    cli_app()
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\admin\.conda\envs\superset\lib\site-packages\flask_appbuilder\console.py", line 137, in create_admin
    auth_type.get(_appbuilder.sm.auth_type, "No Auth method")
AttributeError: 'NoneType' object has no attribute 'auth_type'`

**Comment by rusackas** [comment]
Based on timestamps and inactivity of this thread, I believe this issue is in reference to an unspecified yet unsupported version of Superset.

If anyone thinks this is still relevant today in Superset 1.5.x or 2.x.x versions, please let us know. Otherwise, I think we can probably close this one out. CC @eschutho for input or confirmation of closability (which _should_ be a word).
