### ISSUE TITLE
0.37.2 New OSError: [Errno 92] Protocol not available

### ISSUE THREAD

**Issue by bestao88** [apache/incubator-superset#11157]
### Superset 0.37.2, gunicorn start report error as OSError: [Errno 92] Protocol not available

what you expected to happen.

### running in order

what actually happens.

#### Screenshots
gunicorn -w 1 -k gevent --timeout 120 -b 192.168.18.10:4040 --limit-request-line 0 --lim
it-request-field_size 0 "superset.app:create_app()"
[2020-10-05 09:22:17 +0800] [120] [INFO] Starting gunicorn 20.0.4
[2020-10-05 09:22:17 +0800] [120] [INFO] Listening at: http://192.168.18.10:4040 (120)
[2020-10-05 09:22:17 +0800] [120] [INFO] Using worker: gevent
[2020-10-05 09:22:17 +0800] [122] [INFO] Booting worker with pid: 122
[2020-10-05 09:22:17 +0800] [122] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/snow/anaconda3/envs/env35/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/snow/anaconda3/envs/env35/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 160, in init_process
    self.patch()
  File "/home/snow/anaconda3/envs/env35/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 61, in patch
    sockets.append(socket.socket(s.FAMILY, socket.SOCK_STREAM,
  File "/home/snow/anaconda3/envs/env35/lib/python3.8/site-packages/gevent/_socket3.py", line 142, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available
[2020-10-05 09:22:17 +0800] [122] [INFO] Worker exiting (pid: 122)
[2020-10-05 09:22:17 +0800] [120] [INFO] Shutting down: Master
[2020-10-05 09:22:17 +0800] [120] [INFO] Reason: Worker failed to boot.

#### How to reproduce the bug

1. OS: WSL,Debian 10
2. Install superset 0.37.2
3. Database changed to Mysql
4. worked as fine: superset run -p 8088 --with-threads --reload --debugger
5. See error: gunicorn -w 1 -k gevent --timeout 120 -b 192.168.18.10:4040 --limit-request-line 0 --lim

### Environment

(please complete the following information):

- superset version: `0.37.2`
- python version: `3.8.5`
- gunicorn version: `20.0.4`
- gevent version: `20.9.0`

Requirement already satisfied: gevent in ./anaconda3/envs/env35/lib/python3.8/site-packages (20.9.0)
Requirement already satisfied: greenlet>=0.4.17; platform_python_implementation == "CPython" in ./anaconda3/envs/env35/lib/python3.8/site-packages (from gevent) (0.4.17)
Requirement already satisfied: setuptools in ./anaconda3/envs/env35/lib/python3.8/site-packages (from gevent) (49.6.0.post20200925)
Requirement already satisfied: zope.interface in ./anaconda3/envs/env35/lib/python3.8/site-packages (from gevent) (5.1.2)
Requirement already satisfied: zope.event in ./anaconda3/envs/env35/lib/python3.8/site-packages (from gevent) (4.5.0)

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [Y] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bestao88** [comment]
Please help me close the bug.
Resolved:
1. Upgrade WSL from 1.0 to 2.0
2. Use the netsh to mapping network
Everything is working fine!
