### ISSUE TITLE
Helm install unable to create admin account

### ISSUE THREAD

**Issue by technomage** [apache/incubator-superset#11251]
After installing superset (0.36.0) using helm chart (1.1.11), creating the admin account results in an exception

### Expected results
User should be created

### Actual results
An exception is produced and user is not able to log in

#### How to reproduce the bug

Install superset with helm 1.1.11 with values:

superset:
  enabled: true
  persistence:
    enabled: true

### Environment

(please complete the following information):

- superset version: `superset version` 0.36.0
- python version: `python --version` 3.6.10 in pod
- node.js version: `node -v`  node not found in pod
- npm version: `npm -v` not found in pod

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

michael@michael:~$ sudo kubectl exec -it cog-superset-7c4c7d8594-ld2zt -- fabmanager create-admin --app superset
[sudo] password for michael: 
fabmanager is going to be deprecated in 2.2.X, you can use the same commands on the improved 'flask fab <command>'
Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: admin@cog.net
Password: 
Repeat for confirmation: 
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/usr/local/bin/fabmanager", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/console.py", line 422, in cli
    cli_app()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/console.py", line 137, in create_admin
    auth_type.get(_appbuilder.sm.auth_type, "No Auth method")
AttributeError: 'NoneType' object has no attribute 'auth_type'
command terminated with exit code 1

**Comment by technomage** [comment]
Instructions must have been out of date.  Using superset-init did work when exec into the pod.  I have yet to get the custom init file to work, but that is probably me.
