### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory

### ISSUE THREAD

**Issue by wbsljh** [apache/incubator-superset#1191]
i get the problem when i run  "npm run prod", it throw the following errors。i guess if it missing the dependency "babel-preset-es2015-loose" in the package.json?

ERROR in ./~/react-grid-layout/index.js
Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory "D:\develop\workspace_py\caravel\caravel\assets\node_modules\react-grid-layout"
    at D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:281:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:20)
    at OptionManager.mergePresets (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:254:10)
    at OptionManager.mergeOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:239:14)
    at OptionManager.init (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:338:12)
    at File.initOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:131:12)
 @ ./javascripts/dashboard/components/GridLayout.jsx 17:23-51

ERROR in ./~/redux-localstorage/lib/persistState.js
Module build failed: ReferenceError: [BABEL] D:\develop\workspace_py\caravel\caravel\assets\node_modules\redux-localstorage\lib\persistState.js: Using removed Babel 5 option: D:\develop\workspace_py\caravel\caravel\assets\node_modules\redux-localstorage.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:214:20)
    at OptionManager.init (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:338:12)
    at File.initOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:131:12)
 @ ./javascripts/reduxUtils.js 20:25-54

ERROR in ./~/react-map-gl/~/mapbox-gl-shaders/index.js
Module not found: Error: Cannot resolve module 'fs' in D:\develop\workspace_py\caravel\caravel\assets\node_modules\react-map-gl\node_modules\mapbox-gl-shaders
 @ ./~/react-map-gl/~/mapbox-gl-shaders/index.js 3:9-22

**Comment by wbsljh** [comment]
after install the dependency "babel-preset-es2015-loose" get the errors change, as follow:
=========================================================
ERROR in ./~/react-grid-layout/index.js
Module build failed: Error: Couldn't find preset "stage-1" relative to directory "D:\\develop\\workspace_py\\caravel\\caravel\\assets\\node_modules\\react-grid-layout"
    at D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:281:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:20)
    at OptionManager.mergePresets (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:254:10)
    at OptionManager.mergeOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:239:14)
    at OptionManager.init (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\options\option-manager.js:338:12)
    at File.initOptions (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (D:\develop\workspace_py\caravel\caravel\assets\node_modules\babel-loader\index.js:131:12)
 @ ./javascripts/dashboard/components/GridLayout.jsx 17:23-51

**Comment by Dowgen** [comment]
@wbsljh 大兄弟解决了吗，我也遇到这个问题

**Comment by mistercrunch** [comment]
this is stale, closing
