### ISSUE TITLE
Dashboards are empty, and "go to dashboard" button is disabled

### ISSUE THREAD

**Issue by edevil** [apache/incubator-superset#1597]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.13.1

### Expected results

Dashboard should show added slices. "Go to dashboard" button should not be empty.

### Actual results

When I visit the dashboard URL I get an empty page. Also, the "go to dashboard" button is disabled.

<img width="339" alt="screen shot 2016-11-14 at 18 13 26" src="https://cloud.githubusercontent.com/assets/12426/20276966/92fe14ae-aa96-11e6-9f5d-696443706852.png">

### Steps to reproduce

Create slices, add them to a dashboard.

**Comment by mistercrunch** [comment]
Do you have a javascript stacktrace in the console?

**Comment by phreatom** [comment]
Got the same error. Stacktrace when opening the dashboard:

Uncaught TypeError: n.position_json.forEach is not a function
    at i (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:209:27572)
    at HTMLDocument.<anonymous> (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:210:1177)
    at l (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:35:22569)
    at Object.fireWith [as resolveWith] (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:35:23337)
    at Function.ready (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:35:25156)
    at HTMLDocument.c (http://SERVERNAME/static/assets/dist/dashboard.0.13.1.entry.js:25:931)

**Comment by edevil** [comment]
I have the same stack trace as @phreatom.

**Comment by phreatom** [comment]
ed48255 seems to fix the empty dashboard. (now running a master build) However the disabled "go to dashboard" button remains.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 524 days. Feel free to comment and request for this issue to be reopened.
