### ISSUE TITLE
UnicodeEncodeError when export csv on sql lab

### ISSUE THREAD

**Issue by kylozw** [apache/incubator-superset#1602]
I run it on macOS 10.12.1.
Issue comes when I rename the sql tab to Chinese name.

### Superset version
0.13.1

### Expected results
download a csv file

### Actual results
Internal Server Error
And the logs:
```
[2016-11-14 15:33:44 +0800] [25] [ERROR] Error handling request /superset/csv/BybA_1DWl
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/usr/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 342, in write
    self.send_headers()
  File "/usr/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 338, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "ascii"))
  File "/usr/lib/python3.5/site-packages/gunicorn/util.py", line 511, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 210-211: ordinal not in range(128)
```

### Steps to reproduce
1. rename the sql tab to Chinese name.
2. run query
3. click .csv

**Comment by xrmx** [comment]
Which version of superset? Please use the template issue when filing issue.

**Comment by kylozw** [comment]
Hi, @xrmx. It's 0.13.1, and I've updated the description.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 523 days. Feel free to comment and request for this issue to be reopened.

**Comment by vimagick** [comment]
The issue is still not fixed though
