### ISSUE TITLE
Cannot create pie chart when there is no date column in the table

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-superset#1689]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.13.2

### Actual results
```
2016-11-25 14:23:22,778:ERROR:root:local variable 'dttm_col' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/superset/views.py", line 1277, in explore_json
    payload = viz_obj.get_json()
  File "/usr/local/lib/python3.4/dist-packages/superset/viz.py", line 324, in get_json
    'data': self.get_data(),
  File "/usr/local/lib/python3.4/dist-packages/superset/viz.py", line 1234, in get_data
    df = self.get_df()
  File "/usr/local/lib/python3.4/dist-packages/superset/viz.py", line 1226, in get_df
    df = super(DistributionPieViz, self).get_df(query_obj)
  File "/usr/local/lib/python3.4/dist-packages/superset/viz.py", line 169, in get_df
    self.results = self.datasource.query(**query_obj)
  File "/usr/local/lib/python3.4/dist-packages/superset/models.py", line 1103, in query
    inner_time_filter = dttm_col.get_time_filter(
UnboundLocalError: local variable 'dttm_col' referenced before assignment
```

### Steps to reproduce

Create pie chart for table without date column.

Hint: you can do this with sunburst diagram.

**Comment by spspaul** [comment]
For the record, I got the same exception when I updated from:
```
%> pip show caravel
---
Metadata-Version: 1.1
Name: caravel
Version: 0.11.0
```
to
```
%> pip show superset 2>&1 | head -2
Name: superset
Version: 0.13.2
```
Once I provided a value for **```Time Column```** in the Slice definition
using the **```Distribution - NVD3 - Pie Chart```** widget, it started working again.
