### ISSUE TITLE
SQL Lab exception when executed query is not limited or with a limit > SQL_MAX_ROW

### ISSUE THREAD

**Issue by TibboddiT** [apache/incubator-superset#1690]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.13.2

### Expected results

Should return a nice error message, or simply limit the recordset applying SQL_MAX_ROW

### Actual results

```
2016-11-25 14:00:45,541:ERROR:superset:Exception on /superset/sql_json/ [POST]                                                                                                        [45/1355]
Traceback (most recent call last):
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: query.client_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/superset/models.py", line 2226, in wrapper
    return f(*args, **kwargs)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/superset/views.py", line 2039, in sql_json
    session.commit()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nux-admin/Superset/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: query.client_id [SQL: 'INSERT INTO "query" (client_id, database_id, tmp_table_name, user_id, status, tab_name, sql_editor_id, schema, sql, select_sql, executed_sql, "limit", limit_used, select_as_cta, select_as_cta_used, progress, rows, error_message, results_key, start_time, end_time, changed_on) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('ryxMN6Sze', 1, '', 1, 'running', 'Untitled Query 2', 'BkufBjBze', '', 'SELECT * FROM birth_names', None, None, 500, 0, 0, 0, 0, None, None, None, 1480082445536.15, None, '2016-11-25 14:00:45.540682')]
```

### Steps to reproduce

Just exec any query that returns more than `SQL_MAX_ROW` rows in SQL Lab without a `LIMIT` clause, OR with a limit > `SQL_MAX_ROW`.

The exception says that a unique constraint failed. I guess the query throwing this exception is the one that sets the `failed` status on the query record on the `query` table. But the status showed in the exception is `running`, so i don't know. 

The query is marked as running in the query browser.

Here the query tested is 
```
SELECT * FROM birth_names
```
and the `SQL_MAX_ROW` is set to 500 in config.

```
SELECT * FROM birth_names LIMIT 501
``` 
fails, but 
```
SELECT * FROM birth_names LIMIT 500
```
doesn't.

**Comment by dmigo** [comment]
Wasn't able to reproduce this one on 89f6ccc1c6efdc7bbf73ecf8daddefd70691b99e

**Comment by mistercrunch** [comment]
We use `shortid` https://github.com/dylang/shortid for this, I'm not sure what the odds of collisions may be. Should be extremely low.

**Comment by andrewmusselman** [comment]
I'm seeing this same issue when running certain queries with Postgres 9, installed on an EC2 host using these instructions: https://www.dremio.com/visualize-your-data-lake-with-dremio-and-apache-superset

Cloned and checked out hash:
`git clone https://github.com/apache/incubator-superset.git && cd incubator-superset && git checkout 0cf354c`


```
Error message:

Sorry, something went wrong
500 - Internal Server Error
Stacktrace

 Traceback (most recent call last): File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context cursor, statement, parameters, context File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute cursor.execute(statement, parameters) sqlite3.IntegrityError: column client_id is not unique The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/ec2-user/incubator-superset/superset/views/core.py", line 2310, in sql_json_exec session.flush() File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2479, in flush self._flush(objects) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush transaction.rollback(_capture_exception=True) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise raise value File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush flush_context.execute() File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute rec.execute(self) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute uow, File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj insert, File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1137, in _emit_insert_statements statement, params File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute return meth(self, multiparams, params) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement distilled_params, File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context e, statement, parameters, cursor, context File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception util.raise_from_cause(sqlalchemy_exception, exc_info) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise raise value.with_traceback(tb) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context cursor, statement, parameters, context File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) column client_id is not unique [SQL: INSERT INTO "query" (extra_json, client_id, database_id, tmp_table_name, user_id, status, tab_name, sql_editor_id, schema, sql, select_sql, executed_sql, "limit", select_as_cta, select_as_cta_used, progress, rows, error_message, results_key, start_time, start_running_time, end_time, end_result_backend_time, tracking_url, changed_on) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('{}', 'bSqgSSCA5b', 2, '', '2', 'running', 'Copy of Total views per asset', 'A721kpy2j', 'public', "select\n mtitle\n , date\n , count(*)\nfrom\n (select\n distinct\n m.title as mtitle\n , v.date as date\n , v.ip as ip\n , v.checks ... (51 characters truncated) ... v.checksum = m.checksum\n and m.title like '%Oklahoma%')\n as dist_user_asset_date\ngroup by mtitle, date\norder by mtitle, date, count desc;", None, None, None, 0, 0, 0, None, None, None, 1585469953416.2778, None, None, None, None, '2020-03-29 08:19:13.417183')] (Background on this error at: http://sqlalche.me/e/gkpj) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app response = self.full_dispatch_request() File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise raise value File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request() File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/ec2-user/incubator-superset/venv/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 168, in wraps return f(self, *args, **kwargs) File "/home/ec2-user/incubator-superset/superset/utils/log.py", line 59, in wrapper value = f(*args, **kwargs) File "/home/ec2-user/incubator-superset/superset/views/core.py", line 2249, in sql_json return self.sql_json_exec(request.json, log_params) File "/home/ec2-user/incubator-superset/superset/views/core.py", line 2316, in sql_json_exec raise Exception(_("Query record was not created as expected.")) Exception: Query record was not created as expected. ```

**Comment by eugeniamz** [comment]
> I'm seeing this same issue when running certain queries with Postgres 9, installed on an EC2 host using these instructions: https://www.dremio.com/visualize-your-data-lake-with-dremio-and-apache-superset
> 

Can you share and example of your query so I try? This issues is with a pretty old version, I can try with the latest.

**Comment by andrewmusselman** [comment]
Sure, here is the schema I'm running it against:

```
views
date DATE
time TIME WITHOUT TIME ZONE
ip INET
checksum VARCHAR
media VARCHAR
segment VARCHAR
time_taken VARCHAR
ua VARCHAR

mapping
id VARCHAR
title VARCHAR
checksum VARCHAR
```
Query:

```
select
  date
  , count(*)
from
 (select
    distinct
    v.date as date
    , v.ip as ip
  from
    views v)
  as dist_user_asset_date
group by date
order by date asc;
```

This query ran okay in another install of superset, and works fine in the postgres repl.
