### ISSUE TITLE
[SQL Lab] failed to add a new context variable flask.g.user in the JINJA_CONTEXT_ADDONS

### ISSUE THREAD

**Issue by ganshanshan** [apache/incubator-superset#1702]
Make sure these boxes are checked before submitting your issue - thank you!

- [ yes] I have checked the superset logs for python stacktraces and included it here as text if any
- [ yes] I have reproduced the issue with at least the latest released version of superset
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar

I want to use flask.g.uesr in the Jinja2 temlpate of SQL Lab.But it failed when I config the config.py file, this wokrs okay in the 0.12.0.

config.py:
```
from flask import g
...
JINJA_CONTEXT_ADDONS = {
    'user': g.user, 
}
```
restart server,the error code:
```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/u01/github/rdc-hand-china/superset/superset/bin/superset", line 7, in <module>
    from superset.cli import manager
  File "/u01/github/rdc-hand-china/superset/superset/__init__.py", line 24, in <module>
    app.config.from_object(CONFIG_MODULE)
  File "/usr/localb/python3.5/dist-packages/flask/config.py", line 163, in from_object
    obj = import_string(obj)
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/u01/github/rdc-hand-china/superset/superset/config.py", line 248, in <module>
    'user': g.user, 
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/localb/python3.5/dist-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

### Superset version
0.13.2

### Expected results
Run SQL In SQL lab like：select '{{user.username}}'

### Actual results
failed

### Steps to reproduce
1.config the config.py like ,
```
from flask import g
...
JINJA_CONTEXT_ADDONS = {
    'user': g.user, 
}
```
2.restart the server,but get failed.

```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/u01/github/rdc-hand-china/superset/superset/bin/superset", line 7, in <module>
    from superset.cli import manager
  File "/u01/github/rdc-hand-china/superset/superset/__init__.py", line 24, in <module>
    app.config.from_object(CONFIG_MODULE)
  File "/usr/localb/python3.5/dist-packages/flask/config.py", line 163, in from_object
    obj = import_string(obj)
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/u01/github/rdc-hand-china/superset/superset/config.py", line 248, in <module>
    'user': g.user, 
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/localb/python3.5/dist-packages/Werkzeug-0.11.10-py3.5.egg/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/localb/python3.5/dist-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

**Comment by ganshanshan** [comment]
I fix it. 
1.Add from .. import .. code the jinja_contxt.py
`from flask import g`
 
2.Add context at  row 57 of  jinja_contxt.py
```
self.context = {
     'user': g.user,
  }
```
![_b9 ac 1_g9 wxo 4 k o u](https://cloud.githubusercontent.com/assets/19347709/20699903/dea467aa-b644-11e6-9ed1-4e75c8ccf7de.jpg)

3.restart the server.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 509 days. Feel free to comment and request for this issue to be reopened.
