### ISSUE TITLE
[slicemodelview/list] clicking on `Visualization Type` to sort doesn't work on slice list page

### ISSUE THREAD

**Issue by ascott** [apache/incubator-superset#1776]
`/slicemodelview/list/?_od_SliceModelView=asc&_oc_SliceModelView=viz_type`

*stacktrace*
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/views.py", line 453, in list
    widgets=widgets)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/model/list.html", line 13, in block "content"
    {% block list_list scoped %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/model/list.html", line 15, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/widgets/base_list.html", line 23, in top-level template code
    {% block begin_loop_values %}
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/runtime.py", line 289, in __init__
    self._after = self._safe_next()
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/runtime.py", line 323, in _safe_next
    return next(self._iterator)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/models/base.py", line 87, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/usr/local/lib/python2.7/dist-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/models/base.py", line 44, in _get_attr_value
    return getattr(item, col)()
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/models.py", line 255, in datasource_link
    datasource = self.datasource
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/models.py", line 243, in datasource
    return self.get_datasource
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/utils.py", line 94, in __call__
    value = self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/models.py", line 249, in get_datasource
    self.cls_model).filter_by(
  File "/usr/local/lib/python2.7/dist-packages/superset-0.14.1-py2.7.egg/superset/models.py", line 239, in cls_model
    return SourceRegistry.sources[self.datasource_type]
KeyError: u''
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 502 days. Feel free to comment and request for this issue to be reopened.
