### ISSUE TITLE
Unserializable object True of type

### ISSUE THREAD

**Issue by merkylove** [apache/incubator-superset#1903]
Getting error: 

> Unserializable object True of type

when trying to add boolean field to a Filter chart type.

Superset version 0.15.0

Here is traceback:
```
TypeError: Unserializable object True of type <type 'numpy.bool_'>
2017-01-05 10:43:01,463:ERROR:root:Unserializable object True of type <type 'numpy.bool_'>
Traceback (most recent call last):
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/superset/views.py", line 1388, in explore_json
    payload = viz_obj.get_json()
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/superset/viz.py", line 349, in get_json
    return self.json_dumps(payload)
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/superset/viz.py", line 353, in json_dumps
    return json.dumps(obj, default=utils.json_int_dttm_ser, ignore_nan=True)
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/home/superset/superset_virtualenv/local/lib/python2.7/site-packages/superset/utils.py", line 271, in json_int_dttm_ser
    "Unserializable object {} of type {}".format(obj, type(obj))
TypeError: Unserializable object True of type <type 'numpy.bool_'>
```

**Comment by xrmx** [comment]
Should be fixed in latest master, please try and let us know. Thanks!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 317 days. Feel free to comment and request for this issue to be reopened.
