### ISSUE TITLE
UnicodeEncodeError when show slice record

### ISSUE THREAD

**Issue by raptium** [apache/incubator-superset#1935]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.1

### Expected results
The Slice Page

### Actual results
500 Server Error Page with Stacktrace

```
        Traceback (most recent call last):
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/views.py", line 469, in show
    related_views=self._related_views)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 25, in block "content"
    {% block show_form %}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 27, in block "show_form"
    {{ widgets.get('show')()|safe }}
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/users/guanhao/apps/superset/venv/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/show.html", line 33, in top-level template code
    <td><span style="white-space: pre-line">{{value_columns[loop.index-1]}}</span></td>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

### Steps to reproduce
1. Create a dashboard with name in non-ascii characters, eg. `测试`.
2. Create a slice and add it to the dashboard created above.
3. Click `Show Record` link on the slice list.

**Comment by xrmx** [comment]
Since python3 work fine i'm tempted to start adding `from __future__ import unicode_literals` on top of each file so that we'll handle strings the same way.

**Comment by mistercrunch** [comment]
Using mysql? Tried setting the charset on the connection string as in  `mysql://user:password@1.1.1.1/db?charset=utf8`?

**Comment by yamyamyuo** [comment]
> Using mysql? Tried setting the charset on the connection string as in mysql://user:password@1.1.1.1/db?charset=utf8? @mistercrunch 

this can fix dashboard show record, however, slice show record is still 500 error

**Comment by xrmx** [comment]
@yamyamyuo that's not a fix, which version are you using?

**Comment by yamyamyuo** [comment]
@xrmx I am using superset 0.22.1
If I use chinese characters in dashboard name or slice name , the above issues will show.
I noticed that mysql db data has question mark (?) instead of chinese characters. So I set the mysql charset. This problem is solved after setdefaultencoding.
