### ISSUE TITLE
json.decoder.JSONDecodeError when visualizing queries on Postgres JSONB fields 

### ISSUE THREAD

**Issue by farzadshafiee** [apache/incubator-superset#1985]
When I try to visualize a query on JSONB fields, Superset throws following error: 

```
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 266 (char 265)
```

Here's the query:

```sql
SELECT 
    ((sprime#>>'{summary,items_total}')::int - (s#>>'{summary,items_total}')::int) AS shipping_rebate,
    to_char(submitted_at, 'YYYY-MM-DD')::date as order_date
FROM (
    SELECT "order".branch_id, "order".user_id, "order".id AS order_id, "invoice".id AS invoice_id, payment_type, "order".status, "order".submitted_at, settlement_id, reference, "invoice".manifest->(jsonb_array_length(manifest)-1) AS s, "invoice".manifest->(0) AS sprime
    FROM public.rhn_orders AS "order", public.rhn_customer_invoices AS "invoice"
    WHERE "invoice".invoiceable_id = "order".id 
        AND "invoice".invoiceable_type = 'Order' 
        AND "order".status = 'successful'
) AS "sale" 
```

Query runs successfully: 
<img width="1055" alt="screen shot 2017-01-15 at 3 56 52 pm" src="https://cloud.githubusercontent.com/assets/8026878/21962442/5e9f9aa4-db3b-11e6-9d7d-86b193378e7e.png">

But when I try to visualize it, Superset set throws the following error (full stack trace): 

```
        Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/superset/models.py", line 2348, in wrapper
    value = f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/superset/views.py", line 2214, in sqllab_viz
    data = json.loads(request.args.get('data'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 266 (char 265)
```
I've tried different type casting for each field, tried putting quotes around values, but all failed with exact same error.
If I, for example, run a query to just count the orders (from the same tables with same conditions), I can visualize it. It fails only when I try to query JSONB fields.

Superset Ver.: `0.15.1`

**Comment by xrmx** [comment]
In git master the data get passed with POST instead of GET, maybe that helps? If not please pastebin the content of requests.args.get('data') (requests.form.get('data') on master) from sqllab_viz view.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 459 days. Feel free to comment and request for this issue to be reopened.
