### ISSUE TITLE
ValueError: Could not reserve memory block

### ISSUE THREAD

**Issue by koooge** [apache/incubator-superset#1986]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.1
I used [Docker image (community contributed)](https://github.com/amancevice/superset)

### Actual results
```
2017-01-15 16:05:00,167:INFO:flask_appbuilder.base:Registering class CssTemplateModelView on menu CSS Templates
2017-01-15 16:05:01,151:INFO:flask_appbuilder.base:Registering class CssTemplateAsyncModelView on menu
Loading examples into <SQLA engine='mysql://superset:superset@mysql:3306/superset'>
Creating default CSS templates
Loading energy related dataset
Creating table [wb_health_population] reference
2017-01-15 16:05:04,662:INFO:root:Creating database reference
2017-01-15 16:05:07,795:INFO:root:mysql://superset:superset@mysql:3306/superset
Loading [World Bank's Health Nutrition and Population Stats]
Traceback (most recent call last):
  File "/usr/bin/superset", line 85, in <module>
    manager.run()
  File "/usr/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/superset/cli.py", line 58, in load_examples
    data.load_world_bank_health_n_pop()
  File "/usr/lib/python3.5/site-packages/superset/data/__init__.py", line 174, in load_world_bank_health_n_pop
    pdf = pd.read_json(f)
  File "/usr/lib/python3.5/site-packages/pandas/io/json.py", line 211, in read_json
    date_unit).parse()
  File "/usr/lib/python3.5/site-packages/pandas/io/json.py", line 279, in parse
    self._parse_no_numpy()
  File "/usr/lib/python3.5/site-packages/pandas/io/json.py", line 496, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None)
ValueError: Could not reserve memory block`
```

Does superset require large amount of memory?

### Steps to reproduce
```
% docker-compose up -d redis mysql
% docker-compose up -d superset
% docker-compose exec superset demo
```

**Comment by xrmx** [comment]
How much memory was it using?

**Comment by koooge** [comment]
I used docker on vagrant. Too little?

```
vagrant@debian:~$ cat /proc/meminfo
MemTotal:         506284 kB
```

**Comment by haydenjames** [comment]
Had this issue on 512Mb DO Droplet. :P

Solved by adding swap:
`
fallocate -l 1G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
cp /etc/fstab /etc/fstab.bak
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
`

**Comment by koooge** [comment]
thank you ! :+1:
