### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by amien90** [apache/incubator-superset#2173]
I followed the steps from the site, but i get this error. What 'm missing?

Already tried:

sudo chown -R $USER /usr/local/lib/python2.7

Fixed:

sudo pip install virtualenv
virtualenv --python python3 env
source env/bin/activate

`
Exception:
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/parallels/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/dateutil/__init__.py'

`

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

latest

**Comment by xrmx** [comment]
We don't have any "sudo pip install virtualenv" in the documentation so you are not following the instructions.
python3 already have virtualenv *python3 -m venv venv* will create a virtualenv called *venv*.

**Comment by monothorn** [comment]
For those it still didn't work, try using the flag --no-cache-dir as shown 
`pip --no-cache-dir install superset`

hope it helps!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 216 days. Feel free to comment and request for this issue to be reopened.
