### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2194]
sueprset==0.15.4

I meet the `MySQL server has gone away` issues, but i check my MySQL server is fine:
```
OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (error(32, 'Broken pipe'))") [SQL: u'SELECT ab_role.id AS ab_role_id, ab_role.name AS ab_role_name \nFROM ab_role \nWHERE ab_role.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {u'name_1': 'Public', u'param_1': 1}]
2017-02-17 10:20:11,513:ERROR:sqlalchemy.pool.QueuePool:Exception during reset or similar
Traceback (most recent call last):
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/pool.py", line 774, in _reset
    self._reset_agent.rollback()
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/root/superset/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
  File "/root/superset/lib/python2.7/site-packages/pymysql/connections.py", line 771, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/root/superset/lib/python2.7/site-packages/pymysql/connections.py", line 1054, in _execute_command
    self._write_bytes(packet)
  File "/root/superset/lib/python2.7/site-packages/pymysql/connections.py", line 1006, in _write_bytes
    raise err.OperationalError(2006, "MySQL server has gone away (%r)" % (e,))
```

**Comment by asdf2014** [comment]
But i refresh my website page, `superset` works fine again. That issues has been happened so many times :-(

**Comment by alanmcruickshank** [comment]
MySQL by default kills connections if there is no activity on them for eight hours which could cause issues like this. Try passing a `pool_recycle` argument to the `engine_params` segment of the JSON blob in the Datasource setup page. As per the [documentation for SQLAlchemy](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine), a value of 3600 for pool_recycle will recycle each connection every hour and should prevent this issue from happening.

**Comment by mistercrunch** [comment]
I believe the code here: https://github.com/airbnb/superset/blob/master/superset/utils.py#L418 is supposed to address this, and it does for us. We use the mysqlclient native driver though. I'd recommend trying that.

**Comment by asdf2014** [comment]
U say `MySQL client native driver` meaning this?
`SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://xxx:xxx@yyyy:3306/zzzz?charset=utf8'`

**Comment by asdf2014** [comment]
Maybe, i think it could be a problem in my test MySQL instance. I am already try to use MySQL database cluster with Virtual IP that hold `one master and two backup instances` for product environment.

**Comment by mistercrunch** [comment]
pip install mysqlclient and use plain mysql://

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 415 days. Feel free to comment and request for this issue to be reopened.

**Comment by qin4zhang** [comment]
Same problem happened to me. I will try to `pip install mysqlclient` and use plain `mysql://` for SQLALCHEMY_DATABASE_URI.

**Comment by asdf2014** [comment]
@qin4zhang Does it works?

**Comment by qin4zhang** [comment]
@asdf2014 Should I uninstall PyMySQL? The same problem is still alive after trying native driver.

**Comment by asdf2014** [comment]
Okay, you can give a try.

**Comment by qin4zhang** [comment]
How to check if it will be useful?

**Comment by qin4zhang** [comment]
Oh, `ImportError: No module named pymysql`.
I have installed mysqlclient and change url to `mysql://`
