### ISSUE TITLE
some problems in run_tests.sh

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2196]
superset==0.15.4

(env) [root@superset code]# bash run_tests.sh 
```
rm: cannot remove `/root/.superset/unittests.db\r': No such file or directory
rm: cannot remove `/root/.superset/celerydb.sqlite\r': No such file or directory
rm: cannot remove `/root/.superset/celery_results.sqlite\r': No such file or directory
: invalid optionne 8: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option-name] [arg ...]
Traceback (most recent call last):
  File "/root/env/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/env/code/superset/bin/superset", line 11, in <module>
    from superset.cli import manager
  File "/root/env/code/superset/__init__.py", line 25, in <module>
    app.config.from_object(CONFIG_MODULE)
  File "/root/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 436, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'tests.superset_test_config\r'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'tests' found in '/root/env/code/tests/__init__.pyc'.
- 'tests.superset_test_config\r' not found.

Original exception:

'mportError: 'module' object has no attribute 'superset_test_config
Traceback (most recent call last):
  File "/root/env/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/env/code/superset/bin/superset", line 11, in <module>
    from superset.cli import manager
  File "/root/env/code/superset/__init__.py", line 25, in <module>
    app.config.from_object(CONFIG_MODULE)
  File "/root/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 436, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'tests.superset_test_config\r'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'tests' found in '/root/env/code/tests/__init__.pyc'.
- 'tests.superset_test_config\r' not found.

Original exception:

'mportError: 'module' object has no attribute 'superset_test_config
Traceback (most recent call last):
  File "/root/env/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/env/code/superset/bin/superset", line 11, in <module>
    from superset.cli import manager
  File "/root/env/code/superset/__init__.py", line 25, in <module>
    app.config.from_object(CONFIG_MODULE)
  File "/root/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/root/env/lib/python2.7/site-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/utils.py", line 436, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'tests.superset_test_config\r'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'tests' found in '/root/env/code/tests/__init__.pyc'.
- 'tests.superset_test_config\r' not found.

Original exception:

'mportError: 'module' object has no attribute 'superset_test_config
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
VERSION: 0.15.4
GIT SHA: 1edc2b91cf15f669097939c36c6bc8acef5b5913
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
'nvalid command name 'nosetests
: command not found13: coveralls

```

**Comment by asdf2014** [comment]
Just run `python setup.py nosetests` command, got the issues:
```
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
VERSION: 0.15.4
GIT SHA: 1edc2b91cf15f669097939c36c6bc8acef5b5913
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
```

**Comment by asdf2014** [comment]
(env) [root@superset code]# which python
/root/env/bin/python
(env) [root@superset code]# python -V
Python 2.7.12

**Comment by xrmx** [comment]
It looks like you don't have nose installed but this hunk 

```
: invalid optionne 8: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option-name] [arg ...]
```

makes me think that you lost the the *e* in *set -e*

**Comment by asdf2014** [comment]
I don't understand... The `set -e` command just to keep those following commands running safely, why i should worry about it?

(env) [root@superset code]# cat run_tests.sh
```
#!/usr/bin/env bash
echo $DB
rm ~/.superset/unittests.db
rm ~/.superset/celerydb.sqlite
rm ~/.superset/celery_results.sqlite
rm -f .coverage
export SUPERSET_CONFIG=tests.superset_test_config
set -e
superset/bin/superset db upgrade
superset/bin/superset db upgrade  # running twice on purpose as a test
superset/bin/superset version -v
python setup.py nosetests
coveralls
```

**Comment by asdf2014** [comment]
@xrmx Please tell how to install `nose`, cuz i find nothing in [CONTRIBUTING.md](https://github.com/airbnb/superset/blob/master/CONTRIBUTING.md) :-(

(env) [root@superset env]# uname -a
Linux edeppreapp01 2.6.32-279.el6_sn.7.x86_64 #1 SMP Fri May 27 18:04:25 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

By the way, the `CONTRIBUTING.md` is suit for MAC OS, should we add some contents for other system, like CentOS, Ubuntu etc?

**Comment by xrmx** [comment]
Ah! You have to run tests with "./run_tests.sh" not calling "bash run_tests.sh"

**Comment by asdf2014** [comment]
I see, but i got the issues when i run `./run_tests.sh`:

![image](https://cloud.githubusercontent.com/assets/8108788/23060188/9cb1da6c-f537-11e6-8df4-6c925162eb85.png)

**Comment by xrmx** [comment]
Please add some prints to understand what are you missing.

**Comment by asdf2014** [comment]
Okey...

**Comment by rhunwicks** [comment]
On a fresh install I get the same as @asdf2014 originally reported: when I run `./run_tests.sh` I get:

```
ImportError: module 'tests' has no attribute 'superset_test_config'
```


In my case the problem was that the application source directory isn't on the Python path so when you run `run_tests.sh` it can't locate module `tests`. It works for me if I do

```
export PYTHONPATH=.
./run_tests.sh
```

**Comment by asdf2014** [comment]
@rhunwicks Thanks a lot! :smile:
