### ISSUE TITLE
[sql-lab] unserializable object pandas.tslib.Timedelta

### ISSUE THREAD

**Issue by rumbin** [apache/incubator-superset#2322]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

May be related to #1900?

### Superset version
0.15.4, 0.17.0, 0.17.4, 0.18.4, 0.18.5, 0.19.0, 0.19.1

### Expected results
Calculating differences of two timestamps (on a postgres DB) yields a column of type interval.

### Actual results
The (async) query in SQLLab seems to run endlessly. The stack trace of `superset worker` says `TypeError: Unserializable object 1 days 00:00:00 of type <class 'pandas.tslib.Timedelta'>`

### Steps to reproduce
Run 
`select '2017-01-02'::timestamp - '2017--01-01'::timestamp as t_diff` in SQLLab.

**Comment by xrmx** [comment]
Please post the full backtrace, then please try yo upgrade pandas to the latest release and report back.

**Comment by rumbin** [comment]
Here is the full backtrace with pandas==0.19.2:
```
[2017-03-07 12:45:21,790: INFO/MainProcess] Received task: superset.sql_lab.get_sql_results[881d070f-f286-4f8d-b25f-ce6f450a8df1]
[2017-03-07 12:45:21,879: INFO/Worker-23] Running query:
select '2017-01-02'::timestamp - '2017--01-01'::timestamp as t_diff
[2017-03-07 12:45:21,911: ERROR/MainProcess] Task superset.sql_lab.get_sql_results[881d070f-f286-4f8d-b25f-ce6f450a8df1] raised unexpected: TypeError("Unserializable object 1 days 00:00:00 of type <class 'pandas.tslib.Timedelta'>",)
Traceback (most recent call last):
  File "/opt/apps/superset/venv_py3_superset/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/apps/superset/venv_py3_superset/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/apps/superset/venv_py3_superset/lib/python3.4/site-packages/superset/sql_lab.py", line 152, in get_sql_results
    payload = json.dumps(payload, default=utils.json_iso_dttm_ser)
  File "/usr/lib64/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/opt/apps/superset/venv_py3_superset/lib/python3.4/site-packages/superset/utils.py", line 275, in json_iso_dttm_ser
    "Unserializable object {} of type {}".format(obj, type(obj))
TypeError: Unserializable object 1 days 00:00:00 of type <class 'pandas.tslib.Timedelta'>
```

**Comment by rumbin** [comment]
@xrmx: Picked wrong button… Thanks for reopening!

**Comment by rumbin** [comment]
The bug still exists in superset 0.17.0.

**Comment by rumbin** [comment]
Still present in 0.17.4.

Can anyone else confirm this bug, please, or maybe test whether this is related to the type of database that is being queried?

**Comment by Marigold** [comment]
I believe it's related to this issue https://github.com/airbnb/superset/issues/1929. I'm getting this error too with PostgreSQL when using `TIMESTAMP WITH TIME ZONE` column.

**Comment by rumbin** [comment]
Still present in 0.18.5

**Comment by bauchgefuhl** [comment]
Still present in 0.18.4 (obviously)

**Comment by rumbin** [comment]
Still present in 0.19.1, unfortunately
