### ISSUE TITLE
Time Seriess - Line Chart With __timestamp ERROR

### ISSUE THREAD

**Issue by matrixlibing** [apache/incubator-superset#2341]
When i use Time Seriess - Line Chart , the error happened.
```
2017-03-05 20:20:16,450:ERROR:root:u'__timestamp'

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 258, in get_payload
    data = self.get_data(df)
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 900, in get_data
    values=fd.get('metrics'))
  File "/usr/lib64/python2.7/site-packages/pandas/tools/pivot.py", line 120, in pivot_table
    grouped = data.groupby(keys)
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 3778, in groupby
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 1427, in groupby
    return klass(obj, by, **kwds)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 354, in __init__
    mutated=self.mutated)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 2383, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/usr/lib64/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/usr/lib64/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: u'__timestamp'

parsed sql：
SELECT floor(request_ts/60)*60 AS `__timestamp`,
       COUNT(*) AS `count`
FROM `adx_log`
WHERE floor(request_ts/60)*60 >= 1488140290.0
  AND floor(request_ts/60)*60 <= 1488745090.0
GROUP BY floor(request_ts/60)*60 LIMIT 50000

```
Already have results:
```
pyhive.hive:TFetchResultsResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), results=
TRowSet(rows=[], columns=[TColumn(i32Val=None, byteVal=None, i16Val=None, i64Val=TI64Column(nulls='\x00', values=[1488265200, 1488265260, 1488265320, 1488265380, 14882
65440, 1488265500, 1488265560, 1488265620, 1488265680, 1488265740, 1488265800, 1488265860, 1488265920, 1488265980, 1488266040, 1488266100, 1488266160, 1488266220, 1488
266280, 1488266340, 1488266400, 1488266460, 1488266520, 1488266580, 1488266640, 1488266700, 1488266760, 1488266820, 1488266880, 1488266940, 1488267000, 1488267060, 148
8267120, 1488267180, 1488267240, 1488267300, 1488267360, 1488267420, 1488267480, 1488267540, 1488267600, 1488267660, 1488267720, 1488267780, 1488267840, 1488267900, 14
88267960, 1488268020, 1488268080, 1488268140, 1488268200, 1488268260, 1488268320, 1488268380, 1488268440, 1488268500, 1488268560, 1488268620, 1488268680, 1488268740, 1
488290400, 1488290460, 1488290520, 1488290580, 1488290640, 1488290700, 1488290760, 1488290820, 1488290880, 1488290940, 1488291000, 1488291060, 1488291120, 1488291180,
1488291240, 1488291300, 1488291360, 1488291420, 1488291480, 1488291540, 1488291600, 1488291660, 1488291720, 1488291780, 1488291840, 1488291900, 1488291960, 1488292020,
 1488292080, 1488292140, 1488292200, 1488292260, 1488292320, 1488292380, 1488292440, 1488292500, 1488292560, 1488292620, 1488292680, 1488292740, 1488292800, 1488292860
, 1488292920, 1488292980, 1488293040, 1488293100, 1488293160, 1488293220, 1488293280, 1488293340, 1488293400, 1488293460, 1488293520, 1488293580, 1488293640, 148829370
0, 1488293760, 1488293820, 1488293880, 1488293940, 1488294000]), stringVal=None, boolVal=None, doubleVal=None, binaryVal=None), TColumn(i32Val=None, byteVal=None, i16V
al=None, i64Val=TI64Column(nulls='\x00', values=[7, 2, 11, 4, 9, 7, 4, 2, 9, 3, 13, 3, 13, 7, 12, 6, 3, 6, 5, 7, 9, 5, 8, 5, 10, 2, 7, 3, 7, 8, 7, 8, 4, 11, 10, 6, 7,
5, 8, 7, 5, 8, 4, 10, 6, 4, 6, 2, 6, 5, 7, 6, 9, 5, 9, 6, 9, 6, 10, 5, 31, 38, 28, 22, 28, 19, 22, 25, 25, 38, 17, 33, 24, 25, 30, 19, 28, 18, 30, 21, 27, 24, 21, 30,
30, 25, 25, 28, 30, 27, 15, 17, 24, 28, 31, 27, 19, 20, 18, 24, 17, 30, 11, 18, 21, 28, 20, 23, 16, 13, 20, 19, 8, 21, 21, 17, 21, 18, 17, 16, 1]), stringVal=None, boo
lVal=None, doubleVal=None, binaryVal=None)], startRowOffset=0), hasMoreRows=False)
```
### Superset version
pip install superset
version : superset (0.17.0)

### Expected results
x : request_ts  is a time series,formated as HH:mm
y : count(*) 

### Actual results
u'__timestamp'

### Steps to reproduce
1， select a column A  ( type bigint in hive: such as 1488292459 s ) as temporal
2 ,  In Edit sqla table, list table column  , edit A.
     Expression  =>  floor(A/60)*60
     Datetime Format => epoch_s
3 ,  
 show  (time, number) using Time Seriess - Line Chart.

Error :  __timestamp

**Comment by xrmx** [comment]
Please follow the issue template, which version of superset is this?

**Comment by xrmx** [comment]
Looks like a dup of https://github.com/airbnb/superset/issues/953 though

**Comment by matrixlibing** [comment]
pip install superset
version: superset (0.17.0)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 413 days. Feel free to comment and request for this issue to be reopened.
