### ISSUE TITLE
ERROR:root:Failed to parse: None:None

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-superset#2360]
superset==0.17.0

__superset refresh_druid__
```
2017-03-07 15:29:41,316:ERROR:root:Failed to parse: None:None
Traceback (most recent call last):
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/superset/cli.py", line 139, in refresh_druid
    merge_flag=merge)
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/superset/models.py", line 1670, in refresh_datasources
    self.druid_version = self.get_druid_version()
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/superset/models.py", line 1664, in get_druid_version
    return json.loads(requests.get(endpoint).text)['version']
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/home/superset/superset-0.17.0/lib/python2.7/site-packages/requests/models.py", line 376, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: None:None
Refreshed metadata from cluster [druid_test]
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 411 days. Feel free to comment and request for this issue to be reopened.
