### ISSUE TITLE
Sql editor query "no such table"

### ISSUE THREAD

**Issue by Jareechang** [apache/incubator-superset#2391]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
version 0.17

Database: Sqlite3

### Expected results
Should be able to query sample data tables from fresh installs

### Actual results
Superset throws error and says no table exist when querying sample data

### Steps to reproduce
1. Fresh install — steps in tutorial
2. Visit superset (sqlab) http://0.0.0.0:8080/sqllab
3. select `main` as database and schema
4. Use the sample table `energy_usage`
5. Copy Query from table 
6. Insert into editor and Run Query

### Supplementary (Logs)

**superset Backend**:
```
2017-03-12 22:42:58,011:WARNING:root:timeout can't be used in the current context
2017-03-12 22:42:58,011:ERROR:root:signal only works in main thread
Traceback (most recent call last):
  File "/Users/Jerry/opensource/superset/superset/utils.py", line 405, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
ValueError: signal only works in main thread
db URI sqlite:////Users/Jerry/.superset/superset.db
2017-03-12 22:42:58,039:INFO:root:Running query: 
SELECT source,
       target,
       value
FROM main.energy_usage LIMIT 100
OFFSET 0
2017-03-12 22:42:58,047:ERROR:root:no such table: main.energy_usage
Traceback (most recent call last):
  File "/Users/Jerry/opensource/superset/superset/sql_lab.py", line 115, in get_sql_results
    query.executed_sql, **db_engine_spec.cursor_execute_kwargs)
OperationalError: no such table: main.energy_usage
2017-03-12 22:42:58,058:ERROR:root:no such table: main.energy_usage
Traceback (most recent call last):
  File "/Users/Jerry/opensource/superset/superset/views/core.py", line 2032, in sql_json
    data = sql_lab.get_sql_results(query_id, return_results=True)
  File "/Users/Jerry/opensource/superset/env/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/Jerry/opensource/superset/env/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/Jerry/opensource/superset/superset/sql_lab.py", line 119, in get_sql_results
    handle_error(db_engine_spec.extract_error_message(e))
  File "/Users/Jerry/opensource/superset/superset/sql_lab.py", line 70, in handle_error
    raise Exception(query.error_message)
Exception: no such table: main.energy_usage
```

**Comment by zhangjiajie023** [comment]
delete the schema 'main' you selected in the left Select box

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 405 days. Feel free to comment and request for this issue to be reopened.

**Comment by dsidlo** [comment]
After renaming an sqllite table to a new name, all charts refering to the original table failed  to query the table with a "no such table" error. In SqlLab, under the "main" schema, the table had the old name, in the tables drop-down.
