### ISSUE TITLE
superset + firebird problem

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#2452]
Greetings to all. 

I'm having a problem with the firebird database.

- [+ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ +] I have reproduced the issue with at least the latest released version of superset
- [ +] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
version: 0.17.1

 First, I created a connection to the firebird database (firebird: // sysdba: XXXXXXXXXX@192.168.2.15: 3050 / C: / BD / BD). The connection was successful. I saw part of some of the tables from my database. 

![default](https://cloud.githubusercontent.com/assets/11568424/24199854/cea1a39a-0f13-11e7-9776-8948439fdd8e.png)

Then I tried to make a simple query in the sql editor (select * from users) but an error occurred.

![default](https://cloud.githubusercontent.com/assets/11568424/24199984/35dab09c-0f14-11e7-8823-c505ebef0cf6.png)

from terminal logs

```
2017-03-22 15:31:50,175:INFO:root:Running query:
SELECT * from users
2017-03-22 15:31:50,258:INFO:root:Handling cursor
2017-03-22 15:31:50,262:INFO:root:Fetching data: {u'changedOn': datetime.datetime(2017, 3, 22, 13, 31, 50, 257222), u'tempTable': u'', u'userId': 1, u'executedSql': u'SELECT * from users', u'ctas': False, u'tab': u'Untitled Query', u'sqlEditorId': u'r1ZlOiJne', u'id': u'H1n6hgl2g', u'changed_on': '2017-03-22T13:31:50.257222', u'rows': None, u'endDttm': None, u'limit_reached': False, u'state': u'running', u'progress': 0, u'schema': None, u'dbId': 3, u'errorMessage': None, u'db': u'asu', u'user': u'admin', u'sql': u'SELECT * from users', u'startDttm': Decimal('1490189510133.7580566406'), u'limit': 1000000, u'serverId': 9, u'resultsKey': None}
2017-03-22 15:31:50,859:ERROR:root:0 columns passed, passed data had 12 columns
Traceback (most recent call last):
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/views/core.py", line 2043, in sql_json
    data = sql_lab.get_sql_results(query_id, return_results=True)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/sql_lab.py", line 145, in get_sql_results
    list(data), columns=column_names))
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/pandas/core/frame.py", line 263, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/pandas/core/frame.py", line 5352, in _to_arrays
    dtype=dtype)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/pandas/core/frame.py", line 5431, in _list_to_arrays
    coerce_float=coerce_float)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/pandas/core/frame.py", line 5489, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 0 columns passed, passed data had 12 columns
```

If I try to write a query like this (select * from asu.users), a Firebird base error occurs.

![default](https://cloud.githubusercontent.com/assets/11568424/24200061/7cdb05e6-0f14-11e7-9e47-4e53b1e65d42.png)

But I can create a table, and then a slice.
![default](https://cloud.githubusercontent.com/assets/11568424/24200471/d7fdc0c0-0f15-11e7-8780-ddda39d9c0b3.png)

![default](https://cloud.githubusercontent.com/assets/11568424/24200566/239f78d4-0f16-11e7-86da-56143c54d3f2.png)

Problem in the sql editor

At the same time, there were no problems with the mysql database.

 Thanks for the help.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 397 days. Feel free to comment and request for this issue to be reopened.
