### ISSUE TITLE
bug with quotes (create slice)

### ISSUE THREAD

**Issue by bbs2009** [apache/incubator-superset#2590]
Make sure these boxes are checked before submitting your issue - thank you!

- [+] I have checked the superset logs for python stacktraces and included it here as text if any
- [+] I have reproduced the issue with at least the latest released version of superset
- [] I have checked the issue tracker for the same issue and I haven't found one similar

similar #2588

### Superset version
{"GIT_SHA": "", "version": "0.17.4"}

### Expected results
Workable visualization

### Actual results
1. sql qwery

`SELECT 
       "IDSTUDENT",
       "STUDENTFIO",
       "STUDENTGROUP",
       "STUDENTCOURSE",
       "IDDEPARTMENT",
       "DEPARTMENT",
       "SPEC",
       date_trunc('day',"DATELOGIN") as ddtm
FROM public.student_logins LIMIT 100`

![default](https://cloud.githubusercontent.com/assets/11568424/24908438/b34ef56a-1ec8-11e7-9556-9c2750b2ac91.png)

2. i try create slice
![default](https://cloud.githubusercontent.com/assets/11568424/24908518/f7c9beb4-1ec8-11e7-91ea-e21c2b34e47b.png)

One value without quotes is passed to the query. I think the problem is this

in terminal 

```

2017-04-11 15:12:28,323:INFO:root:SELECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTMENT) AS "count_distinct__IDDEPARTMENT"
FROM (SELECT
       "IDSTUDENT",
       "STUDENTFIO",
       "STUDENTGROUP",
       "STUDENTCOURSE",
       "IDDEPARTMENT",
       "DEPARTMENT",
       "SPEC",
       date_trunc('day',"DATELOGIN") as ddtm
FROM public.student_logins LIMIT 100) AS expr_qry
WHERE ddtm >= '1917-04-11 15:12:28' AND ddtm <= '2017-04-11 15:12:28' GROUP BY "DEPARTMENT" ORDER BY "count_distinct__IDDEPARTMENT" DESC
 LIMIT 10000000
2017-04-11 15:12:28,408:ERROR:root:(psycopg2.ProgrammingError) column "iddepartment" does not exist
LINE 1: ...LECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTME...
                                                             ^
 [SQL: 'SELECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTMENT) AS "count_distinct__IDDEPARTMENT" \nFROM (SELECT \n       "IDSTUDENT",\n       "STUDENTFIO",\n       "STUDENTGROUP",\n       "STUDENTCOURSE",\n       "IDDEPARTMENT",\n       "DEPARTMENT",\n       "SPEC",\n       date_trunc(\'day\',"DATELOGIN") as ddtm\nFROM public.student_logins LIMIT 100) AS expr_qry \nWHERE ddtm >= \'1917-04-11 15:12:28\' AND ddtm <= \'2017-04-11 15:12:28\' GROUP BY "DEPARTMENT" ORDER BY "count_distinct__IDDEPARTMENT" DESC \n LIMIT %(param_1)s'] [parameters: {'param_1': 10000000}]
Traceback (most recent call last):
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "iddepartment" does not exist
LINE 1: ...LECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTME...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 544, in query
    df = pd.read_sql_query(qry, con=engine)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/pandas/io/sql.py", line 431, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/pandas/io/sql.py", line 1190, in read_query
    result = self.execute(*args)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/pandas/io/sql.py", line 1081, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2055, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/data/work/virtualenvs/superset3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "iddepartment" does not exist
LINE 1: ...LECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTME...
                                                             ^
 [SQL: 'SELECT "DEPARTMENT" AS "DEPARTMENT", COUNT(DISTINCT IDDEPARTMENT) AS "count_distinct__IDDEPARTMENT" \nFROM (SELECT \n       "IDSTUDENT",\n       "STUDENTFIO",\n       "STUDENTGROUP",\n       "STUDENTCOURSE",\n       "IDDEPARTMENT",\n       "DEPARTMENT",\n       "SPEC",\n       date_trunc(\'day\',"DATELOGIN") as ddtm\nFROM public.student_logins LIMIT 100) AS expr_qry \nWHERE ddtm >= \'1917-04-11 15:12:28\' AND ddtm <= \'2017-04-11 15:12:28\' GROUP BY "DEPARTMENT" ORDER BY "count_distinct__IDDEPARTMENT" DESC \n LIMIT %(param_1)s'] [parameters: {'param_1': 10000000}]
2017-04-11 15:12:28,416:INFO:root:Caching for the next 86400 seconds

```

Many thanks

**Comment by xrmx** [comment]
Could you please replicate with latest master?

**Comment by bbs2009** [comment]
Unfortunately, it still does not work

![default](https://cloud.githubusercontent.com/assets/11568424/25000531/55e15dd6-204a-11e7-981a-3d0bcee21a5f.png)

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 374 days. Feel free to comment and request for this issue to be reopened.
