### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 4

### ISSUE THREAD

**Issue by zhangjiajie023** [apache/incubator-superset#2600]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
change the metadata db from db2 to previous db1 can work 

### Actual results
after changing to db1, exists the encoding error

### Steps to reproduce
1. add `?charset=utf8` in `sqlalchemy_database_uri` , and `create database db1 character set utf8`,
use db1 as the metadata db, works
2. add `?charset=utf8` in `sqlalchemy_database_uri` , and `create database db2 character set utf8`,
use db2 as the metadata db, works
3. ##### change the `sqlalchemy_database_uri `from db2 to db1
4. view a slice or use SQL Lab, occur the encoding bug

#### python3.5   superset 0.15.4  mysql 5.7

```
File "/home/jiajie/project/superset/superset/superset/views.py", line 1588, in explore
    datasources = sorted(datasources, key=lambda ds: ds.full_name)
  File "/home/jiajie/project/superset/superset/superset/views.py", line 1588, in <lambda>
    datasources = sorted(datasources, key=lambda ds: ds.full_name)
  File "/home/jiajie/project/superset/superset/superset/models.py", line 1155, in full_name
    self.database, self.table_name, schema=self.schema)
......................
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "\<string\>", line 1, in \<lambda\>
    
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/orm/strategies.py", line 603, in _emit_lazyload
    return loading.load_on_ident(q, ident_key)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  .......
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/orm/loading.py", line 75, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.1.5.dev0-py3.5-linux-x86_64.egg/sqlalchemy/orm/loading.py", line 75, in <listcomp>
    rows = [proc(row) for row in fetch]
 ....................
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy_utils/types/encrypted.py", line 261, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy_utils/types/encrypted.py", line 89, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 4: invalid continuation byte
```

**Comment by xrmx** [comment]
Could you please replicate using utf8mb4 as character set instead of utf8?

**Comment by zhangjiajie023** [comment]
@xrmx ok,  i'll try， tks. But still amazing

**Comment by kkalyan** [comment]
this is a workaround you can use - convert the utf field to ascii using mysql expression in the edit dimension. 

![image](https://cloud.githubusercontent.com/assets/391567/25008502/bfc944ac-2018-11e7-9db6-82518af18f3e.png)

**Comment by timfeirg** [comment]
Just upgraded superset to python 3.6 today, had the same problem, adding `?charset=utf8mb4` to `SQLALCHEMY_DATABASE_URI` and it's fixed @xrmx @zhangjiajie023

**Comment by xrmx** [comment]
@timfeirg does `?charset=utf8mb4` work too?

**Comment by timfeirg** [comment]
yes, adding `?charset=utf8mb4` fixed this exact problem in my case. @xrmx

**Comment by xrmx** [comment]
@timfeirg sorry, typo :) i meant `?charset=utf8` without the `mb4`

**Comment by timfeirg** [comment]
I'm sorry, I just tried both `?charset=utf8` and `?charset=utf8mb4` using superset under python3.6.1, and open up the example charts provided by superset, for example `superset/dashboard/misc_charts/`, and the request ended up with the same `UnicodeDecodeError` as described in this issue.

If I switch back to python2.7, the example charts would work fine.

[this comment](https://github.com/airbnb/superset/issues/2600#issuecomment-299905182) was a mistake, @xrmx

**Comment by xrmx** [comment]
I'm hitting this too when upgrading a sqlite installation from caravel to superset, both python3.4.

**Comment by xrmx** [comment]
@zhangjiajie023 @timfeirg This to me was caused by having in the config a SECRET_KEY different than the one used to encrypt the password.

**Comment by jerryhall** [comment]
I've been down for some time. I checked the security key and am using same one as with 2.7. 
I upgraded to 3.6 and tried appending the sqlalchemy to this:
`SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(DATA_DIR, 'superset.db?charset=utf8')`
with no luck & I get this error message:
`2017-08-15 02:19:26,671:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: 'charset' is an invalid keyword argument for this function`

Any help would be appreciated!

**Comment by mistercrunch** [comment]
We don't recommend using sqlite in production. Also we don't build against python 3.6 (yet). Might be safer/easier to run py3.4 on against mysql

**Comment by xrmx** [comment]
@mistercrunch it's not an unicode issue, it is trying to decode encrypted data with the wrong key. I've opened a PR raising an intelligible error upstream but i forgot to update it.

**Comment by xrmx** [comment]
@jerryhall I don't think sqlite takes a charset option

**Comment by bmackattack** [comment]
@xrmx any solutions on this?  I believe I'm running into the same error....  Stack trace as follows:
`Loaded your LOCAL configuration at [/usr/local/bin/superset_config.py]
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/superset/security.py", line 92, in get_or_create_main_db
2017-08-31T14:27:13Z  Traceback (most recent call last):
2017-08-31T14:27:13Z      manager.run()
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
2017-08-31T14:27:13Z      result = self.handle(sys.argv[0], sys.argv[1:])
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
2017-08-31T14:27:13Z      res = handle(*args, **config)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
2017-08-31T14:27:13Z      return self.run(*args, **kwargs)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/superset/cli.py", line 28, in init
2017-08-31T14:27:13Z      security.sync_role_definitions()
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/superset/security.py", line 201, in sync_role_definitions
2017-08-31T14:27:13Z      get_or_create_main_db()
2017-08-31T14:27:13Z    File "/usr/local/bin/superset", line 15, in <module>
2017-08-31T14:27:13Z      .filter_by(database_name='main')
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2755, in first
2017-08-31T14:27:13Z      ret = list(self[0:1])
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
2017-08-31T14:27:13Z      return list(res)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
2017-08-31T14:27:13Z      util.raise_from_cause(err)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-08-31T14:27:13Z      reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
2017-08-31T14:27:13Z      raise value
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
2017-08-31T14:27:13Z      rows = [proc(row) for row in fetch]
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 75, in <listcomp>
2017-08-31T14:27:13Z      loaded_instance, populate_existing, populators)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 437, in _instance
2017-08-31T14:27:13Z  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 498, in _populate_full
2017-08-31T14:27:13Z      dict_[key] = getter(row)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 1122, in process
2017-08-31T14:27:13Z      return process_value(impl_processor(value), dialect)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted.py", line 261, in process_result_value
2017-08-31T14:27:13Z      decrypted_value = self.engine.decrypt(value)
2017-08-31T14:27:13Z    File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted.py", line 89, in decrypt
2017-08-31T14:27:13Z      decrypted = decrypted.decode('utf-8')`

**Comment by xrmx** [comment]
@bmackattack if you are using the wrong key the only solution is to use the right one, you are the only one who knows it. My patch just makes the error explicit.

**Comment by jhult** [comment]
Here is how I was able to fix this: https://github.com/apache/superset/issues/8538#issuecomment-922061313
