### ISSUE TITLE
dashboard export issue

### ISSUE THREAD

**Issue by xyhc** [apache/incubator-superset#2667]
Sorry, something went wrong

500 - Internal Server Error

Stacktrace

```
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/python27/lib/python2.7/site-packages/flask_appbuilder/views.py", line 533, in action
    return action.func(self.datamodel.get(pk))
  File "/usr/local/python27/lib/python2.7/site-packages/superset/views.py", line 957, in mulexport
    ids = ''.join('&id={}'.format(d.id) for d in items)
TypeError: 'Dashboard' object is not iterable
```

**Comment by xrmx** [comment]
Which version of superset?

**Comment by xyhc** [comment]
0.15.1

**Comment by xrmx** [comment]
Please reproduce with latest version

**Comment by xyhc** [comment]
I try it ,  thanks!

**Comment by xyhc** [comment]
I upgrade the superset to 0.17.5 ,  but the issue is the same as before.

**Comment by eeve** [comment]
https://github.com/airbnb/superset/blob/master/superset/views/core.py#L474

```
@action("mulexport", __("Export"), __("Export dashboards?"), "fa-database")
    def mulexport(self, items):
```
seem Items are the title of the dashboard , Not Dashboard object

http://flask-appbuilder.readthedocs.io/en/latest/actions.html?highlight=action

**Comment by XavierDeLapeyre** [comment]
Hi all

I am on 0.21.x ( 0.21.0Dev and 0.21.1 )
Where can I find the export Dashboard feature? ( I don't see it anywhere, found the import Dashboard though )

**Comment by mistercrunch** [comment]
<img width="384" alt="screen shot 2017-12-13 at 9 26 56 pm" src="https://user-images.githubusercontent.com/487433/33976819-61c75d5e-e04c-11e7-81de-d5bcbefd569f.png">
