### ISSUE TITLE
Could not build npm on Mac

### ISSUE THREAD

**Issue by lujianmei** [apache/incubator-superset#2752]
Dear,
I got error and could not be able to solve it, and following is the debug log. Please kindly help to find out. Thanks.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.5.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle superset@0.17.6~prebuild: superset@0.17.6
6 silly lifecycle superset@0.17.6~prebuild: no script for prebuild, continuing
7 info lifecycle superset@0.17.6~build: superset@0.17.6
8 verbose lifecycle superset@0.17.6~build: unsafe-perm in lifecycle true
9 verbose lifecycle superset@0.17.6~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kevin/workspace/github/superset/superset/assets/node_modules/.bin:/bin:/sbin:/bin:/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/bin/:/bin:/usr/sbin/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/bin/:/bin/:/bin:/usr/local/cellar/python3/3.5.0/bin:/usr/local/texlive/2015/bin/x86_64-darwin:/usr/local/texlive/2015/texmf-dist/doc/man:/usr/local/texlive/2015/texmf-dist/doc/info:/bin:/::/usr/local/Cellar/ruby/2.2.3/bin:/Users/kevin/.gem/bin::/Users/kevin/develop/android/android-sdk-mac/platform-tools/:/Users/kevin/develop/android/android-sdk-mac/tools/:/Users/kevin/develop/android/android-ndk-r10e:/Users/kevin/develop/apache-ant-1.9.4//bin:/Applications/Docker.app/Contents/Resources/bin:
10 verbose lifecycle superset@0.17.6~build: CWD: /Users/kevin/workspace/github/superset/superset/assets
11 silly lifecycle superset@0.17.6~build: Args: [ '-c', 'NODE_ENV=production webpack --colors --progress' ]
12 silly lifecycle superset@0.17.6~build: Returned: code: 2  signal: null
13 info lifecycle superset@0.17.6~build: Failed to exec build script
14 verbose stack Error: superset@0.17.6 build: `NODE_ENV=production webpack --colors --progress`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid superset@0.17.6
16 verbose cwd /Users/kevin/workspace/github/superset/superset/assets
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v7.10.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 2
23 error superset@0.17.6 build: `NODE_ENV=production webpack --colors --progress`
23 error Exit status 2
24 error Failed at the superset@0.17.6 build script 'NODE_ENV=production webpack --colors --progress'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the superset package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     NODE_ENV=production webpack --colors --progress
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs superset
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls superset
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by yagrawal3** [comment]
I have pretty much similar issue:
```
[2232] multi babel-polyfill ./javascripts/dashboard/Dashboard.jsx 40 bytes {0} [built]
[2233] multi babel-polyfill ./javascripts/explorev2/index.jsx 40 bytes {1} [built]
[2234] multi babel-polyfill ./javascripts/profile/index.jsx 40 bytes {3} [built]
[2235] multi babel-polyfill ./javascripts/welcome.js 40 bytes {4} [built]
    + 2221 hidden modules

ERROR in ./~/css-loader!./~/less-loader/dist!./stylesheets/react-select/select.less
Module build failed:
	&:hover {
		box-shadow: @select-input-hover-box-shadow;
            ^
Variable @select-input-hover-box-shadow is undefined
      in ~/superset/superset/assets/node_modules/react-select/less/control.less (line 64, column 14)
 @ ./stylesheets/react-select/select.less 4:14-124
 @ ./javascripts/css-theme.js

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.18.0-alpha.3 build: `NODE_ENV=production webpack --colors --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the superset@0.18.0-alpha.3 build script 'NODE_ENV=production webpack --colors --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --colors --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

Steps done:
```
cd $SUPERSETHONE/superset/assets
npm install
num run build
```

**Comment by vincentwongso** [comment]
Seems to be working fine for me on latest superset:
```
npm install
npm run prod
```

**Comment by mistercrunch** [comment]
Can't reproduce, idk much about `npm run` but I'm wondering if it could be conflicting with an older webpack version? Perhaps you installed an older webpack globally and the `npm run` command refers to that version instead of the one in Superset's node_modules?

**Comment by yagrawal3** [comment]
Yes. it worked fine for me too with latest superset version. 

However, there are issues when I try to build it on a machine with no access to github or public registry. There are some references to direct github for "supercluster" and "gridster".

**Comment by fufjvnvnf** [comment]
Did you try deleting everything under node_modules folder and try `npm install` again?

**Comment by mistercrunch** [comment]
@yagrawal3 gridster shouldn't be in the dependencies anymore. Supercluster is another story. It would require some work to align on their latest release as our PR to them didn't get upstreamed.

**Comment by yagrawal3** [comment]
@fufjvnvnf yeah. I deleted everything under node_modules and tried again but it didn't work. 

@mistercrunch i see. will wait for Supercluster fix. thanks for heads up.

**Comment by caoxiaozh** [comment]
@yagrawal3 Did you solve the problem? 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! superset@0.18.5 prod: `NODE_ENV=production node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js -p --colors --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the superset@0.18.5 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-06-29T12_18_52_901Z-debug.log
```

**Comment by yagrawal3** [comment]
@caoxiaozh - no luck so far. It builds fine on local machine but on build machines, I get errors due to external dependencies.

**Comment by fufjvnvnf** [comment]
@yagrawal3 Don't build it on your remote machines; run the pypi script on your local machine, then go to the dist folder and upload the newly created tar file to your remote server, then go to your server to unzip the file and run python install.

**Comment by claireliumo** [comment]
@hardy4yooz have u solved the problem?

**Comment by mistercrunch** [comment]
You can use Python setup tools to build a tarball that contains the JS and that you can then deploy that tarball.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 195 days. Feel free to comment and request for this issue to be reopened.
