### ISSUE TITLE
superset not displaying progress and waiting for pyhive results

### ISSUE THREAD

**Issue by santhavathi** [apache/incubator-superset#2759]
Make sure these boxes are checked before submitting your issue - thank you!

- [ Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y ] I have reproduced the issue with at least the latest released version of superset
- [ Y ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18

### Expected results
Results are not displayed after running the query in sql lab

### Actual results
2017-05-15 06:13:34,049:DEBUG:pyhive.hive:TFetchResultsResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), results=TRowSet(rows=[], columns=[TColumn(i32Val=None, byteVal=None, i16Val=None, i64Val=None, stringVal=TStringColumn(nulls='\x00', values=[]), boolVal=None, doubleVal=None, binaryVal=None)], startRowOffset=0), hasMoreRows=False)
```
2017-05-15 05:11:57,471:ERROR:root:
Traceback (most recent call last):
  File "/home/ubuntu/environments/superset/local/lib/python2.7/site-packages/superset/sql_lab.py", line 138, in get_sql_results
    db_engine_spec.handle_cursor(cursor, query, session)
  File "/home/ubuntu/environments/superset/local/lib/python2.7/site-packages/superset/db_engine_specs.py", line 724, in handle_cursor
    resp = cursor.fetch_logs()
  File "/home/ubuntu/environments/superset/local/lib/python2.7/site-packages/superset/db_engines/hive.py", line 34, in fetch_logs
    response.results.rows, 'expected data in columnar format'
AssertionError
```

### Steps to reproduce
virtualenv superset
. ./superset/bin/activate
pip install --upgrade setuptools pip
pip install superset
pip install MySQL-python
pip install pythrifthiveapi
fabmanager create-admin --app superset
superset db upgrade
superset init

Run a query that will take more than 6-7 secs to give the output
The above error is displayed, though the query is actively running in the background.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 343 days. Feel free to comment and request for this issue to be reopened.

**Comment by Jason-Song** [comment]
set async execute option of data source = False,then execute success
