### ISSUE TITLE
use sql lab to mysql 

### ISSUE THREAD

**Issue by will0815** [apache/incubator-superset#2772]
When  i use SQL Lab to mysql, exception like this:
```
2017-05-17 21:46:10,192:INFO:root:Triggering query_id: 56
/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/sql/sqltypes.py:596: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
2017-05-17 21:46:10,838:ERROR:root:[Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/utils/__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/connection.py", line 449, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/utils/__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/connection.py", line 771, in default_channel
    self.connection
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/python3.5/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/python3.5/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/usr/local/python3.5/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/usr/local/python3.5/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/python3.5/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 111] Connection refused
```

**Comment by xrmx** [comment]
Wrong celery configuration?

**Comment by mistercrunch** [comment]
Yup, looks like you can't connect to your broker. Usually for MySQL we don't expect long running queries and you don't have to use/setup the "results backend". If that is the case you can uncheck the "Run Async Queries" checkbox in your database configuration

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 341 days. Feel free to comment and request for this issue to be reopened.
