### ISSUE TITLE
Failure while pulling clickhouse table with datetime (DatetimeTZDtype has no attribute 'char')

### ISSUE THREAD

**Issue by neeraj9** [apache/incubator-superset#2791]
While pulling data from clickhouse within superset things work as long as fields are not of type datetime. When trying to get data for a datetime column then it gives the following python error.

`AttributeError: 'DatetimeTZDtype' object has no attribute 'char'`

### Superset version

`{
GIT_SHA: "",
version: "0.18.2"
}`

### Expected results

SQL query should give all the columns for give query.

### Actual results

Python error (see below).

```
2017-05-22 10:32:10,890:ERROR:root:'DatetimeTZDtype' object has no attribute 'char'
Traceback (most recent call last):
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/superset/views/core.py", line 2028, in sql_json
    query_id=query_id, return_results=True)
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/superset/sql_lab.py", line 181, in get_sql_results
    'columns': cdf.columns if cdf.columns else [],
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/superset/dataframe.py", line 108, in columns
    col_db_type = self.db_type(self.__df.dtypes[col])
  File "/home/neeraj/Apps/superset-env/local/lib/python2.7/site-packages/superset/dataframe.py", line 55, in db_type
    return cls.type_map.get(dtype.char)
AttributeError: 'DatetimeTZDtype' object has no attribute 'char'
```

### Steps to reproduce

1. Create the following table in clickhouse.

```
CREATE TABLE gauge_metric
(
    EventDate Date,
    Timestamp DateTime,
    Node String,
    Name String,
    Value Float32
) ENGINE = MergeTree(EventDate, (Name, Node, Timestamp), 8192);
```

2. Insert some data into the above table.

3. Install [sqlalchemy-clickhouse](https://github.com/cloudflare/sqlalchemy-clickhouse) along with [superset](https://github.com/airbnb/superset).

4. Add clickhouse as datasource with "clickhouse://<ip>:8123" as the SQLAlchemy URI.

5. Open SQL Lab and try executing the following query.

`select EventDate,Node,Value,Timestamp,Name from dbname.gauge_metric LIMIT 10;`

**Comment by RichRadics** [comment]
This is a Pandas bug: https://github.com/pandas-dev/pandas/issues/12985
A workaround is to use `toString(Timestamp)`. If you need to have Timestamp as a datetime data type for slices, then use the toString version to initially create the table in Superset, then edit the definition to take out the `toString` and change the column to a DATETIME data type.

**Comment by fabianmenges** [comment]
#2937 should fix this

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 213 days. Feel free to comment and request for this issue to be reopened.
