### ISSUE TITLE
[error] Database no longer recognized by Superset (error 500)

### ISSUE THREAD

**Issue by DuffautM** [apache/incubator-superset#2966]
### Superset version
0.18.2

### OS 
Ubuntu 14.04

### Expected Results
Access to the dashboards depending on our current database.
Also, access to the Database Tab.

### Outcome
An 500 type error as seen in the error message below.

### Issue 

Using Superset for 2 or 3 weeks now, a problem recently appeared : 
The database we were using was no more recognized by the software, every time we try to access the Database Tab or using the involved Dashboards, we get the following error message : 

```
Sorry, something went wrong

500 - Internal Server Error

Stacktrace

         Traceback (most recent call last):
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/superset/venvsset/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/superset/venvsset/lib/python3.4/site-packages/superset/models/core.py", line 754, in wrapper
    value = f(*args, **kwargs)
  File "/root/superset/venvsset/lib/python3.4/site-packages/superset/utils.py", line 572, in wraps
    return f(self, *args, **kwargs)
  File "/root/superset/venvsset/lib/python3.4/site-packages/superset/views/core.py", line 1011, in explore
    if not self.datasource_access(datasource):
  File "/root/superset/venvsset/lib/python3.4/site-packages/superset/views/base.py", line 95, in datasource_access
    self.schema_access(datasource, user=user) or
  File "/root/superset/venvsset/lib/python3.4/site-packages/superset/views/base.py", line 88, in schema_access
    self.database_access(datasource.database, user=user) or
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 603, in _emit_lazyload
    return loading.load_on_ident(q, ident_key)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
    util.raise_from_cause(err)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    rows = [proc(row) for row in fetch]
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 75, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 437, in _instance
    loaded_instance, populate_existing, populators)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 498, in _populate_full
    dict_[key] = getter(row)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/engine/result.py", line 93, in __getitem__
    return processor(self._row[index])
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy/sql/type_api.py", line 1122, in process
    return process_value(impl_processor(value), dialect)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy_utils/types/encrypted.py", line 261, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/root/superset/venvsset/lib/python3.4/site-packages/sqlalchemy_utils/types/encrypted.py", line 89, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte
```

What's more, the database created with `superset load_examples` is still working, its dashboards are still operating but we can't see it in SQL Lab.

**Comment by xrmx** [comment]
What database is this and what's your connection string?

**Comment by DylanCa** [comment]
It is a distant Database, not a local one, and our connection string is `SQLALECHEMY_DATABASE_URI = 'mysql://xxx:Zu64b3UMYbYzAzy@xxx.xxx.com:3306/xxx?charset=utf8'`

I want to add that we got this [GET] Exception : Exception on /superset/queries/1497429367303 [GET]

( I'm working with @DuffautM IRL )

**Comment by hzy1992** [comment]
Try to set the datasource 'Extra':
`{
    "metadata_params": {},
    "engine_params": { "connect_args": {         "charset": "utf8"        }}
}
`

**Comment by jerryhall** [comment]
@hzy1992 Where does one put the datasource setting 'Extra' that you recommended? I'm having the exact problem, tried the charset in the string which didn't work for me either. Thanks!

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 283 days. Feel free to comment and request for this issue to be reopened.
