### ISSUE TITLE
TypeError: unorderable types: str() > int() on specific distribution bar chart slice

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#3029]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

the slice loads fine, as it did in caravel 0.14.X

### Actual results

```
2017-06-23 15:36:22,271:ERROR:root:unorderable types: str() > int()
Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/superset/viz.py", line 240, in get_payload
    data = self.get_data(df)
  File "/venv/lib/python3.4/site-packages/superset/viz.py", line 1095, in get_data
    values=self.metrics)
  File "/venv/lib/python3.4/site-packages/pandas/core/reshape/pivot.py", line 160, in pivot_table
    table = table.sort_index(axis=1)
  File "/venv/lib/python3.4/site-packages/pandas/core/frame.py", line 3243, in sort_index
    labels = labels._sort_levels_monotonic()
  File "/venv/lib/python3.4/site-packages/pandas/core/indexes/multi.py", line 1240, in _sort_levels_monotonic
    indexer = lev.argsort()
  File "/venv/lib/python3.4/site-packages/pandas/core/indexes/base.py", line 2091, in argsort
    return result.argsort(*args, **kwargs)
TypeError: unorderable types: str() > int()
```

### Steps to reproduce

- open the slice

It happens on a specific slice that i cannot share unfortunately. Note to self: this is "distribuzione uso complessivo per scuola"

**Comment by xrmx** [comment]
Looking at the chart in caravel this looks like a TEXT field with some NULL values that in caravel was displayed as '0' and now something else supposedly :)

**Comment by xrmx** [comment]
Ok so this is the fillna(0) in BaseViz.get_df(). It looks like with [fillna](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html) we can be a bit more smart and try to pass a specific value depending on the column. What do you think?

**Comment by mistercrunch** [comment]
So is this a TEXT field as a metric in PivotViz?

**Comment by xrmx** [comment]
It's a TEXT as breakdown / column in a DistributionBarViz

**Comment by xrmx** [comment]
The following fixes the issue for me, what do you think?
```
diff --git a/superset/connectors/base.py b/superset/connectors/base.py
index e203ef44..81f1e387 100644
--- a/superset/connectors/base.py
+++ b/superset/connectors/base.py
@@ -65,6 +65,10 @@ class BaseDatasource(AuditMixinNullable, ImportMixin):
         return sorted([c.column_name for c in self.columns])
 
     @property
+    def columns_types(self):
+        return {c.column_name: c.type for c in self.columns}
+
+    @property
     def main_dttm_col(self):
         return "timestamp"
 
diff --git a/superset/viz.py b/superset/viz.py
index 75cb4113..e034f8c6 100755
--- a/superset/viz.py
+++ b/superset/viz.py
@@ -42,6 +42,7 @@ class BaseViz(object):
     verbose_name = "Base Viz"
     credits = ""
     is_timeseries = False
+    default_fillna = 0
 
     def __init__(self, datasource, form_data):
         if not datasource:
@@ -60,6 +61,21 @@ class BaseViz(object):
         self.status = None
         self.error_message = None
 
+    def get_fillna_for_type(self, col_type):
+        if col_type == 'TEXT':
+            return '<None>'
+        return self.default_fillna
+
+    def get_fillna_for_columns(self, columns=None):
+        """Returns a dict or scalar that can be passed to DataFrame.fillna"""
+        if columns is None:
+            return self.default_fillna
+        columns_types = self.datasource.columns_with_types
+        fillna = {c: self.get_fillna_for_type(columns_types.get(c)) for c in columns}
+        if not fillna:
+           return self.default_fillna
+        return fillna
+
     def get_df(self, query_obj=None):
         """Returns a pandas dataframe based on the query object"""
         if not query_obj:
@@ -101,7 +117,8 @@ class BaseViz(object):
                 if self.datasource.offset:
                     df[DTTM_ALIAS] += timedelta(hours=self.datasource.offset)
             df.replace([np.inf, -np.inf], np.nan)
-            df = df.fillna(0)
+            fillna = self.get_fillna_for_columns(self)
+            df = df.fillna(fillna)
         return df
 
     def get_extra_filters(self):
```

**Comment by ToonoW** [comment]
Is that fixed?
I use the last version Superset, but I get this error too.

**Comment by rumbin** [comment]
FYI: The Pivot Table is also affected.
