### ISSUE TITLE
SQL Lab error in exporting .csv when query has duplicately named columns

### ISSUE THREAD

**Issue by austenhead** [apache/incubator-superset#3043]
SQL Lab goes to a "500 - Internal Server Error" if you try to export a .csv file from a query that has two columns with the same name if those columns correspond to character typed.

This issue is not suggesting that SQL Lab needs to support the ability to return two fields with the same name, but rather that SQL queries that return some results in the SQL Lab GUI should also return those same results in the .CSV export.

### Superset version
0.18.4

### Expected results
when you `Run Query` in SQL Lab and results are successfully returned, those same results should be downloadable by clicking the `.CSV` button in SQL lab

### Actual results
clicking the `.CSV` button in SQL lab takes you to a 500-error page when the results have certain properties

### Steps to reproduce

1) go to SQL Lab
2) enter the query:
```
SELECT 'a' AS a, 'a' AS a ;
```
3) click "run query". this runs properly and returns a table that looks like:
```
a   a__1
a   a
```
4) click the button that says `.CSV` to export a csv
5) get the error message included below.

Note that in step (2) if you use the query `SELECT 1 AS a, 1 AS a` the .csv export works properly, so maybe the error has something to do with the column type being a string rather than numeric.

### Output from web browser

```
Sorry, something went wrong

500 - Internal Server Error

Stacktrace

         Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/utils.py", line 572, in wraps
    return f(self, *args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/models/core.py", line 756, in wrapper
    value = f(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/views/core.py", line 2075, in csv
    df = query.database.get_df(sql, query.schema)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/models/core.py", line 589, in get_df
    if v.type == numpy.object_ and needs_conversion(df[k]):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/models/core.py", line 584, in needs_conversion
    if isinstance(df_series[0], (list, dict)):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2071, in _getitem_column
    result = result[key]
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 0

      
```

**Comment by rumbin** [comment]
Cannot reproduce this in 0.20.4 and PostgreSQL as database. The columns in the CSV are even more precisely labeled, as you can see in the following comparison:

superset 0.20.4:
```
a,a__1
a,a
```

superset 0.15.4:
```
a,a
a,a
```

@austenhead Can you confirm, and close the issue?

**Comment by austenhead** [comment]
I just upgraded to superset 0.20.4, and I'm still getting the same error that I reported above.

```
-- this works in both the sql lab results tab and when exporting to a .csv
SELECT 'a' AS a, 'a' AS b;
```

```
-- this works fine in the sql lab results tab, but throws the 500 error when exporting to a .csv
SELECT 'a' AS a, 'a' AS a;
```

I get the same results as you when I click `Run Query` and look in the results tab (this was never an issue -- the results always appeared correctly in the results tab). I still get the error if I click the button that says `.CSV` after I run that query.

Is there additional information that I can provide that would help figure out why we might be getting different results when I click the button that says `.CSV` to download the file to have a local .csv of the results output?

**Comment by rumbin** [comment]
Do you have any cache backend configured for SQLLab? If you haven't, that might be a good starting point for figuring out why we get different results.

In my case, Redis is chosen as cache. For this reason, the result of the query gets fetched from the cache when exporting to CSV.

If no cache is configured then the query gets run afresh just for the CSV export. I could imagine, that the column renaming was not implemented for this use case. But I haven't checked the code...

**Comment by austenhead** [comment]
I have no cache backend configured (unless there is some default that I'm unaware of)

**Comment by rumbin** [comment]
In this case I'd start digging in https://github.com/apache/incubator-superset/blob/abfa03474cae49f66caf0d77533bf9b8e040145e/superset/views/core.py#L2181

This is where the query gets executed once more, just for exportring to csv. Judging from your observation that the column renaming is fine withiun the Result tab in SQLLab, my guess is that the column renaming was forgotten to be implemented for the CSV export.

When a Cache backend is configured, the exported results are the very same as the ones shown in SQLLab, thus the columns are correctly renamed.

I haven't tried so far finding the code where the deduplication of the column names takes place, though...

**Comment by rumbin** [comment]
Found it:
https://github.com/apache/incubator-superset/blob/adef5195837bf30c7c326abe19ee14f971f4829e/superset/sql_lab.py#L220

So, this part has to be properly included into the un-cached CSV export...

**Comment by subhajeet2107** [comment]
Is this fixed in latest version ? i am getting the same error
