### ISSUE TITLE
Massive sinking feeling - just updated and now can't launch

### ISSUE THREAD

**Issue by jerryhall** [apache/incubator-superset#3104]
My superset is located in /home/ec2-user/.pyenv/versions/2.7.12/lib/python2.7/site-packages in directories:
/superset and /superset-0.17.0-py2.7.egg-info

I wanted to update to the latest superset (https://pypi.python.org/pypi/superset/0.18.5) and ran
[ sudo pip install superset --upgrade ] and got this message:

```
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):   File "/home/ec2-user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py  import setuptools  # noqa  File "/home/ec2-user/.pyenv/versions/2.7.12/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in  <module>
from six.moves import filter, map  ImportError: No module named six.moves
```
So, I ran [ sudo pip install setuptools --upgrade ] and that went through great. I then reran the superset update command above and it downloaded and installed quite a few packages. 

However, when I try to launch my dashboards I get the Superset header but, no content. When I look in the Python directory above I still only see the .17 package directory. 

I'm worried if I do anything I might regret it so could anyone suggest if what I did is catacalysmic to my install or if I have to do some update to my files so the update is properly located and (ideally) I can retrieve all my slices/dashboards. 

Thanks!

**Comment by jerryhall** [comment]
...er, 
I restarted my httpd and everything is looking great.
a bit new at this (obviously :).
Thanks.
