### ISSUE TITLE
Redshift could not connect to the server

### ISSUE THREAD

**Issue by toncek87** [apache/incubator-superset#3162]
I tried connect to my Redshift database. There are millions of rows. When query time is longer than 
one minute, Superset response is "could not connect to the server". I checked Allow Run Async, but there is another message "Failed to start remote query on worker. Tell your administrator to verify the availability of the message queue." Could you help me with this issue?

**Comment by xrmx** [comment]
You can start by reading the documentation https://superset.incubator.apache.org/installation.html#sql-lab

**Comment by toncek87** [comment]
thanks, i missed it

**Comment by toncek87** [comment]
- I installed Redis
`pip3 install redis`

- dependencies
`pip install -U "celery[redis]"`
- run Redis
`redise-server`

Paste this code to /usr/local/lib/python3.4/dist-packages/superset/config.py
# Configure the class "CeleryConfig", by adding the URL of your Redis installation (in my case, localhost:6379):
```
class CeleryConfig(object):
  BROKER_URL =  'redis://localhost:6379/'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND =  'redis://localhost:6379/'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig
HTTP_HEADERS = {
    'super': 'header!'
}

# comment the current RESULTS_BACKEND value
#RESULTS_BACKEND = None

# assign a new value to RESULTS_BACKEND
RESULTS_BACKEND = FileSystemCache('/tmp/sqllab_cache', default_timeout=60*24*7)
```
When i try superset worker

`Starting SQL Celery worker.
Traceback (most recent call last):
  File "/home/rko/venv/bin/superset", line 15, in <module>
    manager.run()
  File "/home/rko/venv/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/rko/venv/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/rko/venv/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/superset/cli.py", line 189, in worker
    'broker': config.get('CELERY_CONFIG').BROKER_URL,
AttributeError: 'NoneType' object has no attribute 'BROKER_URL'`

Can you give me any tips?

**Comment by toncek87** [comment]
i've installed Redis, run superset worker and run superset server..
SQLlab gives me "Failed to start remote query on worker. Tell your administrator to verify the availability of the message queue."

and console:

/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'changed_on desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/compiler.py:624: SAWarning: Can't resolve label reference 'database_name asc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
2017-07-20 14:15:42,256:INFO:root:Parsing with sqlparse statement SELECT count(uid) as pocet
FROM events2
where event = 'pageview' and time like '%2017-06-30%'
2017-07-20 14:15:42,300:INFO:root:Triggering query_id: 43
/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/sqltypes.py:596: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
2017-07-20 14:15:42,980:ERROR:root:[Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/functional.py", line 36, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 494, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/functional.py", line 38, in __call__
    value = self.__value__ = self.__contract__()
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/connection.py", line 296, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 123, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 164, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 515, in _ensured
    reraise_as_library_errors=False,
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/connection.py", line 296, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 123, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 164, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/superset/views/core.py", line 2011, in sql_json
    store_results=not query.select_as_cta)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/usr/local/lib/python3.4/dist-packages/celery/app/base.py", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.4/dist-packages/celery/app/amqp.py", line 558, in send_task_message
    **properties
  File "/usr/local/lib/python3.4/dist-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 527, in _ensured
    errback and errback(exc, 0)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 515, in _ensured
    reraise_as_library_errors=False,
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/usr/local/lib/python3.4/dist-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.4/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/connection.py", line 296, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 123, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/local/lib/python3.4/dist-packages/amqp/transport.py", line 164, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused
[2017-07-20 14:15:51 +0200] [1746] [INFO] Handling signal: winch
[2017-07-20 14:15:51 +0200] [1746] [INFO] Handling signal: winch

**Comment by xrmx** [comment]
You have misconfigured celery, it's looking for an amqp broker while you said you want to use redis.

**Comment by toncek87** [comment]
i changed that and worker console:

[2017-07-20 14:35:59,067: ERROR/ForkPoolWorker-29] Task superset.sql_lab.get_sql_results[dc953f93-5cf6-4de6-9432-0d09a354ca2e] raised unexpected: Exception("Results backend isn't configured.",)
Traceback (most recent call last):
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 81, in get_sql_results
    handle_error("Results backend isn't configured.")
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 78, in handle_error
    raise Exception(query.error_message)
Exception: Results backend isn't configured.

---------------------------
i have this config:
/superset/config.py

# Configure the class "CeleryConfig", by adding the URL of your Redis installation (in my case, localhost:6379):
class CeleryConfig(object):
  BROKER_URL =  'redis://localhost:6379/'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND =  'redis://localhost:6379/'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')

**Comment by xrmx** [comment]
You have to add to add proper quoting to your code excerpts otherwise it's impossible to help you.

**Comment by toncek87** [comment]
i changed that and worker console:

[2017-07-20 14:35:59,067: ERROR/ForkPoolWorker-29] Task superset.sql_lab.get_sql_results[dc953f93-5cf6-4de6-9432-0d09a354ca2e] raised unexpected: Exception("Results backend isn't configured.",)
Traceback (most recent call last):
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 81, in get_sql_results
    handle_error("Results backend isn't configured.")
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 78, in handle_error
    raise Exception(query.error_message)
Exception: Results backend isn't configured.

---------------------------
i have this config:
/superset/config.py

Configure the class "CeleryConfig", by adding the URL of your Redis installation (in my case, localhost:6379):
```
class CeleryConfig(object):
  BROKER_URL =  'redis://localhost:6379/'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND =  'redis://localhost:6379/'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')
```

is this better?

**Comment by toncek87** [comment]
i changed that and worker console:

[2017-07-20 14:35:59,067: ERROR/ForkPoolWorker-29] Task superset.sql_lab.get_sql_results[dc953f93-5cf6-4de6-9432-0d09a354ca2e] raised unexpected: Exception("Results backend isn't configured.",)
Traceback (most recent call last):
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 81, in get_sql_results
    handle_error("Results backend isn't configured.")
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 78, in handle_error
    raise Exception(query.error_message)
Exception: Results backend isn't configured.

---------------------------
i have this config:
/superset/config.py

Configure the class "CeleryConfig", by adding the URL of your Redis installation (in my case, localhost:6379):
```
class CeleryConfig(object):
  BROKER_URL =  'redis://localhost:6379/'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND =  'redis://localhost:6379/'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')
```

is this better?
What mean? Results backend isn't configured.
