### ISSUE TITLE
Results backend isn't configured

### ISSUE THREAD

**Issue by toncek87** [apache/incubator-superset#3178]
Worker console...:

[2017-07-20 14:35:59,067: ERROR/ForkPoolWorker-29] Task superset.sql_lab.get_sql_results[dc953f93-5cf6-4de6-9432-0d09a354ca2e] raised unexpected: Exception("Results backend isn't configured.",)
Traceback (most recent call last):
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 81, in get_sql_results
    handle_error("Results backend isn't configured.")
  File "/home/rko/venv/lib/python3.4/site-packages/superset/sql_lab.py", line 78, in handle_error
    raise Exception(query.error_message)
Exception: Results backend isn't configured.

---------------------------
i have this config:
/superset/config.py

Configure the class "CeleryConfig", by adding the URL of your Redis installation (in my case, localhost:6379):
```
class CeleryConfig(object):
  BROKER_URL =  'redis://localhost:6379/'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND =  'redis://localhost:6379/'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')
```

is this better?
What does mean? Results backend isn't configured.

**Comment by xrmx** [comment]
There's no need to close and reopen the same issue

**Comment by kquesse** [comment]
i'm facing the same issue, Have you solved this one ? regards

**Comment by mistercrunch** [comment]
Are you sure you `superset_config.py` is in your PYTHONPATH and parsable?
