### ISSUE TITLE
'module' object has no attribute 'NullTranslations'

### ISSUE THREAD

**Issue by crazy2323** [apache/incubator-superset#3182]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Actual results

when i run : superset runserver
```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 12, in <module>
    from superset.cli import manager
  File "/usr/lib/python2.7/site-packages/superset-0.18.5-py2.7.egg/superset/__init__.py", line 131, in <module>
    security_manager_class=app.config.get("CUSTOM_SECURITY_MANAGER"))
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/base.py", line 131, in __init__
    self.init_app(app, session)
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/base.py", line 157, in init_app
    self._add_admin_views()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/base.py", line 254, in _add_admin_views
    self.sm.register_views()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/security/sqla/manager.py", line 67, in register_views
    super(SecurityManager, self).register_views()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/security/manager.py", line 443, in register_views
    category_label=_('Security'))
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/base.py", line 345, in add_view
    baseview = self._check_and_init(baseview)
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/base.py", line 297, in _check_and_init
    baseview = baseview()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/views.py", line 451, in __init__
    super(ModelView, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/baseviews.py", line 628, in __init__
    super(BaseCRUDView, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/baseviews.py", line 395, in __init__
    self._init_properties()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/baseviews.py", line 679, in _init_properties
    super(BaseCRUDView, self)._init_properties()
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/baseviews.py", line 423, in _init_properties
    self._gen_labels_columns(list_cols)
  File "/usr/lib/python2.7/site-packages/Flask_AppBuilder-1.9.1-py2.7.egg/flask_appbuilder/baseviews.py", line 405, in _gen_labels_columns
    if not self.label_columns.get(col):
  File "/usr/lib/python2.7/site-packages/Flask_Babel-0.11.2-py2.7.egg/flask_babel/speaklater.py", line 26, in __len__
    return len(text_type(self))
  File "/usr/lib/python2.7/site-packages/Flask_Babel-0.11.2-py2.7.egg/flask_babel/speaklater.py", line 23, in __str__
    return text_type(self._func(*self._args, **self._kwargs))
  File "/usr/lib/python2.7/site-packages/Flask_Babel-0.11.2-py2.7.egg/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/usr/lib/python2.7/site-packages/Flask_Babel-0.11.2-py2.7.egg/flask_babel/__init__.py", line 217, in get_translations
    return support.NullTranslations()
AttributeError: 'module' object has no attribute 'NullTranslations'

```

**Comment by xrmx** [comment]
Looks like something is wrong between flask-appbuilder and flask-babel. Flask-Babel 0.11.1 appears to work fine here.

**Comment by crazy2323** [comment]
@xrmx pip install Flask-Babel==0.11.1 it works well, thx

**Comment by mistercrunch** [comment]
I pushed a PR to bump flask-babel on FAB

**Comment by xrmx** [comment]
@mistercrunch the fix would be ==0.11.1 or >=0.10.0<0.11.2 . Or we can understand what the issue is :)

**Comment by jlkokko** [comment]
I experienced the same issue after migrating from RHEL to Oracle Linux.

**Comment by mistercrunch** [comment]
@jlkokko can you try `pip install flask-babel==0.11.1`

**Comment by jlkokko** [comment]
Same error.  Again this was on a migration from RHEL to Oracle. On a clean Oracle system that did not have python, I was able to successfully install and run without issue.

**Comment by fparrel** [comment]
What i did to fix on Centos, I added the following lines in /usr/lib/python2.7/site-packages/flask_babel/__init__.py:
`        try:
            return support.NullTranslations()
        except:
            import gettext
            return gettext.NullTranslations()`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. Feel free to comment and request for this issue to be reopened.
