### ISSUE TITLE
Failed connexion to druid with superset

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-superset#3195]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ yes] I have reproduced the issue with at least the latest released version of superset
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Python version
2.7

### Expected results
HTTP Error 403: Forbidden Druid Error: None Query is:

### Steps to reproduce
I follow step to connect to druid

- Click on druid cluster, edit new cluster and save
- Edit new data source 
- End refresh Druid Metadata (But this step in not complete) , i have this error `Error while processing cluster 'Data Innovation Lab' No JSON object could be decoded` 

Thanks for your help

**Comment by amoussoubaruch** [comment]
I' m trying this command superset refresh_druid to initial druid cluster connexion and i have this error :

`[root@cassandra-2 ~]# superset refresh_druid
/usr/lib64/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
2017-07-27 19:53:42,044:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.231.2.3
2017-07-27 19:53:42,084:DEBUG:urllib3.connectionpool:http://10.231.2.3:8000 "GET http://lx1334.res.jcdecaux.org:8081/status HTTP/1.1" 403 3277
Error while processing cluster 'druid cluster'
No JSON object could be decoded
2017-07-27 19:53:42,085:ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/cli.py", line 159, in refresh_druid
    merge_flag=merge)
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 101, in refresh_datasources
    self.druid_version = self.get_druid_version()
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 95, in get_druid_version
    return json.loads(requests.get(endpoint).text)['version']
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Refreshed metadata from cluster [Data Innovation Lab]
`

**Comment by amoussoubaruch** [comment]
Hi!

I have the same problem after it worked last 2 days. I launch my web UI today and i have same error. I don't understand why it's work fine and now it's down.
I refere to this issue #3174. 
Can you please explain me more in detail what is the problem and how i can resolve that? 
Thanks in advance

**Comment by amoussoubaruch** [comment]
When i refresh_druid metadata with command line : superset I have this error. 

2017-08-16 12:43:05,988:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
2017-08-16 12:43:05,990:DEBUG:urllib3.connectionpool:http://localhost:8081 "GET /status HTTP/1.1" 200 None
2017-08-16 12:43:05,991:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
2017-08-16 12:43:05,992:DEBUG:urllib3.connectionpool:http://localhost:8081 "GET /druid/coordinator/v1/metadata/datasources HTTP/1.1" 200 None
2017-08-16 12:43:05,993:INFO:root:Syncing Druid datasource [mydata1]
2017-08-16 12:43:06,126:INFO:root:Syncing Druid datasource [mydata2]
2017-08-16 12:43:06,135:ERROR:root:Failed at fetching the latest segment
Refreshed metadata from cluster [Cluster]

**Comment by mistercrunch** [comment]
Does that datasource have segments?

**Comment by amoussoubaruch** [comment]
Yes my datasource have segments. 
The problem is that it worked correctly (Connexion are ok and i make a dashboard) and day after connexion between superset and druid a broke. I have error that i show in my last comment. 
After that i have this error : "The server could not be reached. You may want to verify your connection and try again". I try to restart and i have error like i describe in my last comment.

**Comment by amoussoubaruch** [comment]
Is it possible that problem is related to a proxy server?

**Comment by mistercrunch** [comment]
Are you closing because it's resolved?

**Comment by amoussoubaruch** [comment]
Yes it's resolved
