### ISSUE TITLE
unable to add postgresql as datasource 

### ISSUE THREAD

**Issue by youyoude** [apache/incubator-superset#3200]
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/superset/views/core.py", line 1376, in testconn
    engine.connect()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1135, in _do_get
    return self._create_connection()
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/pool.py", line 661, in __connect
    exec_once(self.connection, self)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 246, in exec_once
    self(*args, **kw)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 172, in on_connect
    do_on_connect(conn)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 643, in on_connect
    fn(conn)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 618, in on_connect
    hstore_oids = self._hstore_oids(conn)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 785, in oneshot
    result = fn(self, *args, **kw)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 652, in _hstore_oids
    oids = extras.HstoreAdapter.get_oids(conn)
  File "/root/anaconda2/lib/python2.7/site-packages/psycopg2/extras.py", line 904, in get_oids
    """ % typarray)
ProgrammingError: (psycopg2.ProgrammingError) column "typarray" does not exist
LINE 1: SELECT t.oid, typarray
                      ^

**Comment by xrmx** [comment]
Which version of postgresql is this? Are you querying an hstore field? Please add the missing required field from the issue template!

**Comment by mistercrunch** [comment]
what does your sqlalchemy connection string look like?
