### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by STILLSHI** [apache/incubator-superset#3218]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset@0.18.5 

### Expected results

I made some change to the labels in visTypes.js and try to run the npm run build

### Actual results

ERROR in dashboard.b73167600c8e473ac1af.entry.js from UglifyJs
Unexpected token: name (ARRAY_TYPE) [dashboard.b73167600c8e473ac1af.entry.js:47990,4]

ERROR in explore.05e0dff1c0743e3f086d.entry.js from UglifyJs
Unexpected token: name (ARRAY_TYPE) [explore.05e0dff1c0743e3f086d.entry.js:47657,4]

npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! superset@0.18.5 build: `NODE_ENV=production webpack --colors --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the superset@0.18.5 build script 'NODE_ENV=production webpack --colors --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --colors --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ZYDATA/zypy99/lib/python3.5/site-packages/superset/static/assets/npm-debug.log

### Steps to reproduce

1. modify the visType.js with some of the strings
2. run npm run build

**Comment by STILLSHI** [comment]
nom-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle superset@0.18.5~prebuild: superset@0.18.5
6 silly lifecycle superset@0.18.5~prebuild: no script for prebuild, continuing
7 info lifecycle superset@0.18.5~build: superset@0.18.5
8 verbose lifecycle superset@0.18.5~build: unsafe-perm in lifecycle true
9 verbose lifecycle superset@0.18.5~build: PATH: /usr/share/npm/bin/node-gyp-bin:/root/ZYDATA/zypy99/lib/python3.5/site-packages/superset/static/assets/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle superset@0.18.5~build: CWD: /root/ZYDATA/zypy99/lib/python3.5/site-packages/superset/static/assets
11 silly lifecycle superset@0.18.5~build: Args: [ '-c', 'NODE_ENV=production webpack --colors --progress' ]
12 silly lifecycle superset@0.18.5~build: Returned: code: 2  signal: null
13 info lifecycle superset@0.18.5~build: Failed to exec build script
14 verbose stack Error: superset@0.18.5 build: `NODE_ENV=production webpack --colors --progress`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid superset@0.18.5
16 verbose cwd /root/ZYDATA/zypy99/lib/python3.5/site-packages/superset/static/assets
17 error Linux 4.4.0-79-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error superset@0.18.5 build: `NODE_ENV=production webpack --colors --progress`
22 error Exit status 2
23 error Failed at the superset@0.18.5 build script 'NODE_ENV=production webpack --colors --progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the superset package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production webpack --colors --progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs superset
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls superset
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
~

**Comment by STILLSHI** [comment]
this command is running under the assets folder.

**Comment by xrmx** [comment]
If you modified the source code and it fails i can't see how it's an upstream issue.

**Comment by andyComeOn** [comment]
Hi 'xrmx', i want ask u ,u' computer is windows7 or MAC or windows7 have virtual machine that it run linux? when i want modify some demands , i show npm run build .but it is also error? what do u do?
