### ISSUE TITLE
Unable to connect with Vertica

### ISSUE THREAD

**Issue by Juanan92** [apache/incubator-superset#3232]
### Superset version
0.18.5

Hi everyone,
I'm trying to connect Superset with a Vertica database through Sources > Databases with the SQLAlchemy URI 
vertica+vertica_python://user:passwd@hostname:5432/DB 
![error2](https://user-images.githubusercontent.com/10348527/28918609-466e7bba-784a-11e7-93a9-0e0fcfab2b40.PNG)
and I got the following error:
`ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n'NoneType' object has no attribute '__getitem__'"}`
![error1](https://user-images.githubusercontent.com/10348527/28918612-48b538fa-784a-11e7-84b7-040f22ed7c28.PNG)
I have already installed the Vertica connector (`pip install sqlalchemy-vertica-python`) and I have sucessfully connected to a Redshift database.
Any ideas?
Sorry for my noobness...
Thanks in advance

**Comment by xrmx** [comment]
Full stackstrace please

**Comment by hc000** [comment]
@xrmx I tried this new package, got this error:

`2017-09-13 05:46:40,514:ERROR:root:module 'sqlalchemy_vertica' has no attribute 'paramstyle'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/views/core.py", line 1414, in testconn
    engine = create_engine(uri, connect_args=connect_args)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/__init__.py", line 391, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 88, in create
    dialect = dialect_cls(**dialect_args)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/postgresql/base.py", line 2083, in __init__
    default.DefaultDialect.__init__(self, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 196, in __init__
    self.paramstyle = self.dbapi.paramstyle
AttributeError: module 'sqlalchemy_vertica' has no attribute 'paramstyle'`

**Comment by hc000** [comment]
when using an incorrect credentials I get invalid username or password error.
so I think its connecting but its it fails afterwards

**Comment by xrmx** [comment]
@hc000 none of the stacktraces you posted are superset issues and you need to use triple backquote to quote them otherwise they are unreadable. Better option is to open an issue to the vertica dialect with the first stackstrace and ask for help there.

**Comment by hc000** [comment]
@xrmx I only used these python library because it was mentioned specifically in the superset documentation https://superset.incubator.apache.org/installation.html

I followed the documentation for vertica and it doesn't work. I posted the errors above.

It does seem like the issue is NOT with superset specifically, but the docs recommends those package and says it supports vertica.
