### ISSUE TITLE
Superset worker problem

### ISSUE THREAD

**Issue by Plusmonkey** [apache/incubator-superset#3270]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.19.0
### Steps to reproduce
Hi , I install the superset , but i meet a problem about SQL Lab 
I config the config.py about the worker
```
class CeleryConfig(object):
  BROKER_URL = 'redis://localhost:6379/0'
  CELERY_IMPORTS = ('superset.sql_lab', )
  CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
  CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
  CELERYD_LOG_LEVEL = 'DEBUG'
CELERY_CONFIG = CeleryConfig
HTTP_HEADERS = {
    'super': 'header!'
}
          
from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results') 

But My Questions is When i select something a meet a problem : 

[2017-08-10 10:48:41,639: INFO/Worker-11] Parsing with sqlparse statement select * from  hive.app.al_table_saler_clue_count;
[2017-08-10 10:48:41,660: INFO/Worker-11] Set query to 'running'
[2017-08-10 10:48:41,668: ERROR/Worker-11] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/data/venv/lib/python2.7/site-packages/superset/sql_lab.py", line 91, in get_sql_results
    ctask, query_id, return_results, store_results)
  File "/data/venv/lib/python2.7/site-packages/superset/sql_lab.py", line 170, in execute_sql
    schema=query.schema, nullpool=not ctask.request.called_directly)
  File "/data/venv/lib/python2.7/site-packages/superset/models/core.py", line 570, in get_sqla_engine
    uri = self.db_engine_spec.adjust_database_uri(uri, schema)
  File "/data/venv/lib/python2.7/site-packages/superset/db_engine_specs.py", line 393, in adjust_database_uri
    if '/' in database:
TypeError: argument of type 'NoneType' is not iterable
[2017-08-10 10:48:41,669: INFO/Worker-11] [stats_logger] (incr) error_sqllab_unhandled
[2017-08-10 10:48:41,684: INFO/MainProcess] Task superset.sql_lab.get_sql_results[32776322-7571-441f-ba03-18c962860576] succeeded in 0.0714395358227s: None
```

I do not know how can resolve it ?

**Comment by mistercrunch** [comment]
I think you must be missing the catalog/default db in your SQLALCHEMY_URI, I think it should look something like

`presto://myserver:3400/mycatalog/mydefaultdatabase`

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 256 days. Feel free to comment and request for this issue to be reopened.
