### ISSUE TITLE
Unicode character in name of dimension (or in dimension data) cause error

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3324]
Make sure these boxes are checked before submitting your issue - thank you!

### Superset version
Superset 0.19.0

### Expected results
See a graph with russian names of dimensions

### Actual results
Error: 'ascii' codec can't encode characters in position 104-110: ordinal not in range(128)

### Steps to reproduce

1) create a slice with Time series-bar chart visualization, render some metric over time
2) click on Edit datasource
3) On Edit Table, click List metrics, select a metric used to display on step 1
4) rename metric to Unicode name
5) go back to slice, select a new metric from the list and try to render - got this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/viz.py", line 239, in get_payload
    df = self.get_df()
  File "/usr/local/lib/python2.7/site-packages/superset/viz.py", line 79, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 554, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 326, in get_query_str
    compile_kwargs={"literal_binds": True}
UnicodeEncodeError: 'ascii' codec can't encode characters in position 104-110: ordinal not in range(128)
```

**Comment by xrmx** [comment]
Yeah, the str() at line 323 is not going to work fine, does replacing it with unicode() do the trick?

**Comment by izetex** [comment]
I made this change and got another error: 'latin-1' codec can't encode characters in position 111-117: ordinal not in range(256)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 559, in query
    df = self.database.get_df(sql, self.schema)
  File "/usr/local/lib/python2.7/site-packages/superset/models/core.py", line 582, in get_df
    df = pd.read_sql(sql, eng)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/sql.py", line 416, in read_sql
    chunksize=chunksize)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/sql.py", line 1087, in read_query
    result = self.execute(*args)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/sql.py", line 978, in execute
    return self.connectable.execute(*args, **kwargs)

**Comment by xrmx** [comment]
Yeah, need to add this header at the start of the file:
```
# -*- coding: utf-8 -*-
```

BTW please quote properly stacktraces.

**Comment by izetex** [comment]
which file?

**Comment by xrmx** [comment]
The one you modified earlier.

**Comment by izetex** [comment]
This did not help - same error.
Also i tested, that this modification str() -> unicode() does not affect the first error ( unicode data in dimension )

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 247 days. Feel free to comment and request for this issue to be reopened.
