### ISSUE TITLE
Error in SQL Query results on Spatial columns

### ISSUE THREAD

**Issue by izetex** [apache/incubator-superset#3337]
### Superset version

Superset 0.19.0

### Expected results

Results are rendered with spatial data.

### Actual results

Error: 'utf8' codec can't decode byte 0xe6 in position 0: invalid continuation byte

### Steps to reproduce

1) create table in MySQL with spatial data https://dev.mysql.com/doc/refman/5.7/en/spatial-extensions.html
2) go to SQL query
3) select all columns from a table which has spatial data

Trace:
```
2017-08-18 10:57:30,673:INFO:root:Fetching cursor description
2017-08-18 10:57:30,746:ERROR:root:'utf8' codec can't decode byte 0xe6 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/views/core.py", line 2071, in sql_json
    payload = json.dumps(data, default=utils.json_iso_dttm_ser)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 0: invalid continuation byte
```

**Comment by xrmx** [comment]
Please quote the stacktrace and add the superset version per https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#report-bugs

**Comment by izetex** [comment]
Please give me a code to insert in python to make a trace of data there

**Comment by xrmx** [comment]
`print data` should do

**Comment by izetex** [comment]
```
2017-08-18 11:38:52,062:INFO:root:Fetching data: {u'changedOn': datetime.datetime(2017, 8, 18, 8, 38, 52), u'tempTable': u'', u'userId': 1L, u'executedSql': u'SELECT * from tokens', u'ctas': False, u'tab': u'Untitled Query 2', u'sqlEditorId': u'SkM9UXEuZ', u'id': u'BJNjDQ4OZ', u'changed_on': '2017-08-18T08:38:52', u'rows': None, u'endDttm': None, u'limit_reached': False, u'state': u'running', u'progress': 0L, u'schema': u'sprint2prod', u'dbId': 2L, u'errorMessage': None, u'db': u'sprint2prod', u'trackingUrl': None, u'user': u'admin', u'sql': u'SELECT * from tokens', u'startDttm': Decimal('1503045531930.420000'), u'limit': 1000000L, u'serverId': 154L, u'resultsKey': None}
2017-08-18 11:38:52,062:INFO:root:Fetching cursor description
{'status': u'success', 'query': {u'changedOn': datetime.datetime(2017, 8, 18, 8, 38, 52, 72291), u'tempTable': u'', u'userId': 1L, u'executedSql': u'SELECT * from tokens', u'ctas': False, u'tab': u'Untitled Query 2', u'sqlEditorId': u'SkM9UXEuZ', u'id': u'BJNjDQ4OZ', u'changed_on': '2017-08-18T08:38:52.072291', u'rows': 229, u'endDttm': 1503045532070.662, u'limit_reached': False, u'state': u'success', u'progress': 100, u'schema': u'sprint2prod', u'dbId': 2L, u'errorMessage': None, u'db': u'sprint2prod', u'trackingUrl': None, u'user': u'admin', u'sql': u'SELECT * from tokens', u'startDttm': Decimal('1503045531930.420000'), u'limit': 1000000L, u'serverId': 154L, u'resultsKey': None}, 'query_id': 154L, 'columns': [{u'agg': u'count_distinct', u'is_date': False, u'type': u'INT', u'name': 'id', u'is_dim': False}, {u'is_date': False, u'type': u'STRING', u'name': 'location', u'is_dim': True}, {u'agg': u'count_distinct', u'is_date': False, u'type': u'INT', u'name': 'drop_transaction_id', u'is_dim': False}, {u'agg': u'count_distinct', u'is_date': False, u'type': u'OBJECT', u'name': 'pickup_transaction_id', u'is_dim': False}, {u'agg': u'count_distinct', u'is_date': False, u'type': u'OBJECT', u'name': 'transfer_transaction_id', u'is_dim': False}, {u'agg': u'count_distinct', u'is_date': False, u'type': u'INT', u'name': 'token_color_id', u'is_dim': False}, {u'agg': u'sum', u'is_date': False, u'type': u'INT', u'name': 'count', u'is_dim': False}, {u'is_date': True, u'type': u'DATETIME', u'name': 'created_at', u'is_dim': False}, {u'is_date': True, u'type': u'DATETIME', u'name': 'updated_at', u'is_dim': False}], 'data': [{'count': 1, 'created_at': Timestamp('2017-08-09 17:28:57'), 'updated_at': Timestamp('2017-08-10 09:19:41'), 'id': 1, 'pickup_transaction_id': 29.0, 'token_color_id': 1, 'transfer_transaction_id': 42.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00@t\x8f\x94H@\x86\xcc\xd8\x98\x97\xe0K@', 'drop_transaction_id': 10}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:38:15'), 'updated_at': Timestamp('2017-08-10 13:28:09'), 'id': 2, 'pickup_transaction_id': 53.0, 'token_color_id': 1, 'transfer_transaction_id': 54.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00Rj\x94H@\xb9\x1aL\xbez\xe0K@', 'drop_transaction_id': 18}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:38:27'), 'updated_at': Timestamp('2017-08-10 15:07:22'), 'id': 3, 'pickup_transaction_id': 58.0, 'token_color_id': 1, 'transfer_transaction_id': 60.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00 p\xa4\x94H@\x8d\x19E\x03G\xe0K@', 'drop_transaction_id': 19}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:39:35'), 'updated_at': Timestamp('2017-08-10 12:53:56'), 'id': 4, 'pickup_transaction_id': 47.0, 'token_color_id': 1, 'transfer_transaction_id': 51.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00\xf0\xc8\x0e\x98H@\xc4\x0f\x97\xb3\x91\xe2K@', 'drop_transaction_id': 20}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:42:38'), 'updated_at': Timestamp('2017-08-10 09:55:57'), 'id': 5, 'pickup_transaction_id': 45.0, 'token_color_id': 1, 'transfer_transaction_id': 45.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00PW\xbb\x93H@\xc4z\x83M\xb0\xe9K@', 'drop_transaction_id': 21}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:44:43'), 'updated_at': Timestamp('2017-08-10 17:26:44'), 'id': 6, 'pickup_transaction_id': 76.0, 'token_color_id': 1, 'transfer_transaction_id': 78.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00 I\xb2\x8fH@;YF\xd3\xc2\xe4K@', 'drop_transaction_id': 22}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:45:19'), 'updated_at': Timestamp('2017-08-10 08:45:19'), 'id': 7, 'pickup_transaction_id': None, 'token_color_id': 1, 'transfer_transaction_id': None, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\xff\xff\x8f\xa8[\x8fH@F\xeb&\xf5\xe0\xe4K@', 'drop_transaction_id': 23}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:47:03'), 'updated_at': Timestamp('2017-08-10 14:28:35'), 'id': 8, 'pickup_transaction_id': 57.0, 'token_color_id': 1, 'transfer_transaction_id': 57.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x01\x00 \xe0J\x8dH@\t\x144\x1d\xf6\xe4K@', 'drop_transaction_id': 24}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:47:26'), 'updated_at': Timestamp('2017-08-10 15:53:23'), 'id': 9, 'pickup_transaction_id': 70.0, 'token_color_id': 1, 'transfer_transaction_id': 70.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x01\x00\x10;\x96\x8dH@\xd3\xb3\x0bO\xce\xe4K@', 'drop_transaction_id': 25}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:47:55'), 'updated_at': Timestamp('2017-08-10 18:22:01'), 'id': 10, 'pickup_transaction_id': 79.0, 'token_color_id': 1, 'transfer_transaction_id': 80.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00 \xf1\xee\x8cH@`<\x135\xec\xe5K@', 'drop_transaction_id': 26}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:49:12'), 'updated_at': Timestamp('2017-08-10 16:47:01'), 'id': 11, 'pickup_transaction_id': 59.0, 'token_color_id': 1, 'transfer_transaction_id': 72.0, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00pI\xe8\x90H@\x1a\xd0\x83o\x86\xe8K@', 'drop_transaction_id': 27}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:49:58'), 'updated_at': Timestamp('2017-08-10 08:49:58'), 'id': 12, 'pickup_transaction_id': None, 'token_color_id': 1, 'transfer_transaction_id': None, 'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\xff\xff/\x9e\x85\x93H@\x0e\xcc\x82\xab\xdd\xe8K@', 'drop_transaction_id': 28}, {'count': 1, 'created_at': Timestamp('2017-08-10 08:56:40'), 'updated_at': Timestamp('2017-08-10 15:13:18'), 'id': 13, 'pickup_transaction_id': 31.0, 'token_color_id': 1, 't
```

**Comment by izetex** [comment]
I suspect that the following causes the error:

```
'location': '\xe6\x10\x00\x00\x01\x01\x00\x00\x00\x00\x00 \xf1\xee\x8cH@`<\x135\xec\xe5K@'
```

**Comment by mistercrunch** [comment]
What is the database backend? Postgres? Druid?

One path towards a solution is to improve the json serializer function `utils.json_iso_dttm_ser` to handle that specific object type in a specific way.

We may want Superset to support some sort of spacial pivot format that we'd serialize towards. Something as simple as `[lat, long]` in json. Then we'd have to add support for that in a fancy spacial control where you'd have the choice to select one of these new spacial column, or point to a 2 different columns for lat and long (like we do currently in the mapbox viz). People may have a spacial column, or they may have a lat and a long column. Superset should work with both.

In the meantime, if you just want stuff to work, you need to write 2 column expressions, one for lat and one for long, using your database's engine builtin function. I'd assume there's some sort of `get_longitude(spacial_typed_column)` function you can use, and used that in the mapbox viz.

**Comment by izetex** [comment]
The backend is MySQL. The description of spatial extension is https://dev.mysql.com/doc/refman/5.7/en/spatial-extensions.html

I created a SELECT statement with the separate lat / lon INT columns - this is not the problem.

The issue is not that Superset do not understand the MySQL spatial extension, but the error which it generates ( and which prevents by the way to see ANY data in result )

**Comment by xrmx** [comment]
@izetex I'm not sure sqlalchemy supports spatial data by default. As you can see for us that field is a byte string:
```
{u'is_date': False, u'type': u'STRING', u'name': 'location', u'is_dim': True}
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 246 days. Feel free to comment and request for this issue to be reopened.
