### ISSUE TITLE
Cannot Get to Slices Page after Bad Slice Data Edit (tried to add new property to hide scroll bars)

### ISSUE THREAD

**Issue by Todd-Z-Li** [apache/incubator-superset#3507]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
List of Slices

### Actual results
```Stacktrace

         Traceback (most recent call last):
  File "/home/pi/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/pi/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/views.py", line 478, in list
    widgets=widgets)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/pi/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/pi/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/general/model/list.html", line 12, in block "content"
    {% block list_list scoped %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/general/model/list.html", line 13, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/home/pi/venv/lib/python3.5/site-packages/superset/templates/appbuilder/general/widgets/base_list.html", line 25, in top-level template code
    {% block begin_loop_values %}
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/runtime.py", line 410, in __init__
    self._after = self._safe_next()
  File "/home/pi/venv/lib/python3.5/site-packages/jinja2/runtime.py", line 430, in _safe_next
    return next(self._iterator)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 114, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/home/pi/venv/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 58, in _get_attr_value
    if not hasattr(item, col):
  File "/home/pi/venv/lib/python3.5/site-packages/superset/models/core.py", line 214, in slice_link
    url = self.slice_url
  File "/home/pi/venv/lib/python3.5/site-packages/superset/models/core.py", line 200, in slice_url
    obj=self, params=parse.quote(json.dumps(self.form_data))))
  File "/home/pi/venv/lib/python3.5/site-packages/superset/models/core.py", line 184, in form_data
    form_data = json.loads(self.params)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 933 (char 932)
```

### Steps to reproduce
Edit a Slice's property with an unknown property (I added overflow:hidden) in the object of list of properties. I can no longer open the /slicemodelview/list/ or view any slices information at all at any other pages that link to slices (such as trying to add a slice from a dashboard)

**Comment by emmadickson** [comment]
I'm having this same problem. How did you get the slice deleted  I can't even navigate to the page anymore.

**Comment by Todd-Z-Li** [comment]
no solution other than reinstall (so far)

**Comment by Todd-Z-Li** [comment]
@emmadickson solution (sort of):

find the editor for the slice's properties manually, at this URL: 
localhost:8088/slicemodelview/edit/###

where the "###" is the designated number for your chart. You probably won't remember what it is, but if it is near the first few you've created (and after you loaded the examples), then it is probably in the 30s (mine was 37) or 40s

Hope this helps!

**Comment by mistercrunch** [comment]
Thanks for reporting this, I just pushed a fix for it.
