### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by flofei** [apache/incubator-superset#3523]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.19.1 lasted version
node 6.9.1
python 3.5
npm 3.10.8

### Expected results

everythins is ok

### Actual results
when I run command 'npm run dev ' , it happened that error belows:

> ERROR in ./node_modules/react-map-gl/node_modules/viewport-mercator-project/dist-es6/index.js
Module build failed: TypeError: E:/freepay/OpenSource/orgin/superset/superset/assets/node_modules/react-map-gl/node_modules/viewport-mercator-project/dist-es6/index.js: Cannot read property 'indexOf' of undefined
    at Object.relative (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\source-map\lib\util.js:206:15)
    at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\source-map\lib\source-map-consumer.js:731:21)
    at E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\file\index.js:461:51
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at File.mergeSourceMap (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\file\index.js:460:24)
    at File.generate (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\file\index.js:719:25)
    at File.transform (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\file\index.js:554:17)
    at E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\pipeline.js:50:19
    at File.wrap (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\file\index.js:564:16)
    at Pipeline.transform (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at transpile (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-loader\lib\index.js:49:20)
    at Object.module.exports (E:\freepay\OpenSource\orgin\superset\superset\assets\node_modules\babel-loader\lib\index.js:174:20)
 @ ./node_modules/react-map-gl/dist/components/interactive-map.js 47:31-67
 @ ./node_modules/react-map-gl/dist/index.js
 @ ./visualizations/mapbox.jsx
 @ ./visualizations/main.js
 @ ./javascripts/modules/superset.js
 @ ./javascripts/dashboard/Dashboard.jsx
 @ multi babel-polyfill 

> ./javascripts/dashboard/Dashboard.jsx

### Steps to reproduce
1. get last code
2.run command 'npm run dev'

**Comment by graceguo-supercat** [comment]
see this section: https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#npm-packages

Did you run 

> yarn

 to install new dependencies?

**Comment by flofei** [comment]
yes, I did it

**Comment by mistercrunch** [comment]
We don't really support windows. If someone wants to add fixes to the build pipeline to support Windows we'll review them.
