### ISSUE TITLE
[SQL Lab] (sqlite3.ProgrammingError) 

### ISSUE THREAD

**Issue by 15310944349** [apache/incubator-superset#3550]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.19.1

### Expected results
get results data from remote mysql server

### Actual results
ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'UPDATE "query" SET tmp_table_name=?, status=?, error_message=?, changed_on=? WHERE "query".id = ?'] [parameters: (None, u'failed', "unsupported format character '\xe5' (0xffffffe5) at index 74", '2017-09-29 08:06:59.720489', 559)]

### Steps to reproduce
run the fllowing sql from sql editor:
SELECT t_tm_article_id,title,subscribe_id FROM t_article WHERE title like '%品牌刀具%'  limit 1'

**Comment by xrmx** [comment]
Which version of python is this?

**Comment by 15310944349** [comment]
@xrmx Python 2.7.9

**Comment by xrmx** [comment]
Please post the full backtrace from server logs

**Comment by 15310944349** [comment]
@xrmx
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 30: invalid continuation byte
Logged from file sql_lab.py, line 192
2017-10-04 12:02:37,550:ERROR:root:(sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'UPDATE "query" SET tmp_table_name=?, status=?, error_message=?, changed_on=? WHERE "query".id = ?'] [parameters: (None, u'failed', "unsupported format character '\xe5' (0xffffffe5) at index 74", '2017-10-04 04:02:37.549254', 768)]
Traceback (most recent call last):
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/superset/sql_lab.py", line 91, in get_sql_results
    ctask, query_id, return_results, store_results)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/superset/sql_lab.py", line 194, in execute_sql
    return handle_error(db_engine_spec.extract_error_message(e))
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/superset/sql_lab.py", line 120, in handle_error
    session.commit()
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/data00/test_users/luobin/superset/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'UPDATE "query" SET tmp_table_name=?, status=?, error_message=?, changed_on=? WHERE "query".id = ?'] [parameters: (None, u'failed', "unsupported format character '\xe5' (0xffffffe5) at index 74", '2017-10-04 04:02:37.549254', 768)]

**Comment by mistercrunch** [comment]
I'm guessing you have unicode characters in your query?

**Comment by 15310944349** [comment]
@mistercrunch **sql:**SELECT t_tm_article_id,title,subscribe_id FROM t_article WHERE title like '%品牌刀具%' limit 1'

**Comment by 15310944349** [comment]
@xrmx @mistercrunch 
How to solve this problem, thx.

**Comment by mistercrunch** [comment]
Have you tried python 3?

**Comment by 15310944349** [comment]
@mistercrunch  No

**Comment by mistercrunch** [comment]
Python 3 will likely take care of these unicode related issues. Also I would recommend avoiding sqlite outside of a sandbox environment. This is still a bug though.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 193 days. Feel free to comment and request for this issue to be reopened.
