### ISSUE TITLE
distribution chart regression with 0.20.0

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#3560]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.0

### Expected results

Slice is rendered

### Actual results

```
2017-10-02 16:37:59,980:ERROR:root:unorderable types: str() < int()
Traceback (most recent call last):
  File "/home/rm/superset/venv/lib/python3.4/site-packages/superset/viz.py", line 255, in get_payload
    data = self.get_data(df)
  File "/home/rm/superset/venv/lib/python3.4/site-packages/superset/viz.py", line 1127, in get_data
    values=self.metrics)
  File "/home/rm/superset/venv/lib/python3.4/site-packages/pandas/core/reshape/pivot.py", line 160, in pivot_table
    table = table.sort_index(axis=1)
  File "/home/rm/superset/venv/lib/python3.4/site-packages/pandas/core/frame.py", line 3243, in sort_index
    labels = labels._sort_levels_monotonic()
  File "/home/rm/superset/venv/lib/python3.4/site-packages/pandas/core/indexes/multi.py", line 1240, in _sort_levels_monotonic
    indexer = lev.argsort()
  File "/home/rm/superset/venv/lib/python3.4/site-packages/pandas/core/indexes/base.py", line 2091, in argsort
    return result.argsort(*args, **kwargs)
TypeError: unorderable types: str() < int()
```

### Steps to reproduce

load the slice

**Comment by xrmx** [comment]
This is was a problem with the 0.20.0 release, works fine in 0.20.1
