### ISSUE TITLE
Getting General Error <class 'sqlalchemy.exc.StatementError'> when trying to hook up Postgres database

### ISSUE THREAD

**Issue by delainewendling** [apache/incubator-superset#3568]
I am using Superset 0.20.0, Python 3.6.0, cryptography 1.7.2, and postgres 9.6.3. When I attempted to connect a Postgres database to Superset, I first tested the connection with the following SQLAlchemy URI: `postgresql+psycopg2://dwendling:XXXXXXXX@localhost/path` and superset said the connection seemed OK. All of the database tables from the database showed up at the bottom of the screen, so it seemed like everything was going to work.

However, when I pressed save I received the following errors. 

`General Error <class 'sqlalchemy.exc.StatementError'>`

`Traceback (most recent call last):
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 295, in add
    self.session.commit()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
    flush_context.execute()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 623, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 1074, in process
    return impl_processor(process_param(value, dialect))
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted.py", line 248, in process_bind_param
    self._update_key()
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted.py", line 243, in _update_key
    self.engine._update_key(key)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted.py", line 42, in _update_key
    digest = hashes.Hash(hashes.SHA256(), backend=default_backend())
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 27, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 17, in <module>
    from cryptography import utils, x509
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/Users/dwendling/venvs/test/lib/python3.6/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
sqlalchemy.exc.StatementError: (builtins.ImportError) dlopen(/Users/dwendling/venvs/test/lib/python3.6/site-packages/_cffi_backend.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /Users/dwendling/venvs/test/lib/python3.6/site-packages/_cffi_backend.cpython-36m-darwin.so
  Expected in: flat namespace`

### Steps to reproduce

My co-worker tried to reproduce the errors I am receiving but he was able to connect without problem. I am not sure what could be causing the problem, we seem to have the same configuration. Any help would be appreciated!

**Comment by xrmx** [comment]
Looks like a cryptography issue, try to upgrade it to see if  newer version works.

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 202 days. Feel free to comment and request for this issue to be reopened.
