### ISSUE TITLE
Foreign table cannot be loaded in SQL lab Tab

### ISSUE THREAD

**Issue by jessicachen888** [apache/incubator-superset#3694]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
A table names event_warnings should appear in the SQL lab query tab when user select the corresponding databases and schema.
 

### Actual results
![image](https://user-images.githubusercontent.com/16902443/31760961-04cf4b08-b47c-11e7-965d-284cfc9052b4.png)

The event_warnings table appear in the Slice tab
![image](https://user-images.githubusercontent.com/16902443/31761164-aba0dee2-b47c-11e7-928b-35b36123313d.png)

### Steps to reproduce

Use a Foreign Data Wrapper mongodb + multicorn + yam_fdw o create a foreign table in postgresql

**In Postgresql console:**

`CREATE EXTENSION multicorn;

CREATE SERVER mongodb_proxy_server FOREIGN DATA WRAPPER multicorn OPTIONS (wrapper 'yam_fdw.Yamfdw');

CREATE FOREIGN TABLE event_warnings ( 
"_id" varchar OPTIONS (type 'ObjectId'),
"ID" varchar, "Point" varchar,
"Start_Time" timestamptz, "Stop_Time" timestamptz, "Area" varchar,
"Value" float, "Station" varchar, "Device" varchar, "Warning_Type" varchar,
"Warning_Upper_Limit" float, "Warning_Lower_Limit" float,
"Warning_Method" int
)

SERVER mongodb_proxy_server OPTIONS ( 
db 'XXX', collection 'event_warnings', 
host '122.XXX.XXX.XXX', port '27017', user 'username', password 'password'
);`

In superset:
![image](https://user-images.githubusercontent.com/16902443/31761295-08e75450-b47d-11e7-80ce-b5f29de9c3bb.png)

OS: Mac 64 bit

**Comment by xrmx** [comment]
Any interesting bits in the superset server logs?

**Comment by jessicachen888** [comment]
I copy the SQL query from the Slice Tab and paste it into the SQL lab to get the following server log:

![image](https://user-images.githubusercontent.com/16902443/31764052-aedf314a-b485-11e7-899d-ffd5ae653342.png)


`2017-10-19 17:19:54,321:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://Jessica:XXXXXXXXXX@localhost/Jessica
2017-10-19 17:19:54,341:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://Jessica:XXXXXXXXXX@localhost/Jessica
2017-10-19 17:19:54,480:INFO:werkzeug:127.0.0.1 - - [19/Oct/2017 17:19:54] "GET /databaseasync/api/read?_flt_0_expose_in_sqllab=1&_oc_DatabaseAsync=database_name&_od_DatabaseAsync=asc HTTP/1.1" 200 -
2017-10-19 17:19:54,591:INFO:werkzeug:127.0.0.1 - - [19/Oct/2017 17:19:54] "GET /superset/schemas/2/ HTTP/1.1" 200 -
2017-10-19 17:19:54,595:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://Jessica:XXXXXXXXXX@localhost/Jessica
2017-10-19 17:19:54,677:INFO:werkzeug:127.0.0.1 - - [19/Oct/2017 17:19:54] "GET /superset/tables/2/public/undefined/ HTTP/1.1" 200 -
2017-10-19 17:19:54,708:INFO:root:[stats_logger] (incr) sql_json
2017-10-19 17:19:54,712:INFO:root:Parsing with sqlparse statement SELECT "Station" AS "Station",
       COUNT(*) AS count
FROM public.event_warnings
WHERE "Start_Time" >= '2016-01-01 00:00:00'
  AND "Start_Time" <= '2017-10-19 15:02:07'
GROUP BY "Station"
ORDER BY count DESC
LIMIT 50000
2017-10-19 17:19:54,782:INFO:werkzeug:127.0.0.1 - - [19/Oct/2017 17:19:54] "GET /static/appbuilder/fonts/fontawesome-webfont.woff?v=4.7.0 HTTP/1.1" 304 -
2017-10-19 17:19:54,870:INFO:root:Triggering query_id: 32
2017-10-19 17:19:54,870:INFO:root:Running query on a Celery worker
2017-10-19 17:19:55,565:ERROR:root:[Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/utils/__init__.py", line 423, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 449, in _ensured
    return fun(*args, **kwargs)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/utils/__init__.py", line 425, in __call__
    value = self.__value__ = self.__contract__()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 771, in default_channel
    self.connection
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jessica/Desktop/work/incubator-superset-master/superset/views/core.py", line 2106, in sql_json
    store_results=not query.select_as_cta, user_name=g.user.username)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/celery/app/task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 250, in connect
    return self.connection
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/Users/Jessica/anaconda/lib/python3.4/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
OSError: [Errno 61] Connection refused
`

**Comment by xrmx** [comment]
That's celery not being able to connect to your amqp broker.

**Comment by jessicachen888** [comment]
How to enable celery to connect the amqp broker ?

**Comment by xrmx** [comment]
Take a look at the documentation:
https://superset.incubator.apache.org/installation.html#sql-lab

**Comment by jessicachen888** [comment]
I have enabled celery.  But when I run the same query, the following error appears:

<img width="1273" alt="screen shot 2017-10-20 at 2 07 46 pm" src="https://user-images.githubusercontent.com/16902443/31808199-bbbd5dee-b537-11e7-9c7c-9288f2507895.png">

In config.py:

`# On Redis
from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')

class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = ('superset.sql_lab', )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
    CELERYD_LOG_LEVEL = 'DEBUG'
    CELERYD_PREFETCH_MULTIPLIER = 1
    CELERY_ACKS_LATE = True

# CELERY_CONFIG = None
CELERY_CONFIG = CeleryConfig
SQL_CELERY_DB_FILE_PATH = os.path.join(DATA_DIR, 'celerydb.sqlite')
SQL_CELERY_RESULTS_DB_FILE_PATH = os.path.join(DATA_DIR, 'celery_results.sqlite')
`

Console:
`JessicaChens-MacBook-Pro:incubator-superset-master Jessica$ superset worker
 
 -------------- celery@JessicaChens-MacBook-Pro.local v3.1.25 (Cipater)
---- **** ----- 
--- * ***  * -- Darwin-15.6.0-x86_64-i386-64bit
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x109310710
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 32 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                

[2017-10-20 14:00:59,546: WARNING/MainProcess] celery@JessicaChens-MacBook-Pro.local ready.

2017-10-20 14:15:37,576:INFO:root:[stats_logger] (incr) sql_json
2017-10-20 14:15:37,579:INFO:root:Parsing with sqlparse statement SELECT "Station" AS "Station",
       COUNT(*) AS count
FROM public.event_warnings
WHERE "Start_Time" >= '2016-01-01 00:00:00'
  AND "Start_Time" <= '2017-10-19 15:02:07'
GROUP BY "Station"
ORDER BY count DESC
LIMIT 50000
2017-10-20 14:15:37,643:INFO:root:Triggering query_id: 40
2017-10-20 14:15:37,643:INFO:root:Running query on a Celery worker
/Users/Jessica/anaconda/lib/python3.4/site-packages/sqlalchemy/sql/sqltypes.py:596: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
2017-10-20 14:15:37,719:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 14:15:37] "POST /superset/sql_json/ HTTP/1.1" 202 -
`

**Comment by jessicachen888** [comment]
I have installed the s3werkzeugcache and tried 
`from s3cache.s3cache import S3Cache
S3_CACHE_BUCKET = 'foobar-superset'
S3_CACHE_KEY_PREFIX = 'sql_lab_result'
RESULTS_BACKEND = S3Cache(S3_CACHE_BUCKET, S3_CACHE_KEY_PREFIX)`

Still the same error occurs. I saw some solution on the discussion forum before, but I cannot solve mine with their solution

**Comment by jessicachen888** [comment]
I have set all the celery config but when I ran the same query in the SQL Lab, the following error message appears: 
![image](https://user-images.githubusercontent.com/16902443/31810818-bf5e027c-b542-11e7-8097-4db31d2c7bca.png)

But still, in the slices section, the public.event_warnings can be found and do all kinds of visualization. 

The console log appears the following:
2017-10-20 15:54:05,334:INFO:root:[stats_logger] (incr) sql_json
2017-10-20 15:54:05,338:INFO:root:Parsing with sqlparse statement SELECT "Station" AS "Station",
       COUNT(*) AS count
FROM public.event_warnings
WHERE "Start_Time" >= '2016-01-01 00:00:00'
  AND "Start_Time" <= '2017-10-19 16:18:08'
GROUP BY "Station"
ORDER BY count DESC
LIMIT 50000
2017-10-20 15:54:05,421:INFO:root:Triggering query_id: 51
2017-10-20 15:54:05,421:INFO:root:Running query on a Celery worker
2017-10-20 15:54:05,444:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:05] "POST /superset/sql_json/ HTTP/1.1" 202 -
2017-10-20 15:54:05,617:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:05,632:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:05] "GET /superset/queries/1508485922891.331 HTTP/1.1" 200 -
2017-10-20 15:54:07,619:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:07,631:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:07] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:09,621:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:09,632:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:09] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:11,620:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:11,632:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:11] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:13,616:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:13,631:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:13] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:15,617:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:15,630:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:15] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:17,974:INFO:root:[stats_logger] (incr) queries
2017-10-20 15:54:17,984:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:17] "GET /superset/queries/1508486040528.338 HTTP/1.1" 200 -
2017-10-20 15:54:18,081:INFO:root:[stats_logger] (incr) results
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-parameter-build.s3.HeadObject: calling handler <function sse_md5 at 0x105dd90d0>
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-parameter-build.s3.HeadObject: calling handler <function validate_bucket_name at 0x105dd9048>
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-parameter-build.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x10857d748>>
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-parameter-build.s3.HeadObject: calling handler <function generate_idempotent_uuid at 0x105dd4bf8>
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-call.s3.HeadObject: calling handler <function add_expect_header at 0x105dd9510>
2017-10-20 15:54:18,081:DEBUG:botocore.hooks:Event before-call.s3.HeadObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x10857d748>>
2017-10-20 15:54:18,082:DEBUG:botocore.endpoint:Making request for OperationModel(name=HeadObject) (verify_ssl=True) with params: {'headers': {'User-Agent': 'Boto3/1.4.4 Python/3.4.3 Darwin/15.6.0 Botocore/1.5.95'}, 'method': 'HEAD', 'query_string': {}, 'url': 'https://s3.amazonaws.com/foobar-superset/sql_lab_resulted66a13f-1b5b-4e51-a982-62990e1e2b3b', 'body': b'', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x1084d8cf8>, 'signing': {'bucket': 'foobar-superset'}, 'has_streaming_input': False, 'auth_type': None}, 'url_path': '/foobar-superset/sql_lab_resulted66a13f-1b5b-4e51-a982-62990e1e2b3b'}
2017-10-20 15:54:18,082:DEBUG:botocore.hooks:Event request-created.s3.HeadObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1084d8828>>
2017-10-20 15:54:18,082:DEBUG:botocore.hooks:Event choose-signer.s3.HeadObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x105f779e8>>
2017-10-20 15:54:18,082:DEBUG:botocore.hooks:Event choose-signer.s3.HeadObject: calling handler <function set_operation_specific_signer at 0x105dd4ae8>
2017-10-20 15:54:18,082:DEBUG:botocore.hooks:Event before-sign.s3.HeadObject: calling handler <function fix_s3_host at 0x105cb6730>
2017-10-20 15:54:18,089:INFO:werkzeug:127.0.0.1 - - [20/Oct/2017 15:54:18] "GET /superset/results/ed66a13f-1b5b-4e51-a982-62990e1e2b3b/ HTTP/1.1" 410 -

**Comment by xrmx** [comment]
Could you please quote the logs in markdown so they are more readable?

**Comment by jessicachen888** [comment]
Sorry, I have updated.

**Comment by jessicachen888** [comment]
I revert to 0.18.5, the problem solved. I guess there's some bug in the latest version ?

**Comment by mistercrunch** [comment]
Warning: this issue has been inactive for 182 days and will be automatically closed on 2018-04-30 if there is no further activity. You can add the `keepup` label to the issue in order for this bot to keep it open.
