### ISSUE TITLE
Slice Datasource set to None after changing DB connection string

### ISSUE THREAD

**Issue by wfowlks** [apache/incubator-superset#3718]
- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.4

### Expected results
Displays Slice Visualization

### Actual results
<img width="809" alt="screen shot 2017-10-25 at 12 07 30 pm" src="https://user-images.githubusercontent.com/7023176/32009553-6ea7962e-b97d-11e7-9bf7-9cf4418223c4.png">

```
[2017-10-25 12:15:39,691] ERROR in app: Exception on /superset/explore/table/None/ [GET]
Traceback (most recent call last):
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/models/core.py", line 811, in wrapper
    value = f(*args, **kwargs)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/utils.py", line 601, in wraps
    return f(self, *args, **kwargs)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/views/core.py", line 1039, in explore
    datasource_id = int(datasource_id)
ValueError: invalid literal for int() with base 10: 'None'
Exception on /superset/explore/table/None/ [GET]
Traceback (most recent call last):
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centos/superset/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/models/core.py", line 811, in wrapper
    value = f(*args, **kwargs)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/utils.py", line 601, in wraps
    return f(self, *args, **kwargs)
  File "/home/centos/superset/venv/lib/python2.7/site-packages/superset/views/core.py", line 1039, in explore
    datasource_id = int(datasource_id)
ValueError: invalid literal for int() with base 10: 'None'
```

### Steps to reproduce

1. Have a Working SQLAlchemy DB Connection (using the impyla connector).
2. Create a table for the visualization
3. Create a slice from the table
4. Modify the connection string to invalid connection info. Press Save
5. Go to the Slice visualization
6. Fix the SQLAlchemy DB connection string

At this point all the Datasources are cleared and set to 'None' even thought the table was untouched, and there is no easy way to rectify this without creating all new slices, and you cant go to the edit visualization tab as you just get a stacktrace.

**Comment by mistercrunch** [comment]
Warning: this issue has been inactive for 180 days and will be automatically closed on 2018-05-03 if there is no further activity. You can add the `keepup` label to the issue in order for this bot to keep it open.
