### ISSUE TITLE
Cannot View Slices List - 500 Error

### ISSUE THREAD

**Issue by claycrosby** [apache/incubator-superset#3743]
I was creating some slices to familiarize myself with the platform, and I noticed one of my tables wasn't changing as I updated time granularity from daily to weekly. On that slice, I removed the parameters that the help text says automatically populate when you save a slice, and now I am unable to view the slices tab or any dashboard with that slice included.

### Superset version
{"version": "0.19.0", "GIT_SHA": ""}

### Expected results
Click on Slices tab
View list of slices

### Actual results
Click on Slices tab
Get 500 internal error (pasted below)

### Steps to reproduce
Click on Slices tab.

---

Sorry, something went wrong

500 - Internal Server Error

Stacktrace

         Traceback (most recent call last):
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/views.py", line 478, in list
    widgets=widgets)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 13, in block "content"
    {% block list_list scoped %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 15, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/base_list.html", line 23, in top-level template code
    {% block begin_loop_values %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/runtime.py", line 410, in __init__
    self._after = self._safe_next()
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/jinja2/runtime.py", line 430, in _safe_next
    return next(self._iterator)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 87, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/flask_appbuilder/models/base.py", line 36, in _get_attr_value
    if not hasattr(item, col):
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/models/core.py", line 215, in slice_link
    url = self.slice_url
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/models/core.py", line 201, in slice_url
    obj=self, params=parse.quote(json.dumps(self.form_data))))
  File "/home/ubuntu/envs/bid/lib/python3.5/site-packages/superset/models/core.py", line 185, in form_data
    form_data = json.loads(self.params)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by claycrosby** [comment]
I was able to fix this by referencing #3507

**Comment by xrmx** [comment]
Then close the issue, thanks.
