### ISSUE TITLE
srcdoc-polyfill build error

### ISSUE THREAD

**Issue by diggzhang** [apache/incubator-superset#3753]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

```javascript
{
  "GIT_SHA": "b'03e2af8bd923dbdebbc70213b359d36fe89d7b42\\n'",
  "version": "0.20.0"
}
```

### Expected results

```shell
# Update node packages
$ npm install --save srcdoc-polyfill 

# build frontend project
$ npm run dev
```

### Actual results

```shell
ERROR in {$SUPERSET_HOME}incubator-superset/node_modules/srcdoc-polyfill/srcdoc-polyfill.js
Module build failed: Error: Couldn't find preset "airbnb" relative to directory "{$SUPERSET_HOME}incubator-superset/node_modules/srcdoc-polyfill"
    at {$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports ({$SUPERSET_HOME}incubator-superset/superset/assets/node_modules/babel-loader/lib/index.js:175:20)
 @ ./visualizations/markup.js 3:13-39
 @ ./visualizations/main.js
 @ ./javascripts/modules/superset.js
 @ ./javascripts/dashboard/Dashboard.jsx
 @ multi babel-polyfill ./javascripts/dashboard/Dashboard.jsx
```

### Steps to reproduce

pull latest code enter assets then run:

```shell
$ npm run dev
```

**Comment by xrmx** [comment]
Just `npm install` should work
