### ISSUE TITLE
Not able to execute a post request to Superset

### ISSUE THREAD

**Issue by vivekna1** [apache/incubator-superset#3883]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.6

### Actual results

 curl -v -X POST http://192.168.0.5:8088/slicemodelview/api/create -d '{ "item" : {"params" : {"bottom_margin": "auto", "y_axis_label": "", "row_limit": null, "reduce_x_ticks": false, "filters": [], "show_controls": false, "granularity_sqla": null, "viz_type": "dist_bar", "since": "", "x_axis_label": "", "order_bars": false, "color_scheme": "bnbColors", "until": "", "columns": ["year"], "show_bar_value": false, "y_axis_format": ".3s", "metrics": ["impressions"], "where": "", "show_legend": true, "having": "", "datasource": "8__table", "contribution": false, "time_grain_sqla": null, "groupby": ["cid"], "bar_stacked": false}, "slice_name" : "online ads", "datasource_type" : "table", "viz_type" : "dist_bar", "datasource_id" : 8 }}'
*   Trying 192.168.0.5...
* TCP_NODELAY set
* Connected to 192.168.0.5 (192.168.0.5) port 8088 (#0)
> POST /slicemodelview/api/create HTTP/1.1
> Host: 192.168.0.5:8088
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Server: gunicorn/19.7.1
< Date: Thu, 16 Nov 2017 10:07:58 GMT
< Connection: close
< Content-Type: application/json
< Set-Cookie: session=eyJfaWQiOnsiIGIiOiJaV0ptWlRReU9UQmpNR000TlRRM09ESXhORFEyWXpGalptUmxaVGRrTm1FPSJ9LCJsb2NhbGUiOiJlbiJ9.DO70_g.3eeSeA5_1pcUh3WgT73iEbIapZU; HttpOnly; Path=/
< Content-Length: 521
< 
{
  "item": {
    "cache_timeout": "None", 
    "changed_by": "None", 
    "changed_on": "2017-11-16 15:37:58.335298", 
    "created_by": "None", 
    "created_on": "2017-11-16 15:37:58.335228", 
    "dashboards": "[]", 
    "datasource_id": "None", 
    "datasource_name": "", 
    "datasource_type": "", 
    "description": "", 
    "owners": "[]", 
    "params": "", 
    "perm": "", 
    "slice_name": "", 
    "viz_type": ""
  }, 
  "message": "General Error <type 'exceptions.KeyError'>", 
  "severity": "danger"
}
* Closing connection 0

### Steps to reproduce
Curl again with the same data.

The issue is I am not able to get positive response for any similar request to this api.

In config.py - I have modified CSRF_TOKEN = False.
 

-- The error log in Server side.---
2017-11-16 15:37:58,379:ERROR:flask_appbuilder.models.sqla.interface:Add record error: u''
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/models/sqla/interface.py", line 295, in add
self.session.commit()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 157, in do
return getattr(self.registry(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
self.transaction.commit()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 461, in commit
fn(*args, **kw)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/events.py", line 616, in wrap
fn(*arg, **kw)
File "/usr/local/lib/python2.7/dist-packages/superset/models/core.py", line 54, in set_related_perm
src_class = target.cls_model
File "/usr/local/lib/python2.7/dist-packages/superset/models/core.py", line 120, in cls_model
return ConnectorRegistry.sources[self.datasource_type]
KeyError: u''

**Comment by vivekna1** [comment]
--- The error log in Server side.---
2017-11-16 15:37:58,379:ERROR:flask_appbuilder.models.sqla.interface:Add record error: u''
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask_appbuilder/models/sqla/interface.py", line 295, in add
    self.session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 461, in commit
    fn(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/events.py", line 616, in wrap
    fn(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/superset/models/core.py", line 54, in set_related_perm
    src_class = target.cls_model
  File "/usr/local/lib/python2.7/dist-packages/superset/models/core.py", line 120, in cls_model
    return ConnectorRegistry.sources[self.datasource_type]
KeyError: u''
