### ISSUE TITLE
Issue with superset upgrade

### ISSUE THREAD

**Issue by ayush0793** [apache/incubator-superset#3942]
Make sure these boxes are checked before submitting your issue - thank you!

- [done ] I have checked the superset logs for python stacktraces and included it here as text if any
- [done ] I have reproduced the issue with at least the latest released version of superset
- [ done] I have checked the issue tracker for the same issue and I haven't found one similar

I recently upgraded superset from version 0.20.6 to 0.21dev. Now whenever I try access druid datasources the following error occurs in 
```
  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ayush/Desktop/superset-fork/superset/models/core.py", line 860, in wrapper
    value = f(*args, **kwargs)
  File "/home/ayush/Desktop/superset-fork/superset/utils.py", line 624, in wraps
    return f(self, *args, **kwargs)
  File "/home/ayush/Desktop/superset-fork/superset/views/core.py", line 1129, in explore
    'datasource': datasource.data,
  File "/home/ayush/Desktop/superset-fork/superset/connectors/base/models.py", line 148, in data
    for s in sorted(self.column_names):
  File "/home/ayush/Desktop/superset-fork/superset/connectors/base/models.py", line 67, in column_names
    return sorted([c.column_name for c in self.columns])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 635, in _emit_lazyload
    result = q.all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) no such column: columns.datasource_id [SQL: u'SELECT columns.created_on AS columns_created_on, columns.changed_on AS columns_changed_on, columns.id AS columns_id, columns.column_name AS columns_column_name, columns.verbose_name AS columns_verbose_name, columns.is_active AS columns_is_active, columns.type AS columns_type, columns.groupby AS columns_groupby, columns.count_distinct AS columns_count_distinct, columns.sum AS columns_sum, columns.avg AS columns_avg, columns.max AS columns_max, columns.min AS columns_min, columns.filterable AS columns_filterable, columns.description AS columns_description, columns.datasource_id AS columns_datasource_id, columns.dimension_spec_json AS columns_dimension_spec_json, columns.changed_by_fk AS columns_changed_by_fk, columns.created_by_fk AS columns_created_by_fk \nFROM columns \nWHERE ? = columns.datasource_id'] [parameters: (1,)]
```
### Steps to reproduce
Download version 0.20.6
Download version 0.21dev
upgrade db in 0.21dev version and add druid cluster
Access druid datasource in  0.20.6 version
Observe error

**Comment by mistercrunch** [comment]
@john-bodley do you think it's related to your new migration?

**Comment by ayush0793** [comment]
I guess that is the case.

This is the error we get if superset.db of 0.20.6 version is used for superset 0.21dev
OperationalError: (sqlite3.OperationalError) no such column: columns.datasource_name

As you can see the the error above gives an idea that columns do not match.

**Comment by john-bodley** [comment]
@ayush0793 did you run 'superset db upgrade' as part of the upgrade to Superset 0.21dev?

**Comment by ayush0793** [comment]
@john-bodley 
No. 

I wanted to use all the data and configuration done on 0.20 version for the newer version. For that I directly imported the superset.db file into 0.21dev version. But the error persisted. I also tried to initialise the db using 'superset db upgrade' but to no avail.

**Comment by john-bodley** [comment]
@ayush0793 when you ran the 'superset db upgrade' command was an error thrown? If so you paste the stack trace. 

Also could you paste the SQLite schema for the columns table? In addition to the unit tests, when testing this change I successfully was able to upgrade an existing populated SQLite database.

**Comment by ayush0793** [comment]
@john-bodley There is no error when 'superset db upgrade' is executed. Please try accessing druid datasources and open the explore druid window.

**Comment by hajdbo** [comment]
@kristw please close: obsolete.
