### ISSUE TITLE
[windows] Import ERROR superset

### ISSUE THREAD

**Issue by sebastianwindeck** [apache/incubator-superset#3990]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

Hey maybe this question is a little stupid, but I am trying to use superset sql editor and it does not work out. When I start a query it shows pending ... . Okay what did I do: I used redis in the standard configuration how it is presented in docs. But when I start the REDIS-SERVER and the SUPERSET-SERVER and I want to start the worker, but it doesn't work. It shows an Import Error 'superset'. 

### Superset version

0.20.6 

### Expected results

No Error and the SQL Editor works. 

### Actual results

When starting the **superset worker**:

Loaded your LOCAL configuration at [C:\Users\******\venv\Scripts\superset_config.py]
[2017-12-01 23:14:15,769: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2017-12-01 23:14:15,847: DEBUG/MainProcess] | Worker: Building graph...
[2017-12-01 23:14:15,847: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Queues (intra), Pool, Autoscaler, Autoreloader, StateDB, Consumer}
[2017-12-01 23:14:15,941: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2017-12-01 23:14:15,941: DEBUG/MainProcess] | Consumer: Building graph...
[2017-12-01 23:14:15,972: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Tasks, Control, Heart, Gossip, event loop}

 -------------- celery@****** v3.1.25 (Cipater)
---- **** -----
--- * ***  * -- Windows-10-10.0.14393-SP0
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x18c5a8b44a8
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 32 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery

[tasks]
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . superset.sql_lab.get_sql_results

[2017-12-01 23:14:16,003: DEBUG/MainProcess] | Worker: Starting Pool
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 430, in main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 430, in main
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 430, in main
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 557, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
  File "C:\Users\.....\venv\lib\imp.py", line 297, in find_module
    prepare(preparation_data)
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 557, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
  File "C:\Users\.....\venv\lib\imp.py", line 297, in find_module
    prepare(preparation_data)
  File "C:\Users\.....\venv\lib\site-packages\billiard\forking.py", line 557, in prepare
    raise ImportError(_ERR_MSG.format(name), name=name)
**ImportError: No module named 'superset'**

**superset_config.py**

class CeleryConfig(object):
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_IMPORTS = ('superset.sql_lab', )
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}

CELERY_CONFIG = CeleryConfig

from werkzeug.contrib.cache import RedisCache
RESULTS_BACKEND = RedisCache(
    host='localhost', port=6379, key_prefix='superset_results')

LOG_LEVEL = 'DEBUG'

### Steps to reproduce

Use the shell in pythonfolder and type: **python superset worker**

**Comment by xrmx** [comment]
Superset is not supported on windows. Contribution to fix that are more than welcome though.
