### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by jerrison** [apache/incubator-superset#4095]
I am using windows 10 pro
I have two issues:

1. When I type `superset db upgrade` following the installation instructions, I get the following error:
'superset' is not recognized as an internal or external command.  I tried adding to path and it still does not work.  I had to go to the directory and run `python superset db upgrade`.

2.  When I get to the `superset runserver` part, I get the following error:

> python superset runserver
Starting server with command:
gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app
Traceback (most recent call last):
  File "c:\users\jerrison.li\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jerrison.li\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jerrison.li\AppData\Local\Continuum\anaconda3\Scripts\gunicorn.exe\__main__.py", line 5, in <module>
  File "c:\users\jerrison.li\appdata\local\continuum\anaconda3\lib\site-packages\gunicorn\app\wsgiapp.py", line 10, in <module>
    from gunicorn.app.base import Application
  File "c:\users\jerrison.li\appdata\local\continuum\anaconda3\lib\site-packages\gunicorn\app\base.py", line 12, in <module>
    from gunicorn import util
  File "c:\users\jerrison.li\appdata\local\continuum\anaconda3\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by xrmx** [comment]
I think you missed that superset is not supported on windows. It may work on WSL though.

**Comment by jerrison** [comment]
@xrmx The installation instructions says that it is not officially supported but it does have instructions for Windows.

**Comment by xrmx** [comment]
Not supported means please does not file issues you ain't gonna fix yourself. This one is gunicorn not working on windows which is both known and not a superset issue.
