### ISSUE TITLE
Table Metadata Refresh | TypeError: 'SqlaTable' object is not iterable

### ISSUE THREAD

**Issue by dhuckins** [apache/incubator-superset#4206]
Make sure these boxes are checked before submitting your issue - thank you!

- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ X] I have reproduced the issue with at least the latest released version of superset
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.22.1

### Expected results
table metadata to be refreshed

### Actual results
TypeError: 'SqlaTable' object is not iterable

### Steps to reproduce
Trying to refresh a single MySql table by clicking <url>/tablemodelview/show 'Refresh Metadata' button
```
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
         Traceback (most recent call last):
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/superset/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/superset/venv/lib/python3.5/site-packages/flask_appbuilder/views.py", line 558, in action
    return action.func(self.datamodel.get(pk))
  File "/opt/superset/venv/lib/python3.5/site-packages/superset/connectors/sqla/views.py", line 282, in refresh
    for t in tables:
TypeError: 'SqlaTable' object is not iterable
```

**Comment by theikkila** [comment]
This is bug when activating the refresh action in detail view. It works when in listing view selecting first the checkbox and then activating the action through action-menu

**Comment by mistercrunch** [comment]
Thanks for reporting the bug the fix is here:
https://github.com/apache/incubator-superset/pull/4452
