### ISSUE TITLE
Markup raise Exception(_('Empty query?'))

### ISSUE THREAD

**Issue by zhizunbao514** [apache/incubator-superset#4212]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
When I have updated the latest version,Visualization Type is Markup,raise Exception.Can help to solve it, thank you very much!

### Actual results
Traceback (most recent call last):
  File "/home/superset/incubator-superset-master/superset/views/core.py", line 1053, in generate_json
    force=force)
  File "/home/superset/incubator-superset-master/superset/viz.py", line 246, in get_payload
    cache_key = self.cache_key(query_obj)
  File "/home/superset/incubator-superset-master/superset/viz.py", line 239, in cache_key
    self.datasource.get_query_str(query_obj),
  File "/home/superset/incubator-superset-master/superset/connectors/sqla/models.py", line 404, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/home/superset/incubator-superset-master/superset/connectors/sqla/models.py", line 483, in get_sqla_query
    raise Exception(_('Empty query?'))

**Comment by zhaoyongjie** [comment]
Other visualization types can work?

**Comment by zhizunbao514** [comment]
@zhaoyongjie Other normal, what should I do, help me！thank you！

**Comment by zhaoyongjie** [comment]
I can not reproduce your issue. Please send more steps for reproduce.

**Comment by zhizunbao514** [comment]
@zhaoyongjie When I was in use markup chart, he reported to the error
