### ISSUE TITLE
run superset 0.22.1 appear flask-appbuilder None type error 

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#4219]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

I update my superset today, but found warning in my every step of superset initialtion

```
2018-01-16 20:17:45,625:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,626:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,917:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,917:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
```

No matter which init step, like ` fabmanager create-admin --app superset`, `superset db upgrade`, `superset init` to `superset runserver`, all of them pop error message as shown above.

The following are steps to reproduce:

###  fabmanager create-admin --app superset
```

Username [admin]: a
User first name [admin]: a
User last name [user]: a
Email [admin@fab.org]: a@gmail.com
Password:
Repeat for confirmation:
2018-01-16 20:17:45,625:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,626:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,917:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:17:45,917:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
Recognized Database Authentications.
Admin User a created.
```

### superset db upgrade
```
2018-01-16 20:21:50,474:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:21:50,475:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-01-16 20:21:50,754:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:21:50,754:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

### superset runserver
```
2018-01-16 20:22:38,572:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:22:38,573:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-01-16 20:22:38,880:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-16 20:22:38,880:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
Starting server with command:
gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app

[2018-01-16 20:22:39 +0800] [71749] [INFO] Starting gunicorn 19.7.1
[2018-01-16 20:22:39 +0800] [71749] [INFO] Listening at: http://0.0.0.0:8088 (71749)
[2018-01-16 20:22:39 +0800] [71749] [INFO] Using worker: sync
[2018-01-16 20:22:39 +0800] [71752] [INFO] Booting worker with pid: 71752
[2018-01-16 20:22:39 +0800] [71753] [INFO] Booting worker with pid: 71753
[2018-01-16 20:22:40 +0800] [71752] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/serena/Documents/serena/incubator-superset/superset/__init__.py", line 156, in <module>
    update_perms=utils.get_update_perms_flag(),
TypeError: __init__() got an unexpected keyword argument 'update_perms'
[2018-01-16 20:22:40 +0800] [71752] [INFO] Worker exiting (pid: 71752)
[2018-01-16 20:22:40 +0800] [71753] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/Users/serena/Documents/serena/incubator-superset/superset/__init__.py", line 156, in <module>
    update_perms=utils.get_update_perms_flag(),
TypeError: __init__() got an unexpected keyword argument 'update_perms'
[2018-01-16 20:22:40 +0800] [71753] [INFO] Worker exiting (pid: 71753)
Traceback (most recent call last):
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

cannot start superset 😰, and even I started in older version, the css is missing somehow..
I am using OSX, is there anything wrong with my computer??
I used to successfully setup and start superset, but seems unlucky this time.

**Comment by yamyamyuo** [comment]
* even if I have started the superset server, the css seems not working
<img width="1386" alt="screen shot 2018-01-16 at 8 24 41 pm" src="https://user-images.githubusercontent.com/8351385/34988932-7a473240-fafb-11e7-94da-d451bb7c8ed5.png">

<img width="1111" alt="screen shot 2018-01-16 at 8 24 35 pm" src="https://user-images.githubusercontent.com/8351385/34988955-99d0a8c6-fafb-11e7-9ad4-e596b33a8ffb.png">

**Comment by xrmx** [comment]
Are you sure this is 0.22.1 and not a build from git? If that's a build from git you need to build the frontend assets as documented. Which version of flask app builder do you have installed? Is it the same of the one in the setup.py for your version?

**Comment by yamyamyuo** [comment]
@xrmx thanks for your reply! 
### 1. I checked flask-appbuilder
```
~/Documents » pip show flask-appbuilder                                                               
Name: Flask-AppBuilder
Version: 1.9.4
Summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.
Home-page: https://github.com/dpgaspar/flask-appbuilder/
Author: Daniel Vaz Gaspar
Author-email: danielvazgaspar@gmail.com
License: BSD
Location: /Users/serena/Documents/serena/incubator-superset/fix_css/lib/python2.7/site-packages
Requires: colorama, Flask-SQLAlchemy, Flask-Login, click, Flask-Babel, Flask, Flask-OpenID, Flask-WTF
```
this version is required in superset-0.22.1

### 2. I avoid using `superset runserver` under git repo
I run superset in new virtualenv, this time it can run and css is correct, however, the following traceback is still apear.

```
2018-01-17 10:25:09,764:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/serena/Documents/test-superset/lib/python2.7/site-packages/flask_appbuilder/base.py", line 462, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/Users/serena/Documents/test-superset/lib/python2.7/site-packages/flask_appbuilder/security/manager.py", line 804, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-01-17 10:25:09,765:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-01-17 10:25:10,073:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
```

**Comment by yamyamyuo** [comment]
BTW, if I want to run superset from source code, how to deal with the css problem?
 How to build the frontend assets? @xrmx

**Comment by zhaoyongjie** [comment]
```
yongjie.zhao@:assets$ pwd
/workspace/incubator-superset/superset/assets
yongjie.zhao@:assets$ npm install
```
use this case, try again.

**Comment by yamyamyuo** [comment]
@zhaoyongjie after npm install
```
incubator-superset(master*) » npm -v                                         
5.6.0
incubator-superset/superset/assets(master*) » npm install                          
up to date in 7.735s
```

the css is still not working

**Comment by zhaoyongjie** [comment]
You must build frontend project. 
```
yongjie.zhao@:assets$ pwd
/workspace/incubator-superset/superset/assets
yongjie.zhao@:assets$ npm run build
```

**Comment by yamyamyuo** [comment]
@zhaoyongjie thanks! I try to follow this steps: https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment

**Comment by mistercrunch** [comment]
The `update_perms` error means you haven't upgrade `flask-appbuilder` as specified in a recent `setup.py`. If you're developing against the repo run `pip instal -e .` from the root of the repo.

**Comment by xiaohanyu** [comment]
@yamyamyuo the official document already has commands to run from source code. 

For frontend build, just follow some basic steps:

- Use `yarn install` to get all dependencies from npm, do not use `npm`, it often has bugs
- Use `npm run dev` to run development webpack server for frontend assets, with debug info, and large size assets. Or use `npm run build` to build production assets, with smaller size.
