### ISSUE TITLE
Interval type annotation throws NotImplementedError

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#4295]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

With the latest cache logic, cache_key is generated from datasource' get_query_str. But AnnotationDatasource throws NotImplementedError. Frontend receives 500 error.

### Superset version
latest

### Expected results
Render interval annotation

### Actual results
```
Traceback (most recent call last):
  File "/Users/grace_guo/Documents/superset/superset/views/core.py", line 1089, in annotation_json
    payload = viz_obj.get_payload(force=False)
  File "/Users/grace_guo/Documents/superset/superset/viz.py", line 246, in get_payload
    cache_key = self.cache_key(query_obj) if query_obj else None
  File "/Users/grace_guo/Documents/superset/superset/viz.py", line 239, in cache_key
    self.datasource.get_query_str(query_obj),
  File "/Users/grace_guo/Documents/superset/superset/connectors/sqla/models.py", line 61, in get_query_str
    raise NotImplementedError()
```

### Steps to reproduce
Load any chart with interval type annotation.

to: @mistercrunch @fabianmenges @john-bodley

**Comment by graceguo-supercat** [comment]
#4260 fixed this.
closed.
