### ISSUE TITLE
bigquery and sqllab  - table dropdown generates an error

### ISSUE THREAD

**Issue by darylerwin** [apache/incubator-superset#4399]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
very latest including the updated 
lib/python2.7/site-packages/superset/db_engine_specs.py

### Expected results
List of tables ..

### Actual results
After selecting the "schema" it tries to query the tables and the gui comes back and shows
Error while fetching table list.

The log shows:
```
2018-02-10 19:09:21,610:INFO:root:Database.get_sqla_engine(). Masked URL: bigquery://production-bigdata/
2018-02-10 19:09:21,620:DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
2018-02-10 19:09:21,622:DEBUG:google.auth.transport.requests:Making request: POST https://accounts.google.com/o/oauth2/token
2018-02-10 19:09:21,627:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com
2018-02-10 19:09:21,696:DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2018-02-10 19:09:21,700:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com
2018-02-10 19:09:21,804:DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /bigquery/v2/projects/production-bigdata/datasets HTTP/1.1" 200 None
2018-02-10 19:09:21,805:ERROR:root:dataset must be a Dataset or a DatasetReference
Traceback (most recent call last):
  File "/home/derwin/venv/local/lib/python2.7/site-packages/superset/views/base.py", line 62, in wraps
    return f(self, *args, **kwargs)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/superset/views/core.py", line 1335, in tables
    database, database.all_table_names(schema), schema)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/superset/models/core.py", line 724, in all_table_names
    self.db_engine_spec.get_table_names(schema, self.inspector))
  File "/home/derwin/venv/local/lib/python2.7/site-packages/superset/db_engine_specs.py", line 225, in get_table_names
    
  File "/home/derwin/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 201, in get_table_names
    self.bind, schema, info_cache=self.info_cache)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/pybigquery/sqlalchemy_bigquery.py", line 192, in get_table_names
    tables = connection.connection._client.list_dataset_tables(d)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 459, in list_dataset_tables
    return self.list_tables(*args, **kwargs)
  File "/home/derwin/venv/local/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 438, in list_tables
    raise TypeError('dataset must be a Dataset or a DatasetReference')
TypeError: dataset must be a Dataset or a DatasetReference
```

### Steps to reproduce
Select SQLLab
Select BigQuery for Database 
Select one of the Schemas it finds (datasets).
Then the error..

**Comment by xrmx** [comment]
That looks like an issue in pybigquery

**Comment by darylerwin** [comment]
Yes .. now that I look into the error it appears to be the interface. I will close this here and post a note if I am able to resolve it.

**Comment by darylerwin** [comment]
Proposed fix noted over on pybigquery github.

```
#        tables = connection.connection._client.list_tables(d)
          tables = connection.connection._client.list_tables(connection.connection._client.dataset(d.dataset_id))
```

**Comment by xrmx** [comment]
@darylerwin if this turns out fine mind to create a PR for adding a big query entry here please? https://github.com/apache/incubator-superset/blob/master/docs/installation.rst#database-dependencies
