### ISSUE TITLE
yarn run prod fails on master

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#4426]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

342180b263079db2fac5434fc929805d4b441e19

### Expected results

no errors

### Actual results

```
ERROR in ./node_modules/css-loader!./visualizations/chord.css
Module build failed: Error: ENOENT: no such file or directory, open '/home/rm/work/stats/superset/superset/assets/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports (/home/rm/work/stats/superset/superset/assets/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/rm/work/stats/superset/superset/assets/node_modules/svgo/lib/svgo.js:21:19)
    at /home/rm/work//stats/superset/superset/assets/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/home/rm/work//stats/superset/superset/assets/node_modules/postcss/lib/postcss.js:150:35)
    at /home/rm/work/stats/superset/superset/assets/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (<anonymous>)
    at /home/rm/work/stats/superset/superset/assets/node_modules/cssnano/dist/index.js:282:29
    at creator (/home/rm/work/stats/superset/superset/assets/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/home/rm/work/stats/superset/superset/assets/node_modules/css-loader/lib/processCss.js:199:16)
    at Object.module.exports (/home/rm/work/stats/superset/superset/assets/node_modules/css-loader/lib/loader.js:40:2)
 @ ./visualizations/chord.css 4:14-74
 @ ./visualizations/chord.jsx
 @ ./visualizations/main.js
 @ ./javascripts/modules/AnnotationTypes.js
 @ ./javascripts/chart/chartAction.js
 @ ./javascripts/dashboard/components/DashboardContainer.jsx
 @ ./javascripts/dashboard/index.jsx
 @ multi babel-polyfill ./javascripts/dashboard/index.jsx
```

### Steps to reproduce

yarn run prod

postcss-svgo is 2.1.6
svgo is 0.7.2

**Comment by xrmx** [comment]
It built fine recently, closing.

**Comment by xrmx** [comment]
Spoke too soon, 97afcd5809269e885a0dde349081802a427c5674 yarn run build is broken right now.

**Comment by xrmx** [comment]
It looks like it was a a yarn issue https://github.com/yarnpkg/yarn/issues/2276
