### ISSUE TITLE
Cannot use late bindings with views in Redshift 

### ISSUE THREAD

**Issue by theikkila** [apache/incubator-superset#4435]
Cannot use late bindings with views in Redshift, it's probably because superset doesn't use deferred reflection when autoload=True 
See: https://stackoverflow.com/questions/4215920/how-to-bind-engine-when-i-want-when-using-declarative-base-in-sqlalchemy

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.22.1

### Expected results
Even views with late bindings should work

### Actual results
500 error + stack trace when refreshing the metadata
```
        Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 589, in fetch_metadata
    table = self.get_sqla_table_object()
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 584, in get_sqla_table_object
    return self.database.get_table(self.table_name, schema=self.schema)
  File "/usr/local/lib/python3.5/dist-packages/superset/models/core.py", line 780, in get_table
    autoload_with=self.get_sqla_engine())
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 456, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 451, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 533, in _init
    include_columns, _extend_on=_extend_on)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 546, in _autoload
    _extend_on=_extend_on
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2056, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1545, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 389, in reflecttable
    table, include_columns, exclude_columns, **opts)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/reflection.py", line 626, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: debug

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_appbuilder/views.py", line 574, in action_post
    return action.func(items)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/views.py", line 283, in refresh
    t.fetch_metadata()
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 593, in fetch_metadata
    "couldn't fetch column information").format(self.table_name))
Exception: Table [debug] doesn't seem to exist in the specified database, couldn't fetch column information
```
### Steps to reproduce
1. Create view with late binding into redshift.
2. Create new table with reference to that view
3. Refresh metadata (see #4206 how to work around the bug that prevents it)

**Comment by mistercrunch** [comment]
SQLAlchemy dialect bug? What is late-binding?

**Comment by e01n0** [comment]
@theikkila did you get a resolution for this? Its a bit annoying for us as we'd like to use superset over views on redshift spectrum, which must be late binding.

@mistercrunch Late-binding views allows you to drop and make changes to referenced tables without affecting the views.

**Comment by e01n0** [comment]
@theikkila not sure if this is still an issue for you, but the PR referenced above fixes it.
