### ISSUE TITLE
connection https druid cluster 

### ISSUE THREAD

**Issue by jaehokim00** [apache/incubator-superset#4465]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
-  [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Stack Trace ####
```
2018-02-22 20:54:10,051:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 
DNS.NAME.com
Error while processing cluster 'druid'
('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02P',))
2018-02-22 20:54:10,062:ERROR:root:('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02P',))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/cli.py", line 171, in refresh_druid
    merge_flag=merge)
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 123, in refresh_datasources
    self.druid_version = self.get_druid_version()
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 113, in get_druid_version
    return json.loads(requests.get(endpoint,verify=False).text)['version']
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02P',))
Refreshed metadata from cluster [omni druid dev]
```

so I looked at the models.py and it seems that it only support http connection  

def get_pydruid_client(self):
        cli = PyDruid(
            'http://{0}:{1}/'.format(self.broker_host, self.broker_port),
            self.broker_endpoint)
        return cli

how can I make druid connection to https can work ... ?  

### Superset version

# superset version
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.22.1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

### Expected results

Connecting to Druid (allow https connection to druid)
### Actual results

The Stacktrace is there

### Steps to reproduce

I tried to use https instead of http , but it still has SSL HANDSHAKE error...     appreciated if you can help me out on this issue.. The druid we setup only support https ...

**Comment by jaehokim00** [comment]
Python 2.7.5
