### ISSUE TITLE
Empty dashboard 

### ISSUE THREAD

**Issue by SpyderRivera** [apache/incubator-superset#4619]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
23.3
I built from d57d2557b79b791a6cad43f638e2bd6eb3632264

### Expected results
I expect the slice to appear on the dashboard.

### Actual results
<img width="1066" alt="screen shot 2018-03-15 at 7 56 09 am" src="https://user-images.githubusercontent.com/3988262/37468107-aae50522-2827-11e8-87bf-903386c602ef.png">

### Steps to reproduce
Build a chart (slice). When saving choose add to new dashboard. Navigate to that dashboard. Its empty. Note my datasources are all druid

<img width="1216" alt="screen shot 2018-03-15 at 8 07 39 am" src="https://user-images.githubusercontent.com/3988262/37468229-0146a916-2828-11e8-97c5-0267263039de.png">
<img width="1218" alt="screen shot 2018-03-15 at 8 08 46 am" src="https://user-images.githubusercontent.com/3988262/37468270-2312ddd0-2828-11e8-8e1d-2bccb764f5be.png">

### Logs
Running in debug mode and reproducing for logs
```
2018-03-15 08:10:14,437:DEBUG:root:[stats_logger] (incr) dashboard
2018-03-15 08:10:14,548:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:10:14] "GET /superset/dashboard/1/ HTTP/1.1" 200 -
2018-03-15 08:10:44,459:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:10:44] "GET /druiddatasourcemodelview/list/ HTTP/1.1" 200 -
2018-03-15 08:10:54,161:DEBUG:root:[stats_logger] (incr) explore
2018-03-15 08:10:54,268:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:10:54] "GET /superset/explore/druid/9/ HTTP/1.1" 200 -
2018-03-15 08:10:54,967:DEBUG:root:[stats_logger] (incr) explore_json
2018-03-15 08:10:55,038:INFO:root:Cache key: ceb490c0beec93117380bfa5356d894c
2018-03-15 08:10:55,046:INFO:root:Running timeseries query for no groupby values
2018-03-15 08:10:55,345:DEBUG:root:[stats_logger] (incr) loaded_from_source
2018-03-15 08:10:55,360:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:10:55] "POST /superset/explore_json/druid/9/ HTTP/1.1" 200 -
2018-03-15 08:10:55,419:DEBUG:root:[stats_logger] (incr) log
2018-03-15 08:10:55,425:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:10:55] "POST /superset/log/?impression_id=Skzwe1ZuYG&slice_id=0 HTTP/1.1" 200 -
2018-03-15 08:11:23,237:DEBUG:root:[stats_logger] (incr) explore_json
2018-03-15 08:11:23,309:INFO:root:Cache key: 1ca0a736a5faa2b1d8dc5b32cac8fb64
2018-03-15 08:11:23,314:INFO:root:Running two-phase topn query for dimension [adomain_hash]
2018-03-15 08:11:24,941:INFO:root:Phase 1 Complete
2018-03-15 08:11:25,044:DEBUG:root:[stats_logger] (incr) loaded_from_source
2018-03-15 08:11:25,634:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:11:25] "POST /superset/explore_json/druid/9/ HTTP/1.1" 200 -
2018-03-15 08:11:43,346:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:11:43] "GET /dashboardmodelviewasync/api/read?_flt_0_owners=2 HTTP/1.1" 200 -
2018-03-15 08:12:10,711:DEBUG:root:[stats_logger] (incr) explore
2018-03-15 08:12:10,848:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:12:10] "POST /superset/explore/druid/9/?action=saveas&slice_name=test+slice&add_to_dash=new&new_dashboard_name=test+repro&goto_dash=true HTTP/1.1" 200 -
2018-03-15 08:12:10,921:DEBUG:root:[stats_logger] (incr) dashboard
2018-03-15 08:12:11,032:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:12:11] "GET /superset/dashboard/2/ HTTP/1.1" 200 -
```

the only warning/errors in log
```
2018-03-15 07:49:18,541:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 07:49:18] "GET /static/appbuilder/css/bootstrap.min.css.map HTTP/1.1" 404 -
/Users/srivera/testing/test-github-superset/venv/lib/python2.7/site-packages/Flask_AppBuilder-1.9.6-py2.7.egg/flask_appbuilder/fields.py:152: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  warnings.warn('allow_blank=True does not do anything for QuerySelectMultipleField.')
```

```
2018-03-15 08:01:46,261:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:01:46] "GET /dashboardmodelview/list/ HTTP/1.1" 200 -
2018-03-15 08:01:46,276:ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/Users/srivera/testing/test-github-superset/venv/lib/python2.7/site-packages/Werkzeug-0.14.1-py2.7.egg/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/srivera/testing/test-github-superset/venv/lib/python2.7/site-packages/Werkzeug-0.14.1-py2.7.egg/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/Users/srivera/testing/test-github-superset/venv/lib/python2.7/site-packages/Werkzeug-0.14.1-py2.7.egg/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
2018-03-15 08:01:46,355:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:01:46] "GET /dashboardmodelview/list/ HTTP/1.1" 200 -
2018-03-15 08:02:04,269:DEBUG:root:[stats_logger] (incr) dashboard
2018-03-15 08:02:04,372:INFO:werkzeug:127.0.0.1 - - [15/Mar/2018 08:02:04] "GET /superset/dashboard/1/ HTTP/1.1" 200 -
```

**Comment by mistercrunch** [comment]
Seems like `0.23.3` isn't a great release. For now I'd recommend folks to hold until `0.23.4` or `0.24.0`.

**Comment by mistercrunch** [comment]
Think this could be access rights related? @timifasubaa ?

**Comment by mistercrunch** [comment]
@SpyderRivera do you see the same problem on `master`?

**Comment by timifasubaa** [comment]
@SpyderRivera What access permissions does the user have?

**Comment by SpyderRivera** [comment]
I can try on master. My user is admin/alpha

**Comment by SpyderRivera** [comment]
This is fixed when building from master
