### ISSUE TITLE
Unable to add database: General Error <class 'sqlalchemy.exc.OperationalError'>

### ISSUE THREAD

**Issue by namenyi** [apache/incubator-superset#464]
Hey @mistercrunch! 

I have an issue that is somewhat similar to this: https://github.com/airbnb/caravel/issues/399

I am trying to add a PostgreSQL database, the Sqlalchemy Uri is in the right format I think:

`postgresql+psycopg2://USERNAME:PASSWORD@DBIDENTIFIER.eu-central-1.rds.amazonaws.com/DATABASENAME`

When I click on the "Test Connection" button, it says "Seems OK!". However, when I click "Save", it gives the following error:

`General Error <class 'sqlalchemy.exc.OperationalError'>`

Here is a screenshot: https://www.dropbox.com/s/z1ct7rog60zx52o/Screenshot%20from%202016-05-13%2016%3A04%3A43.png?raw=1

Any idea?

**Comment by ttdonovan** [comment]
I'm experiencing the same error and not certain exactly what this means. I think it might have something to do with the `cryptography` pip but not sure.

```
2016-06-16 12:39:53,824:ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.ImportError) dlopen(/Users/Pair/.pyenv/versions/2.7.11/lib/python2.7/site-packages/_cffi_backend.so, 2): Symbol not found: _PyUnicodeUCS2_AsASCIIString
  Referenced from: /Users/Pair/.pyenv/versions/2.7.11/lib/python2.7/site-packages/_cffi_backend.so
  Expected in: flat namespace
 in /Users/Pair/.pyenv/versions/2.7.11/lib/python2.7/site-packages/_cffi_backend.so [SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, extra, changed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)']...
```

**Comment by eligro91** [comment]
happens for me too on mac OS X , full error : 
`2016-07-26 15:14:42,340:ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.ImportError) dlopen(/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _EC_curve_nid2nist
  Referenced from: /Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in /Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so [SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, extra, changed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'cache_timeout': None, 'database_name': u'', 'password': u'eliyahu12', 'sqlalchemy_uri': 'vertica+pyodbc://eliyahu:XXXXXXXXXX@localhost/appcarddb', 'extra': u'{\r\n    "metadata_params": {},\r\n    "engine_params": {}\r\n}\r\n'}]]
Traceback (most recent call last):
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 283, in add
    self.session.commit()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 584, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 978, in process
    return impl_processor(process_param(value, dialect))
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted.py", line 237, in process_bind_param
    self._update_key()
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted.py", line 232, in _update_key
    self.engine._update_key(key)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted.py", line 34, in _update_key
    digest = hashes.Hash(hashes.SHA256(), backend=default_backend())
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 46, in <module>
    from cryptography.hazmat.bindings._openssl import ffi as _ffi
StatementError: (exceptions.ImportError) dlopen(/Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _EC_curve_nid2nist
  Referenced from: /Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in /Users/eliyahugromman/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so [SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, extra, changed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'cache_timeout': None, 'database_name': u'', 'password': u'eliyahu12', 'sqlalchemy_uri': 'vertica+pyodbc://eliyahu:XXXXXXXXXX@localhost/appcarddb', 'extra': u'{\r\n    "metadata_params": {},\r\n    "engine_params": {}\r\n}\r\n'}]]`

**Comment by jinleileiking** [comment]
```
016-11-28 17:33:11,351:ERROR:flask_appbuilder.models.sqla.interface:Add record error: (exceptions.ImportError) /usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m [
SQL: u'INSERT INTO dbs (created_on, changed_on, database_name, sqlalchemy_uri, password, cache_timeout, select_as_create_table_as, expose_in_sqllab, allow_run_sync, allow_run_async, allow_ctas, allow_dml, force_ctas_schema, extra, chang
ed_by_fk, created_by_fk) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'expose_in_sqllab': False, 'allow_run_sync': True, 'allow_ctas': False, 'extra': u'{\r\n    "metadata_params": {},\r\n    "engine_params":
 {}\r\n}\r\n', 'allow_dml': False, 'database_name': u'avteam', 'sqlalchemy_uri': 'mysql://root:XXXXXXXXXX@10.4.23.115/avteam', 'cache_timeout': None, 'allow_run_async': False, 'force_ctas_schema': u'', 'password': u'xxxxxxx'}]]
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 511 days. Feel free to comment and request for this issue to be reopened.
