### ISSUE TITLE
Superset evaluation - SQLLite failure to refresh metadata

### ISSUE THREAD

**Issue by varaga** [apache/incubator-superset#4794]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ Y] I have reproduced the issue with at least the latest released version of superset
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
latest - through pip install

### Steps to reproduce

I'm running superset for evaluation. For the initial launch it worked when Druid was set up on my laptop.
I set up Druid to run on containers backed by postgres for metadata and eventually launched superset.
I configured the druid cluster and it seemed to connect to it however on refreshing the druid meta-data it failed with the following traces
```
2018-04-10 11:27:28,847:ERROR:root:(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140404080691008 and this is thread id 140403468719872 [SQL: 'SELECT clusters.created_on AS clusters_created_on, clusters.changed_on AS clusters_changed_on, clusters.id AS clusters_id, clusters.verbose_name AS clusters_verbose_name, clusters.cluster_name AS clusters_cluster_name, clusters.coordinator_host AS clusters_coordinator_host, clusters.coordinator_port AS clusters_coordinator_port, clusters.coordinator_endpoint AS clusters_coordinator_endpoint, clusters.broker_host AS clusters_broker_host, clusters.broker_port AS clusters_broker_port, clusters.broker_endpoint AS clusters_broker_endpoint, clusters.metadata_last_refreshed AS clusters_metadata_last_refreshed, clusters.cache_timeout AS clusters_cache_timeout, clusters.created_by_fk AS clusters_created_by_fk, clusters.changed_by_fk AS clusters_changed_by_fk \nFROM clusters \nWHERE clusters.cluster_name = ?'] [parameters: [{'%(140403472682120 param)s': 'druid-cluster-local'}]] (Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 637, in _init_compiled
    self.cursor = self.create_cursor()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 952, in create_cursor
    return self._dbapi_connection.cursor()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 970, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140404080691008 and this is thread id 140403468719872
```

**Comment by mistercrunch** [comment]
I'd recommend to use MySQL or Postgres instead. You may want to try a single worker/thread gunicorn instance if using SQLLite.
