### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:jdbc.hive

### ISSUE THREAD

**Issue by matiji66** [apache/incubator-superset#4846]
Make sure these boxes are checked before submitting your issue - thank you!

- I have checked the superset logs for python stacktraces and included it here as text if any
- I have reproduced the issue with at least the latest released version of superset
- I have checked the issue tracker for the same issue and I haven't found one similar
    
### Superset version
Superset 0.24.0 and similar issue :https://github.com/apache/incubator-superset/issues/2632

### Expected results
connect success

### Actual results

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:jdbc.hive
2018-04-19 17:11:20,523:INFO:werkzeug:172.16.0.20 - - [19/Apr/2018 17:11:20] "POST /superset/testconn HTTP/1.1" 500 -
2018-04-19 17:11:59,895:ERROR:root:Can't load plugin: sqlalchemy.dialects:jdbc.hive
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/views/core.py", line 1691, in testconn
    engine = create_engine(uri, connect_args=connect_args)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    entrypoint = u._get_entrypoint()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 150, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 221, in load
    (self.group, name))
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:jdbc.hive
2018-04-19 17:11:59,899:INFO:werkzeug:172.16.0.20 - - [19/Apr/2018 17:11:59] "POST /superset/testconn HTTP/1.1" 500 -
 
### Steps to reproduce
I hive use pip install pyhive
Requirement already satisfied: pyhive in /usr/lib/python2.7/site-packages (0.5.1)
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from pyhive) (0.16.0)

And my SQLAlchemy URI : `jdbc+hive://qing-hadoop-master-srv1:10000/hive `

What should I do to solve this problem
 Beside, impala databases can not be connected either with SQLAlchemy URI : `impala://qing-hadoop-master-srv2:26000/test?auth_mechanism=PLAIN&password=impala&user=impala`

**Comment by matiji66** [comment]
What is a right configuration? Do you have any examples.

**Comment by nankingrider** [comment]
truely some mis-understanding here
in manual there is an example of using "  jdbc+hive://  " as prefix of uri

but actucully just " hive:// " is needed for hive datasource, otherwise error will be prompted like posted.
need to correct the manual i think ?

**Comment by mistercrunch** [comment]
@nankingrider https://github.com/apache/incubator-superset/pull/4942

**Comment by lindajoseph01** [comment]
I tried hive://localhost:10000/test. It showed a message "Seems OK". But none of my tables in the db is not listed in the bottom of the page.
