### ISSUE TITLE
Unable to open superset

### ISSUE THREAD

**Issue by qxlsz** [apache/incubator-superset#4888]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset==0.23.0.dev0

### Actual results
(superset) LUSC02WD09JHTDH:incubator-superset rjosyula$ superset
Traceback (most recent call last):
  File "/Users/rjosyula/superset/bin/superset", line 4, in <module>
    __import__('pkg_resources').run_script('superset==0.23.0.dev0', u'superset')
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/rjosyula/superset/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'unidecode>=0.04.21' distribution was not found and is required by superset

**Comment by xrmx** [comment]
Since it looks like you are already using superset from git, use a newer git master that has all this sorted out. Just remember to install the requirements.txt.

**Comment by mistercrunch** [comment]
Following the instructions in `CONTRIBUTING.md` should fix your issues
