### ISSUE TITLE
Running Superset agains Druid

### ISSUE THREAD

**Issue by lepenr** [apache/incubator-superset#4932]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x ] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.24.0"}

### Expected results
I have data in Druid but when I am trying to query them from Superset, there is error in UI:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 329, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/lib/python2.7/site-packages/superset/viz.py", line 142, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 1238, in query
    client=client, query_obj=query_obj, phase=2)
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 959, in get_query_str
    return self.run_query(client=client, phase=phase, **query_obj)
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 1126, in run_query
    client.timeseries(**qry)
  File "/usr/lib/python2.7/site-packages/pydruid/client.py", line 167, in timeseries
    return self._post(query)
  File "/usr/lib/python2.7/site-packages/pydruid/client.py", line 484, in _post
    res = urllib.request.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

### Steps to reproduce
I successfully followed this:
http://druid.io/docs/latest/tutorials/quickstart.html

But superset querying is not wokring

**Comment by SpyderRivera** [comment]
Double check your broker host and coordinator host.

**Comment by lepenr** [comment]
@SpyderRivera do you mean broker and coordinator setting of Superset?
is that config.py file? Or where I can find it, I think that's a problem though..

**Comment by lepenr** [comment]
Update:
If i run superset refresh_druid
from console, i got a same error as above.
`2018-05-07 10:11:56,304:WARNING:root:Failed 2nd attempt to get latest segment
2018-05-07 10:11:56,305:ERROR:root:<urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/superset/connectors/druid/models.py", line 648, in latest_metadata
    analysisTypes=[])
  File "/usr/lib/python2.7/site-packages/pydruid/client.py", line 286, in segment_metadata
    return self._post(query)
  File "/usr/lib/python2.7/site-packages/pydruid/client.py", line 484, in _post
    res = urllib.request.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
Refreshed metadata from cluster [_default_tier]
`

**Comment by lepenr** [comment]
@SpyderRivera  Thank you for your answare, probem was that broker host was not defined in cluster configuration in super set UI.
