### ISSUE TITLE
Not able to import dashboard in the latest version of superset

### ISSUE THREAD

**Issue by revathijay** [apache/incubator-superset#4945]
Make sure these boxes are checked before submitting your issue - thank you!

- [ check] I have checked the superset logs for python stacktraces and included it here as text if any
- [check ] I have reproduced the issue with at least the latest released version of superset
- [ check] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.24.0
### Expected results
able to import a new dashboard

### Actual results
        Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/superset/models/core.py", line 899, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/superset/utils.py", line 688, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/superset/views/core.py", line 1195, in import_dashboards
    data = json.loads(f.stream.read(), object_hook=utils.decode_dashboards)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

### Steps to reproduce

1. Export a dashboard in json format
2. Try to import the dashboard
3. We get the above error as shown

**Comment by mistercrunch** [comment]
You'll have to export from the newer version as well as we moved away from using pickles in favor or `json` for security reasons.

**Comment by HimanshuArora1234** [comment]
Hello @mistercrunch can you please let me know which version of superset should we used for this feature to work correctly ? Thanks a lot :)

Cheers,
Himanshu

**Comment by mistercrunch** [comment]
Latest?
