### ISSUE TITLE
flask-appbuilder 1.10.0 has requirement Flask<0.12.99,>=0.12.1, but you'll have flask 1.0.2 which is incompatible

### ISSUE THREAD

**Issue by Neuliaus** [apache/incubator-superset#4953]
I'm running a normal installation on 
AWS
t2.medium 
Ubuntu 16.04 
Python 2.7 
pip 10.0.1
Inside venv 

### Superset version  
0.20.4 
Following installation instructiorn

### Expected results 
Install and use Superset 

### Actual results
flask-appbuilder 1.10.0 has requirement Flask<0.12.99,>=0.12.1, but you'll have flask 1.0.2 which is incompatible.

### Steps to reproduce
 sudo virtualenv venv
   21  python -V
   22  pip -V
   23  virtualenv venv
   24  . ./venv/bin/activate
   25  pip install --upgrade setuptools pip
   26  pip install superset
   27  pip show flask-appbuilder 

Name: Flask-AppBuilder
Version: 1.10.0
Summary: Simple and rapid application development framework, built on top of Flask. includes detailed security, auto CRUD generation for your models, google charts and much more.
Home-page: https://github.com/dpgaspar/flask-appbuilder/
Author: Daniel Vaz Gaspar
Author-email: danielvazgaspar@gmail.com
License: BSD
Location: /home/ubuntu/venv/lib/python2.7/site-packages
Requires: Flask-Babel, Flask-OpenID, click, Flask-Login, Flask, colorama, Flask-SQLAlchemy, python-dateutil, Flask-WTF

**Comment by Neuliaus** [comment]
I did uninstall Flask inside the venv , then I installed pip install -U 'Flask~=0.12.2'
pip install superset and seems to work 
 then I hit superset db upgrade and get 
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/home/ubuntu/normal/venv3/bin/superset", line 15, in <module>
    manager.run()
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/superset/migrations/env.py", line 103, in <module>
    run_migrations_online()
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/superset/migrations/env.py", line 96, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/base.py", line 336, in _upgrade_revs
    revs = list(revs)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/revision.py", line 437, in _resolve_revision_number
    self._revision_map
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/util/langhelpers.py", line 239, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/revision.py", line 122, in _revision_map
    for revision in self._generator():
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/base.py", line 99, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/script/base.py", line 812, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/superset/migrations/versions/289ce07647b_add_encrypted_password_field.py", line 16, in <module>
    from sqlalchemy_utils.types.encrypted import EncryptedType
**ImportError: cannot import name EncryptedType**
thoughts ?

**Comment by findepi** [comment]
@Neuliaus i worked around this by pinning `SQLAlchemy-Utils~=0.0,<0.33` as in https://github.com/inspirehep/inspire-next/commit/828856ecfe995d6c93d963c8e57d55c83aa8d603 (https://github.com/inveniosoftware/invenio-oauth2server/issues/170)

**Comment by mistercrunch** [comment]
This is related to the notes in https://github.com/apache/incubator-superset/blob/master/UPDATING.md (the 3rd item)

**Comment by findepi** [comment]
@mistercrunch thanks for referencing the update notes. I must admit i didn't read them.
I don't build from sources. Today I just `pip install superset==0.25.0` in a completely fresh env (+ some optional dependencies needed in my flow, like gevent, pyhive). Then I run `fabmanager` or `gunicorn superset:app` -- I don't have any specific version requirements for flask or sqlalchemy or anything else. How can i incorporate `pip install -r requirements.txt` in this flow?

**Comment by gitvikram** [comment]
Traceback (most recent call last):
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask_appbuilder\security\decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask_appbuilder\views.py", line 475, in list
    widgets = self._list()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask_appbuilder\baseviews.py", line 883, in _list
    page_size=page_size)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask_appbuilder\baseviews.py", line 793, in _get_list_widget
    count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\flask_appbuilder\models\sqla\interface.py", line 115, in query
    count = query_count.scalar()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\orm\query.py", line 2913, in scalar
    ret = self.one()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\orm\query.py", line 2884, in one
    ret = self.one_or_none()
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\orm\query.py", line 2854, in one_or_none
    ret = list(self)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\orm\query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\orm\query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\vsingh2\AppData\Local\Programs\Python\Python36\Scripts\demo\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dbs [SQL: 'SELECT count(?) AS count_1 \nFROM dbs'] [parameters: ('*',)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by TianyangLi** [comment]
@gitvikram to solve the 'Encrypted Type' issue you need to reinstall sqlalchemy-utils to <0.33.0

as for the sqlite3.operationalerror..i'm still figuring that part out, i suspect it has something to do with the flask version.

**Comment by mistercrunch** [comment]
@gitvikram windows isn't really supported at the moment

**Comment by findepi** [comment]
@mistercrunch you closed this having fixed the flask version issue, but @Neuliaus actually reported two problems, the second being 
```
  File "/home/ubuntu/normal/venv3/local/lib/python2.7/site-packages/superset/migrations/versions/289ce07647b_add_encrypted_password_field.py", line 16, in <module>
    from sqlalchemy_utils.types.encrypted import EncryptedType
**ImportError: cannot import name EncryptedType**
```

i was able to work around this pinning `'SQLAlchemy-Utils~=0.0,<0.33'`. If this is the way to go, this should be pinned too, just as flask version.

**Comment by AndreLesa** [comment]
The easiest workaround for now is to just install the requirements as they currently are in the master branch.

Just before running pip install superset, I did:
```
wget https://raw.githubusercontent.com/apache/incubator-superset/master/requirements.txt

pip install -r requirements.txt
```
This get's the latest merged requirements.txt and then you install the dependencies that way.

**Comment by findepi** [comment]
@AndreLesa , as I described my `pip install`-based use-case before (https://github.com/apache/incubator-superset/issues/4953#issuecomment-387448597), what you propose doesn't seem better than just manually pinning the problematic dependencies. -- How can I know that `master`'s `requirements.txt` file is compatible with the version I download with `pip`? 
(Sure, I can look for `requirements.txt` under "correct" tag, but then I need to assume/know/require git tags and pip versions are the same...)

**Comment by mistercrunch** [comment]
I just released `0.25.1` which pins Flask<1.0 . Is the issue with `SQLAlchemy-Utils` related to flask being 1+, or do we need to pin that as well? BTW I couldn't reproduce this here on a fresh virtualenv, what python version is that?

**Comment by findepi** [comment]
@mistercrunch i just tried this once again:

Env is Python 2.7 in ubuntu:16.04. (2.7 is somewhat "recommended" on https://superset.incubator.apache.org/installation.html: "Airbnb currently uses 2.7.* in production")
(You can see details of my env and all the changes i did for the below in my WIP branch https://github.com/starburstdata/superset-docker/commits/findepi/unpin-sqlalchemy)

1. > Is the issue with SQLAlchemy-Utils related to flask being 1+, or do we need to pin that as well?
    
   I unpinned `SQLAlchemy-Utils` without upgrading superset and with flask remaining pinned. Result: https://travis-ci.org/starburstdata/superset-docker/builds/379081519
   ```
     File "/usr/local/lib/python2.7/dist-packages/superset/migrations/versions/289ce07647b_add_encrypted_password_field.py", line 16, in <module>
       from sqlalchemy_utils.types.encrypted import EncryptedType
   ImportError: cannot import name EncryptedType
   ```
2. > I just released 0.25.1 which pins Flask<1.0
   
   I unpinned flask and bump superset version to 0.25.2 (released yesterday). Result: https://travis-ci.org/starburstdata/superset-docker/builds/379094497
    ```
    pkg_resources.DistributionNotFound: The 'Flask<0.12.99,>=0.12.1' distribution was not found and is required by Flask-AppBuilder
    ```

I must be doing something wrong.

**Comment by findepi** [comment]
No, i use docker, so I get fresh state each time

>

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/5007

**Comment by NicolasNeubauer** [comment]
Update your pip to the latest version, this fixed this for me
