### ISSUE TITLE
(exceptions.TypeError) __init__() got an unexpected keyword argument 'connect_timeout'

### ISSUE THREAD

**Issue by birdflyinhigh** [apache/incubator-superset#4974]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce

use presto 

gunicorn \
              -w 10 \
              -k gevent \
              --timeout 120 \
              -b  0.0.0.0:6666 \
              --limit-request-line 0 \
              --limit-request-field_size 0 \
              superset:app

**Comment by danny-zhu** [comment]
I got the same issue when i wanna to build a new hive database connection. The full error stacktrace is :
2020-02-17 09:50:09,700:ERROR:root:__init__() got an unexpected keyword argument 'connect_timeout'
Traceback (most recent call last):
  File "/home/superset/superset/views/core.py", line 1716, in testconn
    with closing(engine.connect()) as conn:
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 2196, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 2296, in raw_connection
    self.pool.unique_connection, _connection
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/dist-packages/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'connect_timeout'

**Comment by danny-zhu** [comment]
Got the reason: core.py configuration was set a default "connect_timeout", remove the default setting will be ok.
