### ISSUE TITLE
Javascript error when loading slice/chart

### ISSUE THREAD

**Issue by allanw** [apache/incubator-superset#4976]
Since upgrading to Superset 0.25.0, I'm getting the following Javascript error when trying to load certain slices. I'm installing Superset via pip.

```
Uncaught ReferenceError: notify is not defined
    at /static/assets/dist/explore.701bc6178837d27ffb52.entry.js:156:593909
    at Array.map (native)
    at t.e (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:156:593639)
    at new t (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:156:591850)
    at f._constructComponentWithoutOwner (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:65:220634)
    at f._constructComponent (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:65:220418)
    at f.mountComponent (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:65:216653)
    at Object.mountComponent (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:40:135696)
    at fe.mountChildren (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:65:211513)
    at fe._createInitialChildren (/static/assets/dist/explore.701bc6178837d27ffb52.entry.js:65:192911)
```

### Superset version
0.25.0

### Expected results
Display the chart

### Actual results
Chart does not load - I just see the loading spinner

### Steps to reproduce
1. Click on Charts
2. Go to a chart

**Comment by allanw** [comment]
Worth noting that after downgrading from 0.25.0 to 0.24.0 the dashboards and charts now load as normal again.

**Comment by Twister42** [comment]
Hello, any news on this ?

**Comment by Twister42** [comment]
Yes.

**Comment by mistercrunch** [comment]
It's tricky to reproduce because it's an error that happens during error handling of another error. The stacktrace on minified code isn't very helpful. Any way you can reproduce on not-minified JS?

**Comment by Twister42** [comment]
Same on master. It crashes in MetricsControl.jsx:204

**Comment by Twister42** [comment]
Ok, found the culprit.
In table_columns there is two lines without column_name. Their creation dates match with the day I first installed Superset (don't remember the version but it was on 20th february).

**Comment by mistercrunch** [comment]
Can you try this patch? https://github.com/apache/incubator-superset/pull/5120

**Comment by mistercrunch** [comment]
Added a commit to the patch trying to register the `AlertsWrapper` earlier. Mind trying that?
