### ISSUE TITLE
superset db upgrade error: ImportError: cannot import name EncryptedType

### ISSUE THREAD

**Issue by gavinju** [apache/incubator-superset#5010]
Hello !
I ran into an error while running superset db upgrade :

  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/dist-packages/superset-0.25.0rc3-py2.7.egg/superset/migrations/versions/289ce07647b_add_encrypted_password_field.py", line 16, in <module>
    from sqlalchemy_utils.types.encrypted import EncryptedType
ImportError: cannot import name EncryptedType

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.2

### Expected results
db upgrade sucessful!

### Actual results
(venv) apps@apps-local:~/Workspace/superset$ superset db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 4, in <module>
    __import__('pkg_resources').run_script('superset==0.25.0rc3', u'superset')
  File "/home/apps/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/apps/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/superset-0.25.0rc3-py2.7.egg/EGG-INFO/scripts/superset", line 15, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-2.0.6-py2.7.egg/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-2.0.6-py2.7.egg/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-2.0.6-py2.7.egg/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Migrate-2.1.1-py2.7.egg/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/dist-packages/superset-0.25.0rc3-py2.7.egg/superset/migrations/env.py", line 102, in <module>
    run_migrations_online()
  File "/usr/local/lib/python2.7/dist-packages/superset-0.25.0rc3-py2.7.egg/superset/migrations/env.py", line 95, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/base.py", line 336, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/revision.py", line 437, in _resolve_revision_number
    self._revision_map
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/langhelpers.py", line 239, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/revision.py", line 122, in _revision_map
    for revision in self._generator():
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/base.py", line 99, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/script/base.py", line 812, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic-0.9.9-py2.7.egg/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/dist-packages/superset-0.25.0rc3-py2.7.egg/superset/migrations/versions/289ce07647b_add_encrypted_password_field.py", line 16, in <module>
    from sqlalchemy_utils.types.encrypted import EncryptedType
ImportError: cannot import name EncryptedType

### Steps to reproduce
execute:  superset db upgrade

**Comment by xrmx** [comment]
Dup of #5005, please close

**Comment by mistercrunch** [comment]
Closing since dup, there's a fix out for review.

**Comment by gavinju** [comment]
OK，Thank you for your help,

**Comment by mistercrunch** [comment]
Should be fixed in `0.25.3`
