### ISSUE TITLE
No field class for DateTime

### ISSUE THREAD

**Issue by Evgeniyer1** [apache/incubator-superset#5014]
When using a database ClickHouse I can not select the Time Grain - day,hour I get an error:
" No field class for DateTime('Europe/Amsterdam') ". When I choose a month or year everything works

### Superset version
0.24.0

![screenshot from 2018-05-16 15-27-11](https://user-images.githubusercontent.com/37840833/40116835-a12cad06-591d-11e8-8e5d-351ed549bb3d.png)

**Comment by seizmo** [comment]
I have the same problem with Decimal(18,4)

**Comment by mistercrunch** [comment]
Can we get a stacktrace? The reason we have an issue template is because we cannot help if we don't have context.

**Comment by janantos** [comment]
having the same issue on superset 0.29.0rc7 with no class for decimal(18,6)

**Comment by long2ice** [comment]
the error is:
```python3
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.6/site-packages/superset/sql_lab.py", line 226, in execute_sql_statement
superset_1  |     db_engine_spec.execute(cursor, sql, async_=True)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs/base.py", line 754, in execute
superset_1  |     cursor.execute(query)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 210, in execute
superset_1  |     self._process_response(response)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 341, in _process_response
superset_1  |     for r in response:
superset_1  |   File "/usr/local/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 222, in select
superset_1  |     model_class = model_class or ModelBase.create_ad_hoc_model(zip(field_names, field_types))
superset_1  |   File "/usr/local/lib/python3.6/site-packages/infi/clickhouse_orm/models.py", line 59, in create_ad_hoc_model
superset_1  |     attrs[name] = cls.create_ad_hoc_field(db_type)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 91, in create_ad_hoc_field
superset_1  |     raise NotImplementedError('No field class for %s' % db_type)
superset_1  | NotImplementedError: No field class for Decimal(10, 4)
```

**Comment by Sammion** [comment]
Same issue like @seizmo 
clickhouse error: No field class for Decimal(18, 3)
My superset version is 1.0.1
