### ISSUE TITLE
No numeric types to aggregate

### ISSUE THREAD

**Issue by birdflyinhigh** [apache/incubator-superset#5095]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Steps to reproduce
----------sql-----------
SELECT "渠道" AS "渠道",
       sum("金额") AS "金额"
FROM
  (SELECT newmode as "渠道",
          amount as "金额"
   FROM bdc_dwd.dw_fact_task_ss_daily
   LIMIT 100) AS "expr_qry"
GROUP BY "渠道"
ORDER BY "金额" DESC
LIMIT 200000
---------sql----------------

Traceback (most recent call last):
  File "/data/www/python/work/superset/viz.py", line 266, in get_payload
    data = self.get_data(df)
  File "/data/www/python/work/superset/viz.py", line 1271, in get_data
    values=self.metrics)
  File "/usr/lib64/python2.7/site-packages/pandas/core/reshape/pivot.py", line 136, in pivot_table
    agged = grouped.agg(aggfunc)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 4036, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 3468, in aggregate
    result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/base.py", line 435, in _aggregate
    **kwargs), None
  File "/usr/lib64/python2.7/site-packages/pandas/core/base.py", line 391, in _try_aggregate_string_function
    return f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 1037, in mean
    return self._cython_agg_general('mean', **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 3354, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only)
  File "/usr/lib64/python2.7/site-packages/pandas/core/groupby.py", line 3425, in _cython_agg_blocks
    raise DataError('No numeric types to aggregate')
DataError: No numeric types to aggregate

**Comment by mistercrunch** [comment]
Which version are you on?

**Comment by QianChao91** [comment]
check this: [https://github.com/apache/incubator-superset/pull/4726](url)
