### ISSUE TITLE
Exception in db upgrade from 0.24.0 to 0.25.6

### ISSUE THREAD

**Issue by asyd** [apache/incubator-superset#5157]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results

db upgrade run successfully 

### Actual results

Got an exception while running db upgrade

### Steps to reproduce

Install superset 0.24.0, initialize database, then upgrade to 0.25.6 and run db upgrade

```
superset@1669fab5cb7f:~$ superset db upgrade
Loaded your LOCAL configuration at [/etc/superset/superset_config.py]
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade e68c4473c581 -> f231d82b9b26, empty message
INFO  [alembic.runtime.migration] Running upgrade f231d82b9b26 -> bf706ae5eb46, cal_heatmap_metric_to_metrics
INFO  [alembic.runtime.migration] Running upgrade f231d82b9b26 -> 30bb17c0dc76, empty message
INFO  [alembic.runtime.migration] Running upgrade 30bb17c0dc76, bf706ae5eb46 -> c9495751e314, empty message
INFO  [alembic.runtime.migration] Running upgrade f231d82b9b26 -> 130915240929, is_sqllab_view
INFO  [alembic.runtime.migration] Running upgrade 130915240929, c9495751e314 -> 5ccf602336a0, empty message
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f948630ab70>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f948630ab70>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by Mingdr** [comment]
me too，ε=(´ο｀*)))·····

**Comment by mistercrunch** [comment]
Weird. Migration `5ccf602336a0` seems empty so I don't see why it's having issues. I see you're on py3.5, can you try on py3.6?
