### ISSUE TITLE
World map is not working for me ....

### ISSUE THREAD

**Issue by AnupKumarSaha** [apache/incubator-superset#5171]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/superset/viz.py", line 329, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/local/lib/python3.5/site-packages/superset/viz.py", line 142, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 683, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 410, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/usr/local/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 489, in get_sqla_query
    raise Exception(_("Metric '{}' is not valid".format(m)))
Exception: Metric 'None' is not valid

**Comment by Tyler-Rex** [comment]
I had this error once, and I fixed it by selecting an option in the 'bubble size' drop down, even though I wasn't using bubbles. I think the lesson is to check that something is selected in all the options, whether or not it matters to you.

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/5080 might tackle this
