### ISSUE TITLE
Bullet chart unhashable type: 'dict'

### ISSUE THREAD

**Issue by ajgil** [apache/incubator-superset#5188]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.5

### Expected results
Bullet chart

### Actual results
unhashable type: 'dict'
![image](https://user-images.githubusercontent.com/29748376/41334612-89093bb6-6ee6-11e8-9a9f-0e7554d35ce0.png)

``` bash
2018-06-13 08:32:19,909:ERROR:root:unhashable type: 'dict'
Traceback (most recent call last):
  File "/site-packages/superset/views/core.py", line 1107, in generate_json payload = viz_obj.get_payload()
  File "/site-packages/superset/viz.py", line 329, in get_payload  payload['data'] = self.get_data(df)
  File "site-packages/superset/viz.py", line 966, in get_data    df['metric'] = df[[self.metric]]
  File "/pandas/core/frame.py", line 2133, in __getitem__    return self._getitem_array(key)
  File "/site-packages/pandas/core/frame.py", line 2177, in _getitem_array    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/site-packages/pandas/core/indexing.py", line 1256, in _convert_to_indexer    indexer = check = labels.get_indexer(objarr)
  File "/site-packages/pandas/core/indexes/base.py", line 2702, in get_indexer    indexer = self._engine.get_indexer(target._values)
  File "pandas/_libs/index.pyx", line 291, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 1317, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'dict'
2018-06-13 08:32:19,981:INFO:werkzeug:10.168.24.69 - - [13/Jun/2018 08:32:19] "POST /superset/explore_json/ HTTP/1.1" 500 -
``` 

### Steps to reproduce
1º create Bullet chart visualization
2º Time column since ever
3º putting metrics and Ranges
![image](https://user-images.githubusercontent.com/29748376/41334634-9c6abb1c-6ee6-11e8-8f9b-5a346024ac2f.png)
4º No filters & No clauses
5º Run query

**Comment by mistercrunch** [comment]
https://github.com/apache/incubator-superset/pull/5108 ?

**Comment by ajgil** [comment]
Made changes on code.. Not found. Here code, im not sure

```python
export default function nvd3Vis(slice, payload) {
  let chart;
  let colorKey = 'key';
  const isExplore = $('#explore-container').length === 1;

  let data;
  if (payload.data) {
    #:data = payload.data.map(x => ({
    #  ...x, key: formatLabel(x.key, slice.datasource.verbose_map),
    #}));
    if (Array.isArray(payload.data)){
        data = payload.data.map(x => ({
                ...x, key: formatLabel(x.key, slice.datasource.verbose_map),
        }));
  } else {
    data = payload.data;
  }

  slice.container.html('');
  slice.clearError();

  let width = slice.width();
  const fd = slice.formData;

  const barchartWidth = function () {
    let bars;
    if (fd.bar_stacked) {
      bars = d3.max(data, function (d) { return d.values.length; });
    } else {
      bars = d3.sum(data, function (d) { return d.values.length; });
    }
    if (bars * minBarWidth > width) {
      return bars * minBarWidth;
    }
    return width;
  };
```

**Comment by ajgil** [comment]
?
