### ISSUE TITLE
Get an error unhashable type: 'dict' in a TableView with a NUMERIC type using PostgreSQL

### ISSUE THREAD

**Issue by llozanoc** [apache/incubator-superset#5202]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.25.6

### Expected results
Colum with the numeric values

### Actual results
<pre>ERROR:root:unhashable type: 'dict'
Traceback (most recent call last):
  File "\site-packages\superset\viz.py", line 364, in get_df_payload
    df = self.get_df(query_obj)
  File "\site-packages\superset\viz.py", line 162, in get_df
    self.results = self.datasource.query(query_obj)
  File "\site-packages\superset\connectors\sqla\models.py", line 713, in query
    sql = self.get_query_str(query_obj)
  File "\site-packages\superset\connectors\sqla\models.py", line 422, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "\site-packages\superset\connectors\sqla\models.py", line 520, in get_sqla_query
    elif m in metrics_dict:
TypeError: unhashable type: 'dict'</pre>

![image](https://user-images.githubusercontent.com/18721916/41426835-2daf0212-7005-11e8-9edd-6793cee960c0.png)

### Steps to reproduce
- Create Table View chart visualization
- Time column since ever
- Putting metrics
- No filters & No clauses
- Run query

**Comment by tomwojcik** [comment]
I and a few others have the exact same problem. The same issue happens when I use a heatmap. Possibly related #4984
Pivot table traceback

```
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/views/core.py", line 1107, in generate_json
    payload = viz_obj.get_payload()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/viz.py", line 329, in get_payload
    payload['data'] = self.get_data(df)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/viz.py", line 628, in get_data
    margins=self.form_data.get('pivot_margins'),
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 5303, in pivot_table
    margins_name=margins_name)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/reshape/pivot.py", line 60, in pivot_table
    if i not in data:
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/generic.py", line 1519, in __contains__
    return key in self._info_axis
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2021, in __contains__
    hash(key)
TypeError: unhashable type: 'dict'
2018-06-22 10:33:24,148:INFO:werkzeug:ip - - [22/Jun/2018 10:33:24] "POST /superset/explore_json/ HTTP/1.1" 500 -
```


Heatmap traceback
```
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/views/core.py", line 1107, in generate_json 
    payload = viz_obj.get_payload()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/viz.py", line 329, in get_payload
    payload['data'] = self.get_data(df)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/superset/viz.py", line 1801, in get_data
    df = df[[x, y, v]]
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2726, in _getitem_array  
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 1314, in _convert_to_indexer
    indexer = check = labels.get_indexer(objarr)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3245, in get_indexer
    indexer = self._engine.get_indexer(target._ndarray_values)
  File "pandas/_libs/index.pyx", line 301, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 1544, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'dict'
2018-06-22 10:27:07,098:INFO:werkzeug:ip - - [22/Jun/2018 10:27:07] "POST /superset/explore_json/ HTTP/1.1" 500 -
```

**Comment by TianyangLi** [comment]
@llozanoc You've got to add an agg function or else it won't know how to parse your request...

**Comment by llozanoc** [comment]
@TianyangLi Are you sure about that? I can make similar queries with other data types  without any problem.
