### ISSUE TITLE
show record page for dashboard broken

### ISSUE THREAD

**Issue by zoneyang** [apache/incubator-superset#5245]
### Superset version
0.24.0

### Actual results
if dashboard has chinese，such as 中文，the page “/dashboardmodelview/show/1” will broken。

**Comment by 296537044** [comment]
Traceback (most recent call last):
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/views.py", line 495, in show
    related_views=self._related_views)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 160, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 25, in block "content"
    {% block show_form %}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/show.html", line 27, in block "show_form"
    {{ widgets.get('show')()|safe }}
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ccgdc/webservice/ccsuperset/ccsupersetpy27env/local/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/show.html", line 36, in top-level template code
    <span style="white-space: pre-line">{{formatter(v) if formatter else v}}</span>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
