### ISSUE TITLE
Something went wrong while fetching the datasource list

### ISSUE THREAD

**Issue by Aaboobacker** [apache/incubator-superset#5422]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if any
- [X] I have reproduced the issue with at least the latest released version of superset
- [X] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest version just installed this week

### Expected results
Dashboard, charts, all other pages should show up.

### Actual results

Sorry, something went wrong
500 - Internal Server Error
Stacktrace
         Traceback (most recent call last):
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/superset/views/core.py", line 2070, in dashboard
    'datasources': {ds.uid: ds.data for ds in datasources},
  File "/home/ec2-user/venv/lib/python2.7/site-packages/superset/views/core.py", line 2070, in <dictcomp>
    'datasources': {ds.uid: ds.data for ds in datasources},
  File "/home/ec2-user/venv/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 380, in data
    d = super(SqlaTable, self).data
  File "/home/ec2-user/venv/lib/python2.7/site-packages/superset/connectors/base/models.py", line 175, in data
    'database': self.database.data,  # pylint: disable=no-member
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 631, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 724, in _emit_lazyload
    primary_key_identity)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 508, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 611, in _populate_full
    dict_[key] = getter(row)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1226, in process
    return process_value(impl_processor(value), dialect)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 408, in process_result_value
    self._update_key()
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 380, in _update_key
    self.engine._update_key(key)
  File "/home/ec2-user/venv/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 49, in _update_key
    digest = hashes.Hash(hashes.SHA256(), backend=default_backend())
  File "/home/ec2-user/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ec2-user/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ec2-user/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/home/ec2-user/venv/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
ImportError: cannot import name certificate_transparency

### Steps to reproduce

Was working absolutely fine and created dashboards, suddenly getting this error when I click on any page.

**Comment by yamyamyuo** [comment]
@Aaboobacker you can verify your superset version through 
```
superset version                                                             
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Superset 0.26.2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
