### ISSUE TITLE
Unable to Visualize - unicode columns regression 

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-superset#5479]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.3

### Expected results
I should able to visualize 

### Actual results
2018-07-24 15:09:07,039:ERROR:root:'ascii' codec can't decode byte 0xc3 in position 1747: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/muru/opensrc/superset/venv/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 743, in query
    df = self.database.get_df(sql, self.schema)
  File "/Users/muru/opensrc/superset/venv/lib/python2.7/site-packages/superset/models/core.py", line 694, in get_df
    sqls = [str(s).strip().strip(';') for s in sqlparse.parse(sql)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1747: ordinal not in range(128)

### Steps to reproduce
select column with unicode characters from table. It is used to work with Superset 0.24.0 version. I upgraded it to latest 0.26.3 version and broke in visualization. 

Is there a workaround for this issue? Please, let me know.

**Comment by mmuru** [comment]
I think, this PR #5387 will resolve this issue.
