### ISSUE TITLE
Datetime column not provided as part table configuration and is required by this type of chart

### ISSUE THREAD

**Issue by hookover** [apache/incubator-superset#5780]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 396, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 190, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 738, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 424, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 528, in get_sqla_query
    'Datetime column not provided as part table configuration '
Exception: Datetime column not provided as part table configuration and is required by this type of chart

------------
The time field in the database is of type int. What should I do?

**Comment by cristina-grosu** [comment]
How was this issue solved?

**Comment by lucien-roquette** [comment]
This error keeps pop-out while the chart worked at the first place. I build the chart, it works exactly the way I would like too but then (after leaving it on a dashboard) this error message shows up :
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/viz.py", line 394, in get_df_payload
    df = self.get_df(query_obj)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/viz.py", line 190, in get_df
    self.results = self.datasource.query(query_obj)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 752, in query
    sql = self.get_query_str(query_obj)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 437, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 542, in get_sqla_query
    'Datetime column not provided as part table configuration '
Exception: Datetime column not provided as part table configuration and is required by this type of chart
