### ISSUE TITLE
Cannot install superset

### ISSUE THREAD

**Issue by emirot** [apache/incubator-superset#5784]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Latest

### Actual results
```
Traceback (most recent call last):  File "/usr/local/bin/superset", line 4, in <module>
    __import__('pkg_resources').require('superset==0.23.0.dev0')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_as
ide
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_ma
ster
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_fr
om_requirements
    dists = ws.resolve(reqs, Environment())  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'superset==0.23.0.dev0' distribution was not found and is required by the application
```

### Steps to reproduce
```virtulenv env
      source env/bin/activate
      pip install superset
      fabmanager create-admin --app superset
```Username [admin]: nonoUser first name [admin]: nono
User last name [user]: nono
Email [admin@fab.org]: nonoPassword:
Repeat for confirmation:
Error: the two entered values do not match
Password:
Repeat for confirmation:Was unable to import superset Error: No module named flask_caching
````
And if I run superset  I get :
```Traceback (most recent call last):
  File "/usr/local/bin/superset", line 4, in <module>
    __import__('pkg_resources').require('superset==0.23.0.dev0')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'superset==0.23.0.dev0' distribution was not found and is required by the application```

**Comment by yamyamyuo** [comment]
try install superset newest version?

**Comment by emirot** [comment]
@yamyamyuo I've done ```pip install superset==0.27.0``` and it gives me the same error.

**Comment by emirot** [comment]
Thanks @yamyamyuo  @TianyangLi  my bad doing `which superset` it was a global one  in `/usr/local/bin/`and not the one in my env...
It's working now !
