### ISSUE TITLE
NoneType object has no attribute empty

### ISSUE THREAD

**Issue by bluestreek18** [apache/incubator-superset#5788]
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
I just upgraded superset. I am not sure what my previous version was. I now get this error whenever I try to view any charts.

Every chart for me has a box saying 'Series' object has no attribute 'items'

I have clickhouse and mssql as a datasource and both of them give the same error message.

I had a look and couldn't find any similar issues.

Thanks

Loaded your LOCAL configuration at [/home/ubuntu/superset/superset_config.pyc]
Loaded your LOCAL configuration at [/home/ubuntu/superset/superset_config.pyc]
2018-08-31 22:01:41,647:DEBUG:root:[stats_logger] (incr) explore
2018-08-31 22:01:43,159:DEBUG:root:[stats_logger] (incr) explore_json
2018-08-31 22:01:43,234:INFO:root:Cache key: 094d43f6eccd8bfa44040097ca0dd902
2018-08-31 22:01:43,238:INFO:root:Database.get_sqla_engine(). Masked URL: clickhouse://192.168.8.80:8123/backup
2018-08-31 22:01:43,283:INFO:root:SELECT date AS __timestamp, SUM(convcount) AS sum__convcount, SUM(session) AS sum__session, SUM(sessionimp) AS sum__sessionimp, SUM(convcounteng) AS sum__convcounteng
FROM session_dist
WHERE date >= toDate('2017-08-31') AND date <= toDate('2018-08-31') GROUP BY date ORDER BY sum__convcount DESC
 LIMIT 10000
2018-08-31 22:01:43,293:INFO:root:Database.get_sqla_engine(). Masked URL: clickhouse://192.168.8.80:8123/backup
2018-08-31 22:01:43,296:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.8.80
2018-08-31 22:01:43,298:DEBUG:urllib3.connectionpool:http://192.168.8.80:8123 "POST / HTTP/1.1" 200 None
2018-08-31 22:01:43,299:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.8.80
2018-08-31 22:01:43,301:DEBUG:urllib3.connectionpool:http://192.168.8.80:8123 "POST /?database=backup HTTP/1.1" 200 None
2018-08-31 22:01:43,303:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.8.80
2018-08-31 22:01:43,339:DEBUG:urllib3.connectionpool:http://192.168.8.80:8123 "POST /?query_id=7225603e-ad69-11e8-9343-fa163e3f74b3&database=backup HTTP/1.1" 200 None
2018-08-31 22:01:43,365:ERROR:root:'Series' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/superset/connectors/sqla/models.py", line 757, in query
    df = self.database.get_df(sql, self.schema)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/superset/models/core.py", line 764, in get_df
    for k, v in df.dtypes.items():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3077, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'items'
2018-08-31 22:01:43,367:ERROR:root:'NoneType' object has no attribute 'empty'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/superset/viz.py", line 394, in get_df_payload
    df = self.get_df(query_obj)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/superset/viz.py", line 201, in get_df
    if not df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
/home/ubuntu/.local/lib/python2.7/site-packages/flask_appbuilder/fields.py:152: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
  warnings.warn('allow_blank=True does not do anything for QuerySelectMultipleField.')

**Comment by bluestreek18** [comment]
I fixed this by doing the below. For whatever reason the upgrade command didn't install the correct packages. Hopefully this can help someone in a similar situation.

`
wget https://raw.githubusercontent.com/apache/incubator-superset/master/requirements.txt
pip install -r requirements.txt
`
