### ISSUE TITLE
Error export datasources from command

### ISSUE THREAD

**Issue by zhaoyongjie** [apache/incubator-superset#5816]
### Superset version
On master branch

### Actual results
```
(incubator-superset-py3) yongjie.zhao@:incubator-superset$ superset export_datasources
Traceback (most recent call last):
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/bin/superset", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/yongjie.zhao/workspace/kyligence/incubator-superset/superset/bin/superset", line 21, in <module>
    cli()
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/yongjie.zhao/.virtualenvs/incubator-superset-py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: export_datasources() got an unexpected keyword argument 'print'
```

It looks like a problem caused by refactoring cli.py

**Comment by arpit-agarwal** [comment]
I think this has been fixed on master top with #5991
