### ISSUE TITLE
non ascii table names cause error in python 2.7

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#5832]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
Be able to create a chart from a table with a unicode name

### Actual results
in python 3.5 it works without problem.
in python 2.7 i get the following error:
`Traceback (most recent call last):
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/#####/testing_superset/superset/env/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/Users/#####/testing_superset/superset/superset/views/core.py", line 460, in add
    for d in datasources
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)`
### Steps to reproduce

- create a table in the database with a unicode name

- in charts, click to add new record and you will get the error only in python 2.7

**Comment by mistercrunch** [comment]
Any good reason why you're still using `2.7`? I think we're about to deprecate support for it.

**Comment by mistercrunch** [comment]
Also which DB is this?

**Comment by aboganas** [comment]
The latest Mariadb

Actually I would prefer python 3.7, I just read in the docs that Airbnb uses 2.7 in production that why I used 2,7. If superset on python 3.7 is fully stable, then I will stick with it.

Thanks

**Comment by aboganas** [comment]
Thank so much. Yep `?charset=utf8` in my connection and everything works perfectly on python 3^.
so I will stick with python 3.6.

You can close this issue if python 2.7 is about to be deprecate.

I really appreciate your help
