### ISSUE TITLE
run with docker get error  amqp Connection refused.

### ISSUE THREAD

**Issue by cjd9023** [apache/incubator-superset#5916]
start with https://superset.incubator.apache.org/installation.html
----
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
docker-compose up -d
docker-compose exec superset bash
bash docker-init.sh
---
on last step, `bash docker-init.sh`
get error below

> superset@0.999.0-dev build /home/work/incubator-superset/superset/assets
> webpack --mode=production --colors --progress

clean-webpack-plugin: /home/work/incubator-superset/superset/assets/dist has been removed.
 95% emitting OptimizeCssAssetsWebpackPluginError: EACCES: permission denied, mkdir '/home/work/incubator-superset/superset/assets/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/work/.npm/_logs/2018-09-17T06_14_13_351Z-debug.log
+ superset runserver -d
+ superset worker
2018-09-17 06:14:14,855:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:14,856:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:14,865:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:14,866:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:16,097:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:16,097:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:16,116:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:16,116:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:16,664:INFO:root:The 'superset worker' command is deprecated. Please use the 'celery worker' command instead.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Starting Superset server in DEBUG mode
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

2018-09-17 06:14:16,695:INFO:werkzeug: * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
2018-09-17 06:14:16,696:INFO:werkzeug: * Restarting with stat
 
 -------------- celery@5cb6bb97e9a9 v4.2.1 (windowlicker)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-debian-9.5 2018-09-17 06:14:16
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7feac96f73c8
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 32 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

2018-09-17 06:14:18,140:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:18,141:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:19,413:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2018-09-17 06:14:19,413:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Starting Superset server in DEBUG mode
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

2018-09-17 06:14:20,028:WARNING:werkzeug: * Debugger is active!
2018-09-17 06:14:20,029:INFO:werkzeug: * Debugger PIN: 534-190-040
[2018-09-17 06:14:21,416: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2018-09-17 06:14:23,426: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...
repeat  the error log forever, 

open the  http://x.x.x.x:8088/login/
input name/pass get error "Invalid login. Please try again."

how can i fix this

thanks

**Comment by cjd9023** [comment]
i set dir with permission 777, fix this error,
thanks
