### ISSUE TITLE
Time Series Table displays blank result

### ISSUE THREAD

**Issue by vnnw** [apache/incubator-superset#5929]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.0rc6 and current Master.

### Expected results
Proper visualization as previous version.

### Actual results
![image](https://user-images.githubusercontent.com/4979571/45732660-e6f2c000-bc0f-11e8-8280-ebf635eabc52.png)

### Steps to reproduce
Install superset with 0.28.0rc6 and current Master.
Add a Time Series Table using demo "Birth" data.

**Comment by chancez** [comment]
Also hitting this. Not sure if it's related but I see the following in the logs:
```
Exception on /superset/explore_json/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/superset/models/core.py", line 1017, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 1246, in explore_json
    samples=samples,
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 1165, in generate_json
    return json_success(viz_obj.json_dumps(payload), status=status)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 465, in json_dumps
    sort_keys=sort_keys,
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
```

**Comment by nmacchitella** [comment]
I have an issue with time-series too. When I use it through superset installed on virualenv i got this exact same problem. And if i try to install on docker and then run i get this https://github.com/apache/incubator-superset/issues/6788

**Comment by Brunoxpszulc** [comment]
I just got updated to 0.28.1 and have the same issue with no visualisation of time series on charts( bars neither lines).

**Comment by Demonya** [comment]
Have anyone sovled this problem? The same issue happen to me,need you help,thanks!

**Comment by ofirz** [comment]
Same issue for me :(
