### ISSUE TITLE
error when using time since > 28 days ago and time grain different than time column

### ISSUE THREAD

**Issue by xrmx** [apache/incubator-superset#597]
I get this exception:

```
Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
```

while on a Time series bar chart and using time since > 28 days ago and time grain different than time column. Any clue on what could be wrong?

**Comment by xrmx** [comment]
Looks like this: https://github.com/pydata/pandas/issues/7139
But should be fixed and tested since a year. Trying to upgrade pandas to 0.18.1 to see if it has been fixed here.

**Comment by mistercrunch** [comment]
Can you share the full stack trace? Otherwise it's hard to know where the error is coming from...

**Comment by xrmx** [comment]
So it looks like i have data with mixed timezones:

```
giu 10 18:37:36 runcaravel[1486]: 2016-06-10 18:37:36,349:ERROR:root:Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
giu 10 18:37:36  runcaravel[1486]: Traceback (most recent call last):
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 399, in _convert_listlike
giu 10 18:37:36 runcaravel[1486]: values, tz = tslib.datetime_to_datetime64(arg)
giu 10 18:37:36 runcaravel[1486]: File "pandas/tslib.pyx", line 1574, in pandas.tslib.datetime_to_datetime64 (pandas/tslib.c:29550)
giu 10 18:37:36 runcaravel[1486]: ValueError: Array must be all same time zone
giu 10 18:37:36 runcaravel[1486]: During handling of the above exception, another exception occurred:
giu 10 18:37:36 runcaravel[1486]: Traceback (most recent call last):
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/views.py", line 722, in explore
giu 10 18:37:36 runcaravel[1486]: payload = obj.get_json()
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/viz.py", line 250, in get_json
giu 10 18:37:36 runcaravel[1486]: 'data': self.get_data(),
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/viz.py", line 1014, in get_data
giu 10 18:37:36 runcaravel[1486]: df = self.get_df()
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/viz.py", line 923, in get_df
giu 10 18:37:36 runcaravel[1486]: df = super(NVD3TimeSeriesViz, self).get_df(query_obj)
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/viz.py", line 143, in get_df
giu 10 18:37:36 runcaravel[1486]: df.timestamp = pd.to_datetime(df.timestamp, utc=False)
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/util/decorators.py", line 91, in wrapper
giu 10 18:37:36 runcaravel[1486]: return func(*args, **kwargs)
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 287, in to_datetime
giu 10 18:37:36 runcaravel[1486]: unit=unit, infer_datetime_format=infer_datetime_format)
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 409, in _to_datetime
giu 10 18:37:36 runcaravel[1486]: values = _convert_listlike(arg._values, False, format)
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 402, in _convert_listlike
giu 10 18:37:36  runcaravel[1486]: raise e
giu 10 18:37:36 runcaravel[1486]: File "/var/www/caravel/venv/local/lib/python3.4/site-packages/pandas/tseries/tools.py", line 388, in _convert_listlike
giu 10 18:37:36 runcaravel[1486]: require_iso8601=require_iso8601
giu 10 18:37:36 runcaravel[1486]: File "pandas/tslib.pyx", line 1960, in pandas.tslib.array_to_datetime (pandas/tslib.c:39429)
giu 10 18:37:36 runcaravel[1486]: File "pandas/tslib.pyx", line 2000, in pandas.tslib.array_to_datetime (pandas/tslib.c:36393)
giu 10 18:37:36  runcaravel[1486]: ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
```

**Comment by xrmx** [comment]
Same happens on pandas 0.18.1

**Comment by xrmx** [comment]
I've tried to poke a bit at this but i can't see a generic solution here:
- pandas gets psycopg2.tz.FixedOffsetTimezone tz objects so their dst(dt) method will always return 0 and thus we cannot adjust the check here to keep dst into account
- caravel handle the objects returned by the query as a whole

Any other ideas or a clue?

**Comment by xrmx** [comment]
I overlooked the fact that the field i use as time column is a DATE so it has not time or timezone. So it's something inside caravel / pandas that is upgrading this to a Timestamp. Any hint on where to look?

**Comment by kurtbradd** [comment]
I'm also receiving this exception on an attribute stored as a timestamp with time zone.
I've tried upgrading to Pandas 0.18.1 with no luck.

**Comment by xrmx** [comment]
@kurtbradd do you get "ValueError: Array must be all same time zone"? If so are you using postgresql? If not that's probably a different issue :)

**Comment by danialgood** [comment]
@xrmx i get the error you mentioned and i'm using postgresql

**Comment by mistercrunch** [comment]
```
runcaravel[1486]: File "/var/www/caravel/venv/src/caravel/caravel/viz.py", line 143, in get_df
giu 10 18:37:36 runcaravel[1486]: df.timestamp = pd.to_datetime(df.timestamp, utc=False)
```
I'm not sure if `utc=False` is really needed here or whether is should be configurable at the column level. Anyhow, a quick fix might be to wrap this in a try statement and fallback on `utc=True` when the `utc=False` call fails.

**Comment by danialgood** [comment]
my timestamps have timezone different than utc
i ended up casting column ({col}) to TIMESTAMP
no problems so far
