### ISSUE TITLE
docker-build.sh failed installing yarn, missing X11 library

### ISSUE THREAD

**Issue by aflyhorse** [apache/incubator-superset#6086]
### Superset version
latest (commit 2a7b64fef5823760fd619f217b3161d2d7d00cc6)

### Expected results
Installation success.

### Actual results
```
Step 23/27 : RUN cd superset/assets && yarn
 ---> Running in cb22a4cbabe8
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.Excluding it from installation.
[4/5] Linking dependencies...
warning " > @data-ui/event-flow@0.0.54" has unmet peer dependency "aphrodite@^1.2.0".
warning "@data-ui/event-flow > recompose@0.23.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning " > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
warning " > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".
warning " > react-test-renderer@15.6.2" has incorrect peer dependency "react@^15.6.2".
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about thiscommand.
error /home/work/incubator-superset/superset/assets/node_modules/gl: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /home/work/incubator-superset/superset/assets/node_modules/gl
Output:
prebuild-install WARN install connect ETIMEDOUT 52.216.225.192:443
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.12.0/node-v8.12.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.12.0/node-v8.12.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.12.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.12.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/work/incubator-superset/superset/assets/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/incubator-superset/superset/assets/node_modules/gl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/incubator-superset/superset/assets/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/work/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/work/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/work/incubator-superset/superset/assets/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/work/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/work/incubator-superset/superset/assets/node_modules/gl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
gyp: Call to 'pkg-config --libs-only-l x11 xi xext' returned exit status 1 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while tryingto load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/work/incubator-superset/superset/assets/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/home/work/incubator-superset/superset/assets/node_modules/gl/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/work/incubator-superset/superset/assets/node_modules/gl
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
The command '/bin/sh -c cd superset/assets && yarn' returned a non-zero code: 1
```

### Steps to reproduce
System CentOS 7.3, using commands in tutorial.
```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
```

**Comment by aflyhorse** [comment]
code merged, close. 😄

**Comment by XuanmoFeng** [comment]
centos 6 is not ok,same error
