### ISSUE TITLE
[0.27.0]Query with presto by Chinese will get a error

### ISSUE THREAD

**Issue by rockxsj** [apache/incubator-superset#6107]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
result rows

### Actual results
the query will never finish and get error message when I check celery worker logs:
```
Traceback (most recent call last):
  File "/data4/pyenv/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 86, in get_sql_results
    session=session)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 161, in execute_sql
    session.merge(query)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1910, in merge
    self._autoflush()
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/MySQLdb/cursors.py", line 234, in execute
    args = tuple(map(db.literal, args))
  File "/data4/pyenv/superset/lib/python3.6/site-packages/MySQLdb/connections.py", line 317, in literal
    s = self.escape(o, self.encoders)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/MySQLdb/connections.py", line 225, in unicode_literal
    return db.string_literal(str(u).encode(db.encoding))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 68-72: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/pyenv/superset/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 90, in get_sql_results
    query = get_query(query_id, session)
  File "/data4/pyenv/superset/lib/python3.6/site-packages/superset/sql_lab.py", line 48, in get_query
    raise SqlLabException('Failed at getting query')
superset.sql_lab.SqlLabException: Failed at getting query
```

### Steps to reproduce
install superset by pip:
``` bash
pip install superset
```

config a datasource point to presto:
```
presto://xxx.xxx.xxx.xxx:8889/hive/fact
```

query in sqllab:
``` sql
SELECT * from search_access_fact WHERE pday = 20181013 and query = '快乐大本营' LIMIT 100
```
--

**Comment by mistercrunch** [comment]
Try python 3.6, we don't support <3.6 starting on the next Superset version

**Comment by zhaoyongjie** [comment]
It's look like MySQL charsets issues.
refer to https://stackoverflow.com/questions/202205/how-to-make-mysql-handle-utf-8-properly

**Comment by mistercrunch** [comment]
It says `presto://` though

**Comment by rockxsj** [comment]
@zhaoyongjie No, the datasource is presto, that's strange  :(

**Comment by zhaoyongjie** [comment]
@rockxsj sorry, Looks from the error log
```
  File "/data4/pyenv/superset/lib/python3.6/site-packages/MySQLdb/connections.py", line 225, in unicode_literal
    return db.string_literal(str(u).encode(db.encoding))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 68-72: ordinal not in range(256)

```

**Comment by mistercrunch** [comment]
Oh good catch @zhaoyongjie, doesn't look like presto in the logs

**Comment by rockxsj** [comment]
@zhaoyongjie I know it looks mysql from logs, but in fact I query the sql from presto datasource in superset.

**Comment by zhaoyongjie** [comment]
@rockxsj could you show me more log with presto?

**Comment by rockxsj** [comment]
@zhaoyongjie The log in subject is full tracestack :(   But I found that when I checked "allow query in sync mode" in datasource config, it worked well.   So I think it's a temp solution    :)

**Comment by zhaoyongjie** [comment]
This is nice workaround, and this issue maybe a bug.

**Comment by 7A6A78** [comment]
@rockxsj 
I resolved this issue by creating database `superset` by myself, the most important thing is that the charset of the mysql database `superset` must be utf8:
`CREATE DATABASE superset CHARACTER SET utf8 COLLATE utf8_general_ci;`

After that, initialize the database:
`superset db upgrade`
