### ISSUE TITLE
Issue when Configuring superset (config.py) with LDAP

### ISSUE THREAD

**Issue by hamidmahmoodnbs** [apache/incubator-superset#6118]
Hi,

I am trying to configure superset to work with LDAP. I am using Superset Version 0.25.6. When I give the configurations in config.py file on the following path /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/superset/config.py. Following are the configurations I am giving.
```
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = "ldap.forumsys.com"
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_SEARCH = "dc=domain,dc=local"
AUTH_LDAP_BIND_USER = "CN=read-only-admin,OU=mathematicians,dc=example,dc=com"
AUTH_LDAP_BIND_PASSWORD = "password"
```
After I login with the users given in free online ldap server (https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/), I gets the following error.
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_appbuilder/security/views.py", line 402, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_appbuilder/security/manager.py", line 662, in auth_user_ldap
    except ldap.LDAPError as e:
AttributeError: module 'ldap' has no attribute 'LDAPError'
```
I would really appreciate if someone can help me.

Regards,
Hamid

**Comment by datinho** [comment]
Hi Hamid,
did you import the submodule AUTH_LDAP?

At start of config.py you must change
`from flask_appbuilder.security.manager import AUTH_DB`
to
`from flask_appbuilder.security.manager import AUTH_LDAP`

**Comment by mistercrunch** [comment]
Error `AttributeError: module 'ldap' has no attribute 'LDAPError'` looks to me like you didn't import the right `ldap` module in your environment or that there is some conflict there.

**Comment by hamidmahmoodnbs** [comment]
@datinho @mistercrunch thanks for your response. I was facing this problem due to multiple ldap libraries in my environment. My problem has been resolved by deleting all ldap libraries and re-installing by pip install python-ldap. 

Thanks
