### ISSUE TITLE
No columns listed in MSSQL database tables.

### ISSUE THREAD

**Issue by zintj** [apache/incubator-superset#6147]
Make sure these boxes are checked before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if any
- [*] I have reproduced the issue with at least the latest released version of superset
- [*] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.27.0

### Expected results
Tables correctly list columns when added.

### Actual results
Connection is made to a MSSQL database, but when adding tables, no columns are listed. However, when opening the same DB in SQL Lab, everything appears correct.

Using the same build below and connecting to a postgres DB, all columns load correctly.

### Steps to reproduce
Built Heroku Superset instance with:
https://github.com/zintj/superset-on-heroku 
Connected with a 'mssql+pymssql://' connection string.
Running Superset locally, I don't have this issue. I'm not sure if it's a package issue or..

Stack trace from attempting to refresh table metadata below:

  ```
       Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: value too long for type character varying(32)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_appbuilder/views.py", line 578, in action_post
    return action.func(items)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/sqla/views.py", line 300, in refresh
    t.fetch_metadata()
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 831, in fetch_metadata
    self.add_missing_metrics(metrics)
  File "/app/.heroku/python/lib/python3.6/site-packages/superset/connectors/base/models.py", line 127, in add_missing_metrics
    exisiting_metrics = {m.metric_name for m in self.metrics}
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 601, in get
    value = self.callable_(state, passive)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 631, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 771, in _emit_lazyload
    with_post_criteria(set_default_params).all()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 457, in all
    return list(self)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 359, in __iter__
    self.session._autoflush()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) value too long for type character varying(32)
 [SQL: 'INSERT INTO table_columns (created_on, changed_on, column_name, verbose_name, is_active, type, groupby, count_distinct, sum, avg, max, min, filterable, description, table_id, is_dttm, expression, python_date_format, database_expression, created_by_fk, changed_by_fk) VALUES (%(created_on)s, %(changed_on)s, %(column_name)s, %(verbose_name)s, %(is_active)s, %(type)s, %(groupby)s, %(count_distinct)s, %(sum)s, %(avg)s, %(max)s, %(min)s, %(filterable)s, %(description)s, %(table_id)s, %(is_dttm)s, %(expression)s, %(python_date_format)s, %(database_expression)s, %(created_by_fk)s, %(changed_by_fk)s) RETURNING table_columns.id'] [parameters: {'created_on': datetime.datetime(2018, 10, 19, 2, 56, 24, 84789), 'changed_on': datetime.datetime(2018, 10, 19, 2, 56, 24, 84809), 'column_name': 'Inv_Num', 'verbose_name': None, 'is_active': True, 'type': 'VARCHAR(9) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS', 'groupby': True, 'count_distinct': False, 'sum': False, 'avg': False, 'max': False, 'min': False, 'filterable': True, 'description': None, 'table_id': 1, 'is_dttm': False, 'expression': '', 'python_date_format': None, 'database_expression': None, 'created_by_fk': 1, 'changed_by_fk': 1}] 
```

**Comment by zintj** [comment]
ALTER TABLE table_columns ALTER COLUMN type TYPE VARCHAR(64); solved this.

**Comment by bsnithin44** [comment]
Hi @zihengCat,
I am facing the same error. Where did you add the ALTER TABLE query?
