### ISSUE TITLE
Dockerfile build error with setup.py

### ISSUE THREAD

**Issue by kk580kk** [apache/incubator-superset#6225]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

```
Step 19/31 : RUN pip install -e .
 ---> Running in a3591fdb8251
Obtaining file:///home/work/incubator-superset
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/work/incubator-superset/setup.py", line 15, in <module>
        with open(PACKAGE_FILE) as package_file:
    NotADirectoryError: [Errno 20] Not a directory: '/home/work/incubator-superset/superset/static/assets/package.json'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/work/incubator-superset/
```

### Superset version
https://github.com/apache/incubator-superset/commit/0f6b39a6f73dfcbccfd5c1ce91b54f7622df8fb9

### Expected results
Want to build docker images  with success result

### Actual results
Error with setup.py:15

### Steps to reproduce
Fellow installation guide http://superset.apache.org/installation.html
run command 
```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
```

**Comment by kk580kk** [comment]
Got the same problems on ubuntu18.04
```
incubator-superset git:(master) ✗ pip3 install -e .
Obtaining file:///media/kk580kk/0D2D06A00D2D06A0/workspace/GitHub/apache/incubator-superset
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/kk580kk/0D2D06A00D2D06A0/workspace/GitHub/apache/incubator-superset/setup.py", line 15, in <module>
        with open(PACKAGE_FILE) as package_file:
    NotADirectoryError: [Errno 20] Not a directory: '/media/kk580kk/0D2D06A00D2D06A0/workspace/GitHub/apache/incubator-superset/superset/static/assets/package.json'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /media/kk580kk/0D2D06A00D2D06A0/workspace/GitHub/apache/incubator-superset/
```

**Comment by kk580kk** [comment]
I have check the folder `superset/static/assets/package.json` and find `superset/static/assets` is a **symbolic link** 
why use link here?
and I try to run `rm assets && ln -s ../assets' to rebuild this link.
