### ISSUE TITLE
export_datasources command failed during internal sorting

### ISSUE THREAD

**Issue by gnomeby** [apache/incubator-superset#6265]
### Superset version
Superset version : 0.26.3
Python version : 3.6.3

### Expected results
Run export_datasources 

### Actual results
Traceback (most recent call last):
  File "/home/gnomeby/.virtualenvs/superset/bin/superset", line 15, in <module>
    cli()
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/superset/cli.py", line 328, in export_datasources
    include_defaults=include_defaults)
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/superset/dict_import_export_util.py", line 35, in export_to_dict
    include_defaults=include_defaults) for database in dbs]
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/superset/dict_import_export_util.py", line 35, in <listcomp>
    include_defaults=include_defaults) for database in dbs]
  File "/home/gnomeby/.virtualenvs/superset/lib/python3.6/site-packages/superset/models/helpers.py", line 200, in export_to_dict
    key=lambda k: sorted(k.items())
TypeError: '<' not supported between instances of 'dict' and 'dict'

### Steps to reproduce
Define multiple datasources. I have default one, clickhouse and postgresql
Run
```superset export_datasources ```

**Comment by gnomeby** [comment]
You had a similar issue https://github.com/apache/incubator-superset/issues/5798 that was closed by mistake.

**Comment by demoV** [comment]
I am getting same error in 0.29.0rc7 version. Please help
