### ISSUE TITLE
Calendar Heatmap error in latest master

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#6278]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Master

### Expected results
Calendar Heatmap works

### Actual results
I get the following error
`unsupported operand type(s) for /: 'Timestamp' and 'int'`

Here is the Python 
```
2018-11-06 05:56:26,419:ERROR:root:unsupported operand type(s) for /: 'Timestamp' and 'int'
Traceback (most recent call last):
  File "/Users/alganas/LEXER/master/incubator-superset/superset/views/core.py", line 1162, in generate_json
    payload = viz_obj.get_payload()
  File "/Users/alganas/LEXER/master/incubator-superset/superset/viz.py", line 372, in get_payload
    payload['data'] = self.get_data(df)
  File "/Users/alganas/LEXER/master/incubator-superset/superset/viz.py", line 788, in get_data
    for obj in records
  File "/Users/alganas/LEXER/master/incubator-superset/superset/viz.py", line 788, in <dictcomp>
    for obj in records
TypeError: unsupported operand type(s) for /: 'Timestamp' and 'int'
```

### Steps to reproduce

just try to create a heatmap cal or load Calendar Heatmap multiformat example

**Comment by aboganas** [comment]
@mistercrunch Should I send a pr for the fix that @apimastery or would It introduce other problems

**Comment by aboganas** [comment]
running in development mode, I get the following error
```
Warning: CreatableSelect: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
warningWithoutStack @ webpack-internal:///./node_modules/react/cjs/react.development.js:241
webpack-internal:///./src/visualizations/MapBox/ScatterPlotGlowOverlay.jsx:222 Uncaught TypeError: (0 , _d3Format.round) is not a function
    at ProxyComponent._forEach (webpack-internal:///./src/visualizations/MapBox/ScatterPlotGlowOverlay.jsx:222)
    at List.__iterate (webpack-internal:///./node_modules/immutable/dist/immutable.js:2205)
    at List.forEach (webpack-internal:///./node_modules/immutable/dist/immutable.js:4380)
    at ProxyComponent.redraw (webpack-internal:///./src/visualizations/MapBox/ScatterPlotGlowOverlay.jsx:219)
    at ProxyComponent.redraw (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:580)
    at ProxyComponent.componentDidMount (webpack-internal:///./src/visualizations/MapBox/ScatterPlotGlowOverlay.jsx:123)
    at ProxyComponent.componentDidMount (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:570)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14685)
    at commitAllLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15905)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:145)
webpack-internal:///./node_modules/react-map-gl/node_modules/mapbox-gl/dist/mapbox-gl.js:29 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
b @ webpack-internal:///./node_modules/react-map-gl/node_modules/mapbox-gl/dist/mapbox-gl.js:29
webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14550 The above error occurred in the <ScatterPlotGlowOverlay> component:
    in ScatterPlotGlowOverlay (created by MapBox)
    in div (created by StaticMap)
    in div (created by StaticMap)
    in StaticMap (created by InteractiveMap)
    in div (created by InteractiveMap)
    in InteractiveMap (created by MapBox)
    in MapBox (created by LoadableComponent)
    in LoadableComponent (created by SuperChart)
    in div (created by SuperChart)
    in SuperChart (created by Chart)
    in div (created by Chart)
    in ErrorBoundary (created by Chart)
    in Chart (created by Connect(Chart))
    in Connect(Chart) (created by ParentSize)
    in div (created by ParentSize)
    in ParentSize (created by ExploreChartPanel)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by ExploreChartPanel)
    in div (created by ExploreChartPanel)
    in ExploreChartPanel (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in ExploreViewContainer (created by Connect(ExploreViewContainer))
    in Connect(ExploreViewContainer) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by aboganas** [comment]
using dev installation now I get the following error
```
Uncaught TypeError: Cannot read property '0' of undefined
    at eval (Calendar.js?d33d:98)
    at Array.forEach (<anonymous>)
    at Calendar (Calendar.js?d33d:77)
    at ProxyComponent.execute (reactify.jsx?f3ca:28)
    at ProxyComponent.execute (react-hot-loader.development.js?c2cb:580)
    at ProxyComponent.componentDidMount (reactify.jsx?f3ca:11)
    at ProxyComponent.componentDidMount (react-hot-loader.development.js?c2cb:570)
    at commitLifeCycles (react-dom.development.js?61bb:14685)
    at commitAllLifeCycles (react-dom.development.js?61bb:15905)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:145)
(anonymous) @ Calendar.js?d33d:98
Calendar @ Calendar.js?d33d:77
execute @ reactify.jsx?f3ca:28
startTimer @ react-hot-loader.development.js?c2cb:580
componentDidMount @ reactify.jsx?f3ca:11
componentDidMount @ react-hot-loader.development.js?c2cb:570
commitLifeCycles @ react-dom.development.js?61bb:14685
commitAllLifeCycles @ react-dom.development.js?61bb:15905
callCallback @ react-dom.development.js?61bb:145
invokeGuardedCallbackDev @ react-dom.development.js?61bb:195
invokeGuardedCallback @ react-dom.development.js?61bb:248
commitRoot @ react-dom.development.js?61bb:16075
completeRoot @ react-dom.development.js?61bb:17463
performWorkOnRoot @ react-dom.development.js?61bb:17391
performWork @ react-dom.development.js?61bb:17295
performSyncWork @ react-dom.development.js?61bb:17267
requestWork @ react-dom.development.js?61bb:17155
scheduleWork @ react-dom.development.js?61bb:16949
enqueueSetState @ react-dom.development.js?61bb:11623
Component.setState @ react.development.js?72d0:413
update @ index.js?0a70:205
(anonymous) @ index.js?0a70:215
Promise.then (async)
_loadModule @ index.js?0a70:214
startTimer @ react-hot-loader.development.js?c2cb:580
componentWillMount @ index.js?0a70:168
callComponentWillMount @ react-dom.development.js?61bb:11829
mountClassInstance @ react-dom.development.js?61bb:11917
updateClassComponent @ react-dom.development.js?61bb:13492
beginWork @ react-dom.development.js?61bb:14090
performUnitOfWork @ react-dom.development.js?61bb:16416
workLoop @ react-dom.development.js?61bb:16454
renderRoot @ react-dom.development.js?61bb:16533
performWorkOnRoot @ react-dom.development.js?61bb:17387
performWork @ react-dom.development.js?61bb:17295
performSyncWork @ react-dom.development.js?61bb:17267
requestWork @ react-dom.development.js?61bb:17155
scheduleWork @ react-dom.development.js?61bb:16949
enqueueSetState @ react-dom.development.js?61bb:11623
Component.setState @ react.development.js?72d0:413
onStateChange @ connectAdvanced.js?fe33:205
startTimer @ react-hot-loader.development.js?c2cb:580
dispatch @ createStore.js?61ed:173
(anonymous) @ index.js?b083:11
dispatch @ applyMiddleware.js?05f2:35
(anonymous) @ chartAction.js?2410:173
Promise.then (async)
(anonymous) @ chartAction.js?2410:155
(anonymous) @ index.js?b083:8
(anonymous) @ bindActionCreators.js?f901:3
componentDidMount @ Chart.jsx?70bb:63
componentDidMount @ react-hot-loader.development.js?c2cb:570
commitLifeCycles @ react-dom.development.js?61bb:14685
commitAllLifeCycles @ react-dom.development.js?61bb:15905
callCallback @ react-dom.development.js?61bb:145
invokeGuardedCallbackDev @ react-dom.development.js?61bb:195
invokeGuardedCallback @ react-dom.development.js?61bb:248
commitRoot @ react-dom.development.js?61bb:16075
completeRoot @ react-dom.development.js?61bb:17463
performWorkOnRoot @ react-dom.development.js?61bb:17391
performWork @ react-dom.development.js?61bb:17295
performSyncWork @ react-dom.development.js?61bb:17267
requestWork @ react-dom.development.js?61bb:17155
scheduleWork @ react-dom.development.js?61bb:16949
enqueueSetState @ react-dom.development.js?61bb:11623
Component.setState @ react.development.js?72d0:413
resize @ vx-responsive.es.js?d25d:653
startTimer @ react-hot-loader.development.js?c2cb:580
invokeFunc @ vx-responsive.es.js?d25d:415
trailingEdge @ vx-responsive.es.js?d25d:464
timerExpired @ vx-responsive.es.js?d25d:452
setTimeout (async)
leadingEdge @ vx-responsive.es.js?d25d:423
debounced @ vx-responsive.es.js?d25d:492
(anonymous) @ vx-responsive.es.js?d25d:603
requestAnimationFrame (async)
_loop @ vx-responsive.es.js?d25d:602
(anonymous) @ vx-responsive.es.js?d25d:620
react-dom.development.js?61bb:14550 The above error occurred in the <Calendar> component:
    in Calendar (created by LoadableComponent)
    in LoadableComponent (created by SuperChart)
    in div (created by SuperChart)
    in SuperChart (created by Chart)
    in div (created by Chart)
    in ErrorBoundary (created by Chart)
    in Chart (created by Connect(Chart))
    in Connect(Chart) (created by ParentSize)
    in div (created by ParentSize)
    in ParentSize (created by ExploreChartPanel)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by ExploreChartPanel)
    in div (created by ExploreChartPanel)
    in ExploreChartPanel (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in div (created by ExploreViewContainer)
    in ExploreViewContainer (created by Connect(ExploreViewContainer))
    in Connect(ExploreViewContainer) (created by App)
    in div (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
```
