### ISSUE TITLE
Cant' upload CSV that contains time field with : Delimiter

### ISSUE THREAD

**Issue by aboganas** [apache/incubator-superset#6366]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
from 0.28 to latest master

### Expected results
csv with a time field that contains : Delimiter should upload without a problem

### Actual results
I get the error `TypeError: Object of type OperationalError is not JSON serializable`

the error is
```
127.0.0.1 - - [11/Nov/2018 17:07:24] "GET /csvtodatabaseview/form HTTP/1.1" 200 -
2018-11-11 17:07:24,993:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:24] "GET /csvtodatabaseview/form HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:25] "GET /superset/schemas_access_for_csv_upload?db_id=1 HTTP/1.1" 200 -
2018-11-11 17:07:25,478:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:25] "GET /superset/schemas_access_for_csv_upload?db_id=1 HTTP/1.1" 200 -
2018-11-11 17:07:27,107:DEBUG:root:[stats_logger] (incr) failed_csv_upload
127.0.0.1 - - [11/Nov/2018 17:07:27] "POST /csvtodatabaseview/form HTTP/1.1" 500 -
2018-11-11 17:07:27,117:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "POST /csvtodatabaseview/form HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/sessions.py", line 375, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/json/tag.py", line 296, in dumps
    return dumps(self.tag(value), separators=(',', ':'))
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/Users/alganas/.pyenv/versions/3.6.6/envs/vanila/lib/python3.6/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type OperationalError is not JSON serializable
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2018-11-11 17:07:27,133:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2018-11-11 17:07:27,134:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2018-11-11 17:07:27,134:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2018-11-11 17:07:27,163:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2018-11-11 17:07:27,211:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2018-11-11 17:07:27,262:INFO:werkzeug:127.0.0.1 - - [11/Nov/2018 17:07:27] "GET /csvtodatabaseview/form?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```
### Steps to reproduce

upload a csv file that have a field with date time formate  YYYY-MM-DDTHH:MM:SS

**Comment by aboganas** [comment]
sorry my mistake. the problem cause by missing quotations in text feilds.

closing it now
