### ISSUE TITLE
Out of bounds nanosecond timestamp

### ISSUE THREAD

**Issue by weiqiLee** [apache/incubator-superset#6446]
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.23.2

### Actual results
```
2018-11-27 04:54:20,096:ERROR:root:Out of bounds nanosecond timestamp: 2289-01-01 00:00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/tools/datetimes.py", line 303, in _convert_listlike
    values, tz = tslib.datetime_to_datetime64(arg)
  File "pandas/_libs/tslib.pyx", line 1884, in pandas._libs.tslib.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 325, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 162, in get_df
    df[DTTM_ALIAS], utc=False, format=timestamp_format)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/tools/datetimes.py", line 373, in to_datetime
    values = _convert_listlike(arg._values, True, format)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/tools/datetimes.py", line 306, in _convert_listlike
    raise e
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/tools/datetimes.py", line 294, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 2156, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 2339, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 2307, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 2301, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 1669, in pandas._libs.tslib.convert_datetime_to_tsobject
  File "pandas/_libs/tslib.pyx", line 1848, in pandas._libs.tslib._check_dts_bounds
pandas._libs.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2289-01-01 00:00:00
2018-11-27 04:54:20,098:ERROR:root:'NoneType' object has no attribute 'fillna'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/views/core.py", line 1059, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 293, in get_payload
    payload['data'] = self.get_data(df)
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 1139, in get_data
    df = self.process_data(df)
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 1044, in process_data
    df = df.fillna(0)
AttributeError: 'NoneType' object has no attribute 'fillna'
```

**Comment by mistercrunch** [comment]
`timestamp: 2289-01-01`? What does the data look like in the DB? This may be a pandas bug on their  `pandas.to_datetime` method.

**Comment by ofajardo** [comment]
Same problem here. I have in my databases dates such as 9999-12-31 (yes, it is on purpose, no it is not an error, no, it cannot be changed =) ) 

the problem can be easily reproduced as you said in pandas:

```python
>>> pandas.to_datetime('9999-12-31')
Traceback (most recent call last):
  File "/data/RWD_SHARE/MDH/APPS/superset_dev/supersetenv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 377, in _convert_listlike
    values, tz = conversion.datetime_to_datetime64(arg)
  File "pandas/_libs/tslibs/conversion.pyx", line 188, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/RWD_SHARE/MDH/APPS/superset_dev/supersetenv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 469, in to_datetime
    result = _convert_listlike(np.array([arg]), box, format)[0]
  File "/data/RWD_SHARE/MDH/APPS/superset_dev/supersetenv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 380, in _convert_listlike
    raise e
  File "/data/RWD_SHARE/MDH/APPS/superset_dev/supersetenv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 368, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 492, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 699, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 671, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 657, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslibs/np_datetime.pyx", line 121, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-12-31 00:00:00
```

The thing is obviously that you cannot convert such a date to datetime64[ns] as that one is defined in nanoseconds. It should remain as datetime.datetime or string or whatever it was originally.

I did a couple of quick changes on superset dataframe.py that solve it, but I don't know what is the consequence or if there is a better alternative.

I changed: 

```
pd.DataFrame(list(data), columns=self.column_names).infer_objects())
```

to

```
pd.DataFrame(list(data), columns=self.column_names)) # .infer_objects())
```

because that infer_objects is trying to convert to datetime64ns.
What is the consequence of doing this? Everything looks good in sqlab

and then I had to do yet another change:

```python
data = [dict((k, _maybe_box_datetimelike(v))
                for k, v in zip(self.df.columns, np.atleast_1d(row)))
                for row in self.df.values]
``` 

to

```
data = [dict((k, v)
                for k, v in zip(self.df.columns, np.atleast_1d(row)))
                for row in self.df.values]
```

because that _maybe_box_datetimelike (by the way in pandas 0.24 the underscore is removed, I am working with pandas 0.23 for now) merciless transforms to datetime64ns. 

I think I don't have datetimes with timezone information in my database so I hope it will be good for now ... or are these changes going to bite me very soon?

suggestions appreciated.

**Comment by puranikamey** [comment]
Is there any resolution on this issue?
