### ISSUE TITLE
filter_values macro is not working in 0.30

### ISSUE THREAD

**Issue by zoltantalas** [apache/incubator-superset#6521]
### Superset version

0.30

### Expected results

use filter_values macro like before (0.28,0.29)

there is no more a checkbox that the table is generated in sqllab.(like in previous versions) I guess it might cause the issue.

I checked the code and filter_values function is still there.

### Actual results
```
&#39;filter_values&#39; is undefined
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 329, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/viz.py", line 142, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 683, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 410, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 538, in get_sqla_query
    tbl = self.get_from_clause(template_processor, db_engine_spec)
  File "/usr/local/lib/python3.5/dist-packages/superset/connectors/sqla/models.py", line 434, in get_from_clause
    from_sql = template_processor.process_template(from_sql)
  File "/usr/local/lib/python3.5/dist-packages/superset/jinja_context.py", line 109, in process_template
    return template.render(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 32, in top-level template code
  File "/usr/local/lib/python3.5/dist-packages/jinja2/sandbox.py", line 425, in call
    if not __self.is_safe_callable(__obj):
  File "/usr/local/lib/python3.5/dist-packages/jinja2/sandbox.py", line 338, in is_safe_callable
    return not (getattr(obj, 'unsafe_callable', False) or
jinja2.exceptions.UndefinedError: 'filter_values' is undefined
```

**Comment by villebro** [comment]
@zoltantalas I was unable to reproduce this in both `master`and `0.30`. Can you add some more context on how you got this error?
