### ISSUE TITLE
AttributeError: 'MockConnection' object has no attribute 'run_callable'

### ISSUE THREAD

**Issue by shizidushu** [apache/incubator-superset#6583]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29.0rc7

### Expected results
no error

### Actual results
```
(venv) simon@Z370:~/git/test/incubator-superset-0.29.0rc7$ flask db upgrade --sql
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Generating static SQL
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

INFO  [alembic.runtime.migration] Running upgrade  -> 4e6a06bad7a8, Init
-- Running upgrade  -> 4e6a06bad7a8

CREATE TABLE clusters (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    cluster_name VARCHAR(250), 
    coordinator_host VARCHAR(255), 
    coordinator_port INTEGER, 
    coordinator_endpoint VARCHAR(255), 
    broker_host VARCHAR(255), 
    broker_port INTEGER, 
    broker_endpoint VARCHAR(255), 
    metadata_last_refreshed DATETIME, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    UNIQUE (cluster_name), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE dashboards (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    dashboard_title VARCHAR(500), 
    position_json TEXT, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE dbs (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    database_name VARCHAR(250), 
    sqlalchemy_uri VARCHAR(1024), 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    UNIQUE (database_name), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE datasources (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    datasource_name VARCHAR(255), 
    is_featured BOOLEAN, 
    is_hidden BOOLEAN, 
    description TEXT, 
    default_endpoint TEXT, 
    user_id INTEGER, 
    cluster_name VARCHAR(250), 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    UNIQUE (datasource_name), 
    CHECK (is_featured IN (0, 1)), 
    CHECK (is_hidden IN (0, 1)), 
    FOREIGN KEY(user_id) REFERENCES ab_user (id), 
    FOREIGN KEY(cluster_name) REFERENCES clusters (cluster_name), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE tables (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    table_name VARCHAR(250), 
    main_dttm_col VARCHAR(250), 
    default_endpoint TEXT, 
    database_id INTEGER NOT NULL, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    UNIQUE (table_name), 
    FOREIGN KEY(database_id) REFERENCES dbs (id), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE columns (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    datasource_name VARCHAR(255), 
    column_name VARCHAR(255), 
    is_active BOOLEAN, 
    type VARCHAR(32), 
    groupby BOOLEAN, 
    count_distinct BOOLEAN, 
    sum BOOLEAN, 
    max BOOLEAN, 
    min BOOLEAN, 
    filterable BOOLEAN, 
    description TEXT, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    CHECK (is_active IN (0, 1)), 
    CHECK (groupby IN (0, 1)), 
    CHECK (count_distinct IN (0, 1)), 
    CHECK (sum IN (0, 1)), 
    CHECK (max IN (0, 1)), 
    CHECK (min IN (0, 1)), 
    CHECK (filterable IN (0, 1)), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE metrics (
    id INTEGER NOT NULL, 
    metric_name VARCHAR(512), 
    verbose_name VARCHAR(1024), 
    metric_type VARCHAR(32), 
    datasource_name VARCHAR(255), 
    json TEXT, 
    description TEXT, 
    PRIMARY KEY (id), 
    FOREIGN KEY(datasource_name) REFERENCES datasources (datasource_name), 
    FOREIGN KEY(datasource_name) REFERENCES datasources (datasource_name)
);

CREATE TABLE slices (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    slice_name VARCHAR(250), 
    druid_datasource_id INTEGER, 
    table_id INTEGER, 
    datasource_type VARCHAR(200), 
    datasource_name VARCHAR(2000), 
    viz_type VARCHAR(250), 
    params TEXT, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(druid_datasource_id) REFERENCES datasources (id), 
    FOREIGN KEY(table_id) REFERENCES tables (id), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE sql_metrics (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    metric_name VARCHAR(512), 
    verbose_name VARCHAR(1024), 
    metric_type VARCHAR(32), 
    table_id INTEGER, 
    expression TEXT, 
    description TEXT, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(table_id) REFERENCES tables (id), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE table_columns (
    created_on DATETIME NOT NULL, 
    changed_on DATETIME NOT NULL, 
    id INTEGER NOT NULL, 
    table_id INTEGER, 
    column_name VARCHAR(255), 
    is_dttm BOOLEAN, 
    is_active BOOLEAN, 
    type VARCHAR(32), 
    groupby BOOLEAN, 
    count_distinct BOOLEAN, 
    sum BOOLEAN, 
    max BOOLEAN, 
    min BOOLEAN, 
    filterable BOOLEAN, 
    description TEXT, 
    created_by_fk INTEGER, 
    changed_by_fk INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(table_id) REFERENCES tables (id), 
    CHECK (is_dttm IN (0, 1)), 
    CHECK (is_active IN (0, 1)), 
    CHECK (groupby IN (0, 1)), 
    CHECK (count_distinct IN (0, 1)), 
    CHECK (sum IN (0, 1)), 
    CHECK (max IN (0, 1)), 
    CHECK (min IN (0, 1)), 
    CHECK (filterable IN (0, 1)), 
    FOREIGN KEY(created_by_fk) REFERENCES ab_user (id), 
    FOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)
);

CREATE TABLE dashboard_slices (
    id INTEGER NOT NULL, 
    dashboard_id INTEGER, 
    slice_id INTEGER, 
    PRIMARY KEY (id), 
    FOREIGN KEY(dashboard_id) REFERENCES dashboards (id), 
    FOREIGN KEY(slice_id) REFERENCES slices (id)
);

INSERT INTO alembic_version (version_num) VALUES ('4e6a06bad7a8');

INFO  [alembic.runtime.migration] Running upgrade 4e6a06bad7a8 -> 5a7bad26f2a7, empty message
-- Running upgrade 4e6a06bad7a8 -> 5a7bad26f2a7

ALTER TABLE dashboards ADD COLUMN css TEXT;

ALTER TABLE dashboards ADD COLUMN description TEXT;

UPDATE alembic_version SET version_num='5a7bad26f2a7' WHERE alembic_version.version_num = '4e6a06bad7a8';

INFO  [alembic.runtime.migration] Running upgrade 5a7bad26f2a7 -> 1e2841a4128, empty message
-- Running upgrade 5a7bad26f2a7 -> 1e2841a4128

ALTER TABLE table_columns ADD COLUMN expression TEXT;

UPDATE alembic_version SET version_num='1e2841a4128' WHERE alembic_version.version_num = '5a7bad26f2a7';

INFO  [alembic.runtime.migration] Running upgrade 1e2841a4128 -> 2929af7925ed, TZ offsets in data sources
-- Running upgrade 1e2841a4128 -> 2929af7925ed

ALTER TABLE datasources ADD COLUMN "offset" INTEGER;

ALTER TABLE tables ADD COLUMN "offset" INTEGER;

UPDATE alembic_version SET version_num='2929af7925ed' WHERE alembic_version.version_num = '1e2841a4128';

INFO  [alembic.runtime.migration] Running upgrade 2929af7925ed -> 289ce07647b, Add encrypted password field
-- Running upgrade 2929af7925ed -> 289ce07647b

ALTER TABLE dbs ADD COLUMN password BLOB;

UPDATE alembic_version SET version_num='289ce07647b' WHERE alembic_version.version_num = '2929af7925ed';

INFO  [alembic.runtime.migration] Running upgrade 289ce07647b -> 1a48a5411020, adding slug to dash
-- Running upgrade 289ce07647b -> 1a48a5411020

ALTER TABLE dashboards ADD COLUMN slug VARCHAR(255);

UPDATE alembic_version SET version_num='1a48a5411020' WHERE alembic_version.version_num = '289ce07647b';

INFO  [alembic.runtime.migration] Running upgrade 1a48a5411020 -> 315b3f4da9b0, adding log model
-- Running upgrade 1a48a5411020 -> 315b3f4da9b0

CREATE TABLE logs (
    id INTEGER NOT NULL, 
    action VARCHAR(512), 
    user_id INTEGER, 
    json TEXT, 
    dttm DATETIME, 
    PRIMARY KEY (id), 
    FOREIGN KEY(user_id) REFERENCES ab_user (id)
);

UPDATE alembic_version SET version_num='315b3f4da9b0' WHERE alembic_version.version_num = '1a48a5411020';

INFO  [alembic.runtime.migration] Running upgrade 315b3f4da9b0 -> 55179c7f25c7, sqla_descr
-- Running upgrade 315b3f4da9b0 -> 55179c7f25c7

ALTER TABLE tables ADD COLUMN description TEXT;

UPDATE alembic_version SET version_num='55179c7f25c7' WHERE alembic_version.version_num = '315b3f4da9b0';

INFO  [alembic.runtime.migration] Running upgrade 55179c7f25c7 -> 12d55656cbca, is_featured
-- Running upgrade 55179c7f25c7 -> 12d55656cbca

ALTER TABLE tables ADD COLUMN is_featured BOOLEAN;

/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/util/messaging.py:69: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  warnings.warn(msg)
UPDATE alembic_version SET version_num='12d55656cbca' WHERE alembic_version.version_num = '55179c7f25c7';

INFO  [alembic.runtime.migration] Running upgrade 12d55656cbca -> 2591d77e9831, user_id
-- Running upgrade 12d55656cbca -> 2591d77e9831

Traceback (most recent call last):
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/superset/migrations/env.py", line 98, in <module>
    run_migrations_offline()
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/superset/migrations/env.py", line 49, in run_migrations_offline
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/superset/migrations/versions/2591d77e9831_user_id.py", line 20, in upgrade
    batch_op.create_foreign_key('user_id', 'ab_user', ['user_id'], ['id'])
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/operations/base.py", line 300, in batch_alter_table
    impl.flush()
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/alembic/operations/batch.py", line 69, in flush
    *self.reflect_args, **self.reflect_kwargs)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 456, in __new__
    metadata._remove_table(name, schema)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 451, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 533, in _init
    include_columns, _extend_on=_extend_on)
  File "/home/simon/git/test/incubator-superset-0.29.0rc7/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 543, in _autoload
    autoload_with.run_callable(
AttributeError: 'MockConnection' object has no attribute 'run_callable'

```

### Steps to reproduce
```
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
pip install -r requirements-dev.txt
export FLASK_ENV=development
flask db upgrade --sql
```

**Comment by mistercrunch** [comment]
It trips on the line that goes `batch_op.create_foreign_key('user_id', 'ab_user', ['user_id'], ['id'])` in `superset/migrations/versions/2591d77e9831_user_id.py`. Which database engine are you using?

**Comment by shizidushu** [comment]
sqlite

**Comment by mistercrunch** [comment]
We build against sqlite on Travis, so there has to be something else that's funky about your setup...

**Comment by agrzegorczyk-leonsoftware** [comment]
@shizidushu 
I encountered the same problem, in my case, this was a solution:
https://alembic.sqlalchemy.org/en/latest/batch.html#batch-offline-mode
