### ISSUE TITLE
Docker: TestConnection MonetDB: Cannot load plugin 

### ISSUE THREAD

**Issue by JanHuege** [apache/incubator-superset#6664]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
Latest from github: 10. Jan 2019

### Expected results
Plugin gets recognized and connection works or I get an errormessage from the monetdb connector

### Actual results
Alert: ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n__init__() missing 1 required positional argument: 'database'"}

Stacktrace:
```
superset_1  | Traceback (most recent call last):
superset_1  |   File "/home/superset/superset/views/core.py", line 1760, in testconn
superset_1  |     engine.connect()
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
superset_1  |     return self._connection_cls(self, **kwargs)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
superset_1  |     if connection is not None else engine.raw_connection()
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
superset_1  |     self.pool.unique_connection, _connection)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
superset_1  |     return fn()
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 345, in unique_connection
superset_1  |     return _ConnectionFairy._checkout(self)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 782, in _checkout
superset_1  |     fairy = _ConnectionRecord.checkout(pool)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
superset_1  |     rec = pool._do_get()
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1089, in _do_get
superset_1  |     c = self._create_connection()
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
superset_1  |     return _ConnectionRecord(self)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
superset_1  |     self.__connect(first_connect_check=True)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 667, in __connect
superset_1  |     connection = pool._invoke_creator(self)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
superset_1  |     return dialect.connect(*cargs, **cparams)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 410, in connect
superset_1  |     return self.dbapi.connect(*cargs, **cparams)
superset_1  |   File "/usr/local/lib/python3.6/site-packages/pymonetdb/__init__.py", line 48, in connect
superset_1  |     return Connection(*args, **kwargs)
superset_1  | TypeError: __init__() missing 1 required positional argument: 'database'
superset_1  | 192.168.105.45 - - [11/Jan/2019 12:17:53] "POST /superset/testconn HTTP/1.1" 500 -
superset_1  | 2019-01-11 12:17:53,950:INFO:werkzeug:192.168.105.45 - - [11/Jan/2019 12:17:53] "POST /superset/testconn HTTP/1.1" 500 -
```

### Steps to reproduce
Inside superset container:
pip install sqlalchemy_monetdb
(see https://github.com/gijzelaerr/sqlalchemy-monetdb)
Add Datasource: monetdb://xxx:50000
OR: monetdb+monetdb://xxx:50000 ; monetdb+sqlalchemy_monetdb://xxx:50000

**Comment by villebro** [comment]
Looks like monetdb isn't yet added to `db_engine_specs.py`. It should be easy to add if you feel up to the challenge! I can help if needed.

**Comment by JanHuege** [comment]
My knowledge of monetDB is limited. I just wanted to test it with superset since the docs stated that is possible. I don't feel that confident adding the required mappings for MonetDB specific stuff.
