### ISSUE TITLE
how do we configure superset to use RDS MYSQL (AWS) insted of sqlite database 

### ISSUE THREAD

**Issue by 22vibhutigoel** [apache/incubator-superset#6715]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by 22vibhutigoel** [comment]
my superset version is Version: 0.28.1
Python 3.6.0

**Comment by 22vibhutigoel** [comment]
got beloow error : 

Traceback (most recent call last):
  File "/home/ubuntu/MYVENV/bin/superset", line 6, in <module>
    from superset.cli import create_app
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/superset/__init__.py", line 115, in <module>
    utils.pessimistic_connection_handling(db.engine)
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 559, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ubuntu/MYVENV/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb' 

i have changes below is value in config.py
```SQLALCHEMY_DATABASE_URI = 'mysql://root:password@RDS_HOST_URL:3306/test'```

**Comment by jp-tri** [comment]
I think you're just missing the database dependency for MySQL. Try the following:

```
$ pip install mysqlclient
```

[reference](https://superset.incubator.apache.org/installation.html#database-dependencies)
