### ISSUE TITLE
docker-compose run fails with "Multiple head revisions are present"

### ISSUE THREAD

**Issue by ilyaminati** [apache/incubator-superset#6728]
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

commit 00388811b6e5ea56c8e3c92428d6cd805a98c8d1

### Expected results

This command succeeds, as per installation instructions:

`docker-compose run --rm superset ./docker-init.sh`

### Actual results

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 336, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 445, in _resolve_revision_number
    current_head = self.get_current_head(branch_label)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 271, in get_current_head
    "%s@head" % branch_label if branch_label else "head")
alembic.script.revision.MultipleHeads: Multiple heads are present for given argument 'head'; 8b70aa3d0f87, a33a03f16c4a

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/superset/superset/bin/superset", line 15, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/superset/superset/migrations/env.py", line 116, in <module>
    run_migrations_online()
  File "/home/superset/superset/migrations/env.py", line 109, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 340, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 168, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(multiple_heads))
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 336, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 445, in _resolve_revision_number
    current_head = self.get_current_head(branch_label)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 271, in get_current_head
    "%s@head" % branch_label if branch_label else "head")
alembic.util.exc.CommandError: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads

### Steps to reproduce

`docker-compose run --rm superset ./docker-init.sh`

**Comment by bolkedebruin** [comment]
https://stackoverflow.com/questions/22342643/alembic-revision-multiple-heads-due-branching-error

**Comment by bolkedebruin** [comment]
a clean build and rebase to master probably clears this up, as master builds on travis

**Comment by ilyaminati** [comment]
Yup, the tree must've been temporarily borked somehow, the error cleared up after a pull.
