### ISSUE TITLE
superset fails to auto-detect time field from druid as sql

### ISSUE THREAD

**Issue by donbowman** [apache/incubator-superset#6853]
Using druid 0.13.0
Using superset 'master'
Using sql as the datasource rather than the druid native one.

Any time series charts get:
`"Datetime column not provided as part table configuration and is required by this type of chart"`

If I manually set __time as main datetime when i create the datasource, it works.

I think this could auto-add the __time as temporal.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 410, in get_df_payload
    df = self.get_df(query_obj)
  File "/usr/local/lib/python3.7/site-packages/superset/viz.py", line 213, in get_df
    self.results = self.datasource.query(query_obj)
  File "/usr/local/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 799, in query
    sql = self.get_query_str(query_obj)
  File "/usr/local/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 473, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/usr/local/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 579, in get_sqla_query
    'Datetime column not provided as part table configuration '
Exception: Datetime column not provided as part table configuration and is required by this type of chart
```

**Comment by quantd2** [comment]
sorry to jump in a closed one but I have installed the latest release at: https://pypi.org/project/apache-superset/ but the problem still happens

**Comment by mehtajay1** [comment]
@mistercrunch 
 I have installed the latest release at: https://pypi.org/project/apache-superset/ but am still facing the same issue.
