### ISSUE TITLE
JSON generation crash in Sankey Diagram

### ISSUE THREAD

**Issue by ruber0id** [apache/incubator-superset#7026]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.29rc7 (the last one published via Pypi)

### Actual results
The chart block raise TypeError with the following stacktrace not only for example data but also for other tables:
```Traceback (most recent call last):
  File "/root/superset/lib/python3.7/site-packages/superset/views/base.py", line 96, in wraps
    return f(self, *args, **kwargs)
  File "/root/superset/lib/python3.7/site-packages/superset/views/core.py", line 1211, in explore_json
    samples=samples,
  File "/root/superset/lib/python3.7/site-packages/superset/views/core.py", line 1142, in generate_json
    payload = viz_obj.get_payload()
  File "/root/superset/lib/python3.7/site-packages/superset/viz.py", line 374, in get_payload
    payload['data'] = self.get_data(df)
  File "/root/superset/lib/python3.7/site-packages/superset/viz.py", line 1606, in get_data
    df['source'] = df['source'].astype(basestring)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/generic.py", line 5691, in astype
    **kwargs)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 534, in astype
    **kwargs)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 595, in _astype
    dtype = pandas_dtype(dtype)
  File "/root/superset/lib/python3.7/site-packages/pandas/core/dtypes/common.py", line 2029, in pandas_dtype
    raise TypeError("dtype '{}' not understood".format(dtype))
TypeError: dtype '<class 'past.types.basestring.basestring'>' not understood
```
![Sankey Diagram](https://i.imgur.com/XpSl8G0.png)
### Environment
```
Ubuntu 18.04
python==3.7.1
pandas==0.24.1
```

**Comment by AShyPig** [comment]
pandas==0.20.3，can be solved

**Comment by mistercrunch** [comment]
If this is still an issue in master, I think it could be addressed by adding a condition for `basestring` in `superset.utils.core.base_json_conv`

**Comment by syafiqdante** [comment]
Sorry to disturb an closed issue, I have the exact same problem with sanskey chart and downgrading pandas to pandas==0.20.3 doesn't solve it...
```
2019-08-20 09:35:34,392:ERROR:root:dtype '<class 'past.types.basestring.basestring'>' not understood
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/superset/views/core.py", line 1149, in generate_json
    payload = viz_obj.get_payload()
  File "/root/venv/lib/python3.6/site-packages/superset/viz.py", line 371, in get_payload
    payload['data'] = self.get_data(df)
  File "/root/venv/lib/python3.6/site-packages/superset/viz.py", line 1597, in get_data
    df['source'] = df['source'].astype(basestring)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5691, in astype
    **kwargs)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 534, in astype
    **kwargs)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 595, in _astype
    dtype = pandas_dtype(dtype)
  File "/root/venv/lib/python3.6/site-packages/pandas/core/dtypes/common.py", line 2029, in pandas_dtype
    raise TypeError("dtype '{}' not understood".format(dtype))
TypeError: dtype '<class 'past.types.basestring.basestring'>' not understood
```
Does anyone has the solution..?
Help is very much appreciated.
