### ISSUE TITLE
Filter Box isue on pt_BR language

### ISSUE THREAD

**Issue by lucasapaixao** [apache/incubator-superset#7134]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
0.28.1

### Expected results
A translation of filterbox chart

### Actual results
When you apply the pt_BR translation in the Filter Box Chart, it crash with the following message:

PS: In English language does not occur the error

SyntaxError: [sprintf] unexpected placeholder
    at http://10.18.200.102/static/assets/dist/explore.d3beaf73a661104a3627.entry.js:2:812937
    at a (http://10.18.200.102/static/assets/dist/explore.d3beaf73a661104a3627.entry.js:2:813517)
    at c (http://10.18.200.102/static/assets/dist/explore.d3beaf73a661104a3627.entry.js:2:64486)
    at f (http://10.18.200.102/static/assets/dist/explore.d3beaf73a661104a3627.entry.js:2:64798)
    at http://10.18.200.102/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:365206
    at Array.map (<anonymous>)
    at t.<anonymous> (http://10.18.200.102/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:364863)
    at t.<anonymous> (http://10.18.200.102/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:365985)
    at Qi (http://10.18.200.102/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1384797)
    at Xi (http://10.18.200.102/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1384639)

![filterbox](https://user-images.githubusercontent.com/48967533/55034854-3f5aae00-4ff5-11e9-8a1d-ab97f7a8f6af.png)

![filterbox-2](https://user-images.githubusercontent.com/48967533/55035009-9d879100-4ff5-11e9-81a9-a417b0e823a5.png)

### Steps to reproduce
1) Use the EN transalate and create a Filter Box chart
2) Modify the language to pt_BR(Brazilian Portuguese) and the Filter Box will crach.

Ps: Sorry for any translation error.

**Comment by lucasapaixao** [comment]
I found several invalid entries in files messages.json and messages.po, basicly i searched for string % s(with a space between the caracthers) and repacle for %s.
After the change i runned  "pybabel compile -d translations" in superset folder and restart the daemon. 

Reference for solution: https://github.com/apache/incubator-superset/pull/7161/commits/90446298ba7163020dc3c22011180397bcb1985d

**Comment by mistercrunch** [comment]
Just a thought, we should have some sort of continuous integration validating these `.po` files...
