### ISSUE TITLE
Click charts got exception 

### ISSUE THREAD

**Issue by ans76** [apache/incubator-superset#7308]
```
Traceback (most recent call last):
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/views.py", line 478, in list
    widgets=widgets)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 161, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 12, in block "content"
    {% block list_list scoped %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 13, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/widgets.py", line 34, in __call__
    return template.render(args)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/superset/fab_overrides/list.html", line 1, in top-level template code
    {% extends 'appbuilder/general/widgets/list.html' %}
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/widgets/base_list.html", line 25, in top-level template code
    {% block begin_loop_values %}
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/runtime.py", line 435, in __init__
    self._after = self._safe_next()
  File "/opt/py3-superset/lib/python3.6/site-packages/jinja2/runtime.py", line 455, in _safe_next
    return next(self._iterator)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/models/base.py", line 114, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/opt/py3-superset/lib/python3.6/site-packages/flask_appbuilder/models/base.py", line 66, in _get_attr_value
    return getattr(item, col)()
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/models/core.py", line 181, in datasource_link
    return datasource.link if datasource else None
  File "/opt/py3-superset/lib/python3.6/site-packages/superset/connectors/druid/models.py", line 532, in link
    return Markup('<a href="{self.url}">{name}</a>').format(**locals())
TypeError: format() got multiple values for argument 'self'
```

**Comment by ans76** [comment]
#6347

**Comment by ans76** [comment]
Upgrade to 0.29.0 could solve this.

**Comment by aoeiuvb** [comment]
@ans76 
The issue still exists in 0.29

**Comment by ArchanaSekhar20** [comment]
Click on chart give exception still exist.
chart/add gives internal server error. please help with a solution
