### ISSUE TITLE
Error after installation, no user_attribute table

### ISSUE THREAD

**Issue by Exentriq** [apache/incubator-superset#7354]
Dear All, 

after the installation of Superset (following this guide, https://superset.incubator.apache.org/installation.html - I've Ubuntu 18.04 server with latest updates) I got an error after the login:

```
sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_attribute
[SQL: SELECT user_attribute.welcome_dashboard_id AS user_attribute_welcome_dashboard_id 
FROM user_attribute 
WHERE user_attribute.user_id = ?]
[parameters: ('1',)]
(Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
cursor, statement, parameters, context
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
cursor.execute(statement, parameters)
The above exception was the direct cause of the following exception:
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/root/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/root/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/root/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/venv/lib/python3.6/site-packages/superset/views/core.py", line 2768, in welcome
.filter_by(user_id=g.user.get_id())
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3305, in scalar
ret = self.one()
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3275, in one
ret = self.one_or_none()
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
ret = list(self)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
return self._execute_and_instances(context)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
return meth(self, multiparams, params)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
distilled_params,
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
e, statement, parameters, cursor, context
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
util.raise_from_cause(sqlalchemy_exception, exc_info)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
raise value.with_traceback(tb)
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
cursor, statement, parameters, context
File "/root/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_attribute [SQL: SELECT user_attribute.welcome_dashboard_id AS user_attribute_welcome_dashboard_id FROM user_attribute WHERE user_attribute.user_id = ?] [parameters: ('1',)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

Going into an internal page it is working, so I can manage my dashboards and use for example MySQL (adding it as source).
I saw through SQL Lab that there isn't the user_attribute table.

how I can I fix this?
I tried to run:
`superset db upgrade`
but nothing happens, this table still does not exist.

I tried also to set PYTHONPATH before run that command:
`export PYTHONPATH='/root/venv/lib/python3.6/'
echo $PYTHONPATH
/root/venv/lib/python3.6/`

but still the same error:

> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume transactional DDL.
> INFO  [alembic.runtime.migration] Running upgrade bddc498dd179 -> 4451805bbaa1, remove double percents
> Traceback (most recent call last):
>   File "/root/venv/bin/superset", line 15, in <module>
>     cli()
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/flask/cli.py", line 380, in main
>     return AppGroup.main(self, *args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/flask/cli.py", line 257, in decorator
>     return __ctx.invoke(f, *args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
>     _upgrade(directory, revision, sql, tag, x_arg)
>   File "/root/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
>     f(*args, **kwargs)
>   File "/root/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
>     command.upgrade(config, revision, sql=sql, tag=tag)
>   File "/root/venv/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
>     script.run_env()
>   File "/root/venv/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
>     util.load_python_file(self.dir, "env.py")
>   File "/root/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
>     module = load_module_py(module_id, path)
>   File "/root/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/root/venv/lib/python3.6/site-packages/superset/migrations/env.py", line 100, in <module>
>     run_migrations_online()
>   File "/root/venv/lib/python3.6/site-packages/superset/migrations/env.py", line 93, in run_migrations_online
>     context.run_migrations()
>   File "<string>", line 8, in run_migrations
>   File "/root/venv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
>     self.get_context().run_migrations(**kw)
>   File "/root/venv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
>     step.migration_fn(**kw)
>   File "/root/venv/lib/python3.6/site-packages/superset/migrations/versions/4451805bbaa1_remove_double_percents.py", line 82, in upgrade
>     replace('%%', '%')
>   File "/root/venv/lib/python3.6/site-packages/superset/migrations/versions/4451805bbaa1_remove_double_percents.py", line 53, in replace
>     .join(Table)
>   File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2235, in join
>     from_joinpoint=from_joinpoint,
>   File "<string>", line 2, in _join
>   File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/base.py", line 220, in generate
>     fn(self, *args[1:], **kw)
>   File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2414, in _join
>     left, right, onclause, prop, create_aliases, outerjoin, full
>   File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
>     ) = self._join_determine_implicit_left_side(left, right, onclause)
>   File "/root/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
>     "Can't determine which FROM clause to join "
> sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.

**Comment by Exentriq** [comment]
Solved with:
`pip install sqlalchemy==1.2.18`
