### ISSUE TITLE
Sometimes the following error occurs (sqlalchemy.exc.NoSuchColumnError)

### ISSUE THREAD

**Issue by cscainiao** [apache/incubator-superset#7401]
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: [e.g. `v0.29`, `master`, `commit`]
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cscainiao** [comment]
in the master branch

**Comment by cscainiao** [comment]
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
         Traceback (most recent call last):
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 25, in wraps
    if self.appbuilder.sm.has_access(permission_str, self.__class__.__name__):
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 892, in has_access
    return self._has_view_access(g.user, permission_name, view_name)
  File "/root/superset/superset_env/lib/python3.7/site-packages/flask_appbuilder/security/manager.py", line 878, in _has_view_access
    roles = user.roles
  File "/root/superset/superset_env/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 682, in get
    value = self.callable_(state, passive)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 723, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 865, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 531, in all
    return list(self)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 508, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 508, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/root/superset/superset_env/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 629, in _key_fallback
    % expression._string_or_unprintable(key)
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'ab_role.id'"

**Comment by francisliyy** [comment]
Hi, has this bug got fixed?

**Comment by cscainiao** [comment]
uwsgi cfg file add         

lazy-apps = true
