### ISSUE TITLE
Exporting Datasource to YAML fails

### ISSUE THREAD

**Issue by rjurney** [apache/incubator-superset#7437]
Exporting the main sqlite database to YAML via the List Databases interface and its Export to YAML option fails with the error `TypeError: '<' not supported between instances of 'dict' and 'dict'`.

### Expected results

I expect to receive a YAML file.

### Actual results

```bash
2019-05-02 21:28:47,467:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:28:47] "GET /databaseview/list/ HTTP/1.1" 200 -
2019-05-02 21:28:48,209:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:28:48] "GET /superset/csrf_token/ HTTP/1.1" 200 -
g2019-05-02 21:37:49,117:INFO:werkzeug:127.0.0.1 - - [02/May/2019 21:37:49] "POST /databaseview/action_post HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rjurney/Software/incubator-superset/venv/lib/python3.6/site-packages/flask_appbuilder/views.py", line 578, in action_post
    return action.func(items)
  File "/Users/rjurney/Software/incubator-superset/superset/views/base.py", line 195, in yaml_export
    data = [t.export_to_dict() for t in items]
  File "/Users/rjurney/Software/incubator-superset/superset/views/base.py", line 195, in <listcomp>
    data = [t.export_to_dict() for t in items]
  File "/Users/rjurney/Software/incubator-superset/superset/models/helpers.py", line 215, in export_to_dict
    key=lambda k: sorted(k.items()))
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

#### How to reproduce the bug

1. Go to `/databaseview/list/`
2. Click on the checkbox for the 'main' database
3. Select the 'Actions' menu
4. Click on 'Export to YAML'
5. Click 'OK'
6. See error

### Environment

(please complete the following information):

- superset version: [e.g. `v0.31`, `release--0.31`, `700cbf4f`]
- python version: `Python 3.6.7`
- node.js version: `v11.6.0`
- npm version: `6.5.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Aylr** [comment]
I have a tiny PR that fixes this: https://github.com/apache/incubator-superset/pull/7728
