### ISSUE TITLE
UnicodeEncodeError issue while open the role tab

### ISSUE THREAD

**Issue by aibati2008** [apache/incubator-superset#751]
## **I met the UnicodeEncodeError while open the role tab, can anyone give the solution? thanks!**

```
UnicodeEncodeError
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-16: ordinal not in range(128)

Traceback (most recent call last)
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist:  create paste
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/views.py", line 453, in list
    widgets=widgets)
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 158, in render_template
    return render_template(template, **dict(list(kwargs.items()) + list(self.extra_args.items())))
  File "/root/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/root/anaconda2/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/root/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/root/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/root/anaconda2/lib/python2.7/site-packages/caravel/templates/caravel/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/root/anaconda2/lib/python2.7/site-packages/caravel/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/root/anaconda2/lib/python2.7/site-packages/caravel/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 7, in block "content"
    {% block list_search scoped %}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 8, in block "list_search"
    {% call lib.accordion_tag("accordion1",_("Search"), False) %}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/lib.html", line 254, in template
    {{ caller() }}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/templates/appbuilder/general/model/list.html", line 9, in template
    {{ widgets.get('search')()|safe }}
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/widgets.py", line 108, in __call__
    form_fields[col] = self.template_args['form'][col]()
  File "/root/anaconda2/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/fieldwidgets.py", line 174, in __call__
    return super(Select2ManyWidget, self).__call__(field, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/wtforms/widgets/core.py", line 288, in __call__
    html.append(self.render_option(val, label, selected))
  File "/root/anaconda2/lib/python2.7/site-packages/wtforms/widgets/core.py", line 301, in render_option
    return HTMLString('<option %s>%s</option>' % (html_params(**options), escape(text_type(label), quote=False)))
  File "/root/anaconda2/lib/python2.7/site-packages/flask_appbuilder/security/sqla/models.py", line 45, in __repr__
    return str(self.permission).replace('_', ' ') + ' on ' + str(self.view_menu)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-16: ordinal not in range(128)
```

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 622 days. Feel free to comment and request for this issue to be reopened.
