### ISSUE TITLE
Admin and alpha account cannot access dashboard

### ISSUE THREAD

**Issue by mashciku** [apache/incubator-superset#7923]
Superset version 0.28.1
python version 3.6.7

I have been using the admin account to access dashboards for some time and it has been working well till recently when I noticed that both admin and alpha accounts cannot access the dashboard. Gamma accounts however can do this. I also cannot save charts to dashboards, if I try it mentions 'fetching dashboards failed for 2'. 

![Screenshot (9)](https://user-images.githubusercontent.com/29142200/61874930-34a41d00-aef2-11e9-8c78-f0b203beb21a.png)
![Screenshot (10)](https://user-images.githubusercontent.com/29142200/61874939-38d03a80-aef2-11e9-8f36-e209580dcceb.png)
![Screenshot (11)](https://user-images.githubusercontent.com/29142200/61874946-3cfc5800-aef2-11e9-82bd-cfcaf3195b2d.png)

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment]
Hi @mashciku,

Please post the stacktrace as text. And send the metadata for the dashboard (at least the json_metadata field)

**Comment by mashciku** [comment]
Here it is; this is the error I get every time I try to access the dashboard using alpha and admin accounts or if I try to add charts to new dashboards


2019-08-14 12:54:10,370:INFO:werkzeug:41.215.58.118 - - [14/Aug/2019 12:54:10] "GET /dashboard/list/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 123, in wraps
    return f(self, *args, **kwargs)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/views.py", line 531, in list
    self.list_template, title=self.list_title, widgets=widgets
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 224, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 2, in top-level template code
    {% import 'appbuilder/general/lib.html' as lib %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/superset/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/baselayout.html", line 21, in block "body"
    {% block content %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 12, in block "content"
    {% block list_list scoped %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/model/list.html", line 13, in block "list_list"
    {{ widgets.get('list')()|safe }}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/widgets.py", line 37, in __call__
    return template.render(args)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/superset/fab_overrides/list.html", line 1, in top-level template code
    {% extends 'appbuilder/general/widgets/list.html' %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 2, in top-level template code
    {% extends 'appbuilder/general/widgets/base_list.html' %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/templates/appbuilder/general/widgets/base_list.html", line 25, in top-level template code
    {% block begin_loop_values %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/templates/appbuilder/general/widgets/list.html", line 45, in block "begin_loop_values"
    {% for item in value_columns %}
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/runtime.py", line 478, in __next__
    ctx._after = ctx._safe_next()
  File "/home/cmacharia/superset/lib/python3.6/site-packages/jinja2/runtime.py", line 455, in _safe_next
    return next(self._iterator)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/models/base.py", line 124, in get_values
    retdict[col] = self._get_attr_value(item, col)
  File "/home/cmacharia/superset/lib/python3.6/site-packages/flask_appbuilder/models/base.py", line 76, in _get_attr_value
    return getattr(item, col)()
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/models/core.py", line 412, in dashboard_link
    '<a href="{self.url}">{title}</a>'.format(**locals()))
  File "/home/cmacharia/superset/lib/python3.6/site-packages/superset/models/core.py", line 387, in url
    default_filters = json_metadata.get('default_filters')
AttributeError: 'int' object has no attribute 'get'
2019-08-14 12:54:10,397:INFO:werkzeug:41.72.199.38 - - [14/Aug/2019 12:54:10] "GET /dashboard/list/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-08-14 12:54:10,406:INFO:werkzeug:41.215.58.118 - - [14/Aug/2019 12:54:10] "GET /dashboard/list/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-08-14 12:54:10,502:INFO:werkzeug:41.72.199.38 - - [14/Aug/2019 12:54:10] "GET /dashboard/list/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-08-14 12:54:11,524:INFO:werkzeug:41.215.58.118 - - [14/Aug/2019 12:54:11] "GET /dashboard/list/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-08-14 12:54:11,646:INFO:werkzeug:41.215.58.118 - - [14/Aug/2019 12:54:11] "GET /dashboard/list/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
