### ISSUE TITLE
Time-series Period Pivot - DateOffset objects are immutable

### ISSUE THREAD

**Issue by AndLLA** [apache/incubator-superset#7966]
Time-series Period from trunk is no more functional (used to work a couple of weeks ago),
The chart fails with the stack trace below.

Traceback (most recent call last):
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/base.py", line 121, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/core.py", line 1119, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/core.py", line 1046, in generate_json
    payload = viz_obj.get_payload()
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/viz.py", line 379, in get_payload
    payload["data"] = self.get_data(df)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/viz.py", line 1401, in get_data
    freq.normalize = True
  File "pandas/_libs/tslibs/offsets.pyx", line 332, in pandas._libs.tslibs.offsets._BaseOffset.__setattr__
**AttributeError: DateOffset objects are immutable.**

**Comment by villebro** [comment]
It seems `DateOffset` has been made immutable in pandas 0.24, and there was is no obvious solution to making the `normalize` attribute `True`. Let me think about this for a sec to see how it can be solved.

**Comment by AndLLA** [comment]
The chart is now working,
however in my setup the results are strange (time grain=day, last quarter, metric=count(*), freq=1week start monday)
The chart shows all points stuck on the first day of the week (no lines).

<img width="324" alt="Screen Shot 2019-08-03 at 10 35 12" src="https://user-images.githubusercontent.com/44858649/62409617-74e25a00-b5da-11e9-9226-1ce4671a38a0.png">

**Comment by villebro** [comment]
FYI @betodealmeida the fix only seems to work for certain offsets, reopening this. Posted the following on Pandas issue tracker: https://github.com/pandas-dev/pandas/issues/27728
