### ISSUE TITLE
bubble chart - unhashable type: 'dict'

### ISSUE THREAD

**Issue by AndLLA** [apache/incubator-superset#8041]
In superset trunk a bubble chart seems to be "always" failing with the stacktrace below.
Previous bugs ended up as stale or were referring to missing group-by which is now mandatory in the UI and was filled in my case.
Playing around with the configuration leads to the same error.

Which is the correct way of setting up a bubble chart ?

<img width="450" alt="Screen Shot 2019-08-14 at 01 23 51" src="https://user-images.githubusercontent.com/44858649/62984145-5b3edf00-be32-11e9-9168-ae834c2f4778.png">

Traceback (most recent call last):
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/base.py", line 122, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/utils/decorators.py", line 70, in wrapper
    return f(*args, **kwargs)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/core.py", line 1097, in explore_json
    viz_obj, csv=csv, query=query, results=results, samples=samples
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/views/core.py", line 1018, in generate_json
    payload = viz_obj.get_payload()
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/viz.py", line 372, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/viz.py", line 387, in get_df_payload
    query_obj = self.query_obj()
  File "/home/superset/venvSS/lib/python3.6/site-packages/superset/viz.py", line 969, in query_obj
    d["metrics"] = list(set([self.z_metric, self.x_metric, self.y_metric]))
TypeError: unhashable type: 'dict'

**Comment by macorv** [comment]
Hello! If anyone ends here searching for a solution for error 'unhashable type: ´dict´, I have the solution. You should create a metric in your database (Sources --> Tabls --> Edit Record --> Metrics)
![image](https://user-images.githubusercontent.com/20216859/71225529-b50b5600-22b7-11ea-834d-ba7cfecdec5f.png)

Once you created the metrics, you can use it in Bubble Chart.


Regards, 
Martin.
