### ISSUE TITLE
Export as filter_box as CSV 

### ISSUE THREAD

**Issue by sandy-ha** [apache/incubator-superset#8122]
### Expected results
an Export of corrent Filters as csv

### Actual results

I get the follow messeges
Sorry, something went wrong
500 - Internal Server Error

Stacktrace

        Traceback (most recent call last):
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hgs/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hgs/venv/lib/python3.6/site-packages/superset/models/core.py", line 1017, in wrapper
    value = f(*args, **kwargs)
  File "/home/hgs/venv/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 168, in wraps
    return f(self, *args, **kwargs)
  File "/home/hgs/venv/lib/python3.6/site-packages/superset/views/core.py", line 1246, in explore_json
    samples=samples,
  File "/home/hgs/venv/lib/python3.6/site-packages/superset/views/core.py", line 1134, in generate_json
    viz_obj.get_csv(),
  File "/home/hgs/venv/lib/python3.6/site-packages/superset/viz.py", line 481, in get_csv
    include_index = not isinstance(df.index, pd.RangeIndex)
AttributeError: 'NoneType' object has no attribute 'index'

#### How to reproduce the bug

1. Go to a Dashboard with filter_box
2. Click on expoart as csv
![image](https://user-images.githubusercontent.com/53593919/63755475-0c278e00-c8b7-11e9-9cda-d3df5e1a30d9.png)

### Environment

(please complete the following information):

- superset version: `0.28.1`
- python version: ` 3.6.8`
- node.js version: `v8.10.0`
- npm version: `3.5.2`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I have found one closed similar.

**Comment by felexkemboi** [comment]
Have you managed to implement time date filter in filter box?

**Comment by sandy-ha** [comment]
It is the original filter box of the World Bank Demo.
![image](https://user-images.githubusercontent.com/53593919/63826121-e2757200-c95d-11e9-8320-8b1cd5e1de7b.png)
