### ISSUE TITLE
Schedule Email Reports for Charts works incorrect

### ISSUE THREAD

**Issue by ngritsuk** [apache/incubator-superset#8286]
When I try to send test email for chart with **Raw data** email format and **Attachment** delivery type, select checkbox Send Test Email and input email address into  Test Email Recipients, I get **Schedule changes will get applied in one hour**  message and following trace 

```
2019-09-24 15:51:01,893:INFO:werkzeug:172.19.0.2 - - [24/Sep/2019 15:51:01] "GET /superset/explore_json/?csv=true&form_data=%7B%22slice_id%22%3A+27%7D HTTP/1.1" 200 -
[2019-09-24 15:51:01,895: ERROR/MainProcess] Task email_reports.send[1f0a1575-68d6-46ba-9ef1-2552b56468f0] raised unexpected: TypeError('expected bytes-like object, not NoneType',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/superset/superset/tasks/schedules.py", line 367, in schedule_email_report
    deliver_slice(schedule)
  File "/home/superset/superset/tasks/schedules.py", line 346, in deliver_slice
    _deliver_email(schedule, subject, email)
  File "/home/superset/superset/tasks/schedules.py", line 84, in _deliver_email
    dryrun=config.get("SCHEDULED_EMAIL_DEBUG_MODE"),
  File "/home/superset/superset/utils/core.py", line 722, in send_email_smtp
    body, Content_Disposition="attachment; filename='%s'" % name, Name=name
  File "/usr/local/lib/python3.6/email/mime/application.py", line 37, in __init__
    _encoder(self)
  File "/usr/local/lib/python3.6/email/encoders.py", line 32, in encode_base64
    encdata = str(_bencode(orig), 'ascii')
  File "/usr/local/lib/python3.6/base64.py", line 527, in encodebytes
    _input_type_check(s)
  File "/usr/local/lib/python3.6/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not NoneType
127.0.0.1 - - [24/Sep/2019 15:51:03] "GET /health HTTP/1.1" 200 -
2019-09-24 15:51:03,620:INFO:werkzeug:127.0.0.1 - - [24/Sep/2019 15:51:03] "GET /health HTTP/1.1" 200 -
```

**Comment by ngritsuk** [comment]
Superset still has this problem and I guess a have a fix for it.

```
--- a/superset/tasks/schedules.py
+++ b/superset/tasks/schedules.py
@@ -264,7 +264,8 @@ def _get_slice_data(schedule):
         raise URLError(response.getcode())
 
     # TODO: Move to the csv module
-    rows = [r.split(b",") for r in response.content.splitlines()]
+    content = response.readlines()
+    rows = [r.split(b",") for r in content]
 
     if schedule.delivery_type == EmailDeliveryType.inline:
         data = None
@@ -281,7 +282,11 @@ def _get_slice_data(schedule):
             )
 
     elif schedule.delivery_type == EmailDeliveryType.attachment:
-        data = {__("%(name)s.csv", name=slc.slice_name): response.content}
+        csv_content = ""
+        for r in content:
+          csv_content += str(content.pop(0), 'utf-8')
+
+        data = {__("%(name)s.csv", name=slc.slice_name): csv_content}
         body = __(
             '<b><a href="%(url)s">Explore in Superset</a></b><p></p>',
             name=slc.slice_name,

```

**Comment by villebro** [comment]
@ngritsuk nice catch, this might be a regression from the removal of the dependency `requests` that was done a while back due to incompatible licenses. Please put through a PR with your diff, I will be happy to help review and get this fix through.

**Comment by ngritsuk** [comment]
@villebro Done https://github.com/apache/incubator-superset/pull/8339
