### ISSUE TITLE
An unknown error occurred. Please contact your Superset administrator

### ISSUE THREAD

**Issue by liyakhatalisheikh** [apache/incubator-superset#8322]
Hello, I have installed superset using [SupersetOffcDoc](https://superset.incubator.apache.org/installation.html) And successfully ran superset using command `gunicorn superset:app` but when i try to import a dashboard getting **An unknown error occurred. Please contact your Superset administrator**. My logged in user is `ADMIN` and also i found no errors in logs

**Comment by dpgaspar** [comment]
Hi @liya2664,

It's hard to help without logs or more info, please check again your server logs and browser console log. It would help fill out github's bug issue template.

Thanks

**Comment by liya2664** [comment]
Hello @dpgaspar 
I checked browser console log and found nothing, In browser network i checked `import_dashboards` call and found below response
```
Request URL: http://127.0.0.1:8000/superset/import_dashboards
Request Method: POST
Status Code: 302 FOUND
Remote Address: 127.0.0.1:8000
Referrer Policy: no-referrer-when-downgrade
```

**Comment by liya2664** [comment]
Got same issue while using docker as well, I was trying to import a dashboard from version `superset=0.27.0`

**Comment by chintaln** [comment]
hi Liya2664 were you able to over come this issue.  I am experiencing same issue with superset .30 and python3.6.9.  need help with this,  this is blocking me.

**Comment by narenrawat203** [comment]
It looks like similar error message "An unknown error occurred. Please contact your Superset administrator" while exporting dashboard from superset version 0.28.1  to import superset version 0.30.0, Any clue yet ?
Logs below----
------------------------------------supersetLog.log-----------------------------------------------------------
[2019-12-05 17:18:09 +0000] [12490] [DEBUG] GET /dashboard/list/
[2019-12-05 17:18:09 +0000] [12496] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:18:26 +0000] [12488] [DEBUG] GET /dashboard/list/
[2019-12-05 17:18:26 +0000] [12491] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:21:08 +0000] [12486] [DEBUG] GET /dashboard/list/
[2019-12-05 17:21:08 +0000] [12487] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:21:12 +0000] [12496] [DEBUG] GET /superset/dashboard/8/
2019-12-05 17:21:12,941:DEBUG:root:[36m[stats_logger] (incr) dashboard[0m
2019-12-05 17:21:12,965:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@52.34.148.89:5432/cdp
2019-12-05 17:21:12,966:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@52.34.148.89:5432/cdp
[2019-12-05 17:21:13 +0000] [12492] [DEBUG] GET /superset/favstar/Dashboard/8/count
[2019-12-05 17:21:13 +0000] [12496] [DEBUG] GET /csstemplateasyncmodelview/api/read
[2019-12-05 17:21:13 +0000] [12492] [DEBUG] GET /superset/favstar/Dashboard/8/count/
[2019-12-05 17:21:13 +0000] [12491] [DEBUG] POST /superset/explore_json/
2019-12-05 17:21:13,839:DEBUG:root:[36m[stats_logger] (incr) explore_json[0m
2019-12-05 17:21:13,849:DEBUG:parsedatetime:eval - with context - False, False
2019-12-05 17:21:13,853:INFO:root:Cache key: 84d28b9a84f889fe7f7712633fd1b29d
2019-12-05 17:21:13,854:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@52.34.148.89:5432/cdp
2019-12-05 17:21:13,855:INFO:root:SELECT COUNT(*) AS count, count(DISTINCT top_deter) AS "COUNT_DISTINCT(top_deter)" 
FROM wellcare_clm_new.chd_at_risk_patient_top_deter ORDER BY count DESC 
 LIMIT 10000
2019-12-05 17:21:13,859:INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://postgres:XXXXXXXXXX@52.34.148.89:5432/cdp
2019-12-05 17:21:13,876:DEBUG:root:[36m[stats_logger] (incr) loaded_from_source[0m
[2019-12-05 17:21:15 +0000] [12485] [DEBUG] POST /superset/log/
2019-12-05 17:21:15,139:DEBUG:root:[36m[stats_logger] (incr) log[0m
[2019-12-05 17:21:29 +0000] [12492] [DEBUG] GET /dashboard/list/
[2019-12-05 17:21:29 +0000] [12496] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:23:20 +0000] [12488] [DEBUG] GET /dashboard/list/
[2019-12-05 17:23:20 +0000] [12490] [DEBUG] GET /dashboard/list/
[2019-12-05 17:23:20 +0000] [12492] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:23:21 +0000] [12488] [DEBUG] GET /dashboard/list/
[2019-12-05 17:23:21 +0000] [12491] [DEBUG] GET /dashboard/list/
[2019-12-05 17:23:21 +0000] [12488] [DEBUG] GET /superset/csrf_token/
[2019-12-05 17:23:24 +0000] [12486] [DEBUG] GET /superset/import_dashboards
2019-12-05 17:23:24,242:DEBUG:root:[36m[stats_logger] (incr) import_dashboards[0m
[2019-12-05 17:23:33 +0000] [12487] [DEBUG] POST /superset/import_dashboards
2019-12-05 17:23:34,021:DEBUG:root:[36m[stats_logger] (incr) import_dashboards[0m
[2019-12-05 17:23:34 +0000] [12485] [DEBUG] GET /dashboard/list/
[2019-12-05 17:23:34 +0000] [12488] [DEBUG] GET /superset/csrf_token/

--------------------------------------supersetAccessLog.log-------------------------------------------------
24.170.39.226 - - [05/Dec/2019:17:18:09 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4906 "http://35.161.160.114:8088/dashboard/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:18:09 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:18:26 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4904 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:18:26 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:08 +0000] "GET /dashboard/list/ HTTP/1.1" 200 4907 "http://35.161.160.114:8088/chart/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:08 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:13 +0000] "GET /superset/dashboard/8/ HTTP/1.1" 200 4216 "http://35.161.160.114:8088/dashboard/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:13 +0000] "GET /superset/favstar/Dashboard/8/count HTTP/1.1" 308 331 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:13 +0000] "GET /csstemplateasyncmodelview/api/read HTTP/1.1" 200 734 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:13 +0000] "GET /superset/favstar/Dashboard/8/count/ HTTP/1.1" 200 12 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:13 +0000] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A82%7D HTTP/1.1" 200 734 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:15 +0000] "POST /superset/log/?explode=events&dashboard_id=8 HTTP/1.1" 200 20 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:29 +0000] "GET /dashboard/list/ HTTP/1.1" 200 4904 "http://35.161.160.114:8088/superset/dashboard/8/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
73.206.168.80 - - [05/Dec/2019:17:21:29 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:20 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4903 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:20 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4903 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:20 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:21 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4906 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:21 +0000] "GET /dashboard/list/? HTTP/1.1" 200 4906 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:21 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:24 +0000] "GET /superset/import_dashboards HTTP/1.1" 200 2911 "http://35.161.160.114:8088/dashboard/list/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:34 +0000] "POST /superset/import_dashboards HTTP/1.1" 302 239 "http://35.161.160.114:8088/superset/import_dashboards" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:34 +0000] "GET /dashboard/list/ HTTP/1.1" 200 5001 "http://35.161.160.114:8088/superset/import_dashboards" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
24.170.39.226 - - [05/Dec/2019:17:23:34 +0000] "GET /superset/csrf_token/ HTTP/1.1" 200 115 "http://35.161.160.114:8088/dashboard/list/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
-------------------------------------------------------------------------------------------

**Comment by snehil1001** [comment]
Hi, I am also facing same issue. Could you please suggest solution or reopen this ticket ?

**Comment by Liyakhat-Ali** [comment]
@snehil1001 We have created our own docker image with our requirement version, I cannot reopen the issue as repo collaborator closed it

**Comment by ebauch** [comment]
Same issue here. It has likely todo with the json format being changes when switching versions. I exported dashboards from 0.30.0 and tried to import into a new instance of 0.36. The specific error in the console was (use --debuger) on import

```
TypeError: 'is_restricted' is an invalid keyword argument for SqlMetric
```
So I opened the exported json file and deleted all rows with "is_restricted" keys. An example is shown below. 

```
"d3format": null,
                            "description": null,
                            "expression": "count(*)",
                            "id": 2,
                            "is_restricted": false,
                            "metric_name": "",
                            "metric_type": null,
                            "table_id": 1,
                            "verbose_name": "count(*)",
                            "warning_text": null
```
This resolved the issue for me and the dashboard file imported successfully.

**Comment by stevensuting** [comment]
@dpgaspar This issue still seems to persist in v1.1.0 
**Logs**
It does a series of 
`INFO:superset.datasets.commands.importers.v0:Importing col` successfully
Then throws `AttributeError: 'NoneType' object has no attribute 'id'`

```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "superset-venv/lib/python3.9/site-packages/superset/views/core.py", line 629, in import_dashboards
    ImportDashboardsCommand(
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 329, in run
    import_dashboards(db.session, content, self.database_id)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 308, in import_dashboards
    import_dashboard(dashboard, import_time=import_time)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 171, in import_dashboard
    new_slc_id = import_chart(slc, remote_slc, import_time=import_time)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 73, in import_chart
    slc_to_import.datasource_id = datasource.id  # type: ignore
AttributeError: 'NoneType' object has no attribute 'id'
ERROR:superset.views.core:'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "superset-venv/lib/python3.9/site-packages/superset/views/core.py", line 629, in import_dashboards
    ImportDashboardsCommand(
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 329, in run
    import_dashboards(db.session, content, self.database_id)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 308, in import_dashboards
    import_dashboard(dashboard, import_time=import_time)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 171, in import_dashboard
    new_slc_id = import_chart(slc, remote_slc, import_time=import_time)
  File "superset-venv/lib/python3.9/site-packages/superset/dashboards/commands/importers/v0.py", line 73, in import_chart
    slc_to_import.datasource_id = datasource.id  # type: ignore
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by prashant-shahi** [comment]
I had the same issue. Renaming the database to the old one, did the job.


If you are unsure of what was the old database. You can find it at the end of the export file itself with the `database_name` key.

**Comment by stevensuting** [comment]
Yup, @prashant-shahi. The issue in my case was also because the datasource name in the export file did not exist on the superset instance I was importing it on.

**Comment by asdi744** [comment]
> I had the same issue. Renaming the database to the old one, did the job.
> 
> If you are unsure of what was the old database. You can find it at the end of the export file itself with the `database_name` key.

Thanks Man!
the database name in json file (dashboard to be imported) should match the destination database_name.

**Comment by linpaws-reverse** [comment]
Please check the database name, it should be same to import dashboard or can rename to existing database name in json (database_name) before importing json
