### ISSUE TITLE
0.34 breaks Dashboard JSON Export with a redirect loop

### ISSUE THREAD

**Issue by mwcm** [apache/incubator-superset#8355]
### Expected results

JSON representation of dashboard data is downloaded

### Actual results

infinite redirect loop back and forth between:
1. /dashboard/export_dashboards_form?id=1
and 
2. /login (with a ?next parameter set to URL 1)

#### Screenshots

N/A

#### How to reproduce the bug

1. Go to 'Dashboards'
2. Tick the checkbox beside a dashboard
3. Click on 'Actions'
4. Click on 'Export'
5. Click 'OK' on the confirmation dialogue

### Environment

(please complete the following information):

- superset version: `0.34`
- python version: `3.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.

This is what shows in the logs after trying to export a Dashboard's JSON.
Have not seen this error (or any other security related error) occur on any other pages, or after taking other actions.
```
flask_oidc:Invalid ID token cookie
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/flask_oidc/__init__.py", line 353, in _get_cookie_id_token
itsdangerous.exc.SignatureExpired: Signature expired
File "/usr/lib/python3.6/site-packages/itsdangerous/jws.py", line 205, in loads
date_signed=self.get_issue_date(header)
return self.cookie_serializer.loads(id_token_cookie)
```

- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

there seem to be similar Issues going a year or two back, but I couldn't find an open Issue for it currently, (this is one of the past issues #3145)

### Additional context

this has been reported multiple times in the past, there was even a PR below which never got merged and was then closed by a bot for inactivity 
https://github.com/apache/incubator-superset/pull/5914

the logs also make me suspect this could be related to / caused by the security manager issues I've seen reported against the latest release

**Comment by mwcm** [comment]
Update: 
We've added the changes included in PR #5914 to our Superset deploy, it fixed our export issue!
