### ISSUE TITLE
Report the "root:'charset' is an invalid keyword argument for this function" errors When connecting to Oracle

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/incubator-superset#8393]
I had an error when configuring Superset connect to oracle.

The error was attributable to issues with sqlalchemy

### Environment
- superset version: Superset 0.30.0
- python version: Python 3.6.9

### Details errors

2019-10-15 04:22:48,682:INFO:root:Database.get_sqla_engine(). Masked URL: oracle+cx_oracle://XXXX:XXXXXXXXXX@10.12.192.55:1521/xxxx?charset=utf8
2019-10-15 04:22:48,683:ERROR:root:'charset' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/onepiece/python3/lib/python3.6/site-packages/superset/views/core.py", line 1706, in testconn
    with closing(engine.connect()) as conn:
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2196, in connect
    return self._connection_cls(self, **kwargs)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2296, in raw_connection
    self.pool.unique_connection, _connection
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    return fn()
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/onepiece/python3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
TypeError: 'charset' is an invalid keyword argument for this function

**Comment by villebro** [comment]
Please update to Superset 0.34.1 (most recent version) to check if the error has been resolved.

**Comment by villebro** [comment]
I believe you need to set the `NLS_LANG` environment variable to change character encodings on Oracle. If you are able to solve the issue please feel free to submit a PR adding a note to the Oracle installation documentation under `docs/installation.rst`.
