### ISSUE TITLE
`superset load_examples` times out with TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8520]
### Expected results

Successful load of examples after invoking `superset load_examples`

### Actual results
` TimeoutError: [Errno 110] Connection timed out `

#### Screenshots

```
(venv-superset) [root@usb-gce-superset-dev-01 ~]# superset load_examples
2019-11-06 20:55:20,276:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
2019-11-06 20:55:21,806:INFO:root:Database.get_sqla_engine(). Masked URL: sqlite:////root/.superset/superset.db
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv-superset/bin/superset", line 31, in <module>
    cli()
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/venv-superset/lib/python3.6/site-packages/superset/cli.py", line 143, in load_examples
    load_examples_run(load_test_data, only_metadata, force)
  File "/root/venv-superset/lib/python3.6/site-packages/superset/cli.py", line 84, in load_examples_run
    examples.load_energy(only_metadata, force)
  File "/root/venv-superset/lib/python3.6/site-packages/superset/examples/energy.py", line 38, in load_energy
    data = get_example_data("energy.json.gz")
  File "/root/venv-superset/lib/python3.6/site-packages/superset/examples/helpers.py", line 72, in get_example_data
    content = request.urlopen(f"{BASE_URL}{filepath}?raw=true").read()
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
(venv-superset) [root@usb-gce-superset-dev-01 ~]#
```

#### How to reproduce the bug

1.  `pip install superset`
2. `superset db upgrade`
3. `export FLASK_APP=superset; flask fab create-admin`
4. `superset load_examples`

### Environment

(please complete the following information):

- superset version: Superset 0.30.0
- python version: Python 3.6.8
- node.js version: bash: node: command not found
- npm version: bash: npm: command not found

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- **I have no idea where to find the logs**
- [x ] I have reproduced the issue with at least the latest released version of superset.

SIMILAR ISSUE -> https://github.com/apache/incubator-superset/issues/8491

# Speculation

Corporate proxy is blocking access to raw.githubusercontent.com and there is no way to provide a proxy.

**Comment by betodealmeida** [comment]
@metaperl would it work if we allowed the examples to be loaded from a local path, instead of a URL? You would download the files somewhere else, and run:

```bash
$ superset load_examples examples-data-master.zip
```

**Comment by ningzhiqun** [comment]
> @metaperl would it work if we allowed the examples to be loaded from a local path, instead of a URL? You would download the files somewhere else, and run:
> 
> ```shell
> $ superset load_examples examples-data-master.zip
> ```
Where do I download it?（examples-data-master.zip）

**Comment by metaperl** [comment]
> would it work if we allowed the examples to be loaded from a local path, instead of a URL?

Yes, I think so.

**Comment by vietvudanh** [comment]
I work in an no Internet connection environment, I cloned data from [example repo](https://github.com/apache-superset/examples-data), open http server, then point [BASE_URL](https://github.com/apache/incubator-superset/blob/c36a7e3adae0ef27c3f16f890a396e2463c63bdd/superset/examples/helpers.py#L30) to my local server.

**Comment by liudonghua123** [comment]
I have the same issue, I use anaconda in my macos, how can I found the location of the installed [BASE_URL](https://github.com/apache/incubator-superset/blob/c36a7e3adae0ef27c3f16f890a396e2463c63bdd/superset/examples/helpers.py#L30)?

**Comment by RoyeeW** [comment]
> 我有同样的问题，我在我的 macos 中使用 anaconda，我怎样才能找到安装的[BASE_URL](https://github.com/apache/incubator-superset/blob/c36a7e3adae0ef27c3f16f890a396e2463c63bdd/superset/examples/helpers.py#L30)的位置？

lib/python3.8/site-packages/superset/examples/helpers.py

**Comment by RoyeeW** [comment]
> 我在没有 Internet 连接的环境中工作，我从[示例 repo](https://github.com/apache-superset/examples-data)克隆数据，打开 http 服务器，然后将[BASE_URL](https://github.com/apache/incubator-superset/blob/c36a7e3adae0ef27c3f16f890a396e2463c63bdd/superset/examples/helpers.py#L30)指向我的本地服务器。

thx，well done for me

**Comment by soul-zym** [comment]
Set SUPERSET_LOAD_EXAMPLES=false in both docker/.env and docker/.env-non-dev. Restart all components including superset_app, superset_init, superset_worker, and so on. superset_db, superset_cache (I am using docker to install is referred to above as the default docker container name). The problem disappears after restarting. [But I'm not sure if the init process is working, it exits, and the log seems to be halfway to "Init Step 3/4 [Complete] -- Setting up roles and perms" and then nothing.]
