### ISSUE TITLE
hdp superset started error:'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by lupengfeige** [apache/incubator-superset#8717]
resource_management.core.exceptions.ExecutionFailed: Execution of 'source /usr/hdp/current/superset/conf/superset-env.sh ; /usr/hdp/current/superset/bin/superset init' returned 1. 2019-11-23 08:47:41,412:ERROR:flask_appbuilder.base:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/hdp/3.1.0.0-78/superset/lib/python3.4/site-packages/flask_appbuilder/base.py", line 469, in _add_permission
    self.sm.add_permissions_view(baseview.base_permissions, baseview.__class__.__name__)
  File "/usr/hdp/3.1.0.0-78/superset/lib/python3.4/site-packages/flask_appbuilder/security/manager.py", line 819, in add_permissions_view
    if perm_view.permission.name not in base_permissions:
AttributeError: 'NoneType' object has no attribute 'name'
2019-11-23 08:47:41,413:ERROR:flask_appbuilder.base:Add Permission on View Error: 'NoneType' object has no attribute 'name'

**Comment by AlexSeven77** [comment]
I also come across this problem recently. Did we fix it yet?

**Comment by villebro** [comment]
@AlexSeven77 please open a new ticket if you are running into this problem on the latest release or master branch.
