### ISSUE TITLE
npm error 68% building 3528/3594 modules 66 active ...-map/node_modules/d3-array/src/count.jsinternal/child_process.js:366     throw errnoException(err, 'spawn');     ^

### ISSUE THREAD

**Issue by Aabhusan** [apache/incubator-superset#8763]
68% building 3528/3594 modules 66 active ...-map/node_modules/d3-array/src/count.jsinternal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:551:9)
    at new PoolWorker (/app/superset/assets/node_modules/thread-loader/dist/WorkerPool.js:49:43)
    at WorkerPool.createWorker (/app/superset/assets/node_modules/thread-loader/dist/WorkerPool.js:338:23)
    at WorkerPool.distributeJob (/app/superset/assets/node_modules/thread-loader/dist/WorkerPool.js:329:28)
    at /app/superset/assets/node_modules/async/queue.js:10:5
    at process (/app/superset/assets/node_modules/async/internal/queue.js:164:17)
    at Immediate.<anonymous> (/app/superset/assets/node_modules/async/internal/setImmediate.js:27:16)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev build: `cross-env NODE_OPTIONS=--max_old_space_size=8192 NODE_ENV=production webpack --mode=production --colors --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superset@0.999.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-05T07_15_33_517Z-debug.log

**Comment by nytai** [comment]
@Aabhusan looks like a node out of memory error. What are the resources of the machine you're trying to build this on?

**Comment by Aabhusan** [comment]
@nytai , i ma using t2.micro ec2 instance  should  i upgrade the instance type??

**Comment by nytai** [comment]
@Aabhusan that would be my first try, you'll want something with ~8gb of memory for the build. Alternatively you could try changing some of the flags on this line https://github.com/apache/incubator-superset/blob/master/superset/assets/package.json#L17

`NODE_OPTIONS=--max_old_space_size=8192` tells node how much memory it has available
