### ISSUE TITLE
impala can't resolve username

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-superset#880]
```
impala can't resolve username
impala://xxx:xxxx@192.x.x.x:21050/default
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/caravel/views.py", line 1029, in testconn
    engine.connect()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
TypeError: connect() got an unexpected keyword argument 'username'
```

**Comment by xrmx** [comment]
@qinzl1 looks like something's off between your dsn string, sqlalchemy and the dialect for impala. Am not sure we can fix anything here. Which version of impyla do you have?

**Comment by qinzl1** [comment]
@xrmx my impyla version is (0.13.8)

**Comment by mistercrunch** [comment]
This seems specific to the SqlAlchemy lib you use for impala and your connection string. Nothing related to Caravel AFAICT

**Comment by linpelvis** [comment]
@qinzl1 You can use the following URI.
impala://192.x.x.x:21050/default?auth_mechanism=LDAP&user=xxx&password=xxx

**Comment by qinzl1** [comment]
thanks for everybody

**Comment by qinzl1** [comment]
i hive an other program, i can connect impala for caravel,but con not connect impala for superset
ERROR: {"error": "Connection failed!\n\nThe error message returned was:\n(exceptions.AttributeError) TBufferedTransport instance has no attribute 'trans' [SQL: u'SHOW TABLES IN default']"}

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 410 days. Feel free to comment and request for this issue to be reopened.
