### ISSUE TITLE
'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#8847]
Attempting to install Superset from github fails when attempting to install pydruid:
`pip install -r requirements-dev.txt`

 with this error:

```
Collecting pydruid==0.5.7 (from -r requirements-dev.txt (line 29))
  Downloading https://mydns.com/our/api/pypi/pyre-usb/packages/packages/a8/bd/88ab430c639819871e069c9ccccebdd3c3698b044e0109545a902b880ddc/pydruid-0.5.7.tar.gz (6.0MB)
    100% |████████████████████████████████| 6.0MB 30.6MB/s
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    [DEBUG:pip.vcs:__init__.py:60 -             register() ] Registered VCS backend: hg
    [DEBUG:pip.vcs:__init__.py:60 -             register() ] Registered VCS backend: svn
    [DEBUG:pip.vcs:__init__.py:60 -             register() ] Registered VCS backend: bzr
    ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
    Traceback (most recent call last):
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/root/dev/venv-superset/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp9sv5kfoj', '--quiet', 'pytest-runner']' returned non-zero exit status 1\
.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9nj4zke_/pydruid/setup.py", line 52, in <module>
        "Programming Language :: Python :: 3.6",
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/root/dev/venv-superset/lib64/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/root/dev/venv-superset/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp9sv5kfoj', '--quiet', 'pytest-runner']' returned non-zero exit status\
 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9nj4zke_/pydruid/
(venv-superset) [root@usb-gce-superset-dev-01 incubator-superset]#


```

**Comment by swahareddy** [comment]
I am facing the same error when trying to install google-cloud-documentai on my work machine (but no errors on my personal machine).
