### ISSUE TITLE
After login only a close button is seen

### ISSUE THREAD

**Issue by nabinkhadka** [apache/incubator-superset#8883]
When I run the latest master branch with docker-compose.yml, then I login as admin with password admin. But once I login, there is just a close button and I can see the following error in one of the container.

```
superset-node_1    |
superset-node_1    | > superset@0.999.0-dev dev /app/superset/assets
superset-node_1    | > webpack --mode=development --colors --progress --debug --watch
superset-node_1    |
superset-node_1    | sh: 1: webpack: not found
superset-node_1    | npm ERR! code ELIFECYCLE
superset-node_1    | npm ERR! syscall spawn
superset-node_1    | npm ERR! file sh
superset-node_1    | npm ERR! errno ENOENT
superset-node_1    | npm ERR! superset@0.999.0-dev dev: `webpack --mode=development --colors --progress --debug --watch`
superset-node_1    | npm ERR! spawn ENOENT
superset-node_1    | npm ERR!
superset-node_1    | npm ERR! Failed at the superset@0.999.0-dev dev script.
superset-node_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
superset-node_1    |
superset-node_1    | npm ERR! A complete log of this run can be found in:
superset-node_1    | npm ERR!     /root/.npm/_logs/2019-12-23T02_34_06_505Z-debug.log
incubator-superset_superset-node_1 exited with code 1
```
## /root/.npm/_logs/2019-12-23T02_34_06_505Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle superset@0.999.0-dev~predev: superset@0.999.0-dev
6 info lifecycle superset@0.999.0-dev~dev: superset@0.999.0-dev
7 verbose lifecycle superset@0.999.0-dev~dev: unsafe-perm in lifecycle true
8 verbose lifecycle superset@0.999.0-dev~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/superset/assets/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle superset@0.999.0-dev~dev: CWD: /app/superset/assets
10 silly lifecycle superset@0.999.0-dev~dev: Args: [ '-c',
10 silly lifecycle   'webpack --mode=development --colors --progress --debug --watch' ]
11 info lifecycle superset@0.999.0-dev~dev: Failed to exec dev script
12 verbose stack Error: superset@0.999.0-dev dev: `webpack --mode=development --colors --progress --debug --watch`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid superset@0.999.0-dev
14 verbose cwd /app/superset/assets
15 verbose Linux 4.9.184-linuxkit
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
17 verbose node v10.18.0
18 verbose npm  v6.13.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error superset@0.999.0-dev dev: `webpack --mode=development --colors --progress --debug --watch`
23 error spawn ENOENT
24 error Failed at the superset@0.999.0-dev dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by nabinkhadka** [comment]
Duplicate of https://github.com/apache/incubator-superset/issues/8818
