### ISSUE TITLE
pydruid only listed as a dev requirement

### ISSUE THREAD

**Issue by metaperl** [apache/incubator-superset#9014]
### Expected results

`flask fab create-permissions` creates all new permissions (given that superset_config.py is in PYTHONPATH).

### Actual results

`flask fab create-permissions` fails with the error:

```
[INFO:flask_appbuilder.baseviews:baseviews.py:213 -       _register_urls() ] Registering route /logmodelview/list/ ('GET',)
[INFO:flask_appbuilder.baseviews:baseviews.py:213 -       _register_urls() ] Registering route /logmodelview/show/<pk> ['GET']
Traceback (most recent call last):
  File "/root/dev/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/root/dev/venv/lib64/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/root/dev/venv/lib64/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/dev/venv/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/dev/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/dev/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/dev/venv/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/dev/venv/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/dev/venv/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/dev/venv/lib64/python3.6/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/root/dev/venv/lib64/python3.6/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/root/dev/venv/lib64/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/root/superset-base-image/superset/__init__.py", line 244, in <module>
    ConnectorRegistry.register_sources(module_datasource_map)
  File "/root/superset-base-image/superset/connectors/connector_registry.py", line 37, in register_sources
    module_obj = __import__(module_name, fromlist=class_names)
  File "/root/superset-base-image/superset/connectors/druid/__init__.py", line 17, in <module>
    from . import models, views
  File "/root/superset-base-image/superset/connectors/druid/models.py", line 460, in <module>
    class DruidDatasource(Model, BaseDatasource):
  File "/root/superset-base-image/superset/connectors/druid/models.py", line 832, in DruidDatasource
    def get_post_agg(mconf: Dict) -> Postaggregator:
NameError: name 'Postaggregator' is not defined
(venv) [root@usb-gce-superset-dev-01 bin]# 
```

### Additional context

https://github.com/apache/incubator-superset/issues/8426

**Comment by dpgaspar** [comment]
Hi @metaperl,

Following #8426 I see that you were using a specific commit. Can you confirm this?
pydruid became an extra dependency since 0.34.0
