### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by FU100** [apache/incubator-superset#9276]
1.
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
docker-compose up

2.
```
######################################################################
superset-init_1    | 
superset-init_1    | 
superset-init_1    | Init Step 3/4 [Starting] -- Loading examples
superset-init_1    | 
superset-init_1    | 
superset-init_1    | ######################################################################
superset-init_1    | 
superset-init_1    | INFO:root:logging was configured successfully
superset-init_1    | DEBUG:asyncio:Using selector: EpollSelector
superset-init_1    | INFO:root:Database.get_sqla_engine(). Masked URL: postgresql://superset:XXXXXXXXXX@db:5432/superset
superset-init_1    | Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
superset-init_1    | Loading examples metadata and related data into examples
superset-init_1    | Creating default CSS templates
superset-init_1    | Loading energy related dataset
superset-init_1    | Traceback (most recent call last):
superset-init_1    |   File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
superset-init_1    |     encode_chunked=req.has_header('Transfer-encoding'))
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
superset-init_1    |     self._send_request(method, url, body, headers, encode_chunked)
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
superset-init_1    |     self.endheaders(body, encode_chunked=encode_chunked)
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
superset-init_1    |     self._send_output(message_body, encode_chunked=encode_chunked)
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
superset-init_1    |     self.send(msg)
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
superset-init_1    |     self.connect()
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 1407, in connect
superset-init_1    |     super().connect()
superset-init_1    |   File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
superset-init_1    |     (self.host,self.port), self.timeout, self.source_address)
superset-init_1    |   File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
superset-init_1    |     raise err
superset-init_1    |   File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
superset-init_1    |     sock.connect(sa)
superset-init_1    | ConnectionRefusedError: [Errno 111] Connection refused
```
3. how to fix this error?

**Comment by mistercrunch** [comment]
Does the box not have internet access?

**Comment by cricket007** [comment]
Add environment variable `SUPERSET_LOAD_EXAMPLES=no`

Ref. https://github.com/apache/incubator-superset/blob/master/docker/docker-init.sh#L51

**Comment by FU100** [comment]
Thanks, now superset is up.

**Comment by vellengs** [comment]
Should  set SUPERSET_LOAD_EXAMPLES=no ? but it isn't documented !
