### ISSUE TITLE
debug the project, report the issue

### ISSUE THREAD

**Issue by pengcao** [apache/incubator-superset#9423]
Traceback (most recent call last):
```
  File "F:/02.work/bi/incubator-superset-master/superset/run.py", line 12, in <module>
    from superset import app
  File "F:\02.work\bi\incubator-superset-master\superset\__init__.py", line 22, in <module>
    from superset.connectors.connector_registry import ConnectorRegistry
  File "F:\02.work\bi\incubator-superset-master\superset\connectors\connector_registry.py", line 18, in <module>
    from typing import Dict, List, Optional, Set, Type, TYPE_CHECKING
  File "F:\02.work\bi\incubator-superset-master\superset\typing.py", line 18, in <module>
    from typing import Any, Callable, Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Any'
```

**Comment by mistercrunch** [comment]
This looks like Windows, which is not actively supported at this time. Try a linux VM or Docker
