### ISSUE TITLE
AttributeError: 'SqlaTable' object has no attribute 'get_schema_perm'

### ISSUE THREAD

**Issue by rangerzhou** [apache/incubator-superset#9424]
Ubuntu 18.04
Python3.7

`$ superset load_examples      
2020-03-31 09:20:55,605:INFO:root:logging was configured successfully
2020-03-31 09:20:55,649:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
2020-03-31 09:20:56,544:INFO:root:Database.get_sqla_engine(). Masked URL: sqlite:////home/ranger/.superset/superset.db
Creating table [wb_health_population] reference
Traceback (most recent call last):
  File "/home/ranger/anaconda3/envs/superset/bin/superset", line 31, in <module>
    cli()
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/superset/cli.py", line 142, in load_examples
    load_examples_run(load_test_data, only_metadata, force)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/superset/cli.py", line 83, in load_examples_run
    examples.load_energy(only_metadata, force)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/superset/examples/energy.py", line 63, in load_energy
    db.session.merge(tbl)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2117, in merge
    self._autoflush()
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1591, in _autoflush
    self.flush()
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 264, in save_obj
    ) in states_to_update
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1432, in _finalize_insert_update_commands
    mapper.dispatch.after_insert(mapper, connection, state)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/sqlalchemy/orm/events.py", line 719, in wrap
    fn(*arg, **kw)
  File "/home/ranger/anaconda3/envs/superset/lib/python3.7/site-packages/superset/security/manager.py", line 805, in set_perm
    and target.schema_perm != target.get_schema_perm()
AttributeError: 'SqlaTable' object has no attribute 'get_schema_perm'
(superset) `

**Comment by rangerzhou** [comment]
Uninstall and rm -rf ~/.superset，then install successfully
``` shell
# Download anaconda: https://www.anaconda.com/distribution/#linux
$ bash ~/Download/Anaconda3-2020.02-Linux-x86_64.sh
# Create conda env
$ conda create -n superset python=3.7
# Activate env
$ conda activate superset
# Install superset
$ pip install apache-superset
# Install flask-appbuilder
$ pip install flask-appbuilder
# Install necessary modules
$ pip install wtforms_json flask_compress celery flask_migrate flask_talisman flask_caching sqlparse bleach markdown numpy pandas parsedatetime pathlib2 simplejson humanize python-geohash polyline geopy cryptography backoff msgpack pyarrow contextlib2 croniter retry selenium isodate
# Initialize the database
$ superset db upgrade 
# Create an admin user # fabmanager create-admin --app superset
$ export FLASK_APP=superset
$ flask fab create-admin
# Load some data to play with
$ superset load_examples
# Create default roles and permissions
$ superset init
# To start a development web server on port 8088, use -p to bind to another port
$ superset run -p 8088 --with-threads --reload --debugger

**Comment by willbarrett** [comment]
@rangerzhou I'm glad you found a workaround. If it seems like this was a temporary issue, would it be OK to close this issue?

**Comment by rangerzhou** [comment]
> @rangerzhou I'm glad you found a workaround. If it seems like this was a temporary issue, would it be OK to close this issue?

Yea, of course.
