### ISSUE TITLE
TableViz regression when displaying no data for a Druid datasource in 0.36.0rc3

### ISSUE THREAD

**Issue by elukey** [apache/incubator-superset#9468]
While testing 0.36.0rc3 I noticed that a TableViz of a Druid datasource returns the following message when no data is returned by the query:

"None of [Index(['project', 'count'], dtype='object')] are in the [columns]"

As opposed to "No data" (Superset 0.35.0)

### Expected results

"No data" or similar error message returned (less cryptic for the user).

### Actual results

UI shows "None of [Index(['project', 'count'], dtype='object')] are in the [columns]".

#### How to reproduce the bug

1. Go to Druid datasources
2. Click on one datasource
3. Run a query that returns no result
4. See the error displayed

### Environment

(please complete the following information):

- superset version: `0.36.0rc3`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This is the stacktrace reported:

```
Apr  4 08:42:09 an-tool1005 superset[16630]: "None of [Index(['project', 'count'], dtype='object')] are in the [columns]"
Apr  4 08:42:09 an-tool1005 superset[16630]: Traceback (most recent call last):
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/base.py", line 124, in wraps
Apr  4 08:42:09 an-tool1005 superset[16630]:     return f(self, *args, **kwargs)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/utils/decorators.py", line 70, in wrapper
Apr  4 08:42:09 an-tool1005 superset[16630]:     return f(*args, **kwargs)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 717, in explore_json
Apr  4 08:42:09 an-tool1005 superset[16630]:     viz_obj, csv=csv, query=query, results=results, samples=samples
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 639, in generate_json
Apr  4 08:42:09 an-tool1005 superset[16630]:     payload = viz_obj.get_payload()
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 406, in get_payload
Apr  4 08:42:09 an-tool1005 superset[16630]:     payload["data"] = self.get_data(df)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 628, in get_data
Apr  4 08:42:09 an-tool1005 superset[16630]:     df[non_percent_metric_columns],
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3001, in __getitem__
Apr  4 08:42:09 an-tool1005 superset[16630]:     indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1285, in _convert_to_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     return self._get_listlike_indexer(obj, axis, **kwargs)[1]
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1092, in _get_listlike_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1177, in _validate_read_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     key=key, axis=self.obj._get_axis_name(axis)
Apr  4 08:42:09 an-tool1005 superset[16630]: KeyError: "None of [Index(['project', 'count'], dtype='object')] are in the [columns]"
Apr  4 08:42:09 an-tool1005 superset[16630]: ERROR:superset.views.base:"None of [Index(['project', 'count'], dtype='object')] are in the [columns]"
Apr  4 08:42:09 an-tool1005 superset[16630]: Traceback (most recent call last):
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/base.py", line 124, in wraps
Apr  4 08:42:09 an-tool1005 superset[16630]:     return f(self, *args, **kwargs)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/utils/decorators.py", line 70, in wrapper
Apr  4 08:42:09 an-tool1005 superset[16630]:     return f(*args, **kwargs)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 717, in explore_json
Apr  4 08:42:09 an-tool1005 superset[16630]:     viz_obj, csv=csv, query=query, results=results, samples=samples
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/views/core.py", line 639, in generate_json
Apr  4 08:42:09 an-tool1005 superset[16630]:     payload = viz_obj.get_payload()
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 406, in get_payload
Apr  4 08:42:09 an-tool1005 superset[16630]:     payload["data"] = self.get_data(df)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 628, in get_data
Apr  4 08:42:09 an-tool1005 superset[16630]:     df[non_percent_metric_columns],
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3001, in __getitem__
Apr  4 08:42:09 an-tool1005 superset[16630]:     indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1285, in _convert_to_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     return self._get_listlike_indexer(obj, axis, **kwargs)[1]
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1092, in _get_listlike_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
Apr  4 08:42:09 an-tool1005 superset[16630]:   File "/srv/deployment/analytics/superset/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1177, in _validate_read_indexer
Apr  4 08:42:09 an-tool1005 superset[16630]:     key=key, axis=self.obj._get_axis_name(axis)
Apr  4 08:42:09 an-tool1005 superset[16630]: KeyError: "None of [Index(['project', 'count'], dtype='object')] are in the [columns]"
```
Can this be related to one of the following?
https://github.com/apache/incubator-superset/pull/9006
https://github.com/apache/incubator-superset/pull/8985

**Comment by elukey** [comment]
@villebro this doesn't seem a big problem for rc3 but it will be more difficult for users to understand what it is happening.. Let me know what you think about it :)

**Comment by villebro** [comment]
Good catch @elukey 👍  Are you using the legacy druid connector or the sqlalchemy one?

**Comment by elukey** [comment]
> Good catch @elukey 👍 Are you using the legacy druid connector or the sqlalchemy one?

Good question, I am not entirely sure how to check but I suspect the legacy one, I don't see any sqlalchemy configuration for Druid clusters.
