### ISSUE TITLE
fabmanager error

### ISSUE THREAD

**Issue by cyang52** [apache/incubator-superset#9563]
I was trying to setup superset on windows.
after run "fabmanager create-admin --app superset", it reports, :"'fabmanager' is not recognized as an internal or external command, operable program or batch file."
any idea how to fix it?

**Comment by mistercrunch** [comment]
Are you on Windows?

**Comment by cyang52** [comment]
Yes, 
I did some research, changes the location at XXX\Lib\site-packages\superset\bin> and run" python superset db upgrade" but the problem is still there, it reportes:"
Traceback (most recent call last):
  File "superset", line 18, in <module>
    from superset.cli import superset
  File "G:\python\myproject\env\lib\site-packages\superset\__init__.py", line 18, in <module>
    from flask import current_app, Flask
ModuleNotFoundError: No module named 'flask'"

**Comment by mistercrunch** [comment]
Windows is not officially supported, but others may be able to help. It keeps being reported that Superset [can] work on Windows. You may want to look at other issues with the `.windows` label and ask people who have reported success.

**Comment by vdmitriyev** [comment]
You can try to use [Docker Desktop](https://docs.docker.com/docker-for-windows/) or [vagrant](https://www.vagrantup.com/)  + [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (both will run Apache Superset inside Linux-based system and Windows will be a hosting operation system). There are some issues with this approach, but here you may find more information on how to address them - https://github.com/apache/incubator-superset/issues/8632

P.S. Otherwise it could be not that easy task to deploy this solution directly on Windows. You will need to create a proper "virtual environment" with all dependencies and requirements for Python and also for Node.js, install and configure PostgreSQL (I assume), as well as use proper PATH to be able to run everything.

**Comment by cyang52** [comment]
thanks, I will try it 
but right now I intend to pip install pyarrow, it fails several times and reports:"
ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly"

**Comment by vdmitriyev** [comment]
> thanks, I will try it
> but right now I intend to pip install pyarrow, it fails several times and reports:"
> ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly"

It is most probably an issue with installation of packages for Python on Windows. There are packages that require properly installed *Visual C++ Redistributable for Visual Studio 2015** (or another version - depends on an official *Visual C++ compiler* for the Python version that is used on your machine). In case of pyarrow according to the documentation [here](https://arrow.apache.org/docs/python/install.html), you will most probably need to install the *Visual C++ Redistributable for Visual Studio 2015*. 

A possible workaround (I am not sure if it will work in this particular case with Apache Superset) to use https://www.anaconda.com/distribution/ together with it's conda (instead of pip) for further package installations required for Apache Superset.

**Comment by cyang52** [comment]
> > thanks, I will try it
> > but right now I intend to pip install pyarrow, it fails several times and reports:"
> > ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly"
> 
> It is most probably an issue with installation of packages for Python on Windows. There are packages that require properly installed _Visual C++ Redistributable for Visual Studio 2015_* (or another version - depends on an official _Visual C++ compiler_ for the Python version that is used on your machine). In case of pyarrow according to the documentation [here](https://arrow.apache.org/docs/python/install.html), you will most probably need to install the _Visual C++ Redistributable for Visual Studio 2015_.
> 
> A possible workaround (I am not sure if it will work in this particular case with Apache Superset) to use https://www.anaconda.com/distribution/ together with it's conda (instead of pip) for further package installations required for Apache Superset.

Thanks, I already download Visual C++ Redistributable , but set up failed.

**Comment by cyang52** [comment]
I reinstall build tools (2019 version) it appears another bug:
after run python superset db upgrade
I get :
ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 59, in create_app
    app_initializer.init_app()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 429, in init_app_in_ctx
    self.configure_fab()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 507, in configure_fab
    appbuilder.init_app(self.flask_app, db.session)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\base.py", line 210, in init_app
    self.sm = self.security_manager_class(self)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\security\sqla\manager.py", line 63, in __init__
    self.userstatschartview.datamodel = user_datamodel
AttributeError: 'NoneType' object has no attribute 'datamodel'
Traceback (most recent call last):
  File "superset", line 21, in <module>
    superset()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 367, in load_app
    app = call_factory(self, self.create_app)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 116, in call_factory
    return app_factory()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 66, in create_app
    raise ex
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 59, in create_app
    app_initializer.init_app()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 429, in init_app_in_ctx
    self.configure_fab()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 507, in configure_fab
    appbuilder.init_app(self.flask_app, db.session)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\base.py", line 210, in init_app
    self.sm = self.security_manager_class(self)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\security\sqla\manager.py", line 63, in __init__
    self.userstatschartview.datamodel = user_datamodel
AttributeError: 'NoneType' object has no attribute 'datamodel'
any ideas?

**Comment by vdmitriyev** [comment]
@cyang52 do you have the database, which can be accessed by your installation?
