### ISSUE TITLE
Bug when set superset

### ISSUE THREAD

**Issue by cyang52** [apache/incubator-superset#9580]
after run "python superset db upgrade"
I get :
ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 59, in create_app
    app_initializer.init_app()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 429, in init_app_in_ctx
    self.configure_fab()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 507, in configure_fab
    appbuilder.init_app(self.flask_app, db.session)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\base.py", line 210, in init_app
    self.sm = self.security_manager_class(self)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\security\sqla\manager.py", line 63, in __init__
    self.userstatschartview.datamodel = user_datamodel
AttributeError: 'NoneType' object has no attribute 'datamodel'
Traceback (most recent call last):
  File "superset", line 21, in <module>
    superset()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 367, in load_app
    app = call_factory(self, self.create_app)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask\cli.py", line 116, in call_factory
    return app_factory()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 66, in create_app
    raise ex
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 59, in create_app
    app_initializer.init_app()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 429, in init_app_in_ctx
    self.configure_fab()
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\superset\app.py", line 507, in configure_fab
    appbuilder.init_app(self.flask_app, db.session)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\base.py", line 210, in init_app
    self.sm = self.security_manager_class(self)
  File "G:\python\myproject\env\Lib\site-packages\superset\bin\venv\lib\site-packages\flask_appbuilder\security\sqla\manager.py", line 63, in __init__
    self.userstatschartview.datamodel = user_datamodel
AttributeError: 'NoneType' object has no attribute 'datamodel'
any ideas?

**Comment by willbarrett** [comment]
Hi @cyang52 - running Superset under Windows is not supported. I'd recommend running Superset under a Linux VM or under Docker. Good luck!
