### ISSUE TITLE
Chart email schedules not delivering

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#9607]
I have scheduled a report with cron tab frequency every 15 min. It is throwing an error saying slices.id is not found. I have check the chart creation and slice.id in slices table as well. everything looks fine. Please suggest any ideas here. Thanks.
### Expected results

Worker log:
[2020-04-22 00:18:46,794: ERROR/ForkPoolWorker-7] Task email_reports.send[2fd14c5c-2df8-4130-a5da-2af92e0d5068] raised unexpected: NoSuchColumnError("Could not locate column in row for column 'slices.id'",)
Traceback (most recent call last):
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/obi/ApacheSuperset/superset_36/Superset/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/obi/ApacheSuperset/superset_36/Superset/superset/tasks/schedules.py", line 714, in schedule_email_report
    deliver_slice(schedule)
  File "/obi/ApacheSuperset/superset_36/Superset/superset/tasks/schedules.py", line 677, in deliver_slice
    email = _get_slice_visualization(schedule)
  File "/obi/ApacheSuperset/superset_36/Superset/superset/tasks/schedules.py", line 636, in _get_slice_visualization
    slc = schedule.slice
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 286, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 722, in get
    value = self.callable_(state, passive)
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 750, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 840, in _emit_lazyload
    session.query(self.mapper), primary_key_identity
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/ext/baked.py", line 615, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 101, in instances
    cursor.close()
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
    rows = [proc(row) for row in fetch]
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in _instance
    tuple([row[column] for column in pk_cols]),
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/orm/loading.py", line 525, in <listcomp>
    tuple([row[column] for column in pk_cols]),
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/engine/result.py", line 686, in _key_fallback
    replace_context=err,
  File "/obi/ApacheSuperset/superset_36/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'slices.id'"
what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by thammaneni** [comment]
Resolved.
