### ISSUE TITLE
SQLLab: Async Query Fails (Internal Server Error)

### ISSUE THREAD

**Issue by GiannisDimitriou** [apache/incubator-superset#9646]
After upgrading to 0.35.2 any Async query through SQL Lab fails with the below response:

<html> <head> <title>Internal Server Error</title> </head> <body> <h1><p>Internal Server Error</p></h1> </body> </html>

What puzzles me is that all Charts are working fine even the preview of the table in SQL Lab is working.

This is the error I get from the logs:
[ERROR] Error handling request /superset/results/91e112f7-e4a6-41f1-a38c-69dea540eb1e/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 168, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/utils/log.py", line 60, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 2444, in results
    obj = _deserialize_results_payload(payload, query, results_backend_use_msgpack)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 208, in _deserialize_results_payload
    ds_payload = msgpack.loads(payload, raw=False)
  File "msgpack/_unpacker.pyx", line 209, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

In another similar environment that I upgraded to 0.35.2 I don't experience any similar issues, so I am not sure if its a bug or some configuration issue.

If I disable the asynchronous query from my datasource then everything works as expected.

#### Screenshots

![image](https://user-images.githubusercontent.com/47314887/80227373-330cae80-8656-11ea-9657-b28f87b32e8f.png)

#### How to reproduce the bug

1. Set a datasource to allow asynchronous queries
2. Click on SQL Lab
3. Issue any query on the same datasource

### Environment

(please complete the following information):

- superset version: `0.35.2`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ *] I have checked the superset logs for python stacktraces and included it here as text if there are any.

**Comment by villebro** [comment]
This functionality has been refined a bunch in the `0.36.0` release. I would suggest trying that out. If your problem persists, I can try to help debug the issue. Btw, on what database engine are you running into this issue?

**Comment by GiannisDimitriou** [comment]
@villebro Both datasource and metadata is PostgreSQL.

I will try to upgrade to 0.36.0 and I will update if that solve the issue.
