### ISSUE TITLE
not able to install superset from source code

### ISSUE THREAD

**Issue by mantej-emilence** [apache/incubator-superset#9690]
im not able to properly install apache superset from the github master latest 
but im able to properly install it via pip install superset(its not the latest version)

### Expected results
i expected the results to install superset without any problem
what you expected to happen.

### Actual results
95% emitting CopyPlugin/home/tatsign/superset/incubator-superset/superset-frontend/node_modules/thread-loader/dist/WorkerPool.js:390
              throw _iteratorError2;
              ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at PoolWorker.writeEnd (/home/tatsign/superset/incubator-superset/superset-frontend/node_modules/thread-loader/dist/WorkerPool.js:97:22)
    at PoolWorker.dispose (/home/tatsign/superset/incubator-superset/superset-frontend/node_modules/thread-loader/dist/WorkerPool.js:261:12)
    at WorkerPool.disposeWorkers (/home/tatsign/superset/incubator-superset/superset-frontend/node_modules/thread-loader/dist/WorkerPool.js:378:20)
    at Timeout._onTimeout (/home/tatsign/superset/incubator-superset/superset-frontend/node_modules/thread-loader/dist/WorkerPool.js:362:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:677:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:154:17)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    [... lines matching original stack trace ...]
    at processTimers (internal/timers.js:492:7) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superset@0.999.0-dev dev: `webpack --mode=development --colors --progress --debug --watch`

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/61014306/80637336-78791380-8a7c-11ea-9b65-e4abd0561116.png)

#### How to reproduce the bug
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md
im following this guide
node 14.0,12.6.3 both been tested on

1. Go to '...'virtualenv -p python3 venv # setup a python3.6 virtualenv
source venv/bin/activate

# Install external dependencies
pip install -r requirements.txt
pip install -r requirements-dev.txt

# Install Superset in editable (development) mode
pip install -e .

# Create an admin user in your metadata database
superset fab create-admin

# Initialize the database
superset db upgrade

# Create default roles and permissions
superset init
# From the root of the repository
cd superset-frontend

# Install dependencies from `package-lock.json`
npm ci

# Start a watcher that recompiles your assets as you modify them (but have to manually reload your browser to see changes.)
npm run dev(i get the error above at this point)
### Environment

(please complete the following information):

- superset version: `superset version0.99 master branch latest`
- python version: `python --version 3.6.3`
- node.js version: `node -v 14.00,12.6.3`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [. ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [. ] I have reproduced the issue with at least the latest released version of superset.
- [. ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by yanickrochon** [comment]
I have the same issue. Superset is utterly broken and I can't rebuild the assets folder because of this.

**Comment by ktmud** [comment]
Superset is not tested on Windows. I'd recommend using a Linux virtual machine or Docker containers.

**Comment by yanickrochon** [comment]
I haven't personally used Windows since 2004. It won't build a production environment under Linux for me. See issue #10066

**Comment by willbarrett** [comment]
Hi @mantej-emilence would you mind sharing more details on your execution environment? I'm particularly interested in Linux flavor and version, and the available memory during build. We've seen similar problems to this when trying to build on a small VM or container.
