### ISSUE TITLE
Upgrading from 0.35.2 to 0.36.0 version with Postgresql database

### ISSUE THREAD

**Issue by JeanBaptisteINITIATIVES** [apache/incubator-superset#9736]
Hello everybody,

We use Superset almost since 1 year now, and all I can say is that's a great tool... Thank a lot for all contributors !
I actually have the 0.35.2 Superset version, with a Postgresql database implementation. I tried migrating to the new 0.36.0 version, but I can't migrate the Postgresql database (i run "superset db upgrade" after the upgrade). I thought that I could do it manually, but there are too much changes in the db tables to make it properly.
Did I miss something with the migration ?

Thanks for your help, best regards

Jean-Baptiste

**Comment by rumbin** [comment]
Please provide a detailed error description and/or log. What is the output of 'superset db upgrade'? If it succeeded, did you also run 'superset init' subsequently?

**Comment by JeanBaptisteINITIATIVES** [comment]
Thanks @rumbin for your quick response. I didn't provide an error description because there is not... The 'superset db upgrade' succeed and I ran 'superset init'. The problem is that th e upgrading override the config.py file and the SQL alchemy connection to the Postgresql database. Do I have to modify the config.py before the db upgrade ?

**Comment by JeanBaptisteINITIATIVES** [comment]
> Please provide a detailed error description and/or log. What is the output of 'superset db upgrade'? If it succeeded, did you also run 'superset init' subsequently?

@rumbin , this is the error log when running 'superset db upgrade' AFTER changing the config.py (my mistake...) 👍 
`logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/home/superset/superset/lib/python3.6/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade def97f26fdfb -> 11c737c17cc6, deprecate_restricted_metrics
INFO  [alembic.runtime.migration] Running upgrade 11c737c17cc6 -> 258b5280a45e, form strip leading and trailing whitespace
INFO  [alembic.runtime.migration] Running upgrade 258b5280a45e -> 1495eb914ad3, time range
INFO  [alembic.runtime.migration] Running upgrade 1495eb914ad3 -> b6fa807eac07, make_names_non_nullable
INFO  [alembic.runtime.migration] Running upgrade b6fa807eac07 -> cca2f5d568c8, add encrypted_extra to dbs
INFO  [alembic.runtime.migration] Running upgrade cca2f5d568c8 -> c2acd2cf3df2, alter type of dbs encrypted_extra
INFO  [alembic.runtime.migration] Running upgrade c2acd2cf3df2 -> 78ee127d0d1d, reconvert legacy filters into adhoc
INFO  [alembic.runtime.migration] Running upgrade 78ee127d0d1d -> db4b49eb0782, Add tables for SQL Lab state
INFO  [alembic.runtime.migration] Running upgrade db4b49eb0782 -> 5afa9079866a, serialize_schema_permissions.py
INFO  [alembic.runtime.migration] Running upgrade 5afa9079866a -> 89115a40e8ea, Change table schema description to long text
INFO  [alembic.runtime.migration] Running upgrade 89115a40e8ea -> 817e1c9b09d0, add_not_null_to_dbs_sqlalchemy_url
INFO  [alembic.runtime.migration] Running upgrade 817e1c9b09d0 -> e96dbf2cfef0, datasource_cluster_fk
Traceback (most recent call last):
  File "/home/superset/superset/bin/superset", line 21, in <module>
    superset()
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/superset/superset/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/superset/superset/lib/python3.6/site-packages/superset/migrations/env.py", line 115, in <module>
    run_migrations_online()
  File "/home/superset/superset/lib/python3.6/site-packages/superset/migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/home/superset/superset/lib/python3.6/site-packages/superset/migrations/versions/e96dbf2cfef0_datasource_cluster_fk.py", line 76, in upgrade
    "fk_datasources_cluster_id_clusters", "clusters", ["cluster_id"], ["id"]
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/operations/batch.py", line 79, in flush
    fn(*arg, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/ddl/impl.py", line 241, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/home/superset/superset/lib/python3.6/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1037, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 436, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 478, in __call__
    return fn(element, compiler, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 423, in _wrap_existing_dispatch
    return existing_dispatch(element, compiler, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 92, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/superset/superset/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3092, in visit_drop_constraint
    "it has no name" % drop.element
sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint UniqueConstraint(); it has no name`

**Comment by dpgaspar** [comment]
Tried to reproduce this by:
- installed superset 0.35.2 with PG and migrated the DB
- upgraded superset to 0.36.0
- migrated the DB

Found no errors:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade b6fa807eac07 -> cca2f5d568c8, add encrypted_extra to dbs
INFO  [alembic.runtime.migration] Running upgrade cca2f5d568c8 -> c2acd2cf3df2, alter type of dbs encrypted_extra
INFO  [alembic.runtime.migration] Running upgrade c2acd2cf3df2 -> 78ee127d0d1d, reconvert legacy filters into adhoc
INFO  [alembic.runtime.migration] Running upgrade 78ee127d0d1d -> db4b49eb0782, Add tables for SQL Lab state
INFO  [alembic.runtime.migration] Running upgrade db4b49eb0782 -> 5afa9079866a, serialize_schema_permissions.py
INFO  [alembic.runtime.migration] Running upgrade 5afa9079866a -> 89115a40e8ea, Change table schema description to long text
INFO  [alembic.runtime.migration] Running upgrade 89115a40e8ea -> 817e1c9b09d0, add_not_null_to_dbs_sqlalchemy_url
INFO  [alembic.runtime.migration] Running upgrade 817e1c9b09d0 -> e96dbf2cfef0, datasource_cluster_fk
INFO  [alembic.runtime.migration] Running upgrade e96dbf2cfef0 -> 3325d4caccc8, empty message
INFO  [alembic.runtime.migration] Running upgrade 3325d4caccc8 -> 0a6f12f60c73, add_role_level_security
INFO  [alembic.runtime.migration] Running upgrade 0a6f12f60c73 -> 72428d1ea401, Add tmp_schema_name to the query object.
INFO  [alembic.runtime.migration] Running upgrade 72428d1ea401 -> b5998378c225, add certificate to dbs
INFO  [alembic.runtime.migration] Running upgrade b5998378c225 -> f9a30386bd74, cleanup_time_grainularity
```

Can you add more information, what do you mean by ` running 'superset db upgrade' AFTER changing the config.py (my mistake...) 👍` ?

**Comment by JeanBaptisteINITIATIVES** [comment]
@dpgaspar , at first, I have the superset 0.35.2 version with PG and my DB migrated. Then, I upgrade to the 0.36.0. The problem is the config.py file is overwritten by the upgrading, and if I process the DB upgrade, it take the SQLite context. So I tried to change the SQLALCHEMY_DATABASE_URI with my PG, before the upgrading, but then it throws the errors mentioned before.
Did I miss something ?

Thanks

**Comment by dpgaspar** [comment]
You can use `SUPERSET_CONFIG_PATH` to set the path to `superset_config.py`. I would repeat the process from the start (restore from backup for example). 
Check alembic version on PG on 0.35.2 it should be `b6fa807eac07` and after the upgrade to 0.36.0 `f9a30386bd74`

**Comment by JeanBaptisteINITIATIVES** [comment]
@dpgaspar , thanks for the response. I'll trie later your recommendation and give you the feedback.

Best regards

**Comment by JeanBaptisteINITIATIVES** [comment]
@dpgaspar , I tried to restore the Superset version, checking dependencies with the requirements.txt. I upgraded Superset to the 0.36.0 version, checked again the dependencies with the requirements.txt to make sure the alembic version was the good one.
But I have still the error message...
I will re-trie later, with a bit of rest ;-)

**Comment by Fentonfi** [comment]
Hi, 

I am also facing similar issue while upgrading from superset 0.35.2 to 0.36.0.

Here is the error, that I see when I do an upgrade

sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint ForeignKeyConstraint(<sqlalchemy.sql.base.ColumnCollection object at 0x7f6d65b606a0>, None, table=Table('datasources', MetaData(bind=None), schema=None)); it has no name

**Comment by JeanBaptisteINITIATIVES** [comment]
Hi,

@dpgaspar , I see that somebody encounter the same issue, and for information I gave up migration after multiple attempts...
If you could re-study the problem, it would be great...

Best regards

Jean-Baptiste

**Comment by Fentonfi** [comment]
Hi Jean-Baptiste,

Thanks, yeah. Even after multiple attempts not able to proceed further.

Regards,
Fenton

**Comment by MApeldoorn** [comment]
Hi Jean-Baptiste,

I managed to get the "superset db upgrade" running, by blocking one line of code in: e96dbf2cfef0_datasource_cluster_fk.py
- #batch_op.drop_constraint(uq_constraint_name, type_="unique")

BR, Mark

**Comment by JeanBaptisteINITIATIVES** [comment]
Hi @MApeldoorn ,

Thank you for your feedback, I will retry the migration soon. I do not know about you but for my part I have for each dashboard many charts ids declared in the "filter_immune_slice_fields" json metadata, and I want to see if the filters are scoped correctly after migration...

Regards,
Jean-Baptiste

**Comment by JeanBaptisteINITIATIVES** [comment]
Hi,

@dpgaspar , @Fentonfi , @MApeldoorn , I confirm that migration succeed with the drop constraint line commented in the migration file mentioned before.
Hope it will help someone else before patching this issue in a future version !

Best regards,
Jean-Baptiste

**Comment by Fentonfi** [comment]
Hi MApeldoorn,

Thanks for the update. We were able to upgrade the superset version, but when we start superset we get "**Internal Server Error**"

I could see that the superset service has been started but, error remains as is.

@JeanBaptisteINITIATIVES ,
Thanks for confirming. :) 

Regards,
Fenton

**Comment by Fentonfi** [comment]
Hi @JeanBaptisteINITIATIVES,

Thanks for the help, the issue was with gunicorn configuration. Now we are able to access our superset application. 
**Used the following instead:**
gunicorn -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 --log-level=debug "superset.app:create_app()"

Once again thanks for the support guys. :) 

Regards,
Fenton
