### ISSUE TITLE
Use load_examples will throw a connection refused error

### ISSUE THREAD

**Issue by Seaven** [apache/incubator-superset#9802]
I installed superset according to the documentation, will throw a connection refused error When executing `superset load_examples`:
```
(superset) seaven@localhost superset % superset load_examples

logging was configured successfully
INFO:superset.utils.logging_configurator:logging was configured successfully
/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/site-packages/flask_caching/__init__.py:189: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  "Flask-Caching: CACHE_TYPE is set to null, "
Loading examples metadata and related data into examples
Creating default CSS templates
Loading energy related dataset
Traceback (most recent call last):
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/seaven/opt/miniconda3/envs/superset/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
```

Follow the stack, I find the code `BASE_URL = "https://github.com/apache-superset/examples-data/blob/master/" ` in `superset/examples/helpers.py`,  the url looks invalid, maybe it should be updated?

**Comment by pengyejun** [comment]
You may need to use proxy access to execute superset load_examples, because it will go to github
eg: proxychains4 superset load_examples
