### ISSUE TITLE
Error When Installing Dev Requirements pydruid

### ISSUE THREAD

**Issue by essajiwa** [apache/incubator-superset#9830]
When running this `pip install -r requirements-dev.txt` i got error on the step when it need to install `pydruid`. 

### Expected results

Should got no error, because it simply just installing the pip

### Actual results

I got this error
```
ERROR: Command errored out with exit status 1:
     command: /Users/essajiwa/Workspace/mentorin/incubator-superset/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-install-hawfhb7x/pydruid/setup.py'"'"'; __file__='"'"'/private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-install-hawfhb7x/pydruid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-pip-egg-info-r2w3byc0
         cwd: /private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-install-hawfhb7x/pydruid/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-install-hawfhb7x/pydruid/setup.py", line 51, in <module>
        "Programming Language :: Python :: 3.7",
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/wheel.py", line 103, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/wheel.py", line 111, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/Users/essajiwa/Workspace/mentorin/incubator-superset/venv/lib/python3.7/site-packages/setuptools/wheel.py", line 132, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/private/var/folders/96/ls_jv_856f188z191jvf8c2r0000gn/T/pip-install-hawfhb7x/pydruid/.eggs/pytest_runner-5.2-py3.7.egg'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
#### How to reproduce the bug

Just run `pip install -r requirements-dev.txt` as a development requirements
### Environment

(please complete the following information):

- superset version: `master` branch
- python version: `3.7.7`
- node.js version: `v14.2.0`
- npm version: `6.14.5`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I'm using MacBook Pro with macOS Catalina version 10.15.4 for development.

And I try to change the `pydruid` version on the  `requirements-dev.txt` from `0.5.9` to `0.5.8` and this bugs is eliminated.

**Comment by villebro** [comment]
Thanks @essajiwa , this is a known issue with `pydruid` on python 3.7, see https://github.com/druid-io/pydruid/issues/198 .

FYI @etr2460 @john-bodley : To ensure a smooth transition to 3.7 and beyond, we should probably fix this bug in the `pydruid` build first.
