### ISSUE TITLE
Throw error on startup in case of wrong webdriver defined in superset_config, and update documentation to show allowed values

### ISSUE THREAD

**Issue by transhapHigsn** [apache/incubator-superset#9876]
In case of defining webdriver for email reports, there is no exact reference to what should be the possible values allowed for the variable.  In [documentation](https://superset.incubator.apache.org/installation.html#email-reports), it is mentioned that webdriver can be one of two `geckodriver` or `chromedriver`, but in [code implementation](https://github.com/apache/incubator-superset/blob/master/superset/tasks/schedules.py#L163) allowed values are  `firefox` and `chrome`.

### Expected results

Let's say, if you set `EMAIL_REPORTS_WEBDRIVER = "geckodriver"` or `EMAIL_REPORTS_WEBDRIVER = "chromedriver"`, then return an error.

### Actual results

Webserver runs without throwing an error, following error is thrown by celery worker:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 374, in schedule_email_report
    deliver_slice(schedule)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 337, in deliver_slice
    email = _get_slice_visualization(schedule)
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 299, in _get_slice_visualization
    driver = create_webdriver()
  File "/usr/local/lib/python3.8/site-packages/superset/tasks/schedules.py", line 155, in create_webdriver
    options.add_argument("--headless")
UnboundLocalError: local variable 'options' referenced before assignment
`

#### How to reproduce the bug

1. set `EMAIL_REPORTS_WEBDRIVER = "geckodriver"`
2. Create an email schedule.
3. Check celery worker logs of the failed task.

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `3.8`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by transhapHigsn** [comment]
I am not sure if anyone will look into this, i am closing this issue now.
