### ISSUE TITLE
Cannot sign in using admin after docker-compose up

### ISSUE THREAD

**Issue by Yuchen-Wang-SH** [apache/incubator-superset#9922]
Hey guys! I am new to superset and I am excited to try it out, but I have some difficulty trying to log in.

After `docker-compose up` and see the login page on `http://localhost:8088/login/`, I cannot successfully sign in using account name `admin` and password `admin`. This is the same situation as described in #9852. If you need pictures to refer to, please refer to the ones in that issue.

Any help is appreciated. Thanks in advance!

**Comment by DataShedEd** [comment]
Same here....!

**Comment by anant-barlota** [comment]
same here :/

**Comment by rusackas** [comment]
Can you see any errors in the console where superset is running?

**Comment by willbarrett** [comment]
Please look carefully at the output from `docker-compose up`. the `superset-init` container is supposed to create the proper admin user. Please check this container's output carefully for errors - it's possible for that process to fail and still have the server boot successfully.

**Comment by DataShedEd** [comment]
Running `docker logs superset_init` returns:

```
Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )


######################################################################

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy-Utils 0.36.6 (/usr/local/lib/python3.6/site-packages), Requirement.parse('sqlalchemy-utils<0.36.5,>=0.33.2'), {'apache-superset'})

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/bin/superset", line 4, in <module>
    __import__('pkg_resources').require('apache-superset==0.999.0.dev0')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3261, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlalchemy-utils<0.36.5,>=0.33.2' distribution was not found and is required by apache-superset
```

**Comment by DataShedEd** [comment]
Reducing the dependency in `requirements.txt`: sqlalchemy-utils==0.36.5` to `sqlalchemy-utils==0.36.4` gets me past that step; however further investigation needs to be done as to whether the dependency at 0.36.5 functions with any other elements of the code calling it.

```
superset_init            | 
superset_init            | ######################################################################
superset_init            | 
superset_init            | 
superset_init            | Init Step 1/4 [Complete] -- Setting up admin user
superset_init            | 
superset_init            | 
superset_init            | ######################################################################
superset_init            | 
superset_init            | 
superset_init            | ######################################################################
superset_init            | 
superset_init            | 
superset_init            | Init Step 2/4 [Starting] -- Applying DB migrations
superset_init            | 
superset_init            | 
superset_init            | ######################################################################
```

**Comment by villebro** [comment]
`sqlalchemy-utils==0.36.5` is broken, so you need to either be on `0.36.6` (this is what `master` branch is on), or go back to `0.36.4`.

**Comment by DataShedEd** [comment]
Looks to have been resolved in https://github.com/apache/incubator-superset/commit/d61594982025d7a05d97b15e99a0253a46c43dfd

**Comment by willbarrett** [comment]
OK. @Yuchen-Wang-SH please re-open this issue if it is not resolved for you.
