### ISSUE TITLE
sql lab editer result {e}

### ISSUE THREAD

**Issue by hmily3913** [apache/incubator-superset#9992]
sql editer中执行任何sql都无结果

### Actual results

结果：{e}

#### Screenshots

![image](https://user-images.githubusercontent.com/3221165/83832484-5c702e00-a71c-11ea-8e5e-6301e1356d39.png)

### Environment

(please complete the following information):

- superset version: `superset 0.36`
- python version: `python 3.7.7`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ *] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by hmily3913** [comment]
查看日志内容：
Triggering query_id: 29
Query 29: module 'signal' has no attribute 'SIGALRM'
Traceback (most recent call last):
  File "D:\superset\venv\lib\site-packages\superset\views\core.py", line 2312, in _sql_json_sync
    with utils.timeout(seconds=timeout, error_message=timeout_msg):
  File "D:\superset\venv\lib\site-packages\superset\utils\core.py", line 584, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
