### ISSUE TITLE
Superset Email Report: TypeError 'str' object is not callable

### ISSUE THREAD

**Issue by phuongnh2** [apache/incubator-superset#9995]
Hi admin, everybody,
I have issue Email report on superset version 036
Enviroment
Centos 7, 
Superset 0360
Python3.6
Celery 4

![image](https://user-images.githubusercontent.com/66466819/83865665-b854aa00-a750-11ea-8948-8f6e61840076.png)

Bugs:
```
[2020-06-05 15:45:01,209: ERROR/ForkPoolWorker-1] Task email_reports.send[3d0fb4fc-347c-4ef5-844c-9d7c9e87ce21] raised unexpected: TypeError("'str' object is not callable",)
Traceback (most recent call last):
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/superset/app.py", line 114, in __call__
    return task_base.__call__(self, *args, **kwargs)
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/superset/tasks/schedules.py", line 378, in schedule_email_report
    deliver_slice(schedule)
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/superset/tasks/schedules.py", line 341, in deliver_slice
    email = _get_slice_visualization(schedule)
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/superset/tasks/schedules.py", line 303, in _get_slice_visualization
    driver = create_webdriver()
  File "/zserver/superset-update-2/lib64/python3.6/site-packages/superset/tasks/schedules.py", line 155, in create_webdriver
    options.binary_location("/usr/local/bin/chromedriver")
TypeError: 'str' object is not callable
```
Help me,
Thanks

**Comment by phuongnh2** [comment]
👍

**Comment by bkyryliuk** [comment]
email reports are working fine for us in production. I would suggest to double check the chrome driver and chromium browser installations and configuration settings.

**Comment by phuongnh2** [comment]
Can you help to step by step build on production ?
